[5기 - 김대휘] 1~2주차 과제: 도서 관리 어플리케이션 제출합니다.
prgrms-be-devcourse/java-library-management pull request #10
Opened 2023-09-27 17:35 UTC by marooo326

## 📌 과제 설명 
도서의 정보와 상태를 관리하는 도서관리 어플리케이션을 구현하였습니다.
콘솔 입력을 통해 도서 정보를 조회/추가/삭제/변경 할 수 있습니다.
도서 정보는 일반모드인 경우 CSV 파일을 통해 관리/저장되며, 테스트 모드인 경우 List로 관리되며 저장되지 않습니다.

## 👩‍💻 요구 사항과 구현 내용 
프로젝트의 패키지 구조는 아래와 같습니다.
### commom
프로젝트에서 전반적으로 사용되는 Message Enum을 작성했습니다.
### domain
도서관리 프로젝트의 가장 주요한 객체인 Book과 Book의 필드(도서상태)인 BookState Enum을 작성하였습니다.
- 모든 생성자가 반드시 모든 필드를 초기화하도록 구현하여 불완전한 객체가 생성되는 것을 막고자 하였습니다.
- 또한, 실행동안 지속적으로 변경되는 state 필드를 제외한 나머지 필드는 setter를 사용하지 않았습니다.
- 응집도를 높이고자 상태변경과 관련된 메소드를 내부에 작성하였습니다.
### provider
도서의 unique한 Id를 제공해주는 BookIdProvider를 작성하였습니다.
### repository
도서 데이터를 직접적으로 다루는 FileBookRepository와 MemBookRepository를 작성하였습니다.
- 두 Repository 클래스는 BookRepository 인터페이스를 구현하도록 하여 전략패턴을 사용하고자 하였습니다.
### service
주요한 비즈니스 로직을 다루는 BookService 클래스를 작성하였습니다.
- ConsoleUI에서 넘겨준 사용자 입력을 매개변수로 받아 비즈니스 로직을 처리하고자 하였습니다.
- 반납 5분 뒤, 상태를 ORGANIZING(도서 정리중)에서 AVAILABLE(대여 가능)으로 변경하는 메서드를 구현하였습니다.
### view
입/출력에 관련된 요소들을 작성하였습니다.
- BookCommand라는 함수형 인터페이스를 정의하고, ConsoleUI의 생성자에서 map을 이용해 if문 분기 없이 입력에 알맞은 메서드를 실행하도록 하였습니다.
- setMode() 메서드를 이용해 선택한 모드에 따라 주입되는 Repository의 구현체를 변경해주었습니다.
- 최대한 입/출력에 관련된 기능을 ConsoleUI가 담당하도록 작성했습니다.

## ✅ PR 포인트 & 궁금한 점 
1. Repsitory에서 Map 자료구조를 사용하는 것이 더 효율적인지 궁금합니다.
요구사항에 있는 조건에 맞추어 Repository에 List로 도서 데이터를 관리하도록 작성하였습니다.
다만, Id를 이용한 직접적인 조회가 많은 과제의 특성상 Map으로 도서데이터를 관리하는 것이 이론적으로는(?) 더 빠를거라는 생각이 들어 질문드립니다.
2. 패키지구조에 대한 개선점이 궁금합니다. 
임의대로 패키지를 구분하였는데, 다른사람이 보았을 때 프로젝트 구조가 원활히 파악되는지 궁금합니다.
만약 잘못된 점이나 개선점이 있다면 알고싶습니다.
3. 커스텀 예외처리
현재는 Messages Enum과 기본 제공되는 예외를 활용하여 예외를 처리하였습니다.
일반적으로 Enum을 활용하는 것 보다 커스텀 예외처리를 하는 것이 바람직한지 궁금합니다.
4. 객체지향적인 부분에서 개선점이 궁금합니다!

2023-09-29 06:34 UTC, ksy90101 requested changes
여기도 일단 큰틀이 깔끔해져야 할거 같습니다. 아래 질문을 생각해보세요.

1. .idea폴더란 무엇일까요?
2. app폴더 내에 있어야 하는 이유가 굳이 있을까요?
3. java-library.iml이란 무엇일까요?

모르는게 있다면 슬랙 DM주시고, 깔끔해진 뒤에 하겠습니다.

2023-09-30 05:20 UTC, ksy90101 requested changes
너무 리뷰를 남길게 많아서, 중간에 끊겠습니다.
두가지를 한번 고민해서 리팩토링을 한 뒤에 리뷰를 한번 살펴보시면 좋을거 같아요.

1. View파일은 View에 역할을 한곳에 모아둔다.
2. 객체에게 메시지를 보낼수 있는 곳은 메시지를 보내보자.

어려운게 잇다면 언제든 슬랙으로  DM 주세요~

2023-09-30 05:20 UTC, ksy90101 commented on build.gradle
> +    id 'java'
java버전을 명시하면 어떨까요?

https://dlee0129.tistory.com/265
https://docs.gradle.org/current/userguide/toolchains.html#sec:consuming
sourceCompatibility & targetCompatibility
toolchain - languageVersion
이거에 대해서도 공부해두면 좋을거 같습니다~

2023-09-30 05:20 UTC, ksy90101 commented on build.gradle
> +}
https://blog.coderifleman.com/2015/04/04/text-files-end-with-a-newline/

해당 글을 참고해보면 어떨까요?

2023-09-30 05:20 UTC, ksy90101 commented on build.gradle
> +    testImplementation 'org.junit.jupiter:junit-jupiter'
의존성 명시에 대해서 통일을 시키면 어덜까요?
platform이라는 함수가 무엇인지 아시나요?

2023-09-30 05:20 UTC, ksy90101 commented on src/main/java/com/programmers/common/Messages.java
> +    BOOK_MANAGEMENT_FEATURE_MESSAGE("""
Java17의 기능을 기가막히게 쓰셧네요 👍

2023-09-30 05:20 UTC, ksy90101 commented on src/main/java/com/programmers/common/Messages.java
> +    NORMAL_MODE_EXECUTION("\n[System] 일반 모드로 애플리케이션을 실행합니다."),
\n보단, system.lineseparator()을 한번 알아보고 사용해보면 어덜까요?

2023-09-30 05:20 UTC, ksy90101 commented on src/main/java/com/programmers/common/Messages.java
> +    }
toString은 어떨때 쓰는걸까요?
https://github.com/Meet-Coder-Study/book-effective-java/blob/main/3%EC%9E%A5/12_toString%EC%9D%84_%ED%95%AD%EC%83%81_%EC%9E%AC%EC%A0%95%EC%9D%98%ED%95%98%EB%9D%BC_%EC%9D%B4%ED%98%B8%EB%B9%88.md
해당글을 한번 참고해보면 어떨까요?

2023-09-30 05:20 UTC, ksy90101 commented on src/main/java/com/programmers/domain/Book.java
> +        this.id = BookIdProvider.generateBookId();
도메인에 View코드가 있는게 맞을까요?
View로 잘 분리해두셨는데, 왜 도메인에 View코드를 넣어두셨을지 궁금합니다 :)

2023-09-30 05:20 UTC, ksy90101 commented on src/main/java/com/programmers/domain/Book.java
> +        this.pages = scanner.nextInt();
nextInt에서 숫자가 아닌 다른 값이 들어오면 어떻게 될까요?

2023-09-30 05:20 UTC, ksy90101 commented on src/main/java/com/programmers/domain/Book.java
> +    }
setter를 쓰는게 아니라 메시지를 보내서 자기 상태를 자기가 변경하게 하면 어떨까요?

2023-09-30 05:20 UTC, ksy90101 commented on src/main/java/com/programmers/domain/Book.java
> +            case LOST -> throw new RuntimeException(Messages.BOOK_NOW_LOST.toString());
이런경우엔 한번에 사용할수 있지 않을까요?

2023-09-30 05:20 UTC, ksy90101 commented on src/main/java/com/programmers/domain/Book.java
> +        }
사실 무조건적으로 switch문이 좋은거 아닙니다.
이 코드를 한번 if문으로 변경해보면 어떨까요?

if (this.state === LOST) { 예외 }

return this.state === RENTED || this.state === AVAILABLE || this.state === ORGANIZING 

이렇게 쓰면 어떨까요?

2023-09-30 05:20 UTC, ksy90101 commented on src/main/java/com/programmers/domain/Book.java
> +                return true;
이런식으로 true, false를 명시하는것 보단, 조건문을 사용해보시는걸 추천해요.

2023-09-30 05:20 UTC, ksy90101 commented on src/main/java/com/programmers/provider/BookIdProvider.java
> +                .orElseGet(() -> new Book(0, "", "", 0, BookState.AVAILABLE));
이렇게 된다면 0이라는 값이 여러개 생길수도 있는거 아닌가요?

2023-09-30 05:20 UTC, ksy90101 commented on src/main/java/com/programmers/repository/BookRepository.java
> +public interface BookRepository {
👍 
아주 굳굳입니다.

2023-09-30 05:20 UTC, ksy90101 commented on src/main/java/com/programmers/repository/FileBookRepository.java
> +    private final String csvFile = "./app/src/main/resources/data.csv";
static이 필요하진 않을까요? (질문)

2023-09-30 05:20 UTC, ksy90101 commented on src/main/java/com/programmers/repository/FileBookRepository.java
> +public class FileBookRepository implements BookRepository {
저에겐 csv가 없어서 해당 부분에서 터집니다.
혹시 이런 경우에 어떻게 하면 좋을지 한번 고민해보시면 어떨까요?

2023-09-30 05:20 UTC, ksy90101 commented on src/main/java/com/programmers/repository/FileBookRepository.java
> +    }
이 클래스가 있어야 하는 이유가 무엇인가요?

2023-09-30 05:20 UTC, ksy90101 commented on src/main/java/com/programmers/repository/FileBookRepository.java
> +        return books.stream().filter(book -> book.getId() == id).findAny();
```suggestion
        return books.stream()
        .filter(book -> book.getId() == id)
        .findAny();
```
1. 한줄의 점 하나씩으로 좀더 위에서 아래로 읽히는 방식으로 하면 어떨까요?
2. book에게 이 id와 맞아? 즉, isSameId와 같이 메시지를 보내서 물어보면 어떨까요?
3. findAny vs findFirst에 대해서 한번 알아보시겠어요?

2023-09-30 05:20 UTC, ksy90101 commented on src/main/java/com/programmers/repository/FileBookRepository.java
> +                .filter(book -> book.getTitle().contains(title)).toList();
이쪽에도 book에게 메시지를 던져보면 어떨까요?

2023-09-30 05:20 UTC, ksy90101 commented on src/main/java/com/programmers/repository/FileBookRepository.java
> +        try (BufferedWriter bw = new BufferedWriter(new FileWriter(csvFile))) {
👍 
try-with-resources를 너무 잘 쓰시네요!!

2023-10-03 06:44 UTC, marooo326 commented on build.gradle
> +    id 'java'
감사합니다! 위에 올려주신 내용에 대해 알아보고 두가지 모두 적용하는 것이 맞다고 생각하여 수정하였습니다.
해당 내용에 대해 간단히 정리도 해보았습니다.
https://velog.io/@marooo326/build.gradle-Java-%EB%B2%84%EC%A0%84-%EB%AA%85%EC%8B%9C%ED%95%98%EA%B8%B0

2023-10-03 06:46 UTC, marooo326 commented on src/main/java/com/programmers/common/Messages.java
> +    }
올려주신 글을 읽어보고, Enum의 경우 위와 같은 방식으로 toString()을 사용하는 것은 적절치 못하다 생각하여 getMessage 메서드로 대체하였습니다..!

2023-10-03 06:49 UTC, marooo326 commented on src/main/java/com/programmers/domain/Book.java
> +        this.id = BookIdProvider.generateBookId();
SRP를 위반한 잘못된 코드를 작성한 것 같습니다. 입출력에 관련된 부분을 ConsoleUi 클래스로 분리하였고, 생성자에서 매개변수를 받아와 객체를 생성하도록 수정하였습니다.

2023-10-03 06:49 UTC, marooo326 commented on src/main/java/com/programmers/domain/Book.java
> +        this.pages = scanner.nextInt();
Console로 입력기능을 분리하면서 InputMismatchException 예외처리를 함께 추가해주었습니다!

2023-10-03 06:52 UTC, marooo326 commented on src/main/java/com/programmers/repository/FileBookRepository.java
> +    private final String csvFile = "./app/src/main/resources/data.csv";
해당 변수들은 모든 인스턴스에서 공유되어야하므로, 클래스 변수로 사용하는 것이 맞다고 생각되어 static 키워드를 추가하였습니다.

2023-10-03 08:25 UTC, kimday0326 commented on src/main/java/com/programmers/domain/Book.java
> +    }
마르코님이 말씀해주신대로 setter를 제거하고 Repository 부분의 함수를 재작성해보았습니다.
```
    @Override
    public void updateBookState(Book book, BookState bookState) {
        if (bookState == BookState.AVAILABLE) {
            book.setToAvailable();
        } else if (bookState == BookState.RENTED) {
            book.setToRented();
        } else if (bookState == BookState.LOST) {
            book.setToLost();
        } else if (bookState == BookState.ORGANIZING) {
            book.setToOrganizing();
        }
    }
```

한 가지 궁금한 점은 setter를 사용하면 비교연산 없이 상태를 변경할 수 있는데, 위처럼 코드를 작성 시 매번 비교연산이 추가됩니다.
그럼에도 불구하고 setter 사용을 최대한 지양하는 것이 옳은지 궁금합니다!

2023-10-03 08:39 UTC, marooo326 commented on src/main/java/com/programmers/repository/FileBookRepository.java
> +        return books.stream().filter(book -> book.getId() == id).findAny();
감사합니다! 말씀해주신 방법을 적용하여 가독성을 개선하였고, findAny와 findFirst의 차이에 대해 알아보았습니다.
findAny의 경우 순서가 보장되지 않고 병렬 스트림에서 주로 사용된다는 것에 대해서도 알게 되었습니다.

id가 unique한 값이기 때문에 어떤 메소드를 사용해도 결과값은 같겠지만, 이 프로젝트에서는 병렬스트림까지 이용할 필요가 없다고 생각되어 사용 방법만 익힌 뒤 findFirst를 적용하였습니다.

2023-10-03 11:09 UTC, marooo326 commented on src/main/java/com/programmers/repository/FileBookRepository.java
> +public class FileBookRepository implements BookRepository {
예외처리를 통해 에러 메세지를 출력하도록 수정하였습니다

2023-10-05 13:49 UTC, ksy90101 commented on build.gradle
> +    id 'java'
이런글은 #99-포스팅-noti에 공유하면 어떨까요.
고생 많으셧어요 멋져요!

2023-10-05 13:50 UTC, ksy90101 commented on src/main/java/com/programmers/domain/Book.java
> +    }
네 비교연산이 느리다고 생각하시나요?
전 아니라고 생각합니다.
요즘 컴퓨터 좋아서 좋아요 ㅋㅋㅋㅋ

2023-10-05 13:50 UTC, ksy90101 commented on src/main/java/com/programmers/domain/Book.java
> +    }
set이라는 단어보단 아니라면 changed같은 단어를 쓰면 어떨까요?
setter는 값을 넣는거 같고 지금 같은change같은 단어는 값을 직접 변경하는것 같으니깐요 ㅎㅎ

2023-10-05 14:07 UTC, ksy90101 requested changes
좀 늦었네요. 고생하셨어요.
궁금한건 슬랙으로~

2023-10-05 14:07 UTC, ksy90101 commented on src/main/java/com/programmers/Main.java
> +}
NLF를 위반했네요.

IDE에 설정하는 법이 있는데 한번 찾아보시면 어떨까요?

2023-10-05 14:07 UTC, ksy90101 commented on src/main/java/com/programmers/Main.java
> +public class Main {
main이라는 키워드가 있는데, 클래스 이름이 Main이면 헷갈리지 않을까요?
어떤 다른 좋은 이름이 있을지 한번 고민해보시면 어떨까요?

2023-10-05 14:07 UTC, ksy90101 commented on src/main/java/com/programmers/common/PromptMessages.java
> +        String NEWLINE = System.lineSeparator();
변수의 네이밍의 규칙은 무엇일까요?
아울러 System.lineSepartor();자체가 상수이지 않을까요?

2023-10-05 14:07 UTC, ksy90101 commented on src/main/java/com/programmers/common/PromptMessages.java
> +    private final String message;
```suggestion
    BOOK_DELETE_PROMPT("Q. 삭제 처리할 도서번호를 입력하세요.");
    
    private final String message;
```
개행을 두고 가독성을 높여보세요.

2023-10-05 14:07 UTC, ksy90101 commented on src/main/java/com/programmers/provider/BookIdProvider.java
> +public class BookIdProvider {
https://github.com/Meet-Coder-Study/book-effective-java/blob/main/2%EC%9E%A5/4_%EC%9D%B8%EC%8A%A4%ED%84%B4%EC%8A%A4%ED%99%94%EB%A5%BC_%EB%A7%89%EC%9C%BC%EB%A0%A4%EA%B1%B0%EB%93%A0_private_%EC%83%9D%EC%84%B1%EC%9E%90%EB%A5%BC_%EC%82%AC%EC%9A%A9%ED%95%98%EB%9D%BC_%EC%9D%B4%ED%98%B8%EB%B9%88.md

이글을 한번 참고해서 적용해보시면 어떨까요?

2023-10-05 14:07 UTC, ksy90101 commented on src/main/java/com/programmers/provider/BookIdProvider.java
> +    private static int MAX_ID = 0;
상수가 아닌데 해당 규칙이 맞을가요?

2023-10-05 14:07 UTC, ksy90101 commented on src/main/java/com/programmers/repository/BookRepository.java
> +    public void addBook(Book Book);
매개변수 네이밍 규칙을 한번 찾아보세요.

2023-10-05 14:07 UTC, ksy90101 commented on src/main/java/com/programmers/repository/BookRepository.java
> +    public void addBook(Book Book);
인터페이스에 접근제어자를 쓰는게 의미가 있을까요?

2023-10-05 14:07 UTC, ksy90101 commented on src/main/java/com/programmers/service/BookService.java
> +    public static void setBookRepository(BookRepository _bookRepository) {
`_`는 어디서 보시고 이렇게 쓰시는건가요?

2023-10-05 14:07 UTC, ksy90101 commented on src/main/java/com/programmers/service/BookService.java
> +    private static int organizingMilliseconds = 1000 * 60 * 5; // 기본 5분
테스트 코드때문에 이렇게 하신거 같은데
이 제어 부분을 interface로 빼서 처리하시면 어떨까요?

https://tecoble.techcourse.co.kr/post/2020-05-17-appropriate_method_for_test_by_interface/

이글을 참고해서 한번 해보세요.

2023-10-05 14:07 UTC, ksy90101 commented on src/main/java/com/programmers/service/BookService.java
> +                .forEach(book -> System.out.println(book.toString()));
서비스에 print를 찍는 부분이 있는게 맞을까요?

2023-10-05 14:07 UTC, ksy90101 commented on src/main/java/com/programmers/view/ConsoleUI.java
> +        while (true) {
while true라면 무한루프 아닌가요? 이렇게 되면 불안정할수가 있어요.
이걸 제거할 방법을 고민해보시겠어요?

2023-10-05 14:07 UTC, ksy90101 commented on src/main/java/com/programmers/view/ConsoleUI.java
> +        functionMap.put(1, this::promptForRegisterBook);
1~7을 상수화나 enum값으로 처리해서 의미전달을 해보시면 어떨까요?

2023-10-05 14:07 UTC, ksy90101 commented on src/main/java/com/programmers/repository/FileBookRepository.java
> +            System.out.println(e.getMessage());
repository에서 에러 메시지를 보여줘야 하는지 고민해보세요.

2023-10-05 14:07 UTC, ksy90101 commented on src/main/java/com/programmers/repository/FileBookRepository.java
> +    public static final String csvSeparator = ",";
상수의 네이밍 확인해주세요.

2023-10-05 14:07 UTC, ksy90101 commented on src/main/java/com/programmers/repository/BookRepository.java
> +public interface BookRepository {
이번 학습 목적으로 Repository 2개에 대한 테스트 코드를 한번 작성해보시면 어떨까요?

2023-10-05 14:07 UTC, ksy90101 commented on src/main/java/com/programmers/domain/Book.java
> +public class Book {
해당 모델도 복잡한 로직이 참 많습니다.

추가 리뷰를 하기 전에 테스트 코드를 작성해두면 어덜까요?

2023-10-10 15:36 UTC, merged