[5기 이유정] 1~2주차 과제: 도서 관리 어플리케이션 제출합니다.
prgrms-be-devcourse/java-library-management pull request #11
Opened 2023-09-27 20:13 UTC by letskuku

## 📌 과제 설명 
- 도서 관리 어플리케이션을 만들었습니다.
- 도서 정보를 파일에 저장하는 일반 모드와 메모리에만 저장하는 테스트 모드를 구분하여 구현합니다.
- 도서 등록, 조회, 검색, 대여, 반납, 분실, 삭제 기능을 구현합니다.
- 도서 반납 직후 5분 간은 정리중 상태로, 대여가 불가하며, 분실 처리된 도서도 반납할 수 있습니다.
- 테스트 코드는 테스트 코드만 보더라도 요구사항을 파악할 수 있도록 구현합니다.

## 👩‍💻 요구 사항과 구현 내용 
### **domain**
- 도서 엔티티
- 도서 상태를 의미하는 enum

### **repository**
- 일반 모드와 테스트 모드를 구분하기 위한 interface
- 일반 모드를 구현한 NormalBookRepository
- 테스트 모드를 구현한 TestBookRepository
- 도서 등록, 조회, 검색, 상태 수정, 삭제 기능 구현

### **application**
- 도서 등록, 조회, 검색, 대여, 반납, 분실, 삭제 전체 로직 구현

### **presentation**
- 모드 선택, 콘솔 입력에 맞는 모드 진입 후 선택 화면 구현

### **utils**
- 콘솔 입출력 구현
- csv 파일 입출력 구현
  - 파일로부터 도서 정보 입력 
  - 콘솔로 등록된 도서 정보 파일에 저장
  - 도서 삭제 후 업데이트된 도서 정보 파일에 저장

### **exception**
- 모드 선택, 모드 진입 후 선택 화면에서 기능 선택 시 올바르지 않은 입력에 대한 예외 구현
- 존재하지 않는 도서 조회에 대한 예외 구현

## ✅ PR 포인트 & 궁금한 점 
1. 객체지향적인 구현 측면에서 개선할만한 부분이 있는지 궁금합니다.
2. 직접 구현한 예외 이외의 예외(ex. IOException)들은 try-catch 문으로 처리했는데 괜찮게 처리한 것인지 궁금합니다.
3. 도서 상태를 변경하거나 반납 일시를 변경함에 있어 setter를 사용하고 싶지 않아 지양하는 방향으로 코드를 짜다보니 Book 생성자를 다소 과하게 사용한 것 같다는 생각이 듭니다. 이런 상황에서는 차라리 setter를 사용하는 것이 좋은가요? 아니면 Book 생성자로 객체를 자주 생성하게 되더라도 setter는 아예 사용하지 않는 것이 좋은가요?
4. 테스트 코드 작성이 사실상 처음입니다. 이전에 스프링을 공부하면서 알게 되었던 given-when-then 패턴과 Assertions를 나름 활용해보았는데, 보통의 테스트 코드 작성과 많이 차이가 나는지, 개선사항이 있는지 궁금합니다.
5. 4에 이어서 테스트 코드를 짜다보니 테스트 코드의 메서드 실행 순서가 실행 결과에 영향을 주게 되어 실행 순서를 지정해주게 되었습니다. 혹시 실행 순서를 지정하는 테스트 코드는 지양하는 것이 좋을까요...?

부족한 부분이나 개선 사항, 안 좋은 습관 같은 것이 보인다면 따끔한 피드백 부탁드립니다!

2023-09-28 05:26 UTC, aegis1920 requested changes
안녕하세요 유정님! 빙봉입니다 🙂 

잘 구현하셨어요! 👍  몇 가지 피드백 드렸으니 확인해주세요~

2023-09-28 05:26 UTC, aegis1920 commented on src/test/java/com/programmers/librarymanagement/NormalManagementServiceTest.java
> +@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
> 테스트 코드 작성이 사실상 처음입니다. 이전에 스프링을 공부하면서 알게 되었던 given-when-then 패턴과 Assertions를 나름 활용해보았는데, 보통의 테스트 코드 작성과 많이 차이가 나는지, 개선사항이 있는지 궁금합니다.

> 4에 이어서 테스트 코드를 짜다보니 테스트 코드의 메서드 실행 순서가 실행 결과에 영향을 주게 되어 실행 순서를 지정해주게 되었습니다. 혹시 실행 순서를 지정하는 테스트 코드는 지양하는 것이 좋을까요...?

- 실행 순서에 종속되는 테스트라고 가정해볼게요. 만약에 다른 사람이 유정님의 테스트 코드에 테스트를 추가했다면 실행 순서에 종속되니 다른 테스트가 깨지지 않을까요? 그럼 그 테스트는 어떤 의미를 가질까요? 
- 테스트 코드에서 어떤 것이 중요한 지 찾아보시고 이야기해주실 수 있을까요?

2023-09-28 05:26 UTC, aegis1920 commented on src/test/java/com/programmers/librarymanagement/NormalManagementServiceTest.java
> +    void successFindByTitle() {
- 이 메서드만 따로 계속 실행시키면 어떻게 되나요?
- 어떤 점이 문제일까요?
- 해결하기 위해선 어떻게 해야할까요?

2023-09-28 05:26 UTC, aegis1920 commented on src/test/java/com/programmers/librarymanagement/NormalManagementServiceTest.java
> +public class NormalManagementServiceTest {
테스트 실행 시 테스트 커버리지까지 확인할 수 있는 기능이 있는데요. 요구사항을 모두 충족했다면 커버리지 100%도 한 번 도전해보시는 걸 추천드립니다!
![image](https://github.com/prgrms-be-devcourse/java-library-management/assets/22311557/0d8f0ce7-48ab-428a-80b6-03a99ad3bdd7)

2023-09-28 05:26 UTC, aegis1920 commented on src/test/java/com/programmers/librarymanagement/NormalManagementServiceTest.java
> +    static NormalBookRepository normalBookRepository;
아래에서 BeforeAll로 선언하고 있는데요. BeforeAll을 쓰지 않고 바로 할당해줘도 되지 않을까요?

2023-09-28 05:26 UTC, aegis1920 commented on src/main/java/com/programmers/librarymanagement/application/LibraryManagementService.java
> +        String result = "[System] 도서가 대여 처리 되었습니다. \n";
서비스 로직에서 View에 해당하는 문자열이 반환되는 것에 대해서 어떻게 생각하실까요?

2023-09-28 05:26 UTC, aegis1920 commented on src/main/java/com/programmers/librarymanagement/application/LibraryManagementService.java
> +                if (book.getReturnDateTime().plusMinutes(5).isAfter(LocalDateTime.now())) {
5라는 건 상수로 빼서 의미를 명확히 해줘도 좋을 것 같아요

2023-09-28 05:26 UTC, aegis1920 commented on src/main/java/com/programmers/librarymanagement/domain/Status.java
> +    CANNOT_RENT("대여중"), // 대여중
`CANNOT_RENT`는 `대여중`이 아닌 `대여 불가`의 의미가 더 맞지 않을까요?

2023-09-28 05:26 UTC, aegis1920 commented on src/main/java/com/programmers/librarymanagement/domain/Status.java
> +    private final String value;
값이라는 변수명보다는 displayName 정도가 더 가까울 것 같습니다!

2023-09-28 05:26 UTC, aegis1920 commented on src/main/java/com/programmers/librarymanagement/presentation/LibraryManagementController.java
> +        int page = Integer.parseInt(consoleIo.getInput());
- 숫자가 아닌 문자가 들어가면 어떻게 되나요?
- 실제 서버라고 가정했을 때 문자가 들어가면 어떻게 될까요?
- 문자가 들어가는 것을 방지하고 싶다면 어떻게 해야할까요?
- 재입력을 받도록 만들 수 있을까요?

2023-09-28 05:26 UTC, aegis1920 commented on src/main/java/com/programmers/librarymanagement/presentation/LibraryManagementController.java
> +        String title = consoleIo.getInput();
적절한 검증이 필요할 것 같아요. 아무런 검증이 없다면 도서 제목으로 만 글자를 입력해도 될테니까요.

2023-09-28 05:26 UTC, aegis1920 commented on src/main/java/com/programmers/librarymanagement/presentation/LibraryManagementController.java
> +                System.out.println("[System] 일반 모드로 애플리케이션을 실행합니다. \n");
분기 너무 깔끔하고 좋네요 👍

2023-09-28 05:26 UTC, aegis1920 commented on src/main/java/com/programmers/librarymanagement/repository/BookRepository.java
> +public interface BookRepository {
👍 👍

2023-09-28 05:26 UTC, aegis1920 commented on src/main/java/com/programmers/librarymanagement/utils/CsvFileIo.java
> +    String PATH = System.getProperty("user.dir") + "/src/main/resources/data.csv";
- 상수를 의미하셨던 것 같아요! private static final을 의도했던 게 맞을까요?
- 만약 맞다면 위치도 수정해주세요!

2023-09-28 05:26 UTC, aegis1920 commented on src/main/java/com/programmers/librarymanagement/repository/NormalBookRepository.java
> +public class NormalBookRepository implements BookRepository{
전반적으로 포맷팅 확인해주세요~
```suggestion
public class NormalBookRepository implements BookRepository {
```

2023-09-28 05:26 UTC, aegis1920 commented on src/main/java/com/programmers/librarymanagement/repository/NormalBookRepository.java
> +    private static final Map<Long, Book> libraryStorage = addBookByFile(csvFileIo.readCsv());
상수 취급이 맞을까요? 상수의 변수명 컨벤션은 뭘까요?

2023-09-28 05:26 UTC, aegis1920 commented on src/main/java/com/programmers/librarymanagement/application/LibraryManagementService.java
> +    private void printBookInfo(List<Book> bookList) {
서비스 레이어에 View 로직이 같이 있네요! 서비스의 역할이 너무 커진 건 아닐까요? 분리해보는 건 어떨까요?

2023-09-28 05:26 UTC, aegis1920 commented on src/main/java/com/programmers/librarymanagement/repository/TestBookRepository.java
> +                .filter(book -> book.getId().equals(id))
> 객체지향적인 구현 측면에서 개선할만한 부분이 있는지 궁금합니다.

book에 있는 것을 get 하지 않고 book에게 tell 하는 건 어떨까요? book.isSame(id) 이런 식으로요!

다른 곳에서도 tell 하도록 바꿀 수 있는 부분이 보이는데 바꿔보시죠!

2023-09-28 05:26 UTC, aegis1920 commented on src/main/java/com/programmers/librarymanagement/utils/ConsoleIo.java
> +        }
> 직접 구현한 예외 이외의 예외(ex. IOException)들은 try-catch 문으로 처리했는데 괜찮게 처리한 것인지 궁금합니다.

넵! 잘 처리해주셨어요! 그런데 여기서 RuntimeException을 다시 던지잖아요? 
그러면 어플리케이션이 어떻게 되나요? 그 상황을 방지하려면 어떻게 해야할까요?

2023-09-28 05:26 UTC, aegis1920 commented on src/main/java/com/programmers/librarymanagement/domain/Book.java
> +    public Book(Long id, String title, String author, int page, Status status, LocalDateTime returnDateTime) {
> 도서 상태를 변경하거나 반납 일시를 변경함에 있어 setter를 사용하고 싶지 않아 지양하는 방향으로 코드를 짜다보니 Book 생성자를 다소 과하게 사용한 것 같다는 생각이 듭니다. 이런 상황에서는 차라리 setter를 사용하는 것이 좋은가요? 아니면 Book 생성자로 객체를 자주 생성하게 되더라도 setter는 아예 사용하지 않는 것이 좋은가요?

아뇨 잘하셨어요! 가급적이면 setter를 사용하지 않는 상황을 만드는 게 중요합니다! setter를 사용하기 시작하면 상태가 계속 변화하는 객체가 유지되기 때문에 사용하지 않는 게 좋습니다.

지금 setter가 없어서 java 17에 나온 record 키워드를 사용할 수도 있겠네요!

2023-09-28 05:26 UTC, aegis1920 commented on src/main/java/com/programmers/librarymanagement/repository/TestBookRepository.java
> +    private static long sequence = 0L;
일반 모드에서는 1부터 시작하는데 테스트는 0부터 시작하네요. 일관성을 맞춰주시면 좋을 것 같습니다!

2023-09-28 05:26 UTC, aegis1920 commented on src/main/java/com/programmers/librarymanagement/application/LibraryManagementService.java
> +                if (book.getReturnDateTime().plusMinutes(5).isAfter(LocalDateTime.now())) {
조건이 맞는지 확인 한 번 부탁드려요! 🙂

2023-09-28 06:54 UTC, cloudwi commented on src/main/java/com/programmers/librarymanagement/presentation/LibraryManagementController.java
> +            default -> throw new SelectNotFoundException();
예외를 활용해서 시스템을 컨트롤 해보는 것은 어떤가요?

지금 현재 선택지 이외의 값을 입력하면 시스템이 종료되고 있는데 
사용자가 잘못된 값을 입력한다고 시스템이 종료하는 것을 의도하셨나요?

2023-09-28 06:54 UTC, cloudwi commented on src/main/java/com/programmers/librarymanagement/presentation/LibraryManagementController.java
> +        int page = Integer.parseInt(consoleIo.getInput());
멘토님의 말에 추상적인 첨언을 하자면 방어적인 코드를 생각해 보시면 좋을 것 같아요.

2023-09-28 06:54 UTC, cloudwi commented on src/main/java/com/programmers/librarymanagement/utils/CsvFileIo.java
> +            bw.close();
자원을 직접 관리하기 위해서 close를 명시적으로 사용하신것 같아요.

하지만 close를 호출하기전에 예외가 발생한다면 어떻게 동작할까요?

2023-09-28 06:54 UTC, cloudwi commented on src/test/java/com/programmers/librarymanagement/NormalManagementServiceTest.java
> +    @BeforeAll
test 사이에 결합이 강하게 생기지 않을까요?

2023-10-01 16:01 UTC, letskuku commented on src/test/java/com/programmers/librarymanagement/NormalManagementServiceTest.java
> +@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
혼자 작성한 프로그램이다보니 다른 사람이 추가적으로 참여하는 경우는 가정해보지 못했던 것 같습니다 그렇게 말씀해주시니 뭐가 문제인지 확실히 알 것 같네요...!
테스트 코드는 각각의 코드들이 의도한대로 동작하는지 확인하는 것에 의미가 있지 않을까요? 단, 종속적이지 않은 테스트 코드를 작성하는 것이 중요할 것 같습니다 그러한 면에서 저의 코드는 많은 문제가 있다고 생각되네요...😥

2023-10-01 16:05 UTC, letskuku commented on src/test/java/com/programmers/librarymanagement/NormalManagementServiceTest.java
> +    void successFindByTitle() {
따로 실행시킬 경우, findByTitle 실행 결과 반환된 bookList의 크기는 2이기 때문에 테스트를 통과하지 못합니다
BeforeAll을 통해 NormalBookRepository를 주입받아 모든 테스트 코드에 하나의 NormalBookRepository만을 사용하려한 것이 문제인 것 같습니다! 매번 새로 의존성을 주입하도록 수정하겠습니다

2023-10-01 16:09 UTC, letskuku commented on src/test/java/com/programmers/librarymanagement/NormalManagementServiceTest.java
> +public class NormalManagementServiceTest {
테스트 커버리지는 리뷰 달아주셔서 처음 찾아보게 된 개념입니다 커버리지 100%를 달성한다면 뿌듯함을 느낄 수 있을 것 같네요... 도전해보도록 하겠습니다💪

2023-10-01 16:11 UTC, letskuku commented on src/test/java/com/programmers/librarymanagement/NormalManagementServiceTest.java
> +    static NormalBookRepository normalBookRepository;
테스트 코드에서 이 부분을 가장 먼저 작성하고 이후에 하위 테스트 코드들을 작성하였는데, 돌아보니 이 부분으로 인해 더욱 테스트 코드들끼리의 결합도가 높아지지 않았나 하는 생각이 듭니다... 수정하도록 하겠습니다

2023-10-01 16:15 UTC, letskuku commented on src/main/java/com/programmers/librarymanagement/application/LibraryManagementService.java
> +        String result = "[System] 도서가 대여 처리 되었습니다. \n";
저도 코드를 작성하는 동안 이 부분이 고민이 되었는데, 당시에는 이 방법이 아니면 rentBook의 반환값으로 대여성공/대여불가/정리중/분실을 의미하는 enum이나 숫자를 넘겨주는 방법밖에는 떠오르지 않아 차라리 문자열을 반환하는 것이 더 깔끔하지 않을까 하는 생각이 들었습니다
view에 해당하는 문자열과 서비스 로직은 당연히 분리되어야 한다고 생각합니다...!

2023-10-01 16:16 UTC, letskuku commented on src/main/java/com/programmers/librarymanagement/application/LibraryManagementService.java
> +                if (book.getReturnDateTime().plusMinutes(5).isAfter(LocalDateTime.now())) {
맞는 말씀인 것 같습니다! 상수 처리해줄 생각을 못했네요...

2023-10-01 16:17 UTC, letskuku commented on src/main/java/com/programmers/librarymanagement/domain/Status.java
> +    CANNOT_RENT("대여중"), // 대여중
의미에 더 맞는 이름으로 수정하도록 하겠습니다!

2023-10-01 16:18 UTC, letskuku commented on src/main/java/com/programmers/librarymanagement/domain/Status.java
> +    private final String value;
반영하도록 하겠습니다~

2023-10-01 16:19 UTC, letskuku commented on src/main/java/com/programmers/librarymanagement/presentation/LibraryManagementController.java
> +        int page = Integer.parseInt(consoleIo.getInput());
적절한 값인지 검증하는 로직을 추가하도록 하겠습니다

2023-10-01 16:19 UTC, letskuku commented on src/main/java/com/programmers/librarymanagement/presentation/LibraryManagementController.java
> +        String title = consoleIo.getInput();
반영하도록 하겠습니다

2023-10-01 16:20 UTC, letskuku commented on src/main/java/com/programmers/librarymanagement/utils/CsvFileIo.java
> +    String PATH = System.getProperty("user.dir") + "/src/main/resources/data.csv";
상수를 의미했던 것이 맞습니다! 위치 수정은 class 바깥으로 옮기라는 말씀이실까요...?

2023-10-01 16:23 UTC, letskuku commented on src/main/java/com/programmers/librarymanagement/repository/NormalBookRepository.java
> +    private static final Map<Long, Book> libraryStorage = addBookByFile(csvFileIo.readCsv());
private static final이 상수의 의미로 쓰이는 줄 몰랐습니다...! 수정하도록 하겠습니다

2023-10-01 16:25 UTC, letskuku commented on src/main/java/com/programmers/librarymanagement/utils/ConsoleIo.java
> +        }
예외를 던질 생각만 했지 가지고 추가적으로 처리할 생각은 못 했던 것 같습니다 올바른 방향으로 수정하겠습니다

2023-10-01 16:26 UTC, letskuku commented on src/main/java/com/programmers/librarymanagement/domain/Book.java
> +    public Book(Long id, String title, String author, int page, Status status, LocalDateTime returnDateTime) {
인텔리제이에서도 record를 사용할 수 있다고 메시지가 떴었습니다 java 17에서 새롭게 나온 개념이군요...! 공부해보도록 하겠습니다

2023-10-01 16:30 UTC, letskuku commented on src/main/java/com/programmers/librarymanagement/presentation/LibraryManagementController.java
> +            default -> throw new SelectNotFoundException();
종료보다는 사용자가 알맞은 값을 입력하도록 안내하는 것이 좋을 것 같습니다!

2023-10-01 16:31 UTC, letskuku commented on src/main/java/com/programmers/librarymanagement/utils/CsvFileIo.java
> +            bw.close();
bufferedWriter는 자주 사용해보지 않아 구글링에 많이 의존했던 것 같습니다... 고민해보도록 하겠습니다!

2023-10-01 16:32 UTC, letskuku commented on src/test/java/com/programmers/librarymanagement/NormalManagementServiceTest.java
> +    @BeforeAll
여기서부터 테스트 코드에서의 문제가 시작된 것 같습니다... 수정하도록 하겠습니다

2023-10-01 20:49 UTC, letskuku commented
말씀해주신 부분들 최대한 반영하여 수정하고자 하였습니다!
service와 view 로직을 분리해보았는데, 나중에 추가적으로 보완한다면 controller에서도 view 로직을 분리하려고 합니다

2023-10-02 04:07 UTC, cloudwi reviewed
입출력 기능을 분리하는 것은 어떤가요?

2023-10-02 04:08 UTC, cloudwi commented on src/main/java/com/programmers/librarymanagement/presentation/LibraryManagementController.java
> +                System.out.println("[System] 테스트 모드로 애플리케이션을 실행합니다. \n");
입 출력 기능을 따로 분리하는 것은 어떤가요?

2023-10-02 04:10 UTC, cloudwi commented on src/main/java/com/programmers/librarymanagement/presentation/LibraryManagementController.java
> +                System.out.println("[System] 테스트 모드로 애플리케이션을 실행합니다. \n");
컨트롤러 로직에 입출력 코드와 함께 섞여 있어서 가독성이 내려가는 것 같아요. 

유정님도 보시다가 복잡성을 느끼셨나요?

2023-10-02 04:11 UTC, cloudwi commented on src/main/java/com/programmers/librarymanagement/utils/ConsoleIo.java
> +        } catch (IOException e) {
언체크 예외를 활용해서 예외를 던지고

어플리케이션이나 컨트롤러단 에서 한번에 처리하는 것은 어떤가요?

2023-10-02 04:13 UTC, cloudwi commented on src/main/java/com/programmers/librarymanagement/utils/ConsoleIo.java
> +        // 입력받은 문자 검증
입력 중 "01"은 1을 나타내는 건가요? 혹은 잘못된 입력일까요?

현재 동작은 

존재하지 않는 선택지입니다. 다시 입력해주세요. 라고 말하고 있어요.

2023-10-02 04:17 UTC, cloudwi commented on src/main/java/com/programmers/librarymanagement/presentation/LibraryManagementController.java
> +        int page = Integer.parseInt(consoleIo.getInputNum());
consoleIo.getInputNum()
이름을 보았을때 숫자를 입력받는 형태인데 반환형은 String 입니다.

반환형을 변경해 보시는건 어떤가요?
또 고민은 형 변환 책임은 누가 가지는게 좋을까요?

2023-10-02 04:20 UTC, cloudwi commented on src/main/java/com/programmers/librarymanagement/application/LibraryManagementService.java
> +        Book book = new Book(bookRepository.createId(), title, author, page, Status.CAN_RENT, LocalDateTime.now());
책을 생성하기 전에 bookID를 먼저 만들고 있어요.

혹시 책 생성 중 문제가 발생하면 불필요한 아이디가 지속적으로 생성될것 같다는 생각이 들어요.

따라서 다른 시점에 아이디를 생성하는 것은 어떤가요?

2023-10-02 04:21 UTC, cloudwi commented on src/main/java/com/programmers/librarymanagement/application/LibraryManagementService.java
> +        Book book = bookRepository.findById(id).orElseThrow(BookNotFoundException::new);
책을 찾지 못하면 서비스가 종료되는 건 의도한 가능일까요?

2023-10-02 04:24 UTC, cloudwi commented on src/main/java/com/programmers/librarymanagement/application/LibraryManagementService.java
> +        switch (book.getStatus()) {
book.getStatus()를 2회 호출하고 있어요.

해당 코드는 꼭 2번 호출 해야하는 걸까요?
줄일 수 있을 것 으로 보여요.

2023-10-02 04:26 UTC, cloudwi commented on src/main/java/com/programmers/librarymanagement/application/LibraryManagementService.java
> +                Book rentBook = new Book(book.getId(), book.getTitle(), book.getAuthor(), book.getPage(), Status.ALREADY_RENT, book.getReturnDateTime());
책을 새롭게 new 해서 업데이트를 하고 있어요.

새롭게 생성하지 않고 기존의 책의 상태를 변경하고 bookRepository.updateBook() 메서드에 넣는 것은 어떻게 생각하시나요?

2023-10-02 04:26 UTC, cloudwi commented on src/main/java/com/programmers/librarymanagement/application/LibraryManagementService.java
> +                    Book arrangeBook = new Book(book.getId(), book.getTitle(), book.getAuthor(), book.getPage(), Status.ALREADY_RENT, book.getReturnDateTime());
이곳도 위와 동일한 리뷰를 남겨요.

2023-10-02 04:27 UTC, cloudwi commented on src/main/java/com/programmers/librarymanagement/application/LibraryManagementService.java
> +        ReturnResult result = ReturnResult.SUCCESS_RETURN;
상태 값을 사용하는 것 보단 예외를 이용해서 로직을 처리해 보시는 건 어떤가요?

예외가 발생하지 않으면 정상적으로 처리된 것이고 예외가 발생하였다면 어떤 문제가 있는지 알려주면 좋을 것 같아요.

2023-10-02 04:29 UTC, cloudwi commented on src/main/java/com/programmers/librarymanagement/application/LibraryManagementService.java
> +    public Boolean lostBook(Long id) {
왜 null을 담을 수 있는 Boolean을 사용했나요?

2023-10-02 04:30 UTC, cloudwi commented on src/main/java/com/programmers/librarymanagement/application/LibraryManagementService.java
> +                Book missBook = new Book(book.getId(), book.getTitle(), book.getAuthor(), book.getPage(), Status.LOST, book.getReturnDateTime());
이 곳도 왜 책을 새롭게 생성하고 있나요? 

status를 변경해서 업데이트 하면 안될까요?

2023-10-02 04:32 UTC, cloudwi commented on src/main/java/com/programmers/librarymanagement/application/LibraryManagementService.java
> +        Book book = bookRepository.findById(id).orElseThrow(BookNotFoundException::new);
해당 하는 곳도 예외가 발생하면 서비스가 종료되어 버립니다.

의도한 기능일 까요?

2023-10-02 04:32 UTC, cloudwi commented on src/main/java/com/programmers/librarymanagement/application/LibraryManagementService.java
> +                Book statusBook = new Book(book.getId(), book.getTitle(), book.getAuthor(), book.getPage(), Status.CAN_RENT, book.getReturnDateTime());
이곳도 새롭게 new 하고 있어요.

2023-10-02 04:35 UTC, cloudwi commented on src/main/java/com/programmers/librarymanagement/domain/ReturnResult.java
> +public enum ReturnResult {
enum Map 과 같은 컬랙션을 활용해서 조금 더 효율적으로 처리해 보시면 어떨까요?

2023-10-02 04:35 UTC, cloudwi commented on src/main/java/com/programmers/librarymanagement/domain/Status.java
> +public enum Status {
조금 더 효율적으로 처리해 보시면 어떨까요?

2023-10-02 04:36 UTC, cloudwi commented on src/main/java/com/programmers/librarymanagement/repository/TestBookRepository.java
> +                .filter(book -> book.getId().equals(id))
멘토님과 동일한 생각을해요.

책의 값을 가지고 오는 것이 아니라 책에게 일치하는지 여부를 물어보는 것은 어떤가요?

2023-10-02 04:37 UTC, cloudwi commented on src/main/java/com/programmers/librarymanagement/repository/TestBookRepository.java
> +        Book originalBook = findById(book.getId()).orElseThrow(BookNotFoundException::new);
책을 찾지 못한다면 시스템이 종료 되는 것 같아요.

2023-10-02 04:38 UTC, cloudwi commented on src/main/java/com/programmers/librarymanagement/repository/TestBookRepository.java
> +    private final List<Book> testStorage = new ArrayList<>();
testStorage를 List로 사용하신 이유가 있을까요?

2023-10-02 04:42 UTC, cloudwi commented on src/main/java/com/programmers/librarymanagement/repository/TestBookRepository.java
> +    private final List<Book> testStorage = new ArrayList<>();
아래의 업데이트와 연관성이 있어요.

2023-10-02 04:43 UTC, cloudwi commented on src/main/java/com/programmers/librarymanagement/repository/TestBookRepository.java
> +        testStorage.remove(originalBook);
객체를 삭제하고 추가하는 로직이 실행되고 있어요.

하지만 최적화할 수 있을 것 같아요.

자바 List에 set 기능을 찾아보시면 좋을것 같아요.

2023-10-02 04:51 UTC, cloudwi commented
과제 하시느라 고생하셨습니다. 😀

2023-10-02 04:58 UTC, letskuku commented on src/main/java/com/programmers/librarymanagement/presentation/LibraryManagementController.java
> +                System.out.println("[System] 테스트 모드로 애플리케이션을 실행합니다. \n");
일단은 service와 입출력 코드는 분리하였고, controller에서도 분리할 예정입니다
그런데 분리하려다보니 출력문 한 줄만을 가지고 있는 메서드가 생기게 되네요... 함수 호출에 드는 오버헤드를 감안하더라도 분리하는 것이 더 옳은 방향인가요?

2023-10-02 04:58 UTC, letskuku commented on src/main/java/com/programmers/librarymanagement/utils/ConsoleIo.java
> +        } catch (IOException e) {
오! 좋은 방법인 것 같습니다 참고하겠습니다

2023-10-02 05:14 UTC, letskuku commented on src/main/java/com/programmers/librarymanagement/presentation/LibraryManagementController.java
> +        int page = Integer.parseInt(consoleIo.getInputNum());
반환형이 int인 것이 더 바람직하겠지만, 이 부분은 예외 처리를 하는 과정에서 이렇게 두게 되었습니다...
```java
System.out.print("> ");

String input;

// IOException 처리
try {
     input = br.readLine().strip();
} catch (IOException e) {
     System.out.println("[System] 올바른 입력 형식이 아닙니다. 다시 입력해주세요. \n");
     input = this.getInputNum();
}
```
try-catch에서 getInputNum을 재귀호출하게 되는데, 반환형을 int로 설정하면 input과 타입이 맞지 않습니다
그렇다고 input을 int로 두자니 문자 형식을 검증하는 로직은 밑에 있는데 try에서 형 변환을 하는 것은 올바르지 않다고 생각했습니다
입력을 다시 요청하는 방식으로 재귀호출만을 생각하여 이렇게 구현하게 되었는데, 오늘 try-catch에서 while문을 활용하기도 한다는 조언을 받아 적용 후 수정해보려고 합니다!

2023-10-02 05:21 UTC, letskuku commented on src/main/java/com/programmers/librarymanagement/application/LibraryManagementService.java
> +    public Boolean lostBook(Long id) {
null 값까지는 고려하지 못했습니다... enum을 많이 만들고 싶지 않아 두 가지의 결과를 반환하는 경우는 boolean을 사용하였습니다

2023-10-02 05:24 UTC, letskuku commented on src/main/java/com/programmers/librarymanagement/repository/TestBookRepository.java
> +    private final List<Book> testStorage = new ArrayList<>();
과제의 요구사항을 그대로 반영한 결과 입니다!
```
애플리케이션은 '테스트 모드'를 지원해야합니다. 
테스트 모드에서는 파일에서 데이터를 읽거나 쓰지 않고 오직 콘솔 입력을 통해서만 데이터를 입력 받고, 저장도 List에만 저장합니다. 
당연히 애플리케이션을 재시작하면 모든 데이터는 날아갑니다. 
테스트 모드로 실행할지 일반 모드로 실행할지는 애플리케이션을 시작할 때 입력에 따라 결정됩니다.
```

2023-10-03 14:17 UTC, aegis1920 commented on src/test/java/com/programmers/librarymanagement/NormalManagementServiceTest.java
> +@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
> 서로에게 종속적이지 않은 테스트 코드를 작성하는 것이 중요할 것 같습니다

잘 파악해주셨네요! 👍 테스트는 언제 테스트하든 항상 성공해야 하는 걸 잊지 마세요.

2023-10-03 14:19 UTC, aegis1920 commented on src/main/java/com/programmers/librarymanagement/application/LibraryManagementService.java
> +        String result = "[System] 도서가 대여 처리 되었습니다. \n";
출력하고자 하는 문자열이 서비스 로직에 있으면 View 단을 바꿀 때 서비스 로직도 바뀝니다. 이 점 주의해서 작성해주세요!

2023-10-03 14:20 UTC, aegis1920 commented on src/main/java/com/programmers/librarymanagement/utils/CsvFileIo.java
> +    String PATH = System.getProperty("user.dir") + "/src/main/resources/data.csv";
구두로 말씀드렸다시피 상수 위치 관례를 이야기했습니다!

2023-10-04 05:06 UTC, letskuku commented on src/main/java/com/programmers/librarymanagement/domain/ReturnResult.java
> +public enum ReturnResult {
현재 코드 상에서 enum을 사용하고 있긴 하지만 enum을 키로 하는 map을 활용할 수 있는 부분은 없는 것 같습니다!
추후에 사용할 부분이 생긴다면 적용해보도록 하겠습니다

2023-10-04 18:00 UTC, letskuku commented on src/main/java/com/programmers/librarymanagement/utils/ConsoleIo.java
> +        // 입력받은 문자 검증
switch문에 넣는 값인 getInputNum의 반환형을 int로 변경해주면서 "01"로 입력하여도 1로 인식하도록 수정되었습니다!

2023-10-04 18:10 UTC, letskuku commented on src/main/java/com/programmers/librarymanagement/application/LibraryManagementService.java
> +        Book book = new Book(bookRepository.createId(), title, author, page, Status.CAN_RENT, LocalDateTime.now());
무슨 말씀인지는 이해하였으나 순수 자바로 작성한 프로젝트에서 Book 객체를 생성한 이후에 id 값을 넣어주는 방법은 setter 밖에는 없는 것 같습니다...! setter를 최대한 사용하고 싶지 않아 현재로서는 위 방법이 최선이라고 생각합니다

2023-10-04 18:20 UTC, letskuku commented on src/main/java/com/programmers/librarymanagement/application/LibraryManagementService.java
> +    public Boolean lostBook(Long id) {
그런데 enum도 null을 담을 수 있지 않나요...?

2023-10-04 18:29 UTC, letskuku commented on src/main/java/com/programmers/librarymanagement/application/LibraryManagementService.java
> +        Book book = bookRepository.findById(id).orElseThrow(BookNotFoundException::new);
고민해보았는데 BookNotFoundException을 catch하여 입력한 도서 번호에 해당하는 도서가 없음을 안내한 후, 기능 선택으로 돌아가도록 설정하는 것이 좋을 것 같습니다!

2023-10-05 09:55 UTC, cloudwi commented on src/main/java/com/programmers/librarymanagement/presentation/LibraryManagementController.java
> +                System.out.println("[System] 테스트 모드로 애플리케이션을 실행합니다. \n");
더 집중화 시킬 기능이 없다면 유정님 의견대로 불필요한 작업인것 같아요!

2023-10-05 09:57 UTC, cloudwi commented on src/main/java/com/programmers/librarymanagement/application/LibraryManagementService.java
> +    public Boolean lostBook(Long id) {
반환형 중에 Null이 필요할까요?

2023-10-05 17:13 UTC, letskuku commented on src/main/java/com/programmers/librarymanagement/presentation/LibraryManagementController.java
> +                System.out.println("[System] 테스트 모드로 애플리케이션을 실행합니다. \n");
불필요한 작업인 것 같기도 하지만 분리하는 것이 유지보수 면에서 좋다고 생각되어 분리하였습니다!

2023-10-05 17:34 UTC, letskuku commented on src/main/java/com/programmers/librarymanagement/application/LibraryManagementService.java
> +    public Boolean lostBook(Long id) {
null은 필요하지 않다고 생각합니다! 
다만 boolean은 null을 담을 수 있어 대체제(?)로 enum을 떠올렸는데, 생각해보니 enum도 null을 담을 수 있다는 점이 걸리네요...

2023-10-05 17:35 UTC, letskuku commented on src/main/java/com/programmers/librarymanagement/application/LibraryManagementService.java
> +                Book rentBook = new Book(book.getId(), book.getTitle(), book.getAuthor(), book.getPage(), Status.ALREADY_RENT, book.getReturnDateTime());
Book 도메인에 책의 상태를 변경할 수 있는 메서드를 추가하도록 하겠습니다!

2023-10-05 17:53 UTC, letskuku commented on src/main/java/com/programmers/librarymanagement/application/LibraryManagementService.java
> +        switch (book.getStatus()) {
코드 리팩토링하였습니다!

2023-10-05 17:55 UTC, letskuku commented on src/main/java/com/programmers/librarymanagement/domain/Status.java
> +public enum Status {
이 부분도 ReturnResult와 마찬가지로 Enum Map을 활용할 수 있는 부분은 아니라고 생각했습니다!

2023-10-05 18:16 UTC, letskuku commented on src/main/java/com/programmers/librarymanagement/application/LibraryManagementService.java
> +        ReturnResult result = ReturnResult.SUCCESS_RETURN;
enum을 만들어 사용하는 것보다 올바른 방향인 것 같습니다! 수정해보도록 하겠습니다

2023-10-05 18:54 UTC, letskuku commented on src/main/java/com/programmers/librarymanagement/application/LibraryManagementService.java
> +    public Boolean lostBook(Long id) {
예외를 이용한 로직 처리로 아예 반환값이 없도록 수정되었습니다

2023-10-05 19:06 UTC, letskuku commented on src/main/java/com/programmers/librarymanagement/repository/TestBookRepository.java
> +                .filter(book -> book.getId().equals(id))
findById와 findByTitle에서 로직 수정하였습니다!

2023-10-05 19:13 UTC, letskuku commented on src/main/java/com/programmers/librarymanagement/repository/TestBookRepository.java
> +        Book originalBook = findById(book.getId()).orElseThrow(BookNotFoundException::new);
controller에서 처리하도록 수정하였습니다!

2023-10-05 19:26 UTC, letskuku commented on src/main/java/com/programmers/librarymanagement/repository/TestBookRepository.java
> +        testStorage.remove(originalBook);
List의 set 메서드를 사용할 경우, 수정하고자 하는 book 객체의 저장 순서를 알아야 합니다
따라서 현재의 방식대로 remove -> add하거나, set을 사용하는 경우 indexOf -> set의 과정을 거쳐야 합니다
어떤 방식이 시간복잡도 면에서 더 효율적일지 검색해보았는데 remove와 indexOf가 O(N), add와 set이 O(1)이라 차이는 없을 것으로 생각합니다
하지만 set을 사용하는 것이 값을 수정하고자 하는 의미가 더 잘 보이는 것 같아 수정하도록 하겠습니다!

2023-10-05 19:49 UTC, letskuku commented
리뷰 반영한 코드 수정 완료하였습니다!
전체적으로 많이 수정되었는데, 아예 파일이 추가된 경우는 다음과 같습니다 (최상단의 PR comment에도 추가된 부분 관련 내용 작성하였습니다)
1. 도서 등록 기능 실행 시 입력 받는 제목, 작가, 페이지 수 정보를 담는 dto 추가
2. 도서 대여 / 반납 / 분실 기능 실행 시 정상 동작 외의 동작들을 예외로 처리하면서 작성한 Exception 추가

2023-10-06 10:58 UTC, cloudwi commented
고생했어요!

2023-10-06 11:25 UTC, letskuku commented
미팅 중에 생각해보니 getBookByTitle에도 updateAllStatus가 필요한데 추가하지 못한 것 같아 추가하였습니다...😅

2023-10-07 05:48 UTC, aegis1920 approved these changes
간단하게 코멘트 조금 더 남겼습니다~
반영해주셔도 되고 반영하지 않으셔도 됩니다!
고생 많으셨어요! 👍

2023-10-07 05:48 UTC, aegis1920 commented on src/main/java/com/programmers/librarymanagement/utils/ConsoleIo.java
> +            }
최대 100글자까지 입력할 수 있다는 건 입력에 대한 검증일까요? 아니면 도메인에 대한 검증일까요? 도메인에 대한 검증이라면 ConsoleIo 클래스에서 검증 로직이 있는 게 맞을지, 도메인에 대한 검증을 어디서 할 지도 고민해보셨으면 좋겠습니다! (만약 입력 검증이 아니고 도메인 검증이라면 이걸 Request 객체에서 할 지, Book 도메인 객체에서 할 지, 그 중간에서 쓰이는 DTO에서 할 지 등등이요!)

2023-10-07 05:48 UTC, aegis1920 commented on src/main/java/com/programmers/librarymanagement/utils/CsvFileIo.java
> +            bw.close();
BufferedWriter를 타고 들어가보면 AutoCloseable이라는 인터페이스가 있는데요. 이 인터페이스가 있으면 try-with-resource를 사용할 수 있습니다. close를 위해 좀 더 안전하게 사용할 수 있는 구문이니 한 번 적용해보세요!

2023-10-07 05:48 UTC, aegis1920 commented on src/test/java/com/programmers/librarymanagement/NormalManagementServiceTest.java
> +    @AfterEach
Repository를 Clear하기 위해서 AfterEach, BeforeEach를 둘 중 하나를 선택해서 구현하셨을 것 같은데요. AfterEach를 선택하신 이유가 있을까요?

2023-10-07 05:48 UTC, aegis1920 commented on src/test/java/com/programmers/librarymanagement/NormalManagementServiceTest.java
> +@DisplayName("Service test for NormalBookRepository")
DisplayName을 사용하는 이유가 무엇일까요? 테스트 명을 한글로 작성하기도 하니 테스트 메서드 이름 컨벤션을 한 번 찾아보셔도 좋을 것 같습니다!

2023-10-07 05:48 UTC, aegis1920 commented on src/test/java/com/programmers/librarymanagement/NormalManagementServiceTest.java
> +    void failDeleteBook() {
나중에 시간 되시면 5분 이후에 대여 가능으로 처리되는 부분도 테스트를 작성해보세요!

2023-10-07 05:48 UTC, aegis1920 commented on src/main/java/com/programmers/librarymanagement/application/LibraryManagementService.java
> +    private void updateAllStatus() {
메서드 이름이 좀 더 명확하면 좋을 것 같습니다. 단순히 메서드명만 보고 이해하기에는 '모든 상태를 변경한다'로만 이해가 되네요.

2023-10-07 05:48 UTC, aegis1920 commented on src/main/java/com/programmers/librarymanagement/repository/NormalBookRepository.java
> +        return new ArrayList<>(libraryStorage.values());
조회 용도로 새로운 리스트로 감쌀 거라면 그 리스트에 대해 변경가능성이 최대한 적게 Immutable로 만드는 것이 좋습니다.

```suggestion
        return libraryStorage.values()
                .stream()
                .toList();
```

2023-10-07 05:48 UTC, aegis1920 commented on build.gradle
파일 포맷팅이 안된 것 같네요?

2023-10-07 05:48 UTC, aegis1920 commented on src/main/java/com/programmers/librarymanagement/application/LibraryManagementService.java
> +        List<Book> bookList = bookRepository.findAll();
자료구조에 용이하게 변수명을 쓰기 위해서 books로 바꾸는 건 어떨까요?
```suggestion
        List<Book> books = bookRepository.findAll();
```

2023-10-07 16:18 UTC, letskuku commented on src/main/java/com/programmers/librarymanagement/utils/CsvFileIo.java
> +            bw.close();
try-with-resources라는 문법이 있는 줄 몰랐는데 자바7부터 도입된 문법이었군요...!
어떤 편리함이 있는지 조사해보았습니다

사용 후에 반납해주어야 하는 자원들은 Closable 인터페이스를 구현하고 있으며, 사용 후에 close 메소드를 호출해주어야 했다.
Java7부터 AutoCloseable 인터페이스를 구현하고 있는 자원에 대해 try-with-resources를 적용 가능하도록 하였고, 이것은 자원을 자동으로 반납해준다.

try-with-resources로 자원을 반납할 경우,
1. 코드를 간결하게 만들 수 있다
2. 번거로운 자원 반납 작업을 하지 않아도 된다
3. 실수로 자원을 반납하지 못하는 경우를 방지할 수 있다
4. 에러로 자원을 반납하지 못하는 경우를 방지할 수 있다
5. 모든 에러에 대한 스택 트레이스를 남길 수 있다

2023-10-07 16:39 UTC, letskuku commented on src/main/java/com/programmers/librarymanagement/utils/ConsoleIo.java
> +            }
입력에 대한 검증으로 생각했습니다!
만약 도메인에 대한 검증을 추가한다면... 어디가 가장 적합할까요? requestDto는 단순히 계층 간의 데이터 전달을 위한 객체라고 생각합니다 따라서 검증이 필요하다면 dto가 전달된 service에서 하는게 어떨까요...?

2023-10-07 16:42 UTC, letskuku commented on src/test/java/com/programmers/librarymanagement/NormalManagementServiceTest.java
> +    @AfterEach
처음 테스트를 시작할 때는 clear 해줄 필요가 없다고 생각하여 AfterEach를 선택하였습니다! 생각해보니 처음부터 repository가 비어있다는 것을 확실히 해주기 위해 BeforeEach를 사용해주는 것도 괜찮을 것 같네요...🤔

2023-10-07 16:45 UTC, letskuku commented on src/test/java/com/programmers/librarymanagement/NormalManagementServiceTest.java
> +@DisplayName("Service test for NormalBookRepository")
무엇을 위한 테스트 클래스인지 클래스 이름보다 명확한 의미를 나타내고자 작성하였습니다!
테스트 명을 한글로 작성할 수 있다는 것은 알고 있었는데 네이밍 컨벤션이 따로 존재하는 줄은 몰랐네요...! 찾아보니 다양한 컨벤션이 있는데 멘토님은 어떤 컨벤션을 선호하시는 편인가요?

2023-10-07 16:50 UTC, letskuku commented on src/test/java/com/programmers/librarymanagement/NormalManagementServiceTest.java
> +    void failDeleteBook() {
커피챗 때 말씀해주셨던 '테스트 가능한 코드'에 대한 부분이 제 코드에서 제일 아쉬운 부분이라고 생각합니다!
나중에 여유가 된다면 시간을 함수 매개변수로 넣도록 코드를 수정해보겠습니다

2023-10-07 16:57 UTC, letskuku commented on src/main/java/com/programmers/librarymanagement/application/LibraryManagementService.java
> +        List<Book> bookList = bookRepository.findAll();
자료구조가 List라서 bookList라는 변수명을 사용한 것은 아닙니다! '목록'이라는 의미를 생각하고 붙인 이름입니다
하지만 사람에 따라 List가 자료구조의 의미로 생각될 수 있을 것 같아 다음부터는 조금더 유연한 네이밍을 할 수 있도록 주의하겠습니다

2023-10-07 16:59 UTC, letskuku commented on src/main/java/com/programmers/librarymanagement/application/LibraryManagementService.java
> +    private void updateAllStatus() {
일리있는 말씀인 것 같습니다 수정하도록 하겠습니다!

2023-10-07 17:01 UTC, letskuku commented on src/main/java/com/programmers/librarymanagement/repository/NormalBookRepository.java
> +        return new ArrayList<>(libraryStorage.values());
mutable, immutable까지는 생각하지 못 했습니다... 수정하도록 하겠습니다!

2023-10-07 17:07 UTC, letskuku commented on build.gradle
지난번 리뷰에서 포맷팅 지적해주셨을 때 직접 작성한 코드들만 체크하여 놓친 것 같습니다...!
다음부터는 더 주의하도록 하겠습니다

2023-10-09 10:16 UTC, aegis1920 commented on src/main/java/com/programmers/librarymanagement/utils/CsvFileIo.java
> +            bw.close();
장점까지 조사해주셨군요 👍

2023-10-09 10:18 UTC, aegis1920 commented on src/test/java/com/programmers/librarymanagement/NormalManagementServiceTest.java
> +    @AfterEach
잘 설명해주셨네요! 👍 저도 테스트를 시작하기 전에 명확하게 클리어했다는 이유로 BeforeEach를 더 선호하긴 합니다!

2023-10-09 10:19 UTC, aegis1920 commented on src/test/java/com/programmers/librarymanagement/NormalManagementServiceTest.java
> +@DisplayName("Service test for NormalBookRepository")
개인차가 있을텐데요. 저는 테스트 함수명 자체를 한글로 작성하는 걸 선호합니다ㅎㅎ 가장 직관적이라고 생각들어서요!

2023-10-09 10:22 UTC, aegis1920 commented
과제도 열심히 해주시고 끝까지 반영하시느라 고생 많으셨습니다! 👍 
과제는 여기서 머지하겠습니다! 이후에 궁금한 점이 있으시면 DM주시거나 코멘트 따로 남겨주세요!

2023-10-09 10:22 UTC, merged