[5기 - 김강훈] 1~2주차 과제: 도서 관리 어플리케이션 제출합니다.
prgrms-be-devcourse/java-library-management pull request #12
Opened 2023-09-27 20:39 UTC by kkangh00n

## 📌 과제 설명 
- 자바를 이용한 도서 관리 어플리케이션입니다.
- console을 이용해 사용자와 도서에 대한 정보를 주고받습니다
- 일반 모드와 테스트 모드로 나뉘며, 일반 모드는 csv파일로, 테스트 모드는 컬렉션 List로 도서를 관리합니다.

## 👩‍💻 요구 사항과 구현 내용 

- Client : 사용자의 동작을 관리합니다. Mode 선택 후 Function을 선택합니다. 메뉴에 있지 않은 선택을 하게 될 때의 적절한 조치를 취합니다.
- ConsoleManager : 동작마다 입출력을 담당합니다. 입력받은 결과를 Client에게 전달하고 Service 동작 결과를 사용자에게 출력합니다.
- Service : ConsoleManager로부터 받아온 정보를 바탕으로 Client가 Service에게 동작을 명령합니다. Repository와 직접적으로 통신합니다.

- Book : 도서의 정보와 상태를 필드로 갖습니다. 도서의 상태를 변경하는 메서드가 내장되어있습니다.
- Status : 도서의 상태를 나타내는 enum클래스

- Repository : 각 모드의 인터페이스. 도서 추가, 전체 조회, 제목 검색 조회, 단일 조회, 도서 삭제 기능이 있습니다. 
- TestRepository : List로 데이터들을 관리합니다. 도서 추가 시 ID는 리스트의 마지막에 있는 객체 ID에 +1을 합니다. 단일 조회 시 존재하지 않는 번호를 입력하면 예외
- FileRepository : 처음 생성되면 csv파일에 있는 도서의 정보를 List에 갖고옵니다. 단순 조회는 List를 통해 이루어지며, 도서 추가나 삭제같은 변경이 이루어지면 List의 정보를 csv파일에 새로 작성합니다.

## ✅ PR 포인트 & 궁금한 점 
- 설계 시 클래스로 Book과 Service, Repository 정도밖에 떠오르지 않아, 막상 구현하였을 때는 Service의 상태가 TestCode를 작성하기 어려운 상태였습니다..!! 어플리케이션 설계 시 객체를 설정하는 기준이나 팁 같은게 있는지 궁금합니다. 

- ConsoleManager의 입출력 기능을 온전히 맡기고 싶었지만, 도서의 상태 변경 시 사용자에게 출력하는 역할은 아직 도메인(Book)에 남아있습니다..! setter함수에 print함수까지 있기에 본능적(?)으로 좋은 방법이 아닌 것 같은데 다른 방법이 있을지, 아니면 접근 자체가 잘못되었는지 궁금합니다!

- getter와 setter가 캡슐화를 위반한다고 알고 있는데, setter는 생성자나 변경메서드를 통해 대체할 수 있지만, getter같은 경우는 안 사용할 수가 없었습니다. 이에 대한 생각이 궁금합니다

2023-09-29 06:36 UTC, ksy90101 requested changes
빌드 도구를 한번 써보면 좋겠습니다.

gradle, maven이란 무엇일까요?

gradle을 사용해 한번 만들어 주시면 어떨까요?

2023-09-29 14:27 UTC, kkangh00n commented
> 빌드 도구란?
- 소스 코드를 실행 가능한 애플리케이션으로 만듦
- 프로젝트에서 필요한 파일을 자동으로 인식해주고 빌드 (properties, jar 파일 등)
- 빌드 : 자바 코드 컴파일 -> 컴파일 한 class 파일을 실행 파일로 내보냄
- 외부 라이브러리 관리 (다운로드, 업데이트)

> gradle, maven이란 무엇일까요?
- 대표적인 빌드 툴
- groovy 문법 사용
- .gradle -> xml 기반 스크립트에 비해 관리가 편함
- maven -> gradle로 넘어가는 추세

> gradle 관련 용어 
참고 -> https://jammdev.tistory.com/209?category=923197, https://greedy0110.tistory.com/159
1. Project : gradle이 빌드하는 프로젝트 -> root 디렉토리에 build.gradle 포함
2. Tasks : 작업의 로직
- ex) 실행 로직 : 코드 컴파일 -> 테스트 실행 -> 소프트웨어 배포
3. Plugins : 여러 Tasks의 집합
- Java Plugin? 참고 -> https://robin00q.tistory.com/15
4. Builds : task 집합을 실행

> gradle 프로젝트로 변경하기 
참고 -> https://velog.io/@viiviii/IntelliJ-Java-%ED%94%84%EB%A1%9C%EC%A0%9D%ED%8A%B8%EB%A5%BC-Gradle-%ED%94%84%EB%A1%9C%EC%A0%9D%ED%8A%B8%EB%A1%9C-%EB%B0%94%EA%BE%B8%EA%B8%B0

>gradle 프로젝트 구조
참고 -> https://velog.io/@sa1341/Gradle-%EA%B8%B0%EB%B3%B8-%EB%8B%A4%EC%A7%80%EA%B8%B0-1%ED%8E%B8
-> https://devshin93.tistory.com/121

2023-09-30 05:33 UTC, ksy90101 requested changes
안녕하세요 강훈님 :)
이번 미션도 고생하셨어요.
알아보신 빌드도구에 대해서 잘 작성해주셨네요!!

리뷰를 남기다가 너무 많은 리뷰를 남긴거 같아서 중간에 끊고 갑니다.

두가지를 먼저 자신만의 생각대로 해보고 리뷰를 적용하면 어떨까 합니다.

1. MVC란 무엇인가? View코드는 하나의 개념인데 이걸 한곳에 모아둘수 없을까? Model은 무엇일까?
2. 파일을 읽기 위해 문제점들은 무엇일까?

2023-09-30 05:33 UTC, ksy90101 commented on build.gradle
> +    id 'java'
https://dlee0129.tistory.com/265
https://docs.gradle.org/current/userguide/toolchains.html#sec:consuming
sourceCompatibility & targetCompatibility
toolchain - languageVersion
이거에 대해서도 공부해두면 좋을거 같습니다~

자바 버전을 한번 고정시키면 어떨까요??

2023-09-30 05:33 UTC, ksy90101 commented on build.gradle
> +    testImplementation platform('org.junit:junit-bom:5.9.1')
1. platform 함수가 무엇인지 아시나요?
2. 아래와 같이 통일 시키면 어떨까요?

2023-09-30 05:33 UTC, ksy90101 commented on build.gradle
> +}
이게 있는 이유가 있나요?

2023-09-30 05:33 UTC, ksy90101 commented on build.gradle
> +}
https://blog.coderifleman.com/2015/04/04/text-files-end-with-a-newline/

이걸 한번 알아보면 어떠까요?

2023-09-30 05:33 UTC, ksy90101 commented on repository.csv
> +1,The Great Gatsby,F. Scott Fitzgerald,180,POSSIBLE
Default 데이터 아주 굿굿 입니다 👍

2023-09-30 05:33 UTC, ksy90101 commented on src/main/java/client/Client.java
> +        }
이걸 아래와 같이 한번 전략패턴을 써보면 어떨까요?

https://rutgo-letsgo.tistory.com/167

2023-09-30 05:33 UTC, ksy90101 commented on src/main/java/client/ConsoleManager.java
> +        System.out.print("\n >");
\n보단 system.lineseparator()을 알아보시면 어떨까요?

2023-09-30 05:33 UTC, ksy90101 commented on src/main/java/client/ConsoleManager.java
> +    BufferedReader br;
BufferedReader를 쓴 이유가 있나요?
참고로 Scanner도 있는데 말이죠.

2023-09-30 05:33 UTC, ksy90101 commented on src/main/java/domain/Book.java
> +    }
개행을 둬서 가독성을 높이면 어떨까요?

2023-09-30 05:33 UTC, ksy90101 commented on src/main/java/domain/Book.java
> +    }
setter가 필요한 이유가 있나요?
없애볼수 있을까요?

2023-09-30 05:33 UTC, ksy90101 commented on src/main/java/domain/Book.java
> +    public void rentalBook(){
메서드 명으로 충분히 이해 가능하지 않을까요?

주석을 제거하면 어덜까요?

2023-09-30 05:33 UTC, ksy90101 commented on src/main/java/domain/Book.java
> +        if(this.status == Status.IMPOSSIBLE) System.out.println("[System] 이미 대여중인 도서입니다.");
도메인에 View코드가 있는게 맞을까요?
예를들어 View가 웹으로 변경되어야 한다면 어떻게 하실예정인가요?
View를 위에서 잘 분리해주셧는데 여기엔 View코드가 남아 있네요 ㅎㅎ

2023-09-30 05:33 UTC, ksy90101 commented on src/main/java/domain/Status.java
> +    private final String statusName;
Status.statusName이라는건 좀 이상하지 않나요?
그냥 name을 써도 될거 같은데요. 참고로 enum엔 name이라는 키워드가 있어요 ㅎㅎ
어떤 이름이 좋을지 한번 고민해보시면 어떨까요?

2023-09-30 05:33 UTC, ksy90101 commented on src/main/java/repository/FileRepository.java
> +            BufferedReader br = new BufferedReader(new InputStreamReader(new FileInputStream(path), StandardCharsets.UTF_8));
FileInputStream과 같이 이런 객체를 사용한 뒤에는 close를 해야 할텐데요.

1. close를 해야 하는 이유가 무엇일지?
2. try-with-resources는 무엇일지?

이 두가지를 찾아서 작성해주시겠어요?

2023-09-30 05:33 UTC, ksy90101 commented on src/main/java/repository/FileRepository.java
> +                bw.write(book.getId() + "," + book.getName() + "," + book.getAuthor() + "," + book.getPage() + "," + book.getStatus().getStatusName());
","같은 경우엔 계속 중복되는데요. 이런 경우 상수를 통해  계속 ","이걸 생성하기보단 어떤걸 의미하는지, JVM입장의 성능상에서도 한번 고민해보시면 좋을거 같습니다.

2023-09-30 05:33 UTC, ksy90101 commented on src/main/java/repository/Repository.java
> +public interface Repository {
아주 굳굳 입니다 👍

2023-09-30 05:33 UTC, ksy90101 commented on src/main/java/repository/TestRepository.java
> +                .findAny()
findAny와 findFirst에 대해서 한번 찾아보시겠어요?

2023-09-30 05:33 UTC, ksy90101 commented on src/main/java/repository/TestRepository.java
> +                .filter(book->book.getName().contains(name))
한줄의 점 하나라는 의미로 디미터의 법칙이라는게 있습니다.

지금 한줄의 점이 2개죠? 이런 경우엔 book에게 메시지를 보내서 Name에 이런 키워드가 포함되어 있어? 같은 메시지를 보내 물어보면 어떨까요?

2023-09-30 05:33 UTC, ksy90101 commented on src/main/java/repository/TestRepository.java
> +        return bookRepository;
현재 List를 외부에 노출시킨다면 이걸 받은 외부에서 bookRepository의 값을 변경한다면 이클래스에 있는 bookRepository는 어떻게 될까요?

2023-09-30 05:33 UTC, ksy90101 commented on src/main/java/service/Service.java
> +    BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
이게 필요한 이유가 무엇인가요?

2023-09-30 05:33 UTC, ksy90101 commented on src/main/java/service/Service.java
> +    private Repository repository;
final을 쓰면 어떨까요?

2023-10-03 08:11 UTC, kkangh00n commented on build.gradle
> +    id 'java'
> sourceCompatibility
- **컴파일에서 사용하는 JDK 버전**
- 소스 코드에서 사용할 수 있는 JAVA 버전을 제한

>targetCompatibility
- **컴파일 후 생성된 클래스 파일의 JAVA 버전**을 제한
- 프로그램에서 실행할 수 있는 가장 낮은 버전

>toolchain
- **프로젝트를 빌드하는데 있어서 JAVA 버전**을 고정
- project 수준 뿐 아닌, tasks 수준에서도 toolchain 설정 가능

2023-10-03 08:24 UTC, kkangh00n commented on build.gradle
> +}
프로젝트 push 전, build 후 jar 파일을 실행했을 때
'no main manifest attribute in demo.jar' 오류 메시지와 함께 실행되지 않아 추가한 것입니다..!!

구글 검색 결과 main 함수를 인식하지 못해서 발생한 오류라는 것을 보고 추가한 것인데, 지금와서 생각해보면 그냥 cmd를 통해 프로젝트 빌드 & 실행을 처음해 봐서 서툴러 생긴 오류인 것 같습니다

2023-10-03 08:40 UTC, kkangh00n commented on build.gradle
> +}
> IEEE에서 지정한 운영체제 간 호환성을 유지하기 위한 표준 명세
1. 행의 끝은 개행
2. 텍스트 파일의 끝은 개행으로 끝난다.

2023-10-03 08:56 UTC, kkangh00n commented on build.gradle
> +    testImplementation platform('org.junit:junit-bom:5.9.1')
> 1. platform 함수가 무엇인지 아시나요?
- 해당 라이브러리의 버전을 제어
> 2. 아래와 같이 통일 시키면 어떨까요?
- 두 코드가 같이 있을 필요가 없을 것 같으며, 하나를 지워야 한다면, 라이브러리 업데이트 시 좀 더 유동적인 아래 코드를 남기는 것이 좋을 것 같습니다.

2023-10-03 10:05 UTC, kkangh00n commented on src/main/java/client/ConsoleManager.java
> +        System.out.print("\n >");
>System.lineseparator()
- OS에 맞게 개행 문자를 리턴

2023-10-03 13:05 UTC, kkangh00n commented on src/main/java/client/ConsoleManager.java
> +    BufferedReader br;
BufferedReader가 Scanner보다 속도가 빠르다는 얘기를 듣고 사용하였습니다
1. BufferedReader 사용 -> 속도 빠르지만, Checked 예외 처리 
2. Scanner 사용 -> 속도는 비교적 느리지만, 예외 처리 안함

속도보다는 불필요한 예외처리를 안 하는 것이 더 좋은 선택지일까요?.?

2023-10-03 13:23 UTC, kkangh00n commented on src/main/java/domain/Status.java
> +    private final String statusName;
해당 상태를 알려주기 때문에, message라는 이름으로 변경하였습니다!!

2023-10-03 13:48 UTC, kkangh00n commented on src/main/java/domain/Book.java
> +    }
> setter가 필요한 이유가 있나요? 없애볼수 있을까요?
- Repository의 가장 마지막 객체의 ID+1을 해주어 save할 객체의 ID로 지정해주는 방식으로 하였습니다..!!
- 이 방식이면 setID를 하는 것이 불가피합니다.
- 다른 방식으로 ID를 지정해주는 것이 더 나을까요?.?

2023-10-03 13:53 UTC, kkangh00n commented on src/main/java/service/Service.java
> +    BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
코드 리팩토링하면서 미처 못지운거 같습니다..!!

2023-10-03 14:01 UTC, kkangh00n commented on src/main/java/service/Service.java
> +    private Repository repository;
변경되지 않는 객체에 대해 final로 선언해주는 것이 더 나은 것 같습니다!!

2023-10-03 14:26 UTC, kkangh00n commented on src/main/java/repository/TestRepository.java
> +        return bookRepository;
너무 단순하게 생각하고 '저장소 전체를 return하면 되겠지' 생각하여 놓친 부분이네요..!!
`return new ArrayList<>(bookRepository);`
로 반환하면 저장소에 요소들에 직접 접근하여 불가능하게 바꾸었습니다!!

2023-10-03 14:39 UTC, kkangh00n commented on src/main/java/repository/TestRepository.java
> +                .filter(book->book.getName().contains(name))
이해되었습니다!!

ID와 name 확인 로직을 Book 객체로 이동시키겠습니다!

2023-10-03 15:17 UTC, kkangh00n commented on src/main/java/repository/TestRepository.java
> +                .findAny()
> findAny와 findFirst에 대해서 한번 찾아보시겠어요?

- findFirst() : Stream의 가장 앞 순서 요소를 반환
- findAny() : 조건에 부합하는 요소 중 가장 먼저 찾은 것 반환
- 둘의 차이는 stream을 병렬(parallel())로 처리할 때 나타난다. 
- findFirst는 안정된 값을 리턴하지만, findAny는 실행 때마다 리턴 값이 달라진다.

직렬 처리 시 둘의 차이는 없는 것 같아 findAny 함수를 사용하였습니다. 혹시나 놓치고 있는 부분이 있다면 말씀해주시면 감사하겠습니다!

2023-10-04 02:10 UTC, kkangh00n commented on src/main/java/client/Client.java
> +        }
좋은 정보 감사합니다!! Function이라는 enum 클래스를 만들어 전략패턴을 사용하였고, 그 안에 로직도 이전하였습니다.

한 가지 의문이 드는 점은 Service와 ConsoleManger를 매개변수로 받아 enum 안에서 로직을 실행하였는데, 의존성과 관련되어 문제되는 부분이 없을까요..??

2023-10-04 02:53 UTC, kkangh00n commented on src/main/java/repository/FileRepository.java
> +                bw.write(book.getId() + "," + book.getName() + "," + book.getAuthor() + "," + book.getPage() + "," + book.getStatus().getStatusName());
반복되는 ','를 상수로 지정하고, String으로 변환하는 해당 작업을 도메인에서 작업하도록 하였습니다!

2023-10-04 04:37 UTC, kkangh00n commented on src/main/java/repository/FileRepository.java
> +            BufferedReader br = new BufferedReader(new InputStreamReader(new FileInputStream(path), StandardCharsets.UTF_8));
> 1. close를 해야 하는 이유가 무엇일지?
- 파일 입출력을 위해 하드디스크에 있는 파일에 내용을 stream을 통해 갖고온다. 
- 이 때 stream은 운영체제가 제공해주는 시스템 자원이기 때문에 GC의 관리를 받지 않아, 수동으로 닫아주어야한다.

> 2. try-with-resources는 무엇일지?
```
try (FileInpuststream fis = new FileInputStream("score.dat");
     DataInputStream dis = new DataInputStream(fis)){
	...
} catch (IOException ie){
	ie.printStackTrace();
}
```
- 사용했던 자원을 반환 해줘야하는 경우 사용
- try블럭을 벗어나는 순간 close() 메서드 호출하여 자원 반

- 참고 -> https://okky.kr/questions/401102

2023-10-04 09:12 UTC, kkangh00n commented on src/main/java/domain/Book.java
> +        if(this.status == Status.IMPOSSIBLE) System.out.println("[System] 이미 대여중인 도서입니다.");
계속 막히는 부분이였습니다..!!

생각해본 결과, 성공 시 출력 문구는 console출력부분에 위임하고, 나머지는 예외로 던져 처리하는 것이 좋을 것 같습니다!!

2023-10-05 14:20 UTC, ksy90101 requested changes
강훈님 안녕하세요.
이번엔 세세한 리뷰보단, 테스트 코드에 대해서 학습을 해보면 어떨까요?

Service, Repository, Book에 대해서 한번 테스트 코드를 작성해보세요.
3개 남겼지만 3개다 오래 걸릴거 같아요. 파이팅이고 궁금한건 슬랙으로 문의주세요.

2023-10-05 14:20 UTC, ksy90101 commented on src/main/java/repository/Repository.java
> +public interface Repository {
리뷰를 남기기 전에, 여기에 대한 테스트 코드를 작성해보시면 어떨까요?

2023-10-05 14:20 UTC, ksy90101 commented on src/main/java/service/Service.java
> +public class Service{
여기도 테스트 코드를 작성해보세요.

2023-10-05 14:20 UTC, ksy90101 commented on src/main/java/domain/Book.java
> +public class Book {
여기도 테스트 코드가 필요한 부분이 무엇인지 고민헤보세요.

2023-10-10 15:35 UTC, merged