[5기 - 홍지인] 1~2주차 과제: 도서 관리 어플리케이션 제출합니다.
prgrms-be-devcourse/java-library-management pull request #13
Opened 2023-09-28 07:12 UTC by JIN-076

## 📌 과제 설명 
- 입력을 통해 사용할 모드를 선택하고, 기능을 선택하는 도서 관리 시스템 서비스
- JSON 파일을 이용하는 일반 모드와 인메모리를 이용하는 테스트 모드에 대한 테스트 코드 작성

## 👩‍💻 요구 사항과 구현 내용 
- Book : 도서 번호, 도서 이름, 저자 이름, 페이지 수, 도서 상태를 필드로 가지는 도메인
- BookState : Enum 클래스로, 도서의 상태를 다루는 도메인
- Mode, General, Tests : 모드에 따라 저장소에 접근해 도서 관리 시스템 기능 구현 (로드, 등록, 조회, 검색, 대여, 반납, 분실, 삭제, 업데이트)
- ConsoleManager : 콘솔에서 입력받는 기능에 대한 책임을 가지는 클래스
- JSONFileManager : JSON 파일을 읽어오고, 작성하는 기능에 대한 책임을 가지는 클래스
- FuncFailureException : 도서 관리 시스템의 기능이 실패하는 경우 발생하는 커스텀 Unchekced Exception 클래스
- LibraryManagement : Mode 클래스의 기능을 사용하는 비즈니스 로직을 담은 클래스 (service)
- AppConfig, CallbackConfig, LibraryConfig, ModeConfig : 사용자의 입력에 따라 적절한 Mode 구현체와 callback 함수를 담아 의존성을 주입해주는 클래스
- Book.json, TestBook.json : 서비스에서 사용하는 파일, 테스트에서 사용하는 파일 (resources)
- Validation : 일반 모드와 테스트 모드에 대한 기능을 검증하는 테스트 코드 (JUnit, AssertJ 활용)
- Client : 도서 관리 시스템을 구동하는 사용자 클래스

애플리케이션이 시작되면, 입력을 받아 일반 모드와 테스트 모드 중 선택할 수 있습니다.
일반 모드와 테스트 모드의 기능이 구동되는 함수는 공통된 로직이 많아 메서드로 추출하고, 일반 모드에서 추가로 호출되어야 하는 자동 등록 기능과 업데이트 기능은 함수형 인터페이스, (람다 표현식)을 사용해서 전달했습니다.
도서를 등록하면, 현재까지 등록된 목록을 확인하여 적절한 도서 번호를 부여하여 등록이 됩니다.
도서 대여, 반납, 분실, 삭제 등의 기능에서 기능이 실패하는 경우 예외를 발생시키며 에러 메시지를 출력합니다.
대여된 도서가 반납이 되면, 5분 간 "도서 정리중" 상태를 가지며, 5분이 지나면 "대여 가능" 상태로 바뀌게 됩니다.
테스트에서는 짧게 10초의 시간이 지나면 상태가 변경되도록 하여 검증을 수행했습니다.
도서 제목을 기준으로 검색하는 기능에 대해서는 Mock 객체를 이용해서 검증하였습니다.

PS. 과제를 구현하면서 메서드 명을 최대한 기능과 일치하도록 작성하면서, 가독성 좋게 작성하려고 하였으나,, 어떠한 이유로 구현하였는지에 대해서 주석으로 남겨두었습니다!

## ✅ 피드백 반영사항  
- 프로젝트 세팅 및 빌드 테스트 반영함

## ✅ PR 포인트 & 궁금한 점 
1. 객체지향적인 설계에 있어서, setter 메서드는 최대한 지양하는 것이 좋다고 하는데, 설계 상의 문제점때문일지, 입력에 따라 분기를 나누고, 필요한 인자를 전달하는 책임이 한 곳에 있어서 그런 것인지 setter 메서드의 사용을 완전히 제거할 수는 없었습니다. 더 좋은 설계 방법이 있을 것 같은데 생각해내지 못한 것 같습니다. 이와 관련해서 피드백을 받고 싶습니다!
2. 실무에서는 실제 서비스 환경과 테스트 환경이 다를 때, 매우 불가피한 상황이 아니라면 테스트 환경에서도 setter 메서드 사용을 무조건 지양하는 편인가요? 테스트 환경에서 setter 메서드를 완전히 제거하는 것이 어려울 때 어떻게 처리하시는지 궁금합니다.
3. 테스트 코드를 작성하면서, 한 번에 테스트하고자 하는 로직(?)의 범위가 작을수록 좋다는 것을 적용하고자 했습니다. 그런데 작성하다보니, 도서의 기능에 비해 너무 많은 테스트 코드가 만들어진 것 같다는 생각을 했습니다. 테스트 코드를 작성할 때 테스트하고자 하는 번위를 어떤 식으로 설정하는 것이 좋은지에 대한 멘토님의 기준이 궁금합니다.
4. 저장소에 접근하는 관리 시스템의 기능을 구현하는 과정에서, 결합도를 낮추기 위해 Mode 인터페이스를 도입하였으나, 일반 모드에서 시스템을 구동하는 함수의 로직과 테스트 모드에서 시스템을 구동하는 함수의 로직이 공통적인 부분을 많이 갖고 있었기 때문에, 이를 default 메서드로 뽑아내고, 일반 모드에서 추가로 필요한 함수를 호출하기 위해 함수형 인터페이스를 사용하였습니다. 이러한 설계에 대해서 객체지향적 설계 관점에서 어떻게 생각하시는지 궁금합니다. 더 좋은 설계 방법이 있지는 않을까 많은 고민이 되었습니다.
5. 반납 메서드에서 비동기 callback 함수와 함수형 인터페이스를 이용한 설계에 대해서 어떻게 생각하시는지 궁금합니다. 객체지향적으로 리팩토링하는 과정에서, 책임에 따른 분리를 최대한 하려고 노력하였으나 완전하게 책임이 분리된 메서드 구현인지 확신은 부족한 것 같습니다.
6. 테스트 코드를 작성하는 과정에서, 도서 제목을 기준으로 검색하는 findByTitle 기능에 대해서 검증을 하기 위해 Mock 객체를 사용하였는데, 혹시 더 나은 방법이나 기술이 있을지 궁금합니다! 추가적으로 어떻게 더 진행하면 좋겠다! 라는 피드백도 있는지 궁금합니다!

처음에 구현을 하면서 기능을 모두 구현해두었다가, 테스트 코드를 작성하면서 어떻게 하면 객체지향적인 설계로 리팩토링할 수 있을지 열심히 고민하면서 구조를 많이 바꾸고 개선했지만, 아직 부족한 점이 매우 많다고 생각합니다. 어떤 식으로 설계하는 것이 객체지향적인 설계다! 하는 정답 패턴이 있는 것은 아니지만 추가적으로 어떻게 개선할 수 있을지, 더 좋은 설계 방법이 있음을 알게 된다면 너무 좋을 것 같습니다! 제가 가지고 있는 안 좋은 습관이나 부족한 부분에 대해서 가감없이 지적을 부탁드립니다!! '매운맛' 코드 리뷰에 대한 마음의 준비는 단단히 해두었으니 그러한 고민 없이 솔직한 코드 리뷰를 해주시면 좋을 것 같습니다,,!

2023-09-29 11:16 UTC, aegis1920 requested changes
안녕하세요 지인님! 빙봉입니다 🙂 

현재 테스트를 신경쓰기보다는 프로덕션 코드에 좀 더 집중해서 개선해보는 걸 추천드립니다! 요구사항은 전부 다 만족했는지, 접근제한자, 포맷팅, 커밋 메시지 등등 확인해봐주세요! 그리고 지인님의 생각은 코멘트로 따로 남겨주시면 더 좋을 것 같습니다~

좀 더 코멘트 드릴 부분이 꽤 있는데요. 너무 많으면 수정이 힘들 것 같아서 일단 이렇게 피드백 드려요! 코멘트 중 이해가 가지 않는 부분이나 궁금한 점은 언제든 편하게 DM 주세요!

---

<img width="891" alt="image" src="https://github.com/prgrms-be-devcourse/java-library-management/assets/22311557/fd1f0003-e810-406b-92b8-b6c9dd827dbc">

동일한 커밋 메시지는 가급적 쓰지 않는 게 좋을 것 같아요. 그리고 `fix .gitignore` 만 있다면 어떤 것을 수정했는지 알 수 없어서 좀 더 명확하게 작성하면 좋을 것 같습니다. 커밋 메시지의 일관성도 챙기면 좋구요! (fix, fixed)

2023-09-29 11:16 UTC, aegis1920 commented on README.md
README는 왜 삭제되었나요?

2023-09-29 11:16 UTC, aegis1920 commented on .gitignore
> +build/
- build가 왜 두 개일까요?
- `/`가 붙은 것과 붙지 않은 것의 차이는 어떤건가요?

2023-09-29 11:16 UTC, aegis1920 commented on build.gradle
> +}
마지막 줄 개행(EOF의 개행)에 신경써주시면 좋을 것 같습니다!
참고로 유닉스 시스템의 표준이 한 줄에 대한 정의가 개행으로 끝납니다. ([링크](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_206))

intellij에서 아래 설정으로 자동으로 넣어줄 수 있습니다 🙂 

<img width="430" alt="image" src="https://github.com/prgrms-be-devcourse/java-library-management/assets/22311557/2fee0f24-e557-454a-a24d-e9d41db11b3d">

2023-09-29 11:16 UTC, aegis1920 commented on build.gradle
> +    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.8.1'
동일한 의존성이 들어가 있기도 하고, 필요하지 않은 의존성도 있는 것 같아요. 정리 부탁드립니다!

2023-09-29 11:16 UTC, aegis1920 commented on settings.gradle
> +rootProject.name = 'Java_libraryManagement'
gradle project name convention에 대해서 알아볼까요?

2023-09-29 11:16 UTC, aegis1920 commented on src/main/java/dev/course/Client.java
> +public class Client {
도서 관리 애플리케이션을 사용하는 주체 클래스라고 하셨는데요. 클래스 이름이 클라이언트가 맞을까요?

2023-09-29 11:16 UTC, aegis1920 commented on src/main/java/dev/course/Client.java
> +    public static void main(String[] args) throws IOException {
main 함수에서 너무 많은 역할을 수행하고 있지 않아 보이나요? 이 과정들을 클래스로 분리해보면 어떨까요?

2023-09-29 11:16 UTC, aegis1920 commented on src/main/java/dev/course/Client.java
> +            if (modeId == 1 || modeId == 2) break;
1, 2의 의미가 명백해서 상수로 빼도 좋을 것 같습니다.

2023-09-29 11:16 UTC, aegis1920 commented on src/main/java/dev/course/Client.java
> + *    이 부분이 단일 책임 원칙, 자신이 가져야 할 책임만을 잘 따르고 있는 설계가 맞는지 의문이 듭니다,,,
> Config 클래스 상에서 입력 값에 따라 알맞은 구현체를 주입해주도록 구현했는데 이 부분이 단일 책임 원칙, 자신이 가져야 할 책임만을 잘 따르고 있는 설계가 맞는지 의문이 듭니다

Client 클래스가 아니라 AppConfig 클래스에 대한 질문이 맞을까요? 만약 맞다면 AppConfig를 입력 값에 따라 알맞은 구현체를 주입해주도록 구현한 것이라고 이해하고 설계했다고 했을 때 잘 구현한 거라고 생각됩니다! 

다만 지금은 Client 클래스이고, Client 클래스가 가져야할 책임이 어떤 걸지 생각해보셨으면 좋겠어요. Client 클래스라는 이름이 맞을지? Client의 책임을 다하고 있는지? 등등?

2023-09-29 11:16 UTC, aegis1920 commented on src/main/java/dev/course/config/AppConfig.java
> + * DI 컨테이너가 아닌 자바 애플리케이션 상에서 의존성을 주입해주고자 Config 클래스를 둠
지인님이 생각하신 DI 컨테이너가 어떤 의미인지 궁금하군요! 말씀해주실 수 있을까요? AppConfig가 DI 컨테이너 역할을 하고 있는 건 아닐까요?

2023-09-29 11:16 UTC, aegis1920 commented on src/main/java/dev/course/config/CallbackConfig.java
> +     */
지인님의 생각은 주석이 아닌 코멘트로 남겨주시면 좋을 것 같아요! 더 좋은 설계 방법에 대해서는 코멘트로 따로 남겨둘게요!

2023-09-29 11:16 UTC, aegis1920 commented on src/main/java/dev/course/config/CallbackConfig.java
> +        }
어떤 곳에서는 1과 2를 명백하게 적어두었고 여기서는 2가 아닌 else를 사용하셨네요. 1과 2, else를 두는 게 좀 더 명백하지 않을까요?

2023-09-29 11:16 UTC, aegis1920 commented on src/main/java/dev/course/repository/Mode.java
> +public interface Mode {
클래스 이름때문에 헷갈리는 부분이 많네요ㅠㅠ Mode에 어떻게 저장할 지, 어떻게 조회할 지가 달라지는 것으로 이해되는데요. Mode 자체를 인터페이스로 봐도 괜찮을까요? 지금 어떤 도메인에 대해서 저장하고 조회하고 있나요? 그 도메인의 이름이 들어가야 명확하지 않을까요? XXXRepository 처럼 좀 더 명확하게 인터페이스 이름을 주어도 괜찮을 것 같아요.

2023-09-29 11:16 UTC, aegis1920 commented on src/main/java/dev/course/repository/Mode.java
> +    void printStartMsg();
지인님이 생각하시는 Repository는 어떤 레이어일 것 같으신가요? Repository 레이어에서 출력하는 게 맞을지 다시 한 번 생각해보죠!

2023-09-29 11:16 UTC, aegis1920 commented on src/main/java/dev/course/repository/Mode.java
> +    default int getBookId(Map<Integer, Book> map) {
출력하는 메서드인 printStartMsg를 제외하면 전부 default 메서드로 구성되어있는데요. 그렇다면 인터페이스가 아니라 클래스로 작성해도 되는 거 아닐까요? 왜 인터페이스로 작성하셨는지 궁금합니다!

2023-09-29 11:16 UTC, aegis1920 commented on src/main/java/dev/course/repository/Mode.java
> + * 1. returns 메서드에서 비동기 callback 함수와 BiConsumer 함수를 이용한 부분에 대해서 어떻게 생각하시는지 궁금합니다.
제 생각을 먼저 말씀드리기 전에 지인님의 생각을 먼저 묻고 싶습니다!

- 지인님이 생각하시는 비동기는 어떤 의미인가요?
- 지금 코드가 비동기로 실행되고 있나요?
- BiConsumer를 사용하신 이유는 어떤 이유에서 사용하신 건가요?

2023-09-29 11:16 UTC, aegis1920 commented on src/main/java/dev/course/repository/Mode.java
> + * 어떤 모드를 사용하는지에 대한 인터페이스
어떤 모드를 사용하는지에 대한 인터페이스가 아니라 repository 역할의 인터페이스로 읽히는데요. 맞을까요?

2023-09-29 11:16 UTC, aegis1920 commented on src/main/java/dev/course/domain/BookState.java
> +    LOAN("대여중"),
loan이라는 단어는 책을 대여할 때 쓰이는 것 같지 않은데요. 확인 한 번 가능할까요?

2023-09-29 11:16 UTC, aegis1920 commented on src/main/java/dev/course/domain/BookState.java
> +    AVAILABLE("대여 가능"),
available 이라는 단어도 이용 가능한의 느낌이 강해서 대여라는 의미도 들어가야할 것 같습니다!

2023-09-29 11:16 UTC, aegis1920 commented on src/main/java/dev/course/repository/mock/MockMode.java
> +public class MockMode implements Mode {
Mock보다는 TestMode라고 명확하게 지칭해주는 게 좋지 않을까요?

2023-09-29 11:16 UTC, aegis1920 commented on src/main/resources/Book.json
> +  "state": "도서 정리중"
Book의 상태를 BookState의 value 값이 아닌 ENUM 값으로 줘야하지 않을까요?

2023-09-29 11:16 UTC, aegis1920 commented on src/main/resources/Book.json
> +  "state": "대여중"
실제 서버에 나가는 데이터라고 생각해주세요! 모두 다 대여 가능 상태여야할 것 같습니다!

2023-09-29 11:16 UTC, aegis1920 commented on src/main/java/dev/course/service/LibraryManagement.java
> +                    case 4:
도서 대여 메뉴로 넘어간 이후에 도서 번호를 입력하라고 나오지 않습니다! 요구사항 확인 부탁드려요!

2023-09-29 11:16 UTC, aegis1920 commented on src/main/java/dev/course/config/CallbackConfig.java
> +public class CallbackConfig {
지인님이 생각하시는 Callback이 어떤 의미인가요? 지금 Callback을 사용하고 있는 건가요? 이 클래스가 구현하는데 정말 필요할까요?

2023-09-29 11:16 UTC, aegis1920 commented on src/test/java/Validation.java
> +public class Validation {
> 실무에서는 실제 서비스 환경과 테스트 환경이 다른 경우에, 매우 불가피한 상황이 아니라면 테스트 환경에서도 setter 사용을 무조건 지양하는 편인가요? 테스트 환경에서드 사용을 지양한다면 그 이유는 좋은 객체지향 설계가 아니기 때문일까요?

setter 사용을 지양하고 있으나 레거시 코드에 이미 존재하는 경우도 있고, setter를 사용하는 것이 성능적으로 더 나을 때도 있어서요. 무조건적으로 지양하는 편은 아닙니다. 테스트 환경에서도 마찬가지구요. setter를 사용하는 건 엄밀히 말했을 때 객체지향의 캡슐화에만 영향이 있다고 볼 수 있겠네요

> 테스트 코드를 작성하면서 가장 어려움을 겪었던 부분은, Mode의 구현체를 적용하여 libraryManagement 인스턴스를 객체지향적으로 설계하고 받아오는 부분이었습니다. 만약 제가 구현한 아키텍처에서 테스트를 위해 무조건 setter 메서드를 사용해야 한다면, 이는 아키텍처 설계가 객체지향적이지 않기 떄문일까요?

위와 같습니다. setter를 사용했다고 해서 객체지향적이지 않다고 말할 순 없습니다!

> 테스트 코드를 작성하면서, 한 번에 테스트하고자 하는 로직(?)의 범위가 작을수록 좋다는 것을 적용하고자 했습니다. 그런데 작성하다보니, 도서의 기능에 비해 너무 많은 테스트 코드가 만들어진 것 같다는 생각을 했습니다. 테스트 코드를 작성할 때 테스트하고자 하는 번위를 어떤 식으로 설정하는 것이 좋은지에 대한 멘토님의 기준이 궁금합니다.

가장 중요한 비즈니스 로직에 대해서 먼저 작성하는 것이 좋습니다. 테스트의 범위에 대해서는 할 이야기가 많은데 나중에 같이 이야기 나눠보시죠! (지금 잘 작성해주셨는데요. 성공하는 테스트보단 예외 케이스에 대한 테스트 먼저 작성해봐주세요!)

2023-09-29 11:16 UTC, aegis1920 commented on src/test/java/Validation.java
> +public class Validation {
테스트의 이름이 Validation만으로 작성되어있네요. 테스트 클래스 이름 컨벤션이라든지, 테스트 메서드 이름의 컨벤션을 참고해주시면 좋을 것 같아요!

2023-09-29 14:05 UTC, JIN-076 commented on src/main/java/dev/course/config/AppConfig.java
> + * DI 컨테이너가 아닌 자바 애플리케이션 상에서 의존성을 주입해주고자 Config 클래스를 둠
제가 생각하는 DI 컨테이너의 역할은 설정 정보를 바탕으로 컨테이너가 객체를 생성하고 외부에서 주입해줌으로써 클래스 사이의 의존 관계를 연결해주는 것이라고 생각합니다!

AppConfig가 DI 컨테이너의 역할을 수행하도록 구현한 것이 맞습니다! 제가 작성한 코멘트의 의미는, 현재 DI 컨테이너 상에서 구동되는 것이 아니기 때문에 직접 DI 컨테이너처럼 의존성을 주입해주고자 Config 클래스를 두었다는 의미입니다! 제가 표현을 명확하게 작성하지 않은 것 같네요😅

2023-09-29 14:38 UTC, JIN-076 commented on .gitignore
> +build/
intelliJ 상에서 .gitIgnore를 작성할 때 /가 붙은 것과 붙지 않은 것 모두 동일하게 디렉토리로 보는 것 같습니다. git에 올리지 않을 파일을 작성하고 push하는 과정에서 cache때문에 .gitignore가 적용되지 않아 테스트겸 두 개를 작성하였는데, 다시 수정하는 것을 생각하지 못했습니다,,!

2023-09-29 14:40 UTC, JIN-076 commented on README.md
README.md 파일이 과제에 대한 요구사항이라는 것을 인지하지 못하고 .gitignore에 작성해서 저장소에 올라가지 않았습니다,, 해당 부분 수정했습니다!

2023-09-29 14:57 UTC, JIN-076 commented on build.gradle
> +    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.8.1'
필요하지 않은 의존성에 대해서 제거하도록 하겠습니다! 
lombok 의존성에 대해서는 @Builder 어노테이션을 사용하기 위해서 compileOnly와 annotationProcessor에서 모두 의존성을 작성해야 컴파일이 되어서 두 개를 모두 넣었습니다!

2023-09-29 14:57 UTC, JIN-076 commented on build.gradle
> +}
그 부분은 생각하지 못했네요! Intellij에서 설정하도록 하겠습니다.

2023-09-29 15:01 UTC, JIN-076 commented on settings.gradle
> +rootProject.name = 'Java_libraryManagement'
gradle project name convention에서는 기본적으로 카멜표기법을 사용한다는 것을 확인했습니다! 수정하겠습니다.

2023-09-29 15:04 UTC, JIN-076 commented on src/main/resources/Book.json
> +  "state": "대여중"
기능 확인하려고 수정해놓고 원상복구를 생각하지 못했습니다. 모두 대여 가능 상태로 수정하겠습니다!

2023-10-01 18:18 UTC, JIN-076 commented on src/main/java/dev/course/Client.java
> + *    이 부분이 단일 책임 원칙, 자신이 가져야 할 책임만을 잘 따르고 있는 설계가 맞는지 의문이 듭니다,,,
Client 클래스라는 이름보다 LibraryApplication 클래스 이름이 더 적절하다고 생각이 되네요! 해당 부분 수정하겠습니다.

2023-10-01 18:19 UTC, JIN-076 commented on src/main/java/dev/course/Client.java
> +public class Client {
Client라는 이름이 적절하지 못했다고 생각이 드네요,, LibraryApplicatioin 클래스의 이름이 더 적절하다고 생각이 되어 해당 부분 수정했습니다!

2023-10-01 18:21 UTC, JIN-076 commented on src/main/java/dev/course/Client.java
> +    public static void main(String[] args) throws IOException {
main 함수에서 수행하고 있는 역할에 대해 BookController를 도입해서 적절하게 분리하면 더욱 좋을 것 같습니다! 해당 부분 수정하겠습니다.

2023-10-01 18:21 UTC, JIN-076 commented on src/main/java/dev/course/Client.java
> +            if (modeId == 1 || modeId == 2) break;
명백한 의미에 대한 변수들을 상수 클래스 Constants를 만들어 수정했습니다!

2023-10-01 18:23 UTC, JIN-076 commented on src/main/java/dev/course/config/CallbackConfig.java
> +public class CallbackConfig {
제가 설계를 하는 과정에서 Repository 레이어와 Service 레이어의 책임에 맞게 분리를 하지 못해서 발생한 문제라고 생각이 듭니다.

설계를 재구성하는 과정에서, BookController 클래스를 도입함으로써 해당 클래스의 필요 없이 구현이 가능한 것을 확인하고 해당 부분 수정했습니다!

2023-10-01 18:24 UTC, JIN-076 commented on src/main/java/dev/course/config/CallbackConfig.java
> +     */
넵 앞으로 코멘트로 남기도록 하겠습니다!

2023-10-01 18:25 UTC, JIN-076 commented on src/main/java/dev/course/config/CallbackConfig.java
> +        }
일관성을 가져가는 것이 더 명백한 것 같습니다! 해당 부분 수정하겠습니다.

2023-10-01 18:26 UTC, JIN-076 commented on src/main/java/dev/course/domain/BookState.java
> +    AVAILABLE("대여 가능"),
대여의 의미가 들어가는 좀 더 명확한 단어로 수정하겠습니다!

2023-10-01 18:26 UTC, JIN-076 commented on src/main/java/dev/course/domain/BookState.java
> +    LOAN("대여중"),
loan이라는 단어보다는 rent 단어가 더 많이 쓰이는 것 같습니다. 해당 부분 확인하고 수정했습니다!

2023-10-01 18:28 UTC, JIN-076 commented on src/main/java/dev/course/repository/Mode.java
> + * 어떤 모드를 사용하는지에 대한 인터페이스
네! Repository 역할에 대한 인터페이스가 맞습니다.

처음 구조를 설계하는 과정에서 Repository 레이어와 Service 레이어에 대한 책임을 제대로 고려하지 못해서 의미를 잘 못 이해한 것 같습니다! 해당 부분에 대해서 수정했습니다.

2023-10-01 18:29 UTC, JIN-076 commented on src/main/java/dev/course/repository/Mode.java
> +public interface Mode {
Repository 클래스 네이밍 컨벤션을 찾아보고 명확한 인터페이스 이름으로 수정했습니다! 앞으로 명확하게 클래스 이름을 짓도록 하겠습니다.

2023-10-01 18:32 UTC, JIN-076 commented on src/main/java/dev/course/repository/Mode.java
> +    default int getBookId(Map<Integer, Book> map) {
Service 레이어에서 어떤 Repository의 구현체를 사용하는지 알지 못하는 상태에서 해당 메서드에 접근할 수 있도록 하는 것이 더 중요하다고 판단해서 인터페이스를 도입했습니다.

새롭게 Repository 레이어와 Service 레이어의 책임에 맞게 역할을 분리하는 과정에서 default 메서드를 없애고 인터페이스와 구현체를 적절하게 수정했습니다!

2023-10-01 18:33 UTC, JIN-076 commented on src/main/java/dev/course/repository/Mode.java
> +    void printStartMsg();
제가 생각하는 Repository는 DB, 즉 저장소에 접근해야 하는 로직을 다루는 레이어라고 생각합니다. 해당 메서드는 저장소에 접근하는 로직을 다루고 있지 않으니 Repository 레이어에서 출력하는 것이 맞지 않겠군요! 사용자의 요청을 받아서 service 로직을 호출해주는 Controller 레이어에서 출력하는 게 맞다고 생각됩니다.

2023-10-01 18:33 UTC, JIN-076 commented on src/main/java/dev/course/repository/mock/MockMode.java
> +public class MockMode implements Mode {
클래스 이름을 지을 때 명확하게 지칭하도록 하겠습니다! 해당 부분 수정했습니다.

2023-10-01 18:35 UTC, JIN-076 commented on src/main/java/dev/course/service/LibraryManagement.java
> +                    case 4:
제가 놓친 요구사항이 있었네요,,😱 다시 요구사항을 제대로 확인하고 맞게 수정했습니다! 제일 중요한 부분이었는데 앞으로 요구사항을 제대로 신경쓰도록 하겠습니다.

2023-10-01 18:36 UTC, JIN-076 commented on src/main/resources/Book.json
> +  "state": "도서 정리중"
ENUM 값이 들어가는 것이 맞다고 생각되어 해당 부분 수정했습니다!

2023-10-01 18:37 UTC, JIN-076 commented on src/test/java/Validation.java
> +public class Validation {
테스트 클래스 이름 컨벤션과 메서드 이름 컨벤션을 참고해서 적절하게 수정하도록 하겠습니다! 앞으로 네이밍 컨벤션에 많이 신경쓰도록 하겠습니다,,!😱

2023-10-01 19:08 UTC, JIN-076 commented
## 👩‍💻 요구 사항과 구현 내용 <!-- 기능을 Commit 별로 잘개 쪼개고, Commit 별로 설명해주세요 -->
- Book : 도서 번호, 도서 이름, 저자 이름, 페이지 수, 도서 상태를 필드로 가지는 도메인
- BookState : Enum 클래스로, 도서의 상태를 다루는 도메인
- AppConstants : 명백한 의미로 사용되는 변수들에 대한 상수들을 선언한 클래스
- BookRepository, GeneralBookRepository, TestBookRepository : 모드에 따라 저장소에 접근해 도서 관리 시스템 기능 구현 (로드, 등록, 조회, 검색, 대여, 반납, 분실, 삭제, 업데이트)
- ConsoleManager : 콘솔에서 입력받는 기능에 대한 책임을 가지는 클래스
- JSONFileManager : JSON 파일을 읽어오고, 작성하는 기능에 대한 책임을 가지는 클래스
- FuncFailureException : 도서 관리 시스템의 기능이 실패하는 경우 발생하는 커스텀 Unchekced Exception 클래스
- FileIOFailureException : 파일을 읽거나 접근하는 과정에서 발생하는 IOException에 대한 Uncheked Exception 클래스
- ConsoleIOFailureException : 콘솔에 입력하거나 읽어오는 과정에서 발생하는 IOException에 대한 Unchecked Exception 클래스
- BookController : 입력값에 따른 적절한 모드를 실행시키고, 입력에 따라 적절한 기능의 Service를 호출하는 Controller 역할의 클래스
- LibraryManagement : Mode 클래스의 기능을 사용하는 비즈니스 로직을 담은 클래스 (service)
- AppConfig,  LibraryConfig, ModeConfig : 사용자의 입력에 따라 적절한 BookRepository 구현체를 담아 의존성을 주입해주는 클래스
- Book.json, TestBook.json : 서비스에서 사용하는 파일, 테스트에서 사용하는 파일 (resources)
- LibararyAppFeatureTest : 일반 모드와 테스트 모드에 대한 기능을 검증하는 테스트 코드 (JUnit, AssertJ 활용)
- LibraryApplication

## ✅ 피드백 반영사항
- 프로젝트 세팅 및 빌드 테스트 반영함
- Gradle 프로젝트, 클래스, ENUM, 테스트 클래스, 테스트 메서드 네이밍 컨벤션에 맞게 변경함
- BookRepository 인터페이스와 구현체의 로직 수정함
- BookController 도입으로 Controller, Repository, Service 레이어의 책임에 맞게 비즈니스 로직, 데이터 접근 로직 수정함
- Book 도메인에서 사용되는 setter 메서드를 제거하고 생성자를 적용함
- 적절하게 접근 제한자 수정함
- 명백한 의미의 변수들을 Constants, 상수 클래스에 선언함
- 바뀐 Repository, Service 로직에 맞게 LibraryAppFeatureTest, 테스트 코드 수정함

처음 도서 관리 애플리케이션을 설계하는 과정에서 어떻게 처리해야 할지 곤란했던 책임을 BookController를 도입함으로써 깔끔하게 해결할 수 있었습니다. 멘토님께서 남겨주신 피드백을 보면서, 각각의 클래스가 가져야 하는 책임이 무엇이고, 어떤 역할을 가져야할지를 재구성하는 과정에서 Controller 레이어, Repository 레이어, Service 레이어의 역할에 맞게 클래스와 메서드를 분리하고 다시 구현했습니다! 
그리고 기본적으로 주어지는 요구사항과 적절한 접근 제한자, 그리고 프로젝트와 클래스, 메서드와 변수들에 대한 네이밍 컨벤션을 지키면서 구현하는 것을 많이 신경썼습니다! 마지막으로 피드백에 남겨주셨던 5분 후의 상태 변경을 위한 비동기에 대해서는 아직 답을 찾아나가는 중입니다! 그 부분도 서둘러서 답을 찾아 반영하도록 하겠습니다!

2023-10-02 04:49 UTC, JIN-076 commented on src/main/java/dev/course/repository/Mode.java
> + * 1. returns 메서드에서 비동기 callback 함수와 BiConsumer 함수를 이용한 부분에 대해서 어떻게 생각하시는지 궁금합니다.
비동기란, 특정 코드가 끝날때까지 코드의 실행을 멈추지 않고 다음 코드를 먼저 실행하는 것을 의미합니다! 제가 작성한 코드의 의미를 잘못 이해하고 있었던 것 같습니다.

제가 작성한 코드는 ThreadPool에서 지정된 시간이 지난 후에 작업을 하도록 스레드를 예약하는 지연 스케쥴링이라고 생각합니다.
해당 로직을 비동기적으로 처리하고, State가 변화하기 전에 시스템이 종료될 경우에 대한 예외 처리에 대해서 추가해서 수정했습니다!

BiConsumer를 사용한 이유는 해당 로직에서 update 메서드를 접근할 수 없기 때문에 이를 실행시키기 위함이었으나, Controller를 도입하고 설계를 재구성하는 과정에서 이를 해결하여 제거했습니다.

2023-10-02 04:55 UTC, cloudwi commented on src/main/java/dev/course/LibraryApplication.java
> +        BookController bookController = new BookController(new AppConfig());
Config 별도로 관리 너무 좋아요!

2023-10-02 04:57 UTC, cloudwi commented on src/main/java/dev/course/controller/BookController.java
> +            while (true) {
while (true) 처럼 무한 반복 보단 
while (flag) 처럼 관리하는 것이 좋지 않을까요?

2023-10-02 04:59 UTC, cloudwi commented on src/main/java/dev/course/controller/BookController.java
> +        while (true) {
여기도 동일합니다.

2023-10-02 04:59 UTC, cloudwi commented on src/main/java/dev/course/controller/BookController.java
> +                        System.out.println("[System] 도서 등록 메뉴로 넘어갑니다.\n");
출력하는 기능을 분리하는 것은 어떤가요?

2023-10-02 05:00 UTC, cloudwi commented on src/main/java/dev/course/controller/BookController.java
> +
거의 모든 매서드에 줄 띄움을 가지고 있는것이 신선했어요.

2023-10-02 05:02 UTC, cloudwi commented on src/main/java/dev/course/service/LibraryManagement.java
> +        this.consoleManager = libraryConfig.getConsoleManager();
더 이상 사용하지 않는 것으로 보여요.

2023-10-02 05:03 UTC, cloudwi commented on src/main/java/dev/course/service/LibraryManagement.java
> +        bookList.forEach(this.bookRepository::printBook);
bookRepository에서 print를 하는 것은 전혀 다른 기능을 bookRepository에서 수행하는 것 같아요.

2023-10-02 05:06 UTC, cloudwi commented on src/main/java/dev/course/service/LibraryManagement.java
> +        if (book.getState().equals(BookState.RENTAL_AVAILABLE)) {
BookState state = book.getState;

와 같이 코드를 간략화 할 수 있을 것 같아요.

그리고 상태에 따라서 분기처리를 조금 더 가독성 높게 만들 수 있을 것 같아요.

예시로 스위치 문을 사용하는 것도 좋고 BookState 내부로 숨기는 것도 좋아 보입니다.

지인님은 어떻게 생각하시나요?

2023-10-02 05:07 UTC, cloudwi commented on src/main/java/dev/course/controller/BookController.java
> +            } catch (FuncFailureException | ConsoleIOFailureException e) {
catch 하지 않는 예외가 발생한다면 서비스가 종료될 것 같아요.

우리가 예상하지 못하는 예외에서도 방어적인 코드가 필요하지 않을까요?

2023-10-02 05:10 UTC, cloudwi commented on src/main/java/dev/course/controller/BookController.java
> +                modeId = consoleManager.getInteger();
사용자가 숫자 이외의 다른 값을 입력하면 서비스가 종료 하고 있어요.

의도 하신 코드인가요?

2023-10-02 05:12 UTC, cloudwi commented on src/main/java/dev/course/controller/BookController.java
> +                        System.out.println("[System] 도서 등록 메뉴로 넘어갑니다.\n");
분리 한다면 class가 더욱 짧고 간결하게 만들 수 있을 것 같아요.

2023-10-02 05:20 UTC, cloudwi commented on src/main/java/dev/course/controller/BookController.java
> +    public Book consoleAboutBookInfo() {
해당 매서드 명으로는 책을 생성하는 기능을 수행한다 라고 명확하게 이해될까요?

2023-10-02 05:22 UTC, cloudwi commented on src/main/java/dev/course/controller/BookController.java
> +                switch (modeId) {
단순 사용자에게 무언가를 입력해라 라고 출력하는 문장의 길이가 너무 길다고 생각되어요.

간략하게 작성 가능할까요?

2023-10-02 05:26 UTC, cloudwi commented on src/main/java/dev/course/service/LibraryManagement.java
> +    public void returns(Long bookId) throws FuncFailureException {
언체크 예외를 밖으로 던지는 이유가 있을까요?

2023-10-02 05:28 UTC, cloudwi commented on src/main/java/dev/course/service/LibraryManagement.java
> +        if (book.getState().equals(BookState.RENTAL_AVAILABLE)) {
book 객체에서 값을 꺼내서 비교하는 것 보단 book객체 에게 이 값이랑 같아? 라고 물어보는 것이 좋다고 생각해요.

지인님은 어떻게 생각하시나요?

2023-10-02 05:35 UTC, cloudwi commented on src/main/java/dev/course/service/LibraryManagement.java
> +            Book returned = new Book(book.getBookId(), book.getTitle(), book.getAuthor(), book.getPage_num(), BookState.ARRANGEMENT);
새로운 Book을 생성하는 것 보단 변경하려는 값을 수정하고 업데이틑 하는 것이 어떤가요?

2023-10-02 05:37 UTC, cloudwi commented on src/main/java/dev/course/service/LibraryManagement.java
> +    public void lost(Long bookId) throws FuncFailureException {
위와 동일 합니다.

2023-10-02 05:38 UTC, cloudwi commented on src/main/java/dev/course/service/LibraryManagement.java
> +        Book book = this.bookRepository.findById(bookId)
삭제할때 꼭 찾아야할까요?

2023-10-02 05:41 UTC, cloudwi commented on src/main/java/dev/course/service/LibraryManagement.java
> +        try {
멀티스레드 환경에서는 고려할 점 들이 많을 것 같아요.

2023-10-03 12:40 UTC, aegis1920 commented on .gitignore
> +build/
네넵 동일하게 디렉토리로 보는데요. /가 붙으면 디렉토리만 보고 붙지 않으면 파일과 디렉토리 둘 다 봅니다!

2023-10-03 12:45 UTC, aegis1920 commented on settings.gradle
> +rootProject.name = 'Java_libraryManagement'
혹시 카멜표기법으로 사용한다는 링크를 얻을 수 있을까요? 저는 [이쪽](https://docs.gradle.org/current/userguide/multi_project_builds.html) 보고 java-library-management로 수정하는 것을 생각했었습니다!

2023-10-03 12:46 UTC, aegis1920 commented on src/main/java/dev/course/config/AppConfig.java
> + * DI 컨테이너가 아닌 자바 애플리케이션 상에서 의존성을 주입해주고자 Config 클래스를 둠
넵 설명 감사합니다!

2023-10-03 13:15 UTC, aegis1920 commented on src/main/java/dev/course/repository/Mode.java
> + * 1. returns 메서드에서 비동기 callback 함수와 BiConsumer 함수를 이용한 부분에 대해서 어떻게 생각하시는지 궁금합니다.
네넵~ 코멘트 이후에 작성된 것 이해했습니다! 관련된 부분은 다시 코멘트 남기거나 할게요!

2023-10-04 16:56 UTC, JIN-076 commented on src/main/java/dev/course/controller/BookController.java
> +            while (true) {
무한루프를 사용하는 것보다 flag로 관리하는 것이 더 좋겠네요!

추가로, 모드에 대한 입력값과 각 기능을 위한 입력값에 잘못된 입력이 들어왔을 경우에 대한 예외 처리 로직을 고민하다가, 잘못된 입력의 최대 횟수를 지정해놓고, 잘못된 입력이 그 이상 들어올 경우 시스템을 종료하는 식으로 처리하면서 while 문을 count로 관리하도록 구현했습니다. 잘못된 입력에 대한 예외 처리는 요구 사항에 따로 나와 있지 않아서 고민하던 중 다음과 같은 방법으로 처리했는데 괜찮은 방법인지 잘 모르겠네요,,

2023-10-04 16:56 UTC, JIN-076 commented on src/main/java/dev/course/controller/BookController.java
> +        while (true) {
윗 코멘트와 동일하게 해당 부분도 모두 수정해두었습니다!

2023-10-04 16:59 UTC, JIN-076 commented on src/main/java/dev/course/controller/BookController.java
> +                        System.out.println("[System] 도서 등록 메뉴로 넘어갑니다.\n");
각 모드에 진입할 때 출력해주는 부분을 ConsoleManager 클래스에 switch-case 문으로 두어서 분리해보았습니다! 이전보다 깔끔하고 간결하게 만들어진 것 같습니다! 추가적으로 기능을 호출하기 위한 입력값을 받기 위한 출력문과 기능 호출 메서드에 대해서는 따로 분리를 하기가 깔끔하지 않은 것 같아서 우선 냅두었는데, 같은 클래스 내에서 각 기능의 메서드에 이를 묶고 switch-case 문에서 기능 당 하나의 메서드만 호출하도록 하는 편이 더 깔끔할까요? 기능에 비해 메서드가 너무 많이 만들어지는 것 같아서 좋은 방법인지 잘 모르겠습니다.

2023-10-04 17:00 UTC, JIN-076 commented on src/main/java/dev/course/controller/BookController.java
> +
코드를 작성하면서 제 나름의 가독성을 좋게 하기 위해 줄 띄움을 두는 편인데, 좋지 않은 습관일까요,,?

2023-10-04 17:00 UTC, JIN-076 commented on src/main/java/dev/course/service/LibraryManagement.java
> +        this.consoleManager = libraryConfig.getConsoleManager();
네! consoleManager 의존성은 사용되지 않아서 해당 부분 제거했습니다!

2023-10-04 17:01 UTC, JIN-076 commented on src/main/java/dev/course/service/LibraryManagement.java
> +        bookList.forEach(this.bookRepository::printBook);
의도한 것은 아닌데, 제가 메서드를 레이어별로 나누는 과정에서 잘 못 넣어둔 것 같습니다. 해당 메서드는 Service 레이어인 LibraryManagement 클래스로 옮겨 수정했습니다!

2023-10-04 17:04 UTC, JIN-076 commented on src/main/java/dev/course/service/LibraryManagement.java
> +        if (book.getState().equals(BookState.RENTAL_AVAILABLE)) {
복잡한 if문을 두는 것이 좋지 않아 보여서 고민하던 차였는데, BookState 내부로 숨기는 아이디어가 좋은 것 같아서, 각 state에 대한 대여, 반납, 분실에 대한 핸들러 로직을 BookState ENUM 클래스로 옮겨두었습니다. 그 과정에서 해당 ENUM 클래스가 의존성으로 주입받은 repository와 Book 오브젝트를 가지고 직접 저장소에 데이터를 수정하는 책임을 가지게 되었는데, 이 부분에 대해서는 책임으로 보았을 때 괜찮은 객체지향 설계(?)인지 궁금합니다!

2023-10-04 17:04 UTC, JIN-076 commented on src/main/java/dev/course/controller/BookController.java
> +            } catch (FuncFailureException | ConsoleIOFailureException e) {
방어적인 코드를 작성하는 것이 매우 필요해보입니다! 앞으로도 예외 처리를 하는 데에 있어서 방어적인 코드를 작성하도록 신경쓰는 게 좋겠네요! 염두해두겠습니다~

2023-10-04 17:05 UTC, JIN-076 commented on src/main/java/dev/course/controller/BookController.java
> +                modeId = consoleManager.getInteger();
전혀 의도하지 않은 부분입니다,, 해당 예외에 대해서는 생각을 하지 못했었네요,,

숫자가 아닌 다른 입력이 들어왔을 때에 대한 예외 처리 로직을 추가했습니다!

2023-10-04 17:06 UTC, JIN-076 commented on src/main/java/dev/course/controller/BookController.java
> +    public Book consoleAboutBookInfo() {
명확하게 메서드 명이 기능을 설명하지는 못하는 것 같습니다. 책을 생성하는 기능을 수행한다는 의미를 명확하게 전달할 수 있도록 메서드 수정했습니다!

2023-10-04 17:07 UTC, JIN-076 commented on src/main/java/dev/course/controller/BookController.java
> +                switch (modeId) {
해당 부분에 대해서 문장의 길이를 짧게 하려고 노력했습니다,,! 다만 길이가 크게 줄어들지 않아서 제가 변경한 부분에 대해서 혹시 더 나은 방법이 있다면 코멘트로 남겨주시면 고민해보고 해당 부분 반영하도록 하겠습니다.

2023-10-04 17:10 UTC, JIN-076 commented on src/main/java/dev/course/service/LibraryManagement.java
> +    public void returns(Long bookId) throws FuncFailureException {
헉,, 코드를 수정하는 과정에서 의미 없는 throws 선언이 되어 있는 것을 지우지 않았네요,, 의미없는 throws 선언들은 모두 제거해두었습니다. 

그리고 대여, 반납, 분실 등 기능에 있어서 예외가 발생해야 한다고 생각한 부분에 대해서는 예외를 던지도록 했고, 이를 BookController에서 받아서 한 번에 처리를 하는 것이 깔끔하다고 생각이 되어서 예외를 던지도록 설계했습니다! 혹시 이 부분에 대해서 제가 잘못 생각하고 있다면 코멘트로 남겨주시면 고민해보도록 하겠습니다.

2023-10-04 17:12 UTC, JIN-076 commented on src/main/java/dev/course/service/LibraryManagement.java
> +        if (book.getState().equals(BookState.RENTAL_AVAILABLE)) {
객체지향 설계 원칙에서 Tell, Don't Ask (TDA) 원칙이 있다는 것을 이번에 처음 알았네요,, 

확실히 오브젝트에서 값을 꺼내는 것보다 오브젝트에게 물어보는 것이 더 좋다고 생각되어집니다! Book 도메인에 tell하는 메서드를 작성해두고 해당 부분 수정했습니다.

2023-10-04 17:14 UTC, JIN-076 commented on src/main/java/dev/course/service/LibraryManagement.java
> +            Book returned = new Book(book.getBookId(), book.getTitle(), book.getAuthor(), book.getPage_num(), BookState.ARRANGEMENT);
처음에는 setter 메서드를 사용해서 변경하려는 값만 수정하고 업데이트를 하도록 했었는데, setter 사용은 (웬만하면?) 지양하는 것이 좋다라는 내용을 접하고 나서 setter를 사용하지 않기 위해서 Book 생성자를 사용하게 되었습니다.

해당 부분에 대해서 state에 대해 값을 수정하는 update 메서드에서 값을 수정하고 이를 저장소와 파일에 업데이트할 수 있도록 구현해두었습니다. 이 부분에 대해서 setter 사용은 어느 정도까지 사용을 하는 것이 괜찮은 것인지,, 값을 변경하려는 범위가 작다면(?) 생성자를 두는 것보다 setter 사용이 나은 것인지 기준이 어렵네요,,  서브멘토님께서는 어떻게 생각하시는지 궁금합니다!

2023-10-04 17:14 UTC, JIN-076 commented on src/main/java/dev/course/service/LibraryManagement.java
> +    public void lost(Long bookId) throws FuncFailureException {
윗 코멘트와 같이 수정해두었습니다!

2023-10-04 17:15 UTC, JIN-076 commented on src/main/java/dev/course/service/LibraryManagement.java
> +        Book book = this.bookRepository.findById(bookId)
삭제하려는 도서에 대해서 존재하지 않을 경우, 존재하지 않는다는 예외를 발생시키고자 findById로 찾도록 구현을 했었습니다.

remove 메서드를 사용하는 과정에서, 키에 매핑되는 값이 없을 경우 null이 발생되는 것을 활용해서 remove 메서드만을 이용해서 삭제하도록 해당 부분 수정했습니다!

2023-10-04 17:18 UTC, JIN-076 commented on src/main/java/dev/course/service/LibraryManagement.java
> +        try {
해당 부분에 대해서 찾아보니, Thread의 sleep 메서드를 사용하는 것이 멀티쓰레드 환경에서 고려해야 할 점이 매우 많다는 내용을 확인했습니다!

그래서 시간을 지연시키는 로직을 고민하다, CountDownLatch 모듈을 이용해서 시간을 지연시키고, 이에 대해서 비동기로 처리하는 로직으로 수정했습니다! 해당 부분 수정하면서 기능을 테스트하는 테스트 코드도 같이 수정해두었습니다! 이렇게 작성했을 경우, 멀티쓰레드 환경에서 고려할 점이 모두 사라졌는지에 대해서는 확신은 부족한 것 같습니다,, 수정한 로직에 대해서 고칠 부분이 있다거나 제가 고려하지 못한 부분이 있다면 코멘트로 남겨주시면 해당 부분 공부하고 반영해보도록 하겠습니다!

2023-10-05 04:53 UTC, JIN-076 commented
## ✅ 피드백 반영사항
- '반납' 메서드에서 '도서 정리중' 상태를 '대여 가능' 상태로 바꾸도록 처리하는 로직에 대해 비동기적으로 처리하기 위해 CompletableFuture 모듈을 사용함
- '반납' 메서드에서 상태가 바뀌는 비동기 로직이 처리되기 전에 시스템이 종료될 경우, 일괄적으로 '대여 가능' 상태로 바뀌도록 예외 처리 추가함
- Thread 모듈의 sleep 메서드를 사용해서 지연을 시킬 경우, 멀티 쓰레드에서 고려해야 할 점이 많아지는 점을 보완하기 위해 CountDownLatch 모듈로 대체함
- Service 레이어에서 '대여' / '반납' / '분실' 메서드의 복잡한 if문을 없애기 위해 BookState ENUM 클래스의 추상 메서드를 사용한 핸들러 로직으로 대체함
- 모드에 대한 입력값이나 기능에 대한 입력값에 대해 잘못된 입력이 들어왔을 경우, 최대 3번까지 Retry가 가능하도록 예외 처리 로직을 추가함

## ✅ PR 포인트 & 궁금한 점 <!-- 리뷰어 분들이 집중적으로 보셨으면 하는 내용을 적어주세요 -->
1. CompletableFuture을 사용해서 비동기적으로 일정한 delay가 지난 후에 상태가 바뀌도록 작성했습니다. 비동기적으로 상태가 변경되기 전에 시스템이 종료될 경우, 일괄적으로 상태를 '대여 가능'으로 변경하고 종료하도록 예외 처리를 추가했습니다.  멘토님과의 1:1 커피챗에서 라이브로 코드를 보여드렸을 때, 수정해야 할 부분이 보여 따로 코멘트를 남겨주시겠다고 하셨는데, 코드 상에서 제가 생각하지 못하거나 놓친 부분이 있는지, 궁금합니다. 

2. Service 레이어에서 Book 오브젝트의 상태에 따라서 처리가 달라지는 if문의 로직이 너무 복잡해 이를 간단하게 처리하고자 BookState ENUM 클래스에 추상 메서드로 핸들러 로직을 만들었습니다. 이 과정에서 ENUM 클래스가 BookRepository 오브젝트를 주입받아서 해당 클래스에서 변경사항을 업데이트하는 책임을 갖게 되었는데, 이에 대해서 객체지향적으로 좋은 설계인지, ENUM 클래스가 갖지 말아야 할 책임을 갖게 된 것은 아닌지 멘토님들의 생각이 궁금합니다!

3. 기존에 비동기적 처리를 테스트하기 위해 일정 시간 delay 시키는 것에 대해 Thread의 sleep 메서드를 사용했었는데, 해당 메서드를 사용할 경우 멀티쓰레드 환경에서 고려해야 할 점이 많아지기 때문에 이를 대체하기 위해 CountDownLatch 모듈을 적용해서 해당 부분을 수정했습니다. 멀티쓰레드 환경에서 안정적이게 작동하게 하기 위해 코드를 수정하였는데, 제가 혹시 놓친 부분이 있을지, 추가적으로 고려해야 할 부분이 있는지 피드백을 받고 싶습니다! 

4. 과제의 구현 사항에서 잘못된 입력이 들어왔을 경우에 대한 예외 처리는 나와있지 않아서, 이에 대해 어떻게 예외 처리를 하면 좋을지 고민하다 잘못 입력이 3번 이상 들어올 경우, 시스템을 종료시키는 것이 좋겠다 라는 생각이 들어 MaxRetryFailureException 예외 클래스를 만들고 예외 처리를 하도록 코드를 추가하였습니다. 이렇게 작성한 예외 처리 로직에 대해서 어떻게 생각하시는지 궁금합니다!

2023-10-05 09:59 UTC, cloudwi commented on src/main/java/dev/course/controller/BookController.java
> +            while (true) {
서비스를 위해서 고민하고 개선한 경험을 하신것 같아요!

고생하셨고 좋은 방법 중 1개 일 것 같다고 말씀드리고 싶어요!

2023-10-05 10:00 UTC, cloudwi commented on src/main/java/dev/course/controller/BookController.java
> +                        System.out.println("[System] 도서 등록 메뉴로 넘어갑니다.\n");
switch-case 문에서 기능 당 하나의 메서드만 호출하도록 

가독성을 생각했을때 좋을 것 같아요.

하지만 불필요한 경우가 있다면 지인님 고민과 생각에 따라 하시면 좋을 것 같아요.

2023-10-05 10:00 UTC, cloudwi commented on src/main/java/dev/course/controller/BookController.java
> +
큰 문제는 없어 보여요.
단순히 신기해서 남겨보아요!

2023-10-05 10:00 UTC, cloudwi commented on src/main/java/dev/course/service/LibraryManagement.java
> +        this.consoleManager = libraryConfig.getConsoleManager();
굿!

2023-10-05 10:02 UTC, cloudwi commented on src/main/java/dev/course/service/LibraryManagement.java
> +        if (book.getState().equals(BookState.RENTAL_AVAILABLE)) {
안좋은 방법이라고 말씀드리고 싶어요.

Book이 가지고 있는 State를 활용해서 Book 객체 안에서 처리하는 방법은 어떤가요?

2023-10-05 10:05 UTC, cloudwi commented on src/main/java/dev/course/controller/BookController.java
> +                switch (modeId) {
이전 보다 개선되었다고 생각해요 !!

2023-10-05 12:51 UTC, JIN-076 commented on src/main/java/dev/course/service/LibraryManagement.java
> +        if (book.getState().equals(BookState.RENTAL_AVAILABLE)) {
서브멘토님께서 남겨주신 부분에 대해서 제가 제대로 이해를 잘 못 하고 있는 것 같아서 다시 코멘트를 남깁니다!

현재 ENUM 클래스에서 인자로 전달받은 BookRepository와 Book 객체를 통해서, 메서드 내에서 BookRepository의 update 메서드를 호출하는 책임을 가지고 있습니다. 멘토님께서 남겨주신, Book이 가지고 있는 State를 활용해서 Book 객체 안에서 처리하는 방법이, 현재 제가 적용한 Book 객체를 주입받아 update 메서드를 호출하는 방법과 다르지 않다는 생각이 들어서요,,,! 
_(어쩌면 제가 '적집 저장소에 데이터를 수정하는 책임' 이라고 남긴 부분때문에 다르게 받아들여진 것은 아닐까,,! 하는 생각도 들었습니다,,,,)_

혹시 Book 클래스 내에서 state 필드를 이용해서 해당 클래스 내에서 처리를 하라는 의미인 것인지, Service 레이어에서 Book 객체 안에서 처리하는 방식으로 하라는 것인지 제가 잘 이해를 못하고 있는 것 같습니다! 혹시 추가적으로 설명을 해주실 수 있을까요?

2023-10-05 13:17 UTC, cloudwi commented on src/main/java/dev/course/service/LibraryManagement.java
> +        if (book.getState().equals(BookState.RENTAL_AVAILABLE)) {
위에서 커뮤니케이션적으로 제대로 이해하지 못하고 리뷰를 한 것 같네요!

하나의 PR에서 변경하고 수정한 내용이 바로바로 반영되어서 보이는 것이 아니라 혼동이 있는 것 같아요!

변경하신거 좋아요.

마지막으로 하나만 더 꼽으면 getState()를 하지 않고 수행할 수 있을까요 ?

2023-10-05 14:50 UTC, JIN-076 commented on src/main/java/dev/course/service/LibraryManagement.java
> +        if (book.getState().equals(BookState.RENTAL_AVAILABLE)) {
서브멘토님께서 조언해주신대로, 
1. BookState ENUM 클래스에서 Repository 의존성 제거, 예외 발생을 담당
2. Book 클래스에서 state의 핸들러 로직 호출, toStatus (setter 대체) 메서드 추가, 이를 아우르는 메서드 추가 (getState()를 숨기기 위함)
3. LibraryManagement 클래스 (service) 에서 상태 변경을 위한 메서드를 호출, 변경된 Book 객체에 대해 update 호출
4. BookRepository에서 수정을 위한 setter 메서드 제거, Book 객체만을 주입받아서 저장소에 업데이트

다음 4가지 변경사항에 대해서 리팩토링을 했고, 테스트 코드에도 변경사항을 모두 수정해두었습니다!

2023-10-05 14:55 UTC, JIN-076 commented on settings.gradle
> +rootProject.name = 'Java_libraryManagement'
아 다시 확인해보니 카멜 표기법이 아니라 하이픈(-)을 사용하는 표기법이 맞는 것 같습니다! 제가 [링크](https://www.quora.com/What-is-the-naming-convention-of-directory-or-projects-name-for-programming-Which-one-is-the-best-hello-word-helloWorld-or-hellow_world)에서 확인을 했는데 혼동하고 잘못 이해를 한 것 같습니다!

하이픈 표기법에 맞춰 수정했습니다!

2023-10-06 10:59 UTC, cloudwi commented on src/main/java/dev/course/service/LibraryManagement.java
> +        if (book.getState().equals(BookState.RENTAL_AVAILABLE)) {
고생하셨습니다.

2023-10-07 05:50 UTC, aegis1920 commented on settings.gradle
> +rootProject.name = 'Java_libraryManagement'
보내주신 링크를 보니 정확한 답은 없다고 이야기하기도 하네요ㅎㅎ
그래도 공식문서에 나온 걸 바탕으로 컨벤션을 잡으면 좀 더 명확해질 것 같습니다!

2023-10-07 09:09 UTC, aegis1920 commented on src/test/java/LibraryAppFeatureTest.java
> +    @DisplayName("테스트 모드에서 정리중인 도서 10초 뒤 도서 대여 성공 검증")
테스트는 자주 실행되기 때문에 속도가 아주 중요합니다! 10초보다 훨씬 더 줄여야할 것 같아요!

2023-10-07 09:09 UTC, aegis1920 commented on src/test/java/LibraryAppFeatureTest.java
> +public class LibraryAppFeatureTest {
실패 케이스에 대해서 잘 검증해주셨네요 👍 👍

2023-10-07 09:09 UTC, aegis1920 commented on src/test/java/LibraryAppFeatureTest.java
> +    private FileOutputStream fileOutputStream;
Writer와 Stream은 테스트 클래스의 필드로 빼지 않아도 될 것 같습니다. Each에서 사용되고 있네요!

2023-10-07 09:09 UTC, aegis1920 commented on src/main/java/dev/course/service/LibraryManagement.java
> +        ScheduledExecutorService executorService = Executors.newScheduledThreadPool(1);
> CompletableFuture을 사용해서 비동기적으로 일정한 delay가 지난 후에 상태가 바뀌도록 작성했습니다. 비동기적으로 상태가 변경되기 전에 시스템이 종료될 경우, 일괄적으로 상태를 '대여 가능'으로 변경하고 종료하도록 예외 처리를 추가했습니다. 멘토님과의 1:1 커피챗에서 라이브로 코드를 보여드렸을 때, 수정해야 할 부분이 보여 따로 코멘트를 남겨주시겠다고 하셨는데, 코드 상에서 제가 생각하지 못하거나 놓친 부분이 있는지, 궁금합니다.

afterDelayArrangementComplete 메서드가 실행될 때마다 1개의 새로운 스레드 풀을 만들게 될 것 같은데요. 스레드 풀을 사용하신 이유가 궁금합니다! (Book이 반납한 시간을 갖고 있도록 하는 구조로 만든다면 5분 delay를 위해서 코드를 따로 작성하지 않아도 될 것 같아보이네요?)

2023-10-07 09:09 UTC, aegis1920 commented on src/main/java/dev/course/service/LibraryManagement.java
> +            boolean completed = latch.await(delay + 1000, TimeUnit.MILLISECONDS);
여기 기본 딜레이에 1000이 추가된 이유는 무엇인가요?

2023-10-07 09:09 UTC, aegis1920 commented on src/main/java/dev/course/domain/Book.java
> +public class Book implements Comparable {
Book이라는 도메인을 순서가 있는 도메인으로 볼 지 조금 애매한 느낌도 듭니다ㅎㅎ

2023-10-07 09:09 UTC, aegis1920 commented on src/main/java/dev/course/domain/BookState.java
> +public enum BookState {
> Service 레이어에서 Book 오브젝트의 상태에 따라서 처리가 달라지는 if문의 로직이 너무 복잡해 이를 간단하게 처리하고자 BookState ENUM 클래스에 추상 메서드로 핸들러 로직을 만들었습니다. 이 과정에서 ENUM 클래스가 BookRepository 오브젝트를 주입받아서 해당 클래스에서 변경사항을 업데이트하는 책임을 갖게 되었는데, 이에 대해서 객체지향적으로 좋은 설계인지, ENUM 클래스가 갖지 말아야 할 책임을 갖게 된 것은 아닌지 멘토님들의 생각이 궁금합니다!

음.. 일단 BookState가 BookRepository를 주입받은 건 아닌 것 같고, Book을 말씀해주신 게 맞을까요? 그리고 주입받았다기보다는 파라미터로 전달받아서 update하는 형태로 보입니다. BookState는 책의 상태를 말해주는 Enum 값인데요. 책의 상태를 말해주는 Enum인데 여기서 책을 빌리는 행동을 handle한다던지, 책 반납하는 행동을 handle한다던지, 이렇게 책임을 갖는 게 맞는지 스스로 고민해보시면 좋겠습니다. 개인적으로는 맞지 않다고 생각들고 전반적으로 책을 handle하는 BookHandler라고 클래스로 분리하든지, Service에서 처리를 하든지 해야될 것 같아요!

2023-10-07 09:09 UTC, aegis1920 commented on src/main/java/dev/course/service/LibraryManagement.java
> +        CountDownLatch latch = new CountDownLatch(1);
> 기존에 비동기적 처리를 테스트하기 위해 일정 시간 delay 시키는 것에 대해 Thread의 sleep 메서드를 사용했었는데, 해당 메서드를 사용할 경우 멀티쓰레드 환경에서 고려해야 할 점이 많아지기 때문에 이를 대체하기 위해 CountDownLatch 모듈을 적용해서 해당 부분을 수정했습니다. 멀티쓰레드 환경에서 안정적이게 작동하게 하기 위해 코드를 수정하였는데, 제가 혹시 놓친 부분이 있을지, 추가적으로 고려해야 할 부분이 있는지 피드백을 받고 싶습니다!

넵, runAsyncToWaitArrangement 부분에 한해서 멀티스레드 환경에서도 작동하도록 잘 수정해주셨는데요. 결론부터 말씀드리면 먼저 다른 부분에서 멀티스레드 환경이 고려되지 않아 수정이 필요합니다.

일단 GeneralBookRepository의 storage 필드 자체가 Concurrency 하지 않아 이대로 멀티스레드 환경으로 가면 데이터가 완전히 꼬이게 될 거예요. 조회하는 필드에서 Immutable 하게 만드는 것도 필요하구요. 개인적으로 멀티스레드에 대한 이해와 개발은 다음 미션에서 해도 충분할 것 같아서 이정도만 코멘트 드려도 될 것 같습니다 🙇

2023-10-07 09:09 UTC, aegis1920 commented on src/main/java/dev/course/controller/BookController.java
> +        System.out.println("[System] 잘못된 정보가 " + count + "회 입력되었습니다. (재입력: 'Y' / 종료 'N')\n");
> 과제의 구현 사항에서 잘못된 입력이 들어왔을 경우에 대한 예외 처리는 나와있지 않아서, 이에 대해 어떻게 예외 처리를 하면 좋을지 고민하다 잘못 입력이 3번 이상 들어올 경우, 시스템을 종료시키는 것이 좋겠다 라는 생각이 들어 MaxRetryFailureException 예외 클래스를 만들고 예외 처리를 하도록 코드를 추가하였습니다. 이렇게 작성한 예외 처리 로직에 대해서 어떻게 생각하시는지 궁금합니다!

지인님이 개발하신 게 웹 서버라고 가정하고 실제로 서비스되고 있다고 생각해볼게요. 사용자에게 서비스되고 있는 와중에 사용자가 3번 잘못 입력했어요. 이때 시스템을 아예 종료시키는 게 맞을까요?

2023-10-08 14:53 UTC, JIN-076 commented on src/test/java/LibraryAppFeatureTest.java
> +    @DisplayName("테스트 모드에서 정리중인 도서 10초 뒤 도서 대여 성공 검증")
해당 부분을 반영해서 '도서 정리중' 상태에서 '대여 가능' 상태로 바꾸는 테스트 시간을 10초에서 2초로 줄였습니다!

2023-10-08 14:54 UTC, JIN-076 commented on src/test/java/LibraryAppFeatureTest.java
> +    private FileOutputStream fileOutputStream;
굳이 클래스의 필드로 뺄 필요가 없겠네요! 해당 부분 반영해서 테스트 클래스의 필드에서 제거했습니다!

2023-10-08 14:56 UTC, JIN-076 commented on src/main/java/dev/course/service/LibraryManagement.java
> +        ScheduledExecutorService executorService = Executors.newScheduledThreadPool(1);
처음 반납을 하고 '도서 정리중' 상태에서 '대여 가능' 상태로 바뀌게 하는 방법을 고민할 때, Book 도메인에 반납한 시간에 대한 필드를 추가해야겠다는 생각을 하지 못하고 비동기적으로 처리를 하는 방법에 대해서 고민하다가 Thread Pool을 사용하는 방법을 선택하게 되었습니다. Book이 반납한 시간을 갖고 있도록 하는 구조에 대해서도 구현을 해보면 좋을 것 같네요!

2023-10-08 14:58 UTC, JIN-076 commented on src/main/java/dev/course/service/LibraryManagement.java
> +            boolean completed = latch.await(delay + 1000, TimeUnit.MILLISECONDS);
특정 delay의 시간이 지난 후에 실행되는 메서드
1. '도서 정리중' -> '대여 가능'으로 상태를 바꾸는 메서드
2. 바뀐 상태에 대해서 JSON 파일에 업데이트하는 메서드
두 메서드를 호출하는 과정에서 1초의 시간이 더 소요되는 것을 감안하여 1초를 추가하였습니다.

2023-10-08 15:01 UTC, JIN-076 commented on src/main/java/dev/course/domain/Book.java
> +public class Book implements Comparable {
조금 애매한 것 같기도 하네요,, 조회를 하고 출력을 하는 과정에서 bookId를 정렬된 순서로 출력하는 것이 좋겠다는 생각이 들어서 그렇게 구현을 하게 되었습니다!

2023-10-08 15:02 UTC, JIN-076 commented on src/main/java/dev/course/domain/BookState.java
> +public enum BookState {
넵! 저도 해당 책임을 BookState 클래스가 갖는 것이 맞지 않다고 생각하여 해당 로직을 Service 레이어에서 처리하도록 수정했습니다!

2023-10-08 15:03 UTC, JIN-076 commented on src/main/java/dev/course/service/LibraryManagement.java
> +        CountDownLatch latch = new CountDownLatch(1);
코멘트 감사합니다! 해당 부분에 대해서 자세히 공부해보도록 하겠습니다! 🙇🏻‍♀️

2023-10-08 15:04 UTC, JIN-076 commented on src/main/java/dev/course/controller/BookController.java
> +        System.out.println("[System] 잘못된 정보가 " + count + "회 입력되었습니다. (재입력: 'Y' / 종료 'N')\n");
시스템을 아예 종료시키는 것은 좋지 않은 방법인 것 같습니다! 잘못된 입력에 대해서 제대로 입력을 할 수 있도록 메시지를 띄워주는 것이 더 좋은 방법일 듯 싶군요!

2023-10-09 10:29 UTC, aegis1920 commented on src/test/java/LibraryAppFeatureTest.java
> +    @DisplayName("테스트 모드에서 정리중인 도서 10초 뒤 도서 대여 성공 검증")
개인적으로는 2초도 많아보이기는 하는데요. 몇 초 뒤에 대여 가능 상태인 것을 검증하기 위해서 테스트에 sleep을 주는 구조가 맞는 건지 의문 들기도 하네요ㅎㅎ 시간을 파라미터로 넣을 수 있도록 한다면 5분 이후인 시간을 넣으면 대여 가능으로 변경, 5분 이전인 시간을 넣으면 정리중인 상태 그대로. 이런 식으로 테스트할 수 있다면 더 나을 것 같습니다.

2023-10-09 10:31 UTC, aegis1920 commented on src/main/java/dev/course/service/LibraryManagement.java
> +        ScheduledExecutorService executorService = Executors.newScheduledThreadPool(1);
스레드 풀의 크기가 하나이기도 하고 어차피 스케줄링을 통해서 특정 로직만 사용하는 구조이니 스레드 풀 없이 스케줄링 + 스레드(스레드 풀 없이 new Thread)의 구조로 갔어도 됐었을 것 같다는 생각이 들었습니다ㅎㅎ 나중에 여유되신다면 한 번 구현해보세요!

2023-10-09 10:39 UTC, aegis1920 commented on src/main/java/dev/course/domain/Book.java
> +public class Book implements Comparable {
Book 도메인을 순서가 있는 도메인으로 보기 어렵다면 도메인에 Comparable을 쓰기보단 Comparator를 직접 구현해서 정렬하는 것이 더 나아보입니다!

2023-10-09 10:41 UTC, aegis1920 commented
과제 열심히 해주시고 끝까지 반영하시느라 고생 많으셨습니다! 👍 
과제는 여기서 머지하겠습니다! 이후에 궁금한 점이 있으시면 DM주시거나 코멘트 따로 남겨주세요!

2023-10-09 10:41 UTC, merged