[5기 - 조인수] 1~2주차 과제: 도서 관리 어플리케이션 제출합니다.
prgrms-be-devcourse/java-library-management pull request #18
Opened 2023-09-29 05:03 UTC by ZZAMBAs

## 📌 과제 설명
이 과제는 도서를 관리하는 애플리케이션을 만드는 과제입니다. 도서관처럼 다음 기능이 있어야 합니다. 
* 신규 도서 등록(제목, 작가, 페이지 수 기입)
* 도서 전체 목록 조회
* 도서 제목을 기준으로 검색
* 도서 번호를 기준으로 다음을 수행
  * 대여
  * 반납
  * 분실 처리
  * 삭제 처리

위 모든 사항을 객체지향적인 코드로 구현하는 것이 핵심입니다.

콘솔로 위 기능을 처리합니다. 1번 운용 모드는 최초에 파일을 받아와 도서를 등록(초기화)합니다. 또 콘솔로 등록한 도서는 File에 저장되어 다음에 애플리케이션 재시작 시에도 유지가 되어야 합니다. 2번 테스트 모드는 단순히 빈 리스트로 시작을 하고 저장을 하지 않습니다.
특이점으로는 반납 후 5분 간 해당 도서는 '정리중' 상태에 들어가 대여가 불가능해진다는 점이 있습니다.

## 👩‍💻 요구 사항과 구현 내용
패키지를 다음으로 구분했습니다.
* main
  * entity
    * Book: 도서 객체를 담당하는 클래스입니다.
    * State: 도서의 현재 상태(대여 가능, 대여중, 정리중, 분실됨, 삭제됨) Enum입니다.
  * manage
    * TotalManager: 전체 매니저 클래스입니다. 전체 관리자가 아래 파일 매니저와 도서 매니저의 기능을 이용해 위 기능의 전반적 처리를 담당하며 실질적 처리는 BookManager에게 위임합니다.
    * file
      * FileManager: 파일 처리 매니저 인터페이스입니다. 읽기와 쓰기 메서드가 있고, 읽기 메서드는 파일을 읽어와 Book 리스트로 반환해주고, 쓰기 메서드는 Book 리스트를 받아서 파일에 필드들을 적어줍니다.
      * CsvFileManager: CSV로 처리하는 파일 처리 매니저 클래스입니다.
      * TestFileManager: 2번 테스트 모드로 운용할 때 사용되며 아무 행동도 하지 않습니다.
    * book
      * BookManager: 도서 처리를 전문으로 담당하는 인터페이스입니다. 위 8가지 기능을 전부 처리합니다.
      * ListBookManager: List<Book>으로 도서들을 관리하고 그 요소들을 수정합니다. saveFile() 메서드로 해당 리스트들을 파일에 저장합니다.
* test
  * manage
    * book
      * ListBookManagerTest: ListBookManager를 테스트 하는 코드입니다.
    * file
      * CsvFileManagerTest: CsvFileManager를 테스트하는 코드입니다.

의존관계 그림은 다음처럼 생각이 되었습니다.

![image](https://github.com/prgrms-be-devcourse/java-library-management/assets/76583883/9ca94c7f-b100-40d2-b1c7-67135f41974f)

## ✅ PR 포인트 & 궁금한 점
멘토님, 안녕하세요. 일단 코드 리뷰 해주셔서 미리 감사드립니다. 제가 매운맛으로 신청했다보니.. 다음 상황을 가정해서 해주시면 정말정말 감사하겠습니다.

> 휴가 갔다 왔는데 같은 부서 신입이 코드를 이렇게 짜놓은 상황 + 오늘까지 이거 다 처리해야 하는 상황 

이런 비슷한 상황으로 부탁드립니다!

1. 최대한 OOP적이면서도 가독성이 높은 코드를 구현하려고 했지만 그렇지 못한 것 같습니다... 예를 들어 if문을 더 줄이고 싶지만 그렇다고 따로 어떻게 할 수 있을지 몰라서 냅두다보니 TotalManager의 run() 메서드에 if else 문이 마구마구 나타납니다. 추가적으로 try catch문도 별로 예쁘게 보이지가 않구요..이런 코드를 어떻게 좋게 만들 수 있을지가 궁금합니다.
2. 제 코드가 SOLID를 전부 지켰다고 볼 수 있을까요? 그 중에서도 SRP는 단일 책임 원칙인데 이게 단일 책임을 지켰다고 저는 생각을 하지만..(BookManager는 도서 관리 책임만 지고, FileManager는 파일 입출력만 신경쓰고..) 실제로는 아닐 수도 있다고 생각합니다. 이것을 확실하게 알 수 있는 방법이 너무 궁금합니다. 답이 딱 나오지 않고 애매한 개념은 저에게 너무나 어려운 것 같습니다..
3. Book 클래스 내부를 보면 getter가 모든 필드에 달려있습니다. 사실은 setter와 getter를 지양하고 필요한 부분만 따로 메서드를 생성하려고 했었습니다. 그런데 그렇게 해서 코드를 짜다보니 Book을 이용하는 클래스에서 Book의 어떤 필드 하나만 필요하게 되기도 하고, 어떤 때는 2개가 필요하고 그래서 나중에 다 필요할 수도 있겠다 싶어서 그냥 getter를 전부 뚫어버렸는데 이건 역시 좋지 못한 걸까요?
4. 개발을 할 때 일단 최소 설계만 하고 구현한 뒤에 리팩토링을 하는 것이 좋을까요, 아니면 첫 설계부터 확실히 잡은 뒤에 코드를 작성하는 것이 좋을까요?
5. 스프링 없는 테스트 코드는 이번이 처음입니다. 사실 테스트 코드와도 친하지는 않은 것 같습니다. 제 테스트 코드의 문제점이 있을까요?
6. 전체적인 제 코드 총평과 제 코드에서 정말 좋지 않다고 생각되는 부분을 뽑아주시면 감사하겠습니다!

2023-09-29 14:15 UTC, aegis1920 requested changes
안녕하세요 인수님! 빙봉입니다 🙂 

몇 가지 코드리뷰 남겼습니다! 확인 부탁드려요!

> 최대한 OOP적이면서도 가독성이 높은 코드를 구현하려고 했지만 그렇지 못한 것 같습니다... 예를 들어 if문을 더 줄이고 싶지만 그렇다고 따로 어떻게 할 수 있을지 몰라서 냅두다보니 TotalManager의 run() 메서드에 if else 문이 마구마구 나타납니다. 추가적으로 try catch문도 별로 예쁘게 보이지가 않구요..이런 코드를 어떻게 좋게 만들 수 있을지가 궁금합니다.

- 개인적으로는 switch 문으로 변경하는 게 가독성이 좀 더 좋을 것 같구요, try catch 문은 예외처리하는데 필요한 부분이라 예쁘게 보이지 않는 부분은 어쩔 수 없는 것 같습니다. 가능한 함수로 빼서 가독성을 좋게 하고 클래스로 뺄 수 있는 부분은 빼보도록 해보죠!

> 제 코드가 SOLID를 전부 지켰다고 볼 수 있을까요? 그 중에서도 SRP는 단일 책임 원칙인데 이게 단일 책임을 지켰다고 저는 생각을 하지만..(BookManager는 도서 관리 책임만 지고, FileManager는 파일 입출력만 신경쓰고..) 실제로는 아닐 수도 있다고 생각합니다. 이것을 확실하게 알 수 있는 방법이 너무 궁금합니다. 답이 딱 나오지 않고 애매한 개념은 저에게 너무나 어려운 것 같습니다..

- SOLID가 다 옳은 게 아닙니다. 때에 따라서 적절하게 활용하는 것이 필요합니다. 예를 들어서, SRP 원칙을 지킨다고 모두 다 클래스로 나눠버리면 하나의 클래스 파일에 하나의 책임만 가지게 되긴 하겠지만, 클래스 파일도 많아지고 굳이 필요없는 wrapper 클래스와 비슷한 느낌의 클래스만 생길 수도 있습니다. 상황에 따라서 적절하게 원칙을 잘 적용할 수 있으면 됩니다. 이는 경험이 해결해줄 문제이구요. (저도 배우고 있는 중입니다 🙂 )

> Book 클래스 내부를 보면 getter가 모든 필드에 달려있습니다. 사실은 setter와 getter를 지양하고 필요한 부분만 따로 메서드를 생성하려고 했었습니다. 그런데 그렇게 해서 코드를 짜다보니 Book을 이용하는 클래스에서 Book의 어떤 필드 하나만 필요하게 되기도 하고, 어떤 때는 2개가 필요하고 그래서 나중에 다 필요할 수도 있겠다 싶어서 그냥 getter를 전부 뚫어버렸는데 이건 역시 좋지 못한 걸까요?

클래스 필드에 대한 Getter를 지양하라의 의미가 무조건 지양하라의 의미는 아니여서요. 객체의 캡슐화를 생각하며 무분별한 Getter 지양에 의미를 두면 좋을 것 같습니다.
이쪽 글을 참고하시면 도움이 될 것 같습니다 ([링크](https://tecoble.techcourse.co.kr/post/2020-04-28-ask-instead-of-getter/))

> 개발을 할 때 일단 최소 설계만 하고 구현한 뒤에 리팩토링을 하는 것이 좋을까요, 아니면 첫 설계부터 확실히 잡은 뒤에 코드를 작성하는 것이 좋을까요?

둘 다 너무 중요한데요. 일단 마감기한이라는 게 존재하기 때문에 둘 중 어느 게 더 중요하냐고 한다면 구현이 더 중요하다고 말할 순 있을 것 같습니다. 설계와 구현에 적절한 시간을 배분해서 완료하는 게 중요합니다.

> 스프링 없는 테스트 코드는 이번이 처음입니다. 사실 테스트 코드와도 친하지는 않은 것 같습니다. 제 테스트 코드의 문제점이 있을까요?

테스트 코드 작성 시 비즈니스 로직에 대한 테스트를 하면 좋을 것 같습니다. 이번 요구사항에서 중요한 `도서가 '대여중' 상태 일 때는 도서를 반납할 수 있습니다. 이때 도서가 반납되면 도서의 상태는 '도서 정리중' 상태로 바뀌어야합니다. 그리고 '도서 정리중' 상태에서 5분이 지난 도서는 '대여 가능'으로 바뀌어야합니다. (대여된 후 5분이 지난 도서를 누군가 대여하려고 했을 때 대여 처리가 되어야한다는 겁니다)`를 테스트할 수 있는 코드를 작성해보는 게 중요합니다. 한 번 시도해보세요!

> 전체적인 제 코드 총평과 제 코드에서 정말 좋지 않다고 생각되는 부분을 뽑아주시면 감사하겠습니다!

전반적으로 잘 작성해주셨습니다! 👍 다만 요구사항을 정확히 만족하는 코드가 가장 중요한 부분이라서요. file path 부분을 잘 고려해서 작성해주시면 좋을 것 같습니다!

2023-09-29 14:15 UTC, aegis1920 commented on build.gradle
> +    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine'
api와 engine을 모두 포함하는 `org.junit.jupiter:junit-jupiter:5.8.1`을 사용했어도 됐을 것 같은데 따로 주신 이유가 있을까요?

2023-09-29 14:15 UTC, aegis1920 commented on build.gradle
> +}
이 부분은 왜 추가된 건가요?

2023-09-29 14:15 UTC, aegis1920 commented on setting.gradle
> +rootProject.name = 'java-library-management'
마지막 줄 개행(EOF의 개행)에 신경써주시면 좋을 것 같습니다!
참고로 유닉스 시스템의 표준이 한 줄에 대한 정의가 개행으로 끝납니다. ([링크](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_206))

intellij에서 아래 설정으로 자동으로 넣어줄 수 있습니다 🙂 

<img width="430" alt="image" src="https://github.com/prgrms-be-devcourse/java-library-management/assets/22311557/2fee0f24-e557-454a-a24d-e9d41db11b3d">

2023-09-29 14:15 UTC, aegis1920 commented on src/main/java/Main.java
> +public class Main {
Main이라는 이름이 아니라 내가 구현하려고 하는 도메인의 이름이 들어가야할 것 같아요! XXXApplicaiton처럼요?

2023-09-29 14:15 UTC, aegis1920 commented on src/main/java/Main.java
> +            }
예외 처리 좋네요! 👍 1과 2는 모드 상태가 명백하기에 상수화해주면 좋을 것 같아요!

2023-09-29 14:15 UTC, aegis1920 commented on src/main/java/Main.java
> +    public static void main(String[] args) {
메인 함수에 너무 많은 것들이 담겨있다고 생각들진 않으실까요? Spring을 해보신 것 같으니 SpringApplication.run()을 떠올려보셔도 좋을 것 같습니다. 실행하는 것 자체를 하나의 클래스로 따로 둬보는 건 어떨까요?

2023-09-29 14:15 UTC, aegis1920 commented on src/main/java/Main.java
> +        Scanner sc = new Scanner(System.in);
별건 아니지만.. main 함수에 있는 이유가 있을까요? static으로 빼보면 어떨까요? 어떤 점이 더 좋을까요?

2023-09-29 14:15 UTC, aegis1920 commented on src/main/java/Main.java
> +                mode = Integer.parseInt(sc.nextLine().trim());
trim보다 더 많은 공백 코드를 제거하는 strip() 함수를 사용해보시죠!(since Java 11)

2023-09-29 14:15 UTC, aegis1920 commented on src/main/java/entity/Book.java
> +package entity;
entity라고 정의해주신 점 인상깊네요. entity 패키지라고 명명하신 이유가 있을까요?

2023-09-29 14:15 UTC, aegis1920 commented on src/main/java/entity/Book.java
> +    private static String[] fieldKoreanName = {"도서번호", "제목", "작가", "페이지 수", "상태"};
상수로 선언해도 될 것 같습니다! 그리고 가급적이면 배열보다는 List를 활용해보는 건 어떨까요? 더 많은 함수들이 있어 활용하기도 좋구요! Java 9부터 of 메서드가 생겨서 좀 더 쉽게 생성할 수 있습니다!

2023-09-29 14:15 UTC, aegis1920 commented on src/main/java/entity/Book.java
> +    private static final int PROCESSING_TIME = 5 * 60 * 1000;
상수와 상수 아닌 것들의 구분을 둬 주시면 가독성이 더 좋아질 것 같아요! 개행으로 구분해보시죠!
그리고 알고 계실 수도 있는데 숫자를 `_`을 넣어서 표현해줄 수 있습니다. 가독성을 위해 긴 숫자들은 `_` 넣어서 표현합니다. e.g. `1_000_000`

2023-09-29 14:15 UTC, aegis1920 commented on src/main/java/entity/Book.java
> +        this.lastReturn = -1;
-1은 어떤 의미인가요? 상수로 명확히 해볼까요?

2023-09-29 14:15 UTC, aegis1920 commented on src/main/java/entity/Book.java
> +    }
entity가 자기 상태를 출력하는 함수를 가지고 있네요.

- entity가 자기 상태를 출력하는 함수를 가지고 있어도 될 지?
- toString()을 오버라이딩해도 됐을 것 같은데 그러지 않은 이유가 있는지?

가 궁금합니다!

2023-09-29 14:15 UTC, aegis1920 commented on src/main/java/entity/Book.java
> +    }
entity에게 tell하는 메서드 생성 좋네요 👍 
Enum 끼리의 비교라면 equals를 쓰지 않고 `==`를 써도 됩니다!

2023-09-29 14:15 UTC, aegis1920 commented on src/main/java/entity/Book.java
> +    private static final int PROCESSING_TIME = 5 * 60 * 1000;
PROCESSING_TIME이라고 한다면 개발자 입장에서 단위가 무엇인지 모를 수 있는데요. 변수명으로 millis라고 적거나 아니면 5분이라고 적거나 혹은 Duration 클래스를 사용하는 게 좋아보입니다 (e.g. `Duration.ofMinutes(5).toMillis()`)

2023-09-29 14:15 UTC, aegis1920 commented on src/main/java/entity/Book.java
> +    public void isOver5Minutes(){
boolean을 return 하고 있는 게 아니므로 is 접두사는 빼야할 것 같고 다른 함수명을 적용해야할 것 같습니다!

2023-09-29 14:15 UTC, aegis1920 commented on src/main/java/entity/State.java
> +    private final String koreanState;
개행 추가해주시고, koreanState 보단 더 나은 변수명이 있을 것 같아요. (e.g. displayName?)

2023-09-29 14:15 UTC, aegis1920 commented on src/main/java/entity/State.java
> +public enum State {
entity 패키지 내에 State라는 이름으로 되어있기 때문에 단순히 상태라는 이름으로는 `책의 상태`라는 의미를 줄 순 없을 것 같습니다. 다른 enum 명으로 변경해보시죠!

2023-09-29 14:15 UTC, aegis1920 commented on src/main/java/exception/BookNumberAlreadyExistException.java
> +    public BookNumberAlreadyExistException() {
사용하지 않는 메서드는 삭제해주세요!

2023-09-29 14:15 UTC, aegis1920 commented on src/main/java/exception/EntityNotFoundException.java
> +public class EntityNotFoundException extends RuntimeException{
RuntimeException으로 주지 않고 NoSuchElementException을 상속해도 괜찮을 것 같네요. 아니면 커스텀하게 만들지 않거나요!

2023-09-29 14:15 UTC, aegis1920 commented on src/main/java/exception/EntityNotFoundException.java
> +public class EntityNotFoundException extends RuntimeException{
여기도 사용하지 않는 메서드는 삭제해주세요!

2023-09-29 14:15 UTC, aegis1920 commented on src/main/java/manage/TotalManager.java
> +    public void run(){
run할 때 기존 데이터를 불러오는 과정이 있다면 init() 과 같은 메서드로 초기 작업이 있어야될 것 같습니다.

2023-09-29 14:15 UTC, aegis1920 commented on src/main/java/manage/book/BookManager.java
> +    State returnBook(int bookNum);
일관성이 있으면 좋을 것 같습니다! e.g. return()

2023-09-29 14:15 UTC, aegis1920 commented on src/main/java/manage/TotalManager.java
> +        books.stream().forEach(book -> {
그냥 foreach를 써도 되겠네요 🙂

2023-09-29 14:15 UTC, aegis1920 commented on src/main/java/manage/TotalManager.java
> +        System.out.print("대여할 도서 번호를 입력해주세요.\n> ");
개행은 시스템마다 다를 수 있어서요! System.lineSeparator()를 활용하시면 좋을 것 같습니다!

2023-09-29 14:15 UTC, aegis1920 commented on src/main/java/manage/book/ListBookManager.java
> +    private final List<Book> bookList; // 전체 노드 풀
다른 자료구조로 바뀌더라도 변수명은 그대로일 수 있도록 books라고 변수명을 수정해보는 건 어떨까요?

2023-09-29 14:15 UTC, aegis1920 commented on src/main/java/manage/book/ListBookManager.java
> +    private final HashMap<Integer, Integer> numToIdx = new HashMap<>(); // {도서번호, idx}
도서번호와 인덱스를 함께 관리하면 추후 유지보수가 힘들어지지 않을까요?
아니면 자료구조 자체를 HashMap 하나로만 관리해도 좋을 것 같습니다. e.g. `HashMap<도서번호, 도서>`

2023-09-29 14:15 UTC, aegis1920 commented on src/main/java/manage/file/CsvFileManager.java
> +        File file = new File(filePath);
- filePath를 temp.csv로만 가져가면 운용모드일 때 Resource에 있는 파일을 못 읽지 않나요?
- 현재 있는 temp.csv 파일이 테스트 모드만을 위한 파일이라면 test 패키지에 있어야하지 않을까요?

2023-09-29 14:15 UTC, aegis1920 commented on src/main/java/manage/file/FileManager.java
> +public interface FileManager {
인터페이스 👍

2023-09-29 14:15 UTC, aegis1920 commented on src/test/java/manage/book/ListBookManagerTest.java
> +                200, State.PROCESSING, System.currentTimeMillis() - 5 * 60 * 1000));
프로덕션 코드에 있는 상수를 그대로 가져다 썼어도 됐을 것 같습니다!

2023-09-29 14:15 UTC, aegis1920 commented on src/test/java/manage/book/ListBookManagerTest.java
> +    void register(){
테스트 명을 명확히 해주면 좋을 거 같아요! 테스트 코드 함수명 컨벤션도 알아보시면 좋을 것 같습니다!

2023-09-29 14:15 UTC, aegis1920 commented on src/main/java/manage/book/ListBookManager.java
BookListManager가 아니고 ListBookManager군요? 어떤 게 더 어울릴까요?

2023-09-30 10:15 UTC, ZZAMBAs commented on build.gradle
> +    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine'
안녕하세요 멘토님! 제가 사실은 gradle 빌드 도구를 직접 이용해 세팅하는 것이 이번이 처음이었습니다. 의존성에 대해서도 잘 몰라서 구글링해서 있던 부분을 가져다 썼더니 저렇게 되었습니다 ㅎㅎ... 다음부터는 의존성도 통합해서 넣도록 하겠습니다!

2023-09-30 10:15 UTC, ZZAMBAs commented on build.gradle
> +}
./gradlew build 시 manifest가 없다는 에러가 자꾸나서 실행 메인 클래스를 설정해주면 안난다고 나와서 추가하게 되었습니다.

2023-09-30 10:17 UTC, ZZAMBAs commented on setting.gradle
> +rootProject.name = 'java-library-management'
이 부분은 혹시 파일 읽기, 쓰기 시에 마지막에 개행을 줘야 한다고 말씀하시는 것이 맞을까요?

2023-09-30 10:17 UTC, ZZAMBAs commented on src/main/java/Main.java
> +public class Main {
넵! LibraryApplication으로 수정하겠습니다!

2023-09-30 10:18 UTC, ZZAMBAs commented on src/main/java/Main.java
> +            }
그 부분을 놓쳤네요. 상수 처리로 수정을 하겠습니다!

2023-09-30 10:26 UTC, ZZAMBAs commented on src/main/java/manage/file/CsvFileManager.java
> +        File file = new File(filePath);
이것도 제 무지에서 비롯된 것 같습니다.. 파일 입출력 코드를 제가 잘 안짜봤어서요.
  저는 운용모드일 때, resources 내부 temp.csv를 읽도록 하고 싶었는데 절대 경로로는 설정하면 안될 것 같아서 상대 경로를 설정하려 했으나 그렇게 하면 빌드된 jar 파일을 실행하는 곳에 따라 저장 장소가 달라졌습니다. 그래서 그냥 temp.csv로 하니 jar 실행 디렉토리 내에서 파일 읽기 쓰기가 되어서 단순히 filePath를 "temp.csv"로 가져갔었습니다. 
  운용 모드는 prod/temp.csv 로, 테스트용으로는 test/temp.csv로 filePath를 설정해 주겠습니다!

2023-09-30 10:26 UTC, ZZAMBAs commented on src/test/java/manage/book/ListBookManagerTest.java
> +                200, State.PROCESSING, System.currentTimeMillis() - 5 * 60 * 1000));
맞습니다. 바로 고칠게요!

2023-09-30 10:26 UTC, ZZAMBAs commented on src/test/java/manage/book/ListBookManagerTest.java
> +    void register(){
이것도 알아보고 수정을 하겠습니다!

2023-09-30 10:27 UTC, ZZAMBAs commented on src/main/java/manage/book/ListBookManager.java
인터페이스 이름을 해치지 않게 하려고 ListBookManager로 하긴 했는데 역시 어색하군요.. BookListManager가 역시 나을 것 같습니다!

2023-09-30 10:36 UTC, ZZAMBAs commented on setting.gradle
> +rootProject.name = 'java-library-management'
아 소스 코드 파일을 개행으로 끝내느 것인가요? 인텔리제이 설정에 이런게 있는지 처음 알게 되었습니다. 감사합니다!

2023-09-30 10:45 UTC, ZZAMBAs commented on src/main/java/Main.java
> +    public static void main(String[] args) {
맞습니다. 따로 클래스를 두어 그것을 실행하도록 하겠습니다.
개인적인 궁금증이긴 한데, main 함수 내에 .run() 메서드만 존재한다면 왜 따로 클래스를 두어 실행을 해야 하는 걸까요??

2023-09-30 10:47 UTC, ZZAMBAs commented on src/main/java/entity/Book.java
> +package entity;
음... 스프링 프로젝트 할때마다 이런 하나의 객체를 다루는 클래스들을 엔티티로 하여 다루길래 무의식적으로 이렇게 한 것 같습니다. 그 이유 말고는 없는 것 같아요.

2023-09-30 10:49 UTC, ZZAMBAs commented on src/main/java/entity/Book.java
> +    private static String[] fieldKoreanName = {"도서번호", "제목", "작가", "페이지 수", "상태"};
메서드 면에서 그런 장점이 있었네요! 상수 선언은 final이 맞겠죠?

2023-09-30 10:52 UTC, ZZAMBAs commented on src/main/java/entity/Book.java
> +    private static final int PROCESSING_TIME = 5 * 60 * 1000;
오... 몰랐습니다. 저 모르는 게 많습니다. 
  PROCESSING_TIME은 5분을 나타내기 위한 상수였는데, 저것을 하나로 퉁쳐서 300_000으로 표현하는 것이 나을까요 아니면 위를 그대로 두고 5 * 60 * 1_000이 나을까요? 전자는 뭔가 잘 이해가 안될 것 같기도 하고 후자는 너무 긴거 같고... 일단은 후자로 남겨 두겠습니다!

2023-09-30 10:53 UTC, ZZAMBAs commented on src/main/java/entity/Book.java
> +    private static final int PROCESSING_TIME = 5 * 60 * 1000;
확실히 모호하네요. PROCESSING_TIME_MILLIS로 수정하겠습니다!

2023-09-30 10:56 UTC, ZZAMBAs commented on src/main/java/entity/Book.java
> +        this.lastReturn = -1;
NEVER_RENTED 로 상수화하겠습니다

2023-09-30 10:58 UTC, ZZAMBAs commented on src/main/java/entity/Book.java
> +    }
오 toString()을 잊고 있었어요! 그걸 쓰는 게 나은 것 같습니다!
  엔티티가 자기 상태를 출력하는 함수를 가지고 있는 것은 뭔가 책임에 어울리지 않는 걸까요? toString()도 존재하니까 있어도 될 것 같기도 한데 엔티티가 가지는 책임은 아닌 것 같기도 하고... 좀 더 고민해 보겠습니다..!

2023-09-30 11:01 UTC, ZZAMBAs commented on src/main/java/entity/Book.java
> +    public void isOver5Minutes(){
이것을 boolean 반환 타입으로 바꾸어도 괜찮을까요?

2023-09-30 11:02 UTC, ZZAMBAs commented on src/main/java/entity/State.java
> +public enum State {
BookState로 변경하겠습니다!

2023-09-30 11:04 UTC, ZZAMBAs commented on src/main/java/entity/State.java
> +    private final String koreanState;
해당 변수명으로 수정하겠습니다!

2023-09-30 11:05 UTC, ZZAMBAs commented on src/main/java/exception/EntityNotFoundException.java
> +public class EntityNotFoundException extends RuntimeException{
보다 자세한 상속을 해야 하기 때문이겠죠? 해당 예외를 상속하도록 바꾸겠습니다!

2023-09-30 11:10 UTC, ZZAMBAs commented on src/main/java/manage/TotalManager.java
> +    public void run(){
멘토님, 혹시 여기서 기존 데이터를 불러오는 과정이 어떤 부분을 의미하시는지 여쭤봐도 될까요? 
기존의 도서 csv 파일은 BookListManager에서 생성자에서 초기화를 해주고 있는데 이를 init()으로 빼는 것이 낫다고 말씀하시는 것이 맞을까요?

2023-09-30 11:11 UTC, ZZAMBAs commented on src/main/java/manage/TotalManager.java
> +        books.stream().forEach(book -> {
stream() 없이도 쓸 수 있었군요!

2023-09-30 11:12 UTC, ZZAMBAs commented on src/main/java/manage/TotalManager.java
> +        System.out.print("대여할 도서 번호를 입력해주세요.\n> ");
감사합니다!

2023-09-30 11:14 UTC, ZZAMBAs commented on src/main/java/manage/book/BookManager.java
> +    State returnBook(int bookNum);
사실 return을 하고 싶었는데 반환 키워드 return과 중복되어서 ㅠㅠ 다른 이름을 생각해서 적어두겠습니다.

2023-09-30 11:15 UTC, ZZAMBAs commented on src/main/java/manage/book/ListBookManager.java
> +    private final List<Book> bookList; // 전체 노드 풀
항상 바뀔 수 있음을 생각해야 하는데 너무 고정시켰네요. 바꾸도록 하겠습니다!

2023-09-30 11:21 UTC, ZZAMBAs commented on src/main/java/manage/book/ListBookManager.java
> +    private final HashMap<Integer, Integer> numToIdx = new HashMap<>(); // {도서번호, idx}
맞습니다. 편의를 위해서 books를 삭제하겠습니다. 위 books만 남길까 고민도 했는데 파일 내 도서번호 순서가 엉망이면 좋지 않을 것 같아서 그냥 위 books를 지우고 HashMap을 books로 이름을 바꾸어 사용하겠습니다.

2023-09-30 11:23 UTC, ZZAMBAs commented on src/main/java/Main.java
> +        Scanner sc = new Scanner(System.in);
저런 공통 유틸을 계속 생성하는 것도 확실히 비효율적이네요. 바로 static으로 바꾸도록 하겠습니다!!

2023-09-30 11:53 UTC, ZZAMBAs commented on src/main/java/entity/Book.java
> +    public void isOver5Minutes(){
changeStateAfter5Minutes() 이름으로 변경했습니다!

2023-09-30 11:59 UTC, ZZAMBAs commented on src/main/java/manage/book/BookManager.java
> +    State returnBook(int bookNum);
revert()로 변경했습니다!

2023-09-30 12:27 UTC, ZZAMBAs commented on src/test/java/manage/book/ListBookManagerTest.java
> +    void register(){
테스트 할 기능을 이름으로 하는 컨벤션으로 적용하겠습니다!

2023-09-30 13:11 UTC, ZZAMBAs commented on src/main/java/manage/file/CsvFileManager.java
> +        File file = new File(filePath);
멘토님.. 첫번째 질문의 답을 못 내겠습니다. 절대 경로를 설정해 주어야 하나요? jar 파일 실행 위치에 따라 파일을 읽는 위치가 달라질 것 같아서 상대 경로를 설정할 수 있는 것인지 잘 모르겠습니다...
이 부분은 좀 더 알아보겠습니다.

2023-10-03 10:11 UTC, aegis1920 commented on build.gradle
> +    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine'
test scope에서 사용하되 Implementatio으로 사용하냐 RuntimeOnly으로 사용하냐에 따라서 또 다를 것 같은데요. 현재 상황에서는 상관없을 것 같아서 위 코멘트 드렸습니다 🙂

2023-10-03 10:14 UTC, aegis1920 commented on build.gradle
> +}
흠.. run configuration에서 잘 설정되어있는데도 그러나요? 저는 지우고 실행해봤는데 잘 됐습니다. 혹시 다시 한 번 확인 가능할까요?
![image](https://github.com/prgrms-be-devcourse/java-library-management/assets/22311557/0e711a00-352a-41e6-9dcf-14941bd410ab)

2023-10-03 10:14 UTC, aegis1920 commented on setting.gradle
> +rootProject.name = 'java-library-management'
나 네넵 파일을 개행으로 끝나는 걸 말씀드렸습니다! 👍

2023-10-03 10:16 UTC, aegis1920 commented on src/main/java/Main.java
> +    public static void main(String[] args) {
구두로도 말씀드렸지만 메인 함수는 Application이 시작되는 지점으로 시작하기 위한 매개변수를 설정하는 곳으로 이해됩니다!

2023-10-03 10:17 UTC, aegis1920 commented on src/main/java/entity/Book.java
> +package entity;
나중에 entity와 domain에 대해서 더 배우실텐데요! 추후 좀 더 고민해보면서 작성해보세요!

2023-10-03 10:17 UTC, aegis1920 commented on src/main/java/entity/Book.java
> +    private static final int PROCESSING_TIME = 5 * 60 * 1000;
넵 구두로 말씀드렸다시피 후자가 더 나은 선택으로 보입니다!

2023-10-03 10:20 UTC, aegis1920 commented on src/main/java/entity/Book.java
> +        this.lastReturn = -1;
NEVER_REVERTED 군요ㅎㅎ 반납되지 않은 상황을 의미한 거라면 NOT_REVERTED도 될 거 같기도 하고요? 만약 완전 초기 상태를 의미하는 거라면 INIT이 들어가야 할 것 같구요

2023-10-03 10:20 UTC, aegis1920 commented on src/main/java/entity/Book.java
> +    public void isOver5Minutes(){
넵 역할에 맞게 함수명을 지어주는 것이 좋습니다!

2023-10-03 10:21 UTC, aegis1920 commented on src/main/java/exception/EntityNotFoundException.java
> +public class EntityNotFoundException extends RuntimeException{
구두로도 말씀드렸지만 이 부분은 고민해보세요!ㅎㅎ

2023-10-03 10:22 UTC, aegis1920 commented on src/main/java/manage/TotalManager.java
> +    public void run(){
구두로도 말씀드린 부분인데요! BookManager의 역할과 초기 등록하는 것을 어디에서 해주면 좋을지 고민해보셔요!

2023-10-03 10:23 UTC, aegis1920 commented on src/main/java/manage/book/BookManager.java
> +    State returnBook(int bookNum);
아 그렇군요ㅋㅋㅋ 저도 모르게 키워드를 생각하지 않고 return()이라고 적었었네요ㅋㅋ

2023-10-03 10:26 UTC, aegis1920 commented on src/main/java/manage/file/CsvFileManager.java
> +        File file = new File(filePath);
구두로 말씀드렸다시피 절대 경로로 설정해주면 직접 서버로 올릴 때 해당 경로를 못 찾는 일이 발생합니다! 이 부분 염두해주시고 피드백 반영해주세요~

2023-10-03 16:59 UTC, cloudwi commented on src/main/java/common/InitApplication.java
> +                mode = Integer.parseInt(sc.nextLine().strip());
sc는 입력을 받는 Scanner의 줄임말로 보여요.

하지만 아무것도 모르는 사람이 보았을 때 어떤 객체인지 정확한 의도를 파악하기 어렵다고 생각해요.

따라서 다른 이름으로 변경하시는 게 어떨까요?

2023-10-03 16:59 UTC, cloudwi commented on src/main/java/common/InitApplication.java
> +        System.out.print("모드를 선택합니다. 1. 운용 모드 2. 테스트 모드" + System.lineSeparator() + "> ");
문자열을 콘솔에 입 출력하는 책임을 분리하는 건 어떤가요?

2023-10-03 16:59 UTC, cloudwi commented on src/main/java/entity/Book.java
> +    private static final List<String> FIELD_DISPLAY_NAMES = List.of("도서번호", "제목", "작가", "페이지 수", "상태");
해당 FIELD_DISPLAY_NAMES 를 사용할 때 .get() 해서 사용하시는 것을 보았어요.

FIELD_DISPLAY_NAMES속 데이터가 궁금하다면 타고 들어가서 확인하고 다시 코드를 작성하는 과정이 번거로울 수 있다고 생각해요.

따라서 조금 더 FIELD_DISPLAY_NAMES를 잘 나타낼 수 있는 형을 사용하는 건 어떨까요?

2023-10-03 16:59 UTC, cloudwi commented on src/main/java/entity/Book.java
> +    public void setBookState(BookState bookState) {
set을 사용하고 있는 것으로 보여요. set 이외의 다른 전략은 없을까요?

2023-10-03 17:05 UTC, cloudwi commented on src/main/java/common/InitApplication.java
> +        }catch (BookNumberAlreadyExistException e){
인재님이 예상하지 못한 예외에 대해서는 따로 처리하지 않고 있어요.

따라서 BookNumberAlreadyExistException 이외의 다른 예외가 발생한다면 서비스가 종료하는 것 일까요?

2023-10-03 17:11 UTC, cloudwi commented on src/main/java/common/InitApplication.java
> +                totalManager = new TotalManager(new BookListManager(new CsvFileManager("temp.csv")));
"temp.csv" 경로를 하드 코딩으로 넣고 있는 것 같아요.

명확한 이름의 상수로 빼는 것이 어떨까요?

2023-10-03 17:16 UTC, cloudwi commented on src/main/java/manage/TotalManager.java
> +            }catch (IllegalArgumentException e){
숫자 9 ~ INT MAX VLAUE 값 을 받았을때 안내 매세지가 제대로 출력되고 있지 않는것 같아요.

의도하신 기능일까요?

2023-10-03 17:18 UTC, cloudwi commented on src/main/java/manage/TotalManager.java
> +        String[] bookInfo = new String[3];
bookInfo 라는 배열을 만들어서 값을 채우고 해당 값으로 Book을 생성해주고 있는 것으로 보여요.

BookInfo를 객체로 관리해보시는 게 어떨까요?

조금 더 가독성과 책임을 분리할 수 있어 보여요.

2023-10-04 02:24 UTC, ZZAMBAs commented on src/main/java/common/InitApplication.java
> +                mode = Integer.parseInt(sc.nextLine().strip());
맞는 말씀입니다! ConsoleInput 정도로 변경하겠습니다.

2023-10-04 02:25 UTC, ZZAMBAs commented on src/main/java/common/InitApplication.java
> +        System.out.print("모드를 선택합니다. 1. 운용 모드 2. 테스트 모드" + System.lineSeparator() + "> ");
클래스를 따로 분리하는 것이 좋을까요? 아니면 메서드를 따로 추출할까요? 방법을 고민해보겠습니다!

2023-10-04 02:35 UTC, ZZAMBAs commented on src/main/java/entity/Book.java
> +    private static final List<String> FIELD_DISPLAY_NAMES = List.of("도서번호", "제목", "작가", "페이지 수", "상태");
계속되는 getter 사용과 바로바로 값을 확인하기 어려운 것이 문제인 것으로 말씀하시는 것이 맞을까요? 다른 자료형을 고민해 보겠습니다...

2023-10-04 02:36 UTC, ZZAMBAs commented on src/main/java/entity/Book.java
> +    public void setBookState(BookState bookState) {
setter를 사실 닫아야 하지만 bookState를 단독으로 바꾸려면 열어야 할 수 밖에 없다고 생각을 했었습니다. 지양해야 하는 만큼 다른 방안을 고심해보겠습니다!

2023-10-04 02:36 UTC, ZZAMBAs commented on src/main/java/common/InitApplication.java
> +        }catch (BookNumberAlreadyExistException e){
주영님 저 인수입니다 ㅠㅠ 다른 예외 가능성을 염두하고 다른 예외가 발생한다면 그 예외도 처리를 하겠습니다!

2023-10-04 02:37 UTC, ZZAMBAs commented on src/main/java/manage/TotalManager.java
> +            }catch (IllegalArgumentException e){
switch 문으로 바꾸면서 default를 빼먹었네요.. 바로 넣겠습니다!

2023-10-04 02:39 UTC, ZZAMBAs commented on src/main/java/manage/TotalManager.java
> +        String[] bookInfo = new String[3];
맞습니다. 바로 객체로 분리하겠습니다!
코드리뷰 감사합니다 주영님!

2023-10-04 02:41 UTC, ZZAMBAs commented on src/main/java/entity/Book.java
> +package entity;
domain으로 네이밍을 변경하겠습니다!

2023-10-04 02:42 UTC, ZZAMBAs commented on src/main/java/entity/Book.java
> +    private static String[] fieldKoreanName = {"도서번호", "제목", "작가", "페이지 수", "상태"};
(private) static final이 상수로 더 맞는 설명으로 이해했습니다!

2023-10-04 02:43 UTC, ZZAMBAs commented on src/main/java/entity/Book.java
> +        this.lastReturn = -1;
변수명 짜기가 프로그래머한테 제일 어렵다는데 정말이네요...

2023-10-04 02:47 UTC, ZZAMBAs commented on src/main/java/entity/Book.java
> +    }
toString()으로 포맷을 정해주는 것이 별로 안좋을 것 같아서 상태 출력을 위한 클래스를 따로 만들겠습니다. 
이유는 이 애플리케이션은 여기서 끝이지만 추후에 혹시라도 출력해주면 안되는 필드가 있을 경우 또는 다른 출력 메서드를 만들어주어야 하는 경우에는 toString()과 결이 안맞을 수도 있다고 생각했습니다.

2023-10-04 02:50 UTC, ZZAMBAs commented on src/main/java/exception/EntityNotFoundException.java
> +public class EntityNotFoundException extends RuntimeException{
기존 예외보다 더 명확하고 자세한 예외를 던져야 할 때라면 사용자 정의 예외를, 그렇지 않아도 되는 상황이라면 기존 예외를 던지도록 하겠습니다. 기존 예외를 던질 때에는 해당 예외가 언제 던져지는지를 고려하여 사용하겠습니다!

2023-10-04 03:02 UTC, ZZAMBAs commented on src/main/java/manage/TotalManager.java
> +    public void run(){
멘토님 이거 사실 기억이 잘 안나서.. 기억을 더듬어 가고 있습니다.
  현재는 BookListManager의 생성자에서 FileManager의 read()로 초기화를 해주고 있으나 FileManager라는 이름에 맞지 않게 Book에 너무 의존적이라 공통 유틸로써의 FileManager를 따로 빼주거나 혹은 현재 FileManager 이름을 BookFileManager로 바꾸라고 말씀을 하셨었던 것 같습니다. 

  그래서 FileManager 이름을 BookFileManager로 바꾸어도 결국 .read()로 BookManager 내에 초기 등록을 해주어야 하는데 이것을 생성자에서 하는 것은 좋지 못한 것일까요? init() 메서드를 따로 만들어도 그것을 외부 클라이언트에서 init()을 실행시키는 것보다 생성자에서 바로 초기화를 해주는 것이 좋다고 생각을 했었습니다.
  상기 내용에 잘못된 내용이 있으면 채찍질 부탁드립니다!!

2023-10-04 06:38 UTC, cloudwi commented on src/main/java/common/InitApplication.java
> +        System.out.print("모드를 선택합니다. 1. 운용 모드 2. 테스트 모드" + System.lineSeparator() + "> ");
클래스로 따로 분리하는 정책이 더 좋아보이지만 

서비스에 적합한 방법을 찾아보실까요?

2023-10-04 06:38 UTC, cloudwi commented on src/main/java/entity/Book.java
> +    private static final List<String> FIELD_DISPLAY_NAMES = List.of("도서번호", "제목", "작가", "페이지 수", "상태");
가독성 관련해서 이야기 해보면 좋을것 같아요.

2023-10-04 06:39 UTC, cloudwi commented on src/main/java/entity/Book.java
> +    public void setBookState(BookState bookState) {
넵 단독으로 변경할 수 있는 매서드를 만드는 방법도 좋을것 같네요.

2023-10-04 06:39 UTC, cloudwi commented on src/main/java/common/InitApplication.java
> +        }catch (BookNumberAlreadyExistException e){
ㅋㅋㅋㅋ 죄송합니다...

다른 예외는 항상 발생할 수 있다고 생각하시는게 좋아요!

2023-10-05 07:05 UTC, ZZAMBAs commented on build.gradle
> +}
오.. 멘토님. 저도 지우니까 되었습니다. 멘토님이 봐주시니 고쳐졌네요

2023-10-05 07:42 UTC, ZZAMBAs commented on src/main/java/manage/file/CsvFileManager.java
> +        File file = new File(filePath);
상대 경로로 설정 후, 운용 모드로 읽을 때 파일이 없으면 생성해주도록 하였습니다.

2023-10-05 08:08 UTC, ZZAMBAs commented on src/main/java/manage/TotalManager.java
> +        String[] bookInfo = new String[3];
주영님. 이부분에 대해 bookInfo를 제거하고 변수를 3개 선언해서 각각 bookTitle, bookAuthor, bookPage로 받은 뒤, new Book(bookTitle, bookAuthor, bookPage)로 생성하는 건 어떻게 보시나요? 
아래처럼 바꿔 볼 예정입니다!
`
bookTitle = CONSOLE_INPUT.nextLine().trim();

        System.out.print("작가 이름을 입력해 주세요." + System.lineSeparator() + "> ");

        bookAuthor = CONSOLE_INPUT.nextLine().trim();

        System.out.print("페이지 수를 입력해 주세요.(숫자만 입력해 주세요!)" + System.lineSeparator() + "> ");

        bookPage = CONSOLE_INPUT.nextLine().trim();

        Book createdBook = new Book(bookTitle, bookAuthor, Integer.parseInt(bookPage));
        bookManager.register(createdBook);
`

2023-10-05 08:10 UTC, ZZAMBAs commented on src/main/java/common/InitApplication.java
> +        System.out.print("모드를 선택합니다. 1. 운용 모드 2. 테스트 모드" + System.lineSeparator() + "> ");
주영님. 만약 TotalManager에 있는 콘솔 입출력의 역할도 클래스로 나눠야 한다면 어떻게 해야 할지 힌트 부탁드려도 될까요?
현재 콘솔 입출력이 들어간 메서드들은 아래와 같은 구조를 띠고 있습니다.

```
콘솔 출력(입력)
기능 수행
콘솔 출력
기능 수행
...
```

이것을 클래스로 따로 분리를 하면 다음이 될 것으로 예상을 했습니다.

```
콘솔입출력클래스.메서드1()
기능수행
콘솔입출력클래스.메서드2()
기능수행
...
```

위 구조가 맞다면 콘솔 출력 내용이 다를 때마다 메서드들을 만들어주는 것이 맞을까요?

2023-10-05 08:28 UTC, ZZAMBAs commented on src/main/java/entity/Book.java
> +    public void setBookState(BookState bookState) {
해당 set 메서드들은 도서를 대여/반납/분실/삭제 처리 시에 사용하였습니다.  setter를 사용하지 않고 Book 객체 내부에 따로 메서드를 만들어서 그곳에서 상태 혹은 마지막 반납 시간을 바꿔주도록 하겠습니다!

2023-10-05 10:39 UTC, ZZAMBAs commented on src/main/java/entity/Book.java
> +    private static final List<String> FIELD_DISPLAY_NAMES = List.of("도서번호", "제목", "작가", "페이지 수", "상태");
이것도 enum을 써야 할 것 같아서 enum으로 분리해 보겠습니다

2023-10-05 12:11 UTC, ZZAMBAs commented on build.gradle
> +}
인텔리제이에서 실행 시에는 문제가 없는데 jar 파일을 직접 실행하려 하면 문제가 생깁니다. 
![image](https://github.com/prgrms-be-devcourse/java-library-management/assets/76583883/39321795-514d-444f-a30f-3e80a62f763d)

이 문제 때문에 추가해줬습니다. 다시 문제가 발생해서 위 문구를 다시 추가를 해주겠습니다!

2023-10-06 16:01 UTC, cloudwi commented on src/main/java/common/InitApplication.java
> +        System.out.print("모드를 선택합니다. 1. 운용 모드 2. 테스트 모드" + System.lineSeparator() + "> ");
출력을 담당하는 객체를 따로 두는 것을 의미해요.

따라서 기존의 

콘솔 출력(입력)
기능 수행
콘솔 출력
기능 수행

의 형태여도 문제가 없지만

콘솔 출력과 입력을 담당하는 객체를 따로 두어 유효성을 검증하고 예외를 처리한다면 책임을 분리 할 수 있지않을까 라는 생각 이었어요!

2023-10-07 09:29 UTC, aegis1920 commented on build.gradle
> +}
오.. 그렇군요. 저도 jar 파일을 직접 실행할 때는 main 클래스 지정이 필요한가봅니다. 저도 직접 jar 파일을 실행해보진 않아서 몰랐네요. 알려주셔서 감사합니다 🙇

2023-10-07 09:40 UTC, aegis1920 approved these changes
간단하게 코멘트 조금 더 남겼습니다~
반영해주셔도 되고 반영하지 않으셔도 됩니다!
고생 많으셨습니다~

2023-10-07 09:40 UTC, aegis1920 commented on src/main/java/common/Util.java
> +public class Util {
유틸 클래스의 경우, private 생성자로 생성을 막아둡니다. (어차피 모두 static만 들어가니까)

2023-10-07 09:40 UTC, aegis1920 commented on src/main/java/manage/TotalManager.java
> +            String[] fieldDisplayName = {
배열보다는 List를 사용해주세요!

2023-10-07 09:40 UTC, aegis1920 commented on src/main/java/domain/BookDisplayField.java
> +public enum BookDisplayField {
어차피 출력하는 부분에서만 쓰여서 따로 enum으로 뺄 필요가 있을까 싶네요. 도메인 패키지에 들어갈 내용도 아니라고 생각들기도 하고요.

2023-10-07 09:40 UTC, aegis1920 commented on src/test/java/manage/book/BookListManagerTest.java
> +public class BookListManagerTest {
반납하고 5분뒤에 대여가능하게 만드는 것도 테스트가 있었으면 좋았겠네요

2023-10-07 09:40 UTC, aegis1920 commented on src/main/java/domain/Book.java
> +    private long lastReturn;
LocalDateTime이면 좀 더 직관적이었을 것 같습니다

2023-10-07 09:40 UTC, aegis1920 commented on src/main/java/manage/book/BookManager.java
> +public interface BookManager {
어차피 하나의 매니저만 있는데 BookMananger 인터페이스가 있어야할까 싶네요?

2023-10-07 17:12 UTC, ZZAMBAs commented on src/main/java/common/InitApplication.java
> +        System.out.print("모드를 선택합니다. 1. 운용 모드 2. 테스트 모드" + System.lineSeparator() + "> ");
감사합니다! 이 부분.. 오늘 안에 고민하여 답을 내어보겠습니다!!

2023-10-07 17:14 UTC, ZZAMBAs commented on src/main/java/domain/BookDisplayField.java
> +public enum BookDisplayField {
이 부분에 대해서 다시 고민해 보겠습니다...

2023-10-07 17:16 UTC, ZZAMBAs commented on src/main/java/manage/book/BookManager.java
> +public interface BookManager {
추가적으로 남겨주셔서 감사합니다 멘토님! 지금까지의 피드백을 반영해서 개발 작업 할 때, 더 신경써보도록 하겠습니다~! 고생 많으셨어요!!!

2023-10-09 10:43 UTC, aegis1920 commented
끝까지 피드백 반영하시느라 고생 많으셨습니다! 👍 
과제는 여기서 머지하겠습니다! 이후에 궁금한 점이 있으시면 DM주시거나 코멘트 따로 남겨주세요!

2023-10-09 10:43 UTC, merged