[5기 - 조은비] 1~2주차 과제: 도서 관리 어플리케이션 제출합니다.
prgrms-be-devcourse/java-library-management pull request #19
Opened 2023-09-29 11:24 UTC by eunbc

안녕하세요 도찌님, 무송님! 도찌팀의 조은비입니다 :relaxed:
첫 과제를 두 분과 함께하게 되어 영광입니다ㅎㅎ
회사 후임이라고 생각하시고 따끔한 리뷰 부탁드려요~! 감사합니다 :raised_hands:

## 📌 과제 설명 

-   도서 관리 애플리케이션 구현하기
    - [x] 도서 등록
    - [x] 도서 전체 목록 조회
    - [x] 도서 제목 기준으로 도서를 검색
    - [x] 도서 대여
    - [x] 도서 반납
    - [x] 도서 분실 처리
    - [x] 도서 삭제 처리
- 도서 상태 관련 요구사항
    - [x] 도서가 '대여 가능' 상태일 때만 도서 대여 가능, 이외 상태일 경우 대여 불가 이유 출력
    - [x] 도서 반납시 '도서 정리중' 상태로 바뀌고, 이후 5분이 지나면 '대여 가능' 상태로 바뀜
    - [x] 도서 분실 처리 후 반납시 '도서 정리중' 상태로 바뀌고, 이후 5분이 지나면 '대여 가능' 상태로 바뀜
- 제약사항
    - [x] 테스트 모드, 일반 모드 구분하기
    - [x] 일반 모드일 경우 json 파일에 변경 사항 저장
- [x] 테스트 코드 작성

## 👩‍💻 요구 사항과 구현 내용 
![스크린샷 2023-09-29 오후 6 44 54](https://github.com/prgrms-be-devcourse/java-library-management/assets/69096886/1ae7a544-d277-4823-969d-4b9bd25e0122)

### - 패키지 구조 및 설명
```bash
├── java/com/programmers/libarary
│   ├── constants 
│   ├── controller
│   ├── dto
│   ├── entity
│   ├── enums
│   ├── exception
│   ├── io
│   ├── repository
│   ├── service
│   └── util
└── Application
``` 

- constants 
    - 프로젝트 전역에서 사용되는 static 변수를 관리
    - MessageConstants
- controller 
    - 클라이언트로부터 요청을 받는 레이어, 모드 & 메뉴 선택
    - ModeController, MenuController
- dto 
    - 계층 간 데이터 전송을 위해 도메인 모델 대신 사용되는 객체
    - BorrowBookRequestDto, FindBookRequestDto...
- entity 
    - 관리하고자 하는 데이터
    - Book
- enums 
    - 제한된 값 목록을 가지는 데이터
    - Mode, Menu
- exception 
    - 커스텀 예외 
    - BookNotFoundException, InvalidMenuException...
- io 
    - 클라이언트로부터 입력을 받고, 결과를 출력하는 관련 객체 
    - Input, Output...
- repository 
    - 데이터를 저장하고 불러오는 로직을 담당하는 객체 
    - FileRepository, MemoryRepository...
- service 
    - 비즈니스 작업 단위를 정의하고 도메인의 각 동작을 조율하는 역할 
- util 
    - 프로젝트 전역에서 사용되는 특정 로직이나 독립적인 기능을 구현 
    - FileUtils

### - 사용한 라이브러리
- jackson-databind, version : 2.15.2 (Java Object와 JSON 형식간의 변환을 위해 사용)
- jackson-datatype-jsr310, version : 2.15.2 (Java 8의 Date & Time data type을 지원하기 위한 Jackson의 추가 라이브러리)
- mockito-core, version: 5.3.1  (단위 테스트를 지원하기 위한 Mocking Framework로, Mock(가짜) 객체를 통해 테스트 코드 작성을 더 원활하게 해줌)

## ✅ PR 포인트 & 궁금한 점 

### - 노력한 점

- 각 객체의 역할과 책임을 최대한 분리하여 작성하려 노력했습니다.
- 가독성을 위하여 모드나 메뉴 선택의 경우, 숫자로 된 입력을 enum으로 변환하였습니다.
- 서비스 로직 시작 전후로 시스템 메시지를 출력하는 부분( ex. [System] 도서 등록 메뉴로 넘어갑니다.)에서, 함수형 인터페이스를 활용하여 중복 코드를 줄였습니다.
- 예외 발생시 어떤 내용인지 알 수 있도록 커스텀 예외 클래스를 생성하였습니다.
- 사용자의 잘못된 입력에 대비하여, 허용된 입력 값 외의 내용을 예외 처리하였습니다.
-  repository에서는 LinkedHashMap을 메모리 캐시로 활용하여, 개별 항목 조회시 O(1)의 시간 복잡도로 조회 가능합니다.

### - 아쉬운 점 & 궁금한 점

1. 현재 프로그램 종료 로직이 따로 없습니다. 사용자가 정상 종료할 수 있는 방법이 있어야 할까요? 
2. setter의 사용을 지양해야 한다고 알고 있는데, 프로그램 로직상 필요한 곳이 있어 사용하게 되었습니다. (book.setId()) 대체할 수 있는 방법이 있을까요?
3. private 메소드의 테스트 코드를 작성하는 팁이 있다면 궁금합니다! (Reflection API는 권장되지 않는다고 들었습니다)
4. 배열[] 형식의 File에서 데이터를 읽어올 때 List로 읽어온 후, repository에서 Map 형식으로 변환해주어 사용하고 있습니다. 처음부터 map 타입으로 읽어올 수 있다면 List -> map 으로 변환 과정이 필요없을 것 같아 아쉽습니다.
6. 반납 후 도서 정리중-> 5분 뒤 대여 가능 상태로 변경하는 로직이 service의 모든 메소드에 들어가 있습니다. 메소드마다 중복되기도 하고, 각 메소드와 관련없는 책임을 늘린 것 같아 아쉽습니다.

2023-09-30 11:39 UTC, moosongsong reviewed
은비님 과제하시느라 정말정말 고생하셨습니다😆 많이 고민하시고 구현하신게 느껴지네요~ 제가 이번 팀미팅에 불참할 것 같아 미리 코멘트 남겨둘게요! 

### # 궁금한 점에 대한 제 답변

> 현재 프로그램 종료 로직이 따로 없습니다. 사용자가 정상 종료할 수 있는 방법이 있어야 할까요?

종료 SIG가 오기 전까지 계속 동작하는 프로그램으로 보고, 굳이 정상 종료 처리를 구현할 필요는 없을 것 같아요!

> private 메소드의 테스트 코드를 작성하는 팁이 있다면 궁금합니다! (Reflection API는 권장되지 않는다고 들었습니다)

private 메서드는 해당 메서드를 호출하는 public&protected 메서드를 통해 간접 테스트를 진행합니다. 이때 정말 private 테스트가 필요한 상황이라면, 코드 설계가 잘못되었다고 판단하고 코드를 수정하는게 바람직하다고 보는데요. 아마 private 메서드를 테스트해야하는 필요성이 느껴진다는 건, 해당 메서드에 책임이 많아졌다는 뜻이겠죠?

2023-09-30 11:39 UTC, moosongsong commented on src/main/java/com/programmers/library/dto/AddBookRequestDto.java
> +			throw new IllegalArgumentException(INVALID_TITLE);
각 예외 상황에 따른 메시지 넘겨주는 것 좋아요! 👍   
cf) 로깅이나 상태에 따른 에러 메시지를 남겨줄때 예외의 메시지를 가져다 쓰기도 하는데요. 그때 상황에 따른 각각의 메시지가 유용하게 쓰인답니다

2023-09-30 11:39 UTC, moosongsong commented on src/main/java/com/programmers/library/entity/Book.java
> +	public void setId(Long id) {
> setter의 사용을 지양해야 한다고 알고 있는데, 프로그램 로직상 필요한 곳이 있어 사용하게 되었습니다. (book.setId()) 대체할 수 있는 방법이 있을까요?

보통 setter가 해당 값을 직접 변경하는 역할을 수행하죠? 결국 어느 곳이라도 변경 시도를 할 수 있는데, 솔직히 값 변경이 로직상 필요할 때 많거든요.   
이때 해당 필드 값을 변경하게 된 의도를 나타내면서, 잘못된 값이 들어가지 않도록 처리해주는 기능을 수행하는 메서드를 만들어 처리해주시면 됩니다.  
```java
// 대강 이런 느낌
public void updateUserName(String name) {
  if(StringUtils.isNotBlank(name) {
    this.name = name;
  }
  // 예외 처리 
}
```
음.. 여기서는 Id를 시퀀스대로 집어넣기 위해서 사용했는데, 아이디는 생성할 때 부여되도록 생성자에서 받아서 처리해주는게 좀 더 좋았을 것 같네요. PK값이 외부에서 변경이 가능한 건 리스크가 매우 크니까용ㅎㄷㄷ

2023-09-30 11:39 UTC, moosongsong commented on src/main/java/com/programmers/library/exception/BookNotFoundException.java
> +		super("존재하지 않는 도서번호 입니다.");
결국 책을 못 빌리는 상황에 대한 예외이고, 각각의 예외들이 수행하는 역할은 메시지만 다르게 들고 있는 걸로 보이는데, 너무 예외가 세분화 되어 있는 것 같지 않나요? 혹시 예외를 (많이)세분화해둔 이유가 있을까요??

2023-09-30 11:39 UTC, moosongsong commented on src/main/java/com/programmers/library/entity/BookStatus.java
> +	private String value;
외부에서 변경하지 않는 필드인 것 같은데 final로 지정하지 않은 이유가 있을까용??

2023-09-30 11:39 UTC, moosongsong commented on src/test/java/com/programmers/library/dto/AddBookRequestDtoTest.java
> +	void testValidRequest() {
제가 한국인이라서 그런가 `@DisplayName`으로 각 테스트에 대한 추가 설명이 있었으면 좋... 았을 수도.... 🥴

2023-09-30 11:39 UTC, moosongsong commented on src/test/java/com/programmers/library/service/LibraryManagerServiceImplTest.java
> +	private LibraryManagerServiceImpl service;
Q) 왜 Mocking을 해야할까요~?

2023-09-30 11:39 UTC, moosongsong commented on src/main/java/com/programmers/library/repository/MemoryRepository.java
> +	public MemoryRepository() {
레포지토리를 생성할 때마다 새로운 저장소가 만들어지는 걸로 보이는데요. 그러면 시퀀스가 같은 도서가 나올걸로 보이는데, 의도한 상황이 맞을까요?

2023-09-30 11:39 UTC, moosongsong commented on build.gradle
> +    implementation 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.15.2'
Q) jackson 말고 json 사용시, 고민했던 라이브러리가 있을까요??

2023-09-30 11:39 UTC, moosongsong commented on src/main/java/com/programmers/library/constants/MessageConstants.java
> +	private MessageConstants() {
private 생성자 good 👍

2023-09-30 11:39 UTC, moosongsong commented on src/main/java/com/programmers/library/dto/ReturnBookRequestDto.java
> +public class ReturnBookRequestDto {
이건 그냥 추가적인 썰. 저희팀에서는 Request와 Response 가 DTO의 의미를 이미 가지고 있다고 판단하고 간단하게 ~Response, ~Request 로 사용하고 있어요. 😆

2023-09-30 11:39 UTC, moosongsong commented on src/test/java/com/programmers/library/service/LibraryManagerServiceImplTest.java
> +		String bookId = "1";
given으로 사용되는 값들이 동일하고, 반복되는 걸로 보이는데요. 테스트를 위해 사용하는 데이터의 중복 작업을 줄일 수 있는 방법은 없을까요?

2023-09-30 11:39 UTC, moosongsong commented on src/test/resources/data.json
> +[]
이것도 추가적인 썰. 테스트용 파일은 파일을 잘 불러오는지 테스트를 하는 경우를 제외하고 직접 파일을 사용하지 않는데, 외부에 테스트코드가 의존하는 상황이라 해당 파일이 변경된다면 테스트 코드가 깨질 가능성 때문인데요.

파일 객체를 따로 만들어서 고립된 테스트를 구현하는 방법을 찾아보시는 것도 좋을 것 같아요~!

2023-10-02 00:55 UTC, eunbc commented on src/main/java/com/programmers/library/entity/Book.java
> +	public void setId(Long id) {
넵! 말씀해주신대로 아이디는 생성할 때 부여되도록 하는 것이 좀 더 좋은 방법인 것 같습니다! 👍

2023-10-02 01:00 UTC, eunbc commented on src/main/java/com/programmers/library/exception/BookNotFoundException.java
> +		super("존재하지 않는 도서번호 입니다.");
책의 상태와 관련된 오류를 추상화하여 BookException으로 묶고, 예외 메시지만 다르게 넣어주는 방법이 좋을 것 같습니다! 
각 상황에 맞는 케이스에 따라 exception을 추가하다 보니 지나치게 세분화된거 같아요

2023-10-02 01:01 UTC, eunbc commented on src/main/java/com/programmers/library/entity/BookStatus.java
> +	private String value;
빠뜨렸습니다.. (ㅠㅠ) 수정하겠습니다!!

2023-10-02 01:02 UTC, eunbc commented on src/test/java/com/programmers/library/dto/AddBookRequestDtoTest.java
> +	void testValidRequest() {
맞습니다 한눈에 설명이 들어오도록 추가하면 훨씬 좋을 것 같아요!! :) 수정하겠습니다

2023-10-02 01:06 UTC, eunbc commented on build.gradle
> +    implementation 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.15.2'
jackson 말고 gson이라는게 있다는걸 알고만 있었는데, 이 둘의 차이점은 잘 몰라서 한번 찾아보겠습니다!

2023-10-02 01:16 UTC, eunbc commented on src/test/java/com/programmers/library/service/LibraryManagerServiceImplTest.java
> +	private LibraryManagerServiceImpl service;
외부 의존성으로부터 독립된, 테스트하고자 하는 메서드의 순수한 동작을 검증하기 위해서 라고 생각합니다!
예를 들면, 서비스 클래스가 어떤 작업 후 사용자에게 문자 메시지를 보내는 경우, 테스트에서는 실제로 사용자에게 문자를 보내는 대신 mock으로 대체 후 서비스에서 수행하고자 하는 로직을 테스트해볼 수 있을 것 같습니다! :)

2023-10-02 01:26 UTC, eunbc commented on src/main/java/com/programmers/library/repository/MemoryRepository.java
> +	public MemoryRepository() {
요구사항에 따르면 테스트 모드일 경우 프로그램 종료시 모든 데이터가 사라져야 합니다 :)

1. 일반 모드로 실행시
FileRepository를 생성할 때 생성자 내부에서 File 데이터를 가져와 max 시퀀스 값을 확인 후 그 다음값으로 Id가 부여되도록 하는 로직이 있습니다
2. 테스트 모드로 실행시 
새로운 저장소를 만들고 시퀀스 값을 0으로 초기화해줍니다!

레포지토리 생성은 프로그램 시작시 사용자 입력(1.일반 모드-파일, 2.테스트 모드-메모리)에 따라 단 한번 생성이 되고, 프로그램이 종료될 때까지는 따로 레포지토리를 새로 생성하고 있지는 않습니다. 따라서 현재로서는 시퀀스가 같은 도서가 나올 일은 없을 거라 생각됩니다!

2023-10-02 01:27 UTC, eunbc commented on src/main/java/com/programmers/library/dto/AddBookRequestDto.java
> +			throw new IllegalArgumentException(INVALID_TITLE);
확인했습니다 감사합니다! :)

2023-10-02 01:28 UTC, eunbc commented on src/main/java/com/programmers/library/constants/MessageConstants.java
> +	private MessageConstants() {
확인했습니다 감사합니다! :)

2023-10-02 01:29 UTC, eunbc commented on src/main/java/com/programmers/library/dto/ReturnBookRequestDto.java
> +public class ReturnBookRequestDto {
오.. 맞아요 통용적인 의미를 가지는 이름은 그렇게 사용해도 좋을 것 같습니다!

2023-10-02 01:30 UTC, eunbc commented on src/test/java/com/programmers/library/service/LibraryManagerServiceImplTest.java
> +		String bookId = "1";
비슷한 데이터를 반복 생성하기보다는 자주 사용하는 변수를 테스트 클래스의 로컬 변수로 선언 후 @BeforeEach에서 초기화해서 사용하면 반복적인 작업이 줄어들 것 같습니다 :)

2023-10-02 01:32 UTC, eunbc commented on src/test/resources/data.json
> +[]
오호.. 넵 맞습니다 테스트에서 파일을 직접 사용하기 보다는, 파일 객체의 의존성을 mock으로 대체하여 순수한 데이터 로직을 테스트해볼 수 있을 것 같습니다!

2023-10-09 02:47 UTC, SangHyunGil requested changes
리뷰 반영해주시느라 너무 고생많으셨어요!
몇 가지 코멘트 남겼으니 확인 부탁드릴게요 😄

2023-10-09 02:47 UTC, SangHyunGil commented on src/main/java/com/programmers/library/util/IdGenerator.java
> +	private static final IdGenerator instance = new IdGenerator();
싱글톤 패턴 구현 간소화를 위해 인스턴스를 바로 생성해주셨군요.
위처럼 진행한다면 어떤 문제점이 있고 이를 해결하기 위한 방법은 어떤게 있을까요?

2023-10-09 02:47 UTC, SangHyunGil commented on src/main/java/com/programmers/library/entity/Book.java
>  	private LocalDateTime returnedAt;
returnedAt은 OrganizingState에 종속적인 값이에요.
이 값을 Book에서 OrganizingState로 옮겨보면 어떨까요?
- OrganizingState 객체에 필요한 정보를 직접 들고있으므로써 외부에 노출하지 않고 역할을 수행할 수 있어 응집도가 높아질 수 있을 것 같아요.
- Book과 State간의 결합도가 낮아질 것 같아요.
실제 OrganizingState에 organize라는 행위를 위임하고 있지만 returnedAt을 book이 들고있으므로써 서

2023-10-09 02:47 UTC, SangHyunGil commented on src/main/java/com/programmers/library/util/FileUtils.java
> +	public List<Book> readFile() {
클래스 쪽 변경이 이루어지지 않은 것 같아요.

2023-10-09 02:47 UTC, SangHyunGil commented on src/main/java/com/programmers/library/entity/state/State.java
> +	State organize(LocalDateTime returnedAt);
OrganizeState를 제외한 나머지 상태에서 현상태를 반환하는 이유가 있나요?

2023-10-09 02:47 UTC, SangHyunGil commented on src/main/java/com/programmers/library/entity/state/State.java
> +public interface State {
원래 Book에 존재하던 모든 상태에 대한 테스트를 각 State로 나누어 테스트 진행하면 테스트 작성하기도 쉽고 보기도 쉬워질 수 있을 것 같아요 👍

2023-10-09 04:42 UTC, eunbc commented on src/main/java/com/programmers/library/util/IdGenerator.java
> +	private static final IdGenerator instance = new IdGenerator();
위와 같은 Eager initialization 방식에서는 클래스 로드 시점에 싱글톤 객체를 초기화하기 때문에 실제로 사용되기 전에 리소스가 사용됩니다. 싱글톤 객체 생성 비용이 크거나, 싱글톤 객체가 전혀 사용되지 않을 경우 불필요한 리소스 낭비일 수 있습니다.

따라서 이 문제점을 해결하기 위해 Lazy initialization 방식을 적용할 수 있습니다!

2023-10-09 08:47 UTC, eunbc commented on src/main/java/com/programmers/library/entity/state/State.java
> +	State organize(LocalDateTime returnedAt);
원래 의도는 통일성을 주기 위해 반환 타입을 통일했었는데,
다른 메소드는 State를 반환할 필요없이 book 내부에서 new 로 생성해주는 편이 깔끔한 것 같습니다! 
아래와 같이 수정했습니다 :)

```

	public void borrow() {
		state.borrow();
		state = new BorrowedState();
	}

	public void returned() {
		state.returned();
		state = new OrganizingState(LocalDateTime.now());
	}

	public void lost() {
		state.lost();
		state = new LostState();
	}

	public void organize() {
		this.state = state.organize();
	}
```

2023-10-09 09:48 UTC, eunbc commented on src/main/java/com/programmers/library/util/IdGenerator.java
> +	private static final IdGenerator instance = new IdGenerator();
[커밋 바로가기](https://github.com/prgrms-be-devcourse/java-library-management/pull/19/commits/a13ea72adf262a9b8c9c00bc4ffd1c8a0210b53d)

```
public class IdGenerator {
	private static volatile IdGenerator instance;
	private final AtomicLong id = new AtomicLong(0L);

	private IdGenerator() {
	}

	public static IdGenerator getInstance() {
		if (instance == null) {
			synchronized (IdGenerator.class) {
				if (instance == null) {
					instance = new IdGenerator();
				}
			}
		}
		return instance;
	}

	public void initialize(Long initId) {
		id.set(initId);
	}

	public Long generateId() {
		return id.incrementAndGet();
	}
}

```

2023-10-09 09:54 UTC, eunbc commented on src/main/java/com/programmers/library/entity/Book.java
>  	private LocalDateTime returnedAt;
끝까지 자세히 설명해주셔서 감사합니다! 이제서야 완벽 이해 되었네요! 적용 완료했습니다 :)

[커밋 바로보기](https://github.com/prgrms-be-devcourse/java-library-management/pull/19/commits/927d0e7da813de85027a10c9a0a559c09b8656d5)

```
public class OrganizingState implements State {

	private LocalDateTime returnedAt;

	public OrganizingState(LocalDateTime returnedAt) {
		this.returnedAt = returnedAt;
	}

	public LocalDateTime getReturnedAt() {
		return returnedAt;
	}

	@Override
	public BookStateType getType() {
		return BookStateType.ORGANIZING;
	}

	@Override
	public void borrow() {
		throw new BookException(ErrorCode.BOOK_UNDER_ORGANIZING);
	}

	@Override
	public void returned() {
		throw new BookException(ErrorCode.BOOK_UNDER_ORGANIZING);
	}

	@Override
	public void lost() {
		// success
	}

	@Override
	public State organize() {
		if (returnedAt.plusMinutes(5).isBefore(LocalDateTime.now())) {
			return new AvailableState();
		} else {
			return this;
		}
	}
}
```

2023-10-09 09:59 UTC, eunbc commented on src/main/java/com/programmers/library/util/FileUtils.java
> +	public List<Book> readFile() {
파일 읽기 쓰기를 담당하는 FileUtils를 Book에 한정해서만 사용할 수 있도록 변경했습니다!
파일을 읽고 쓸때, 인터페이스값인 'State' 때문에 커스텀으로 직렬화, 역직렬화 로직을 구현하다보니 Book에만 적용할 수 있을 거 같아 이렇게 수정하였습니다.

[FileUtils 파일 보기](https://github.com/prgrms-be-devcourse/java-library-management/blob/3a2e86c954263f4b9ec2a9b2b238f9395552123a/src/main/java/com/programmers/library/util/FileUtils.java)

```
public class FileUtils {
	private final ObjectMapper objectMapper;
	private final String filePath;

	public FileUtils(String filePath) {
		this.filePath = filePath;
		objectMapper = new ObjectMapper().registerModule(new JavaTimeModule());
	}

	public List<Book> readFile() {
		if (!Files.exists(Paths.get(filePath))) {
			throw new BookException(ErrorCode.FILE_NOT_EXIST);
		}

		List<Book> list = new ArrayList<>();
		try {
			List<?> objectList = objectMapper.readValue(new File(filePath), List.class);
			for(Object obj : objectList) {
				String stringValue = objectMapper.writeValueAsString(obj);
				FileReadBookDto fileReadBookDto = objectMapper.readValue(stringValue, FileReadBookDto.class);
				list.add(fileReadBookDto.toEntity());
			}
		} catch (IOException e) {
			throw new BookException(ErrorCode.FILE_READ_FAILED);
		}
		return list;
	}

	public void writeFile(List<Book> list) {
		if (!Files.exists(Paths.get(filePath))) {
			throw new BookException(ErrorCode.FILE_NOT_EXIST);
		}

		try {
			List<FileWriteBookDto> fileWriteBookDtos = list.stream()
				.map(FileWriteBookDto::fromEntity)
				.collect(Collectors.toList());
			objectMapper.writeValue(new File(filePath), fileWriteBookDtos);
		} catch (IOException e) {
			throw new BookException(ErrorCode.FILE_WRITE_FAILED);
		}
	}
}
```

2023-10-09 10:02 UTC, eunbc commented on src/main/java/com/programmers/library/entity/state/State.java
> +public interface State {
각 State 별로 테스트 코드 작성 완료하였습니다! [커밋 바로가기](https://github.com/prgrms-be-devcourse/java-library-management/pull/19/commits/3a2e86c954263f4b9ec2a9b2b238f9395552123a)

2023-10-10 13:27 UTC, SangHyunGil commented on src/main/java/com/programmers/library/util/IdGenerator.java
> +	private static final IdGenerator instance = new IdGenerator();
좋습니다 👍 나중에는 Holder 방식에 대해서도 한 번 살펴봐주세요 ㅎㅎ

2023-10-10 13:28 UTC, SangHyunGil approved these changes
그간 과제 수행해주시느라 너무 고생많으셨습니다.
이번에 고민했던 부분들이 은비님에게 많은 도움이 되었으면 좋겠네요 👍 
머지해주셔도 좋습니다 ㅎㅎ

2023-10-10 14:32 UTC, merged