[5기 임수진] 1~2주차 과제 도서관리 어플리케이션 제출합니다.
prgrms-be-devcourse/java-library-management pull request #2
Opened 2023-09-26 15:26 UTC by suzzingv

## 📌 과제 설명 
도서를 관리할 수 있는 애플리케이션을 만들었습니다.

## 👩‍💻 요구 사항과 구현 내용 
-모드
일반 모드 / 테스트 모드
일반 모드: 외부 파일에 데이터를 저장하고 관리합니다.
테스트 모드: 리스트에 데이터를 저장하고 관리합니다.

-서비스
모드를 선택한 후 해당 모드에서 서비스를 실행합니다.
서비스에서는 기능을 선택하고 필요한 객체를 리포지토리에 넣어줬습니다.

-리포지토리
모드에 따라 일반 모드 리포지토리 / 테스트 모드 리포지토리를 서비스에 주입해줬습니다.
일반 모드의 경우 파일을 가져와서 리스트에 저장하고, 리스트를 통해 기능들을 관리해줬습니다.
변경사항이 있는 경우 리스트의 내용을 파일에 아예 새로 썼습니다. -> 이 부분은 성능 개선을 해볼 생각입니다.

테스트 모드의 경우 단순히 리스트에서만 관리해주었습니다.

-등록
Book 객체를 만들어 저장소에 넣어주었습니다.
기본적으로 상태는 "대여 가능"이어야 하므로 생성자에서 "대여 가능"으로 설정해주었습니다.
id는 중복되지 않는 객체의 hashCode를 사용해 부여해주었습니다.

-전체 목록 조회
리스트에 저장된 Book객체들을 조회해 출력해주었습니다.

-제목으로 도서 검색
키워드를 가지고 리스트에서 도서를 찾아 출력해주었습니다.
-> 없는 경우 존재하지 않는다는 메시지가 뜨도록 개선해볼 생각입니다.

-도서 대여
상태에 따라 메시지를 출력해주고, 대여 가능한 경우 Book의 상태를 대여중으로 바꾸어주었습니다.
id에 해당하는 도서가 없는 경우 존재하지 않는다는 메시지를 출력해주었습니다.

-도서 반납
상태에 따라 메시지를 출력해주었습니다.
반납 가능한 경우 Book의 상태를 도서 정리중으로 바꾸어주고, 스레드를 이용해 5분이 지나면 대여 가능으로 상태가 바뀌도록 구현했습니다.
id에 해당하는 도서가 없는 경우 존재하지 않는다는 메시지를 출력해주었습니다.

-도서 분실
상태에 따라 메시지를 출력해주었습니다.
분실 가능한 경우 Book의 상태를 "분실됨"으로 바꾸어주었습니다.

-도서 삭제
id를 가지고 도서를 찾아 삭제해주었습니다.
id에 해당하는 도서가 없는 경우 존재하지 않는다는 메시지를 출력해주었습니다.

## ✅ 피드백 반영사항   

## ✅ PR 포인트 & 궁금한 점  
늘어져있는 switch문 개선법이 궁금합니다. -> 저번에 보내주신 링크가 사라져서 확인을 못했습니다.
5분뒤 상태 변경 테스트코드를 짜는 법이 궁금합니다.
normalRepository 테스트 코드에서 테스트 후 기존 파일의 내용으로 롤백하고 싶은데 테스트 전 도서정리중이었던 도서의 상태를 어떻게 되돌려야할지 모르겠습니다. 프로그램이 시작할 때 도서정리중인 파일을 모두 대여가능한 상태로 바꾸도록 해놔서 도서정리중이었던 도서의 정보를 어떻게 잡아야할지 모르겠습니다.

2023-09-28 07:31 UTC, twotwobread reviewed
전체적으로 반복적인 review를 남기진 않았습니다. repository가 가진 역할과 책임이 많다고 생각하고 그렇기에 테스트 코드 작성이 전체적으로 더 복잡해지는 것 같습니다.
그리고 제가 남긴 review는 저의 생각이기 때문에 무조건적인 반영보다는 생각해보고 관련 정보를 서치해보면 좋을 것 같습니다. 이해가 되지 않는 부분은 같이 얘기해보면 좋을 것 같아요!!

2023-09-28 07:31 UTC, twotwobread commented on app/src/main/java/repository/NormalRepository.java
> +    File file = new File("C:/데브코스/java-library-management/app/src/main/resources/도서.csv");
해당 프로젝트를 실행 시킬 때 path가 잘못되면 error가 발생합니다. 
프로젝트를 실행시키는 환경이 달라질 수 있기에 절대 경로보다는 상대 경로를 이용하는 것이 더 좋을 것 같고 파일명도 최대한 영어를 사용하는 것이 더 좋아보입니다. (resource 경로를 쉽게 읽어올 수 있는 방법이 있는지 찾아보면 좋을 것 같아요)

2023-09-28 07:31 UTC, twotwobread commented on app/src/main/java/Main.java
> +        if(num.equals("1")) {
ModeType enum class를 이용하면 더 가독성이 좋을 것 같습니다.

2023-09-28 07:31 UTC, twotwobread commented on app/src/main/java/repository/Repository.java
> +        System.out.println("\n도서번호 : " + String.valueOf(book.getId())
객체의 toString을 이용하는 것이 더 깔끔할 것 같습니다. 그러면 필요없는 getter도 삭제할 수 있을 것 같아요.

2023-09-28 07:31 UTC, twotwobread commented on app/src/main/java/repository/NormalRepository.java
> +    public void printList() {
repository라는 naming을 했다는 것 자체가 데이터에 대한 접근하는 역할을 가진 객체라고 생각이 되는데 출력까지 하는 것은 하나의 역할만을 가졌다고 생각되지 않습니다. 그래서 하나의 객체가 하나의 책임만을 가지도록 구성하려면 출력을 다른 객체에서 처리하는 것이 좋다고 생각됩니다.

2023-09-28 07:31 UTC, twotwobread commented on app/src/main/java/repository/NormalRepository.java
> +public class NormalRepository implements Repository {
naming이 normal이라는 naming보다는 file과 memory 이런 식으로 직관적으로 이해할 수 있으면 좋을 것 같습니다.

2023-09-28 07:31 UTC, twotwobread commented on app/src/main/java/repository/NormalRepository.java
> +    private void fileToList(List<Book> books, File file) throws IOException {
Foo 리더님의 강의에 따르면 IOException이라는 checked exception throws하게 되면 상위 계층에서 이를 인지하고 있어야 하기에 캡슐화가 깨지는 문제가 있습니다. checked exception을 외부로 던지지 말고 repository에서 잡아서 unchecked exception을 던지는 것이 좋다고 생각합니다.

2023-09-28 07:31 UTC, twotwobread commented on app/src/main/java/service/Service.java
> +        book.setTitle(bf.readLine());
setter가 꼭 필요한 상황이 아니라고 생각하는데 생성자를 활용해보는 것이 더 좋지 않을까요?

2023-09-28 07:31 UTC, twotwobread commented on app/src/main/java/service/Service.java
> +        String titleWord = bf.readLine();
서비스는 애플리케이션의 중요 로직이나 부가 로직들이 수행되는 책임을 가지고 입력의 책임은 분리되는 것이 좋지 않을까 생각합니다.

2023-09-28 07:31 UTC, twotwobread commented on app/src/main/java/thread/NormalChangeStateThread.java
> +            throw new RuntimeException(e);
더 세부적인 Exception을 사용하던지 custom으로 더 적합한 exception을 만드는 것이 좋을 것 같습니다. Runtime은 너무 넓은 범위의 exception이라 생각합니다.

2023-09-28 07:31 UTC, twotwobread commented on app/src/main/java/repository/NormalRepository.java
> +                throw new RuntimeException(e);
더 세부적인 exception을 사용하는 것이 좋을 것 같습니다.
https://medium.com/@rafacdelnero/11-mistakes-java-developers-make-when-using-exceptions-af481a153397

2023-09-28 07:31 UTC, twotwobread commented on app/src/main/java/repository/Book.java
> +    int id;
상태들을 전부 private으로 접근 지정자를 명시하면 좋을 것 같습니다.

2023-09-28 07:31 UTC, twotwobread commented on app/src/test/java/repository/NormalRepositoryTest.java
> +        tmp += "[System] 도서가 대여 처리 되었습니다.\r\n";
대여 가능한 상황과 대여 불가능한 exception이 발생하는 상황은 테스트 코드 작성 시에 분리해서 작성해야 한다고 생각합니다. 테스트 코드에서 하나의 function에서는 하나만을 검증하는 것이 명확하고 테스트 코드가 커지지 않습니다. 테스트 코드를 읽으면 기능에 대한 이해가 갈 수 있어야 하는데 테스트 코드를 읽기가 많이 힘듭니다.
그리고 같은 상황에서 다른 값에 대한 테스트를 수행하고 싶은 경우엔 parameterized test 어노테이션을 찾아보면 좋을 것 같습니다.

2023-09-28 07:37 UTC, suzzingv commented
연휴에 빠른 리뷰 감사드립니다! 찬찬히 읽어보며 수정해보도록 하겠습니다!

네이버 메일앱에서 보냈습니다.
-----Original Message-----
보낸사람: "Lee ***@***.***>
받는사람: ***@***.***>
참조: ***@***.***>, ***@***.***>
날짜: 2023. 9. 28 16:32:09
제목: Re: [prgrms-be-devcourse/java-library-management] [5기 임수진] 1~2주차 과제 도서관리 어플리케이션 제출합니다. (PR #2)

@twotwobread commented on this pull request.
전체적으로 반복적인 review를 남기진 않았습니다. repository가 가진 역할과 책임이 많다고 생각하고 그렇기에 테스트 코드 작성이 전체적으로 더 복잡해지는 것 같습니다.
그리고 제가 남긴 review는 저의 생각이기 때문에 무조건적인 반영보다는 생각해보고 관련 정보를 서치해보면 좋을 것 같습니다. 이해가 되지 않는 부분은 같이 얘기해보면 좋을 것 같아요!!
In app/src/main/java/repository/NormalRepository.java:
> @@ -0,0 +1,157 @@+package repository;++import thread.NormalChangeStateThread;++import java.io.*;+import java.util.ArrayList;+import java.util.List;++import static repository.Book.countId;++public class NormalRepository implements Repository {+ File file = new File("C:/데브코스/java-library-management/app/src/main/resources/도서.csv");
해당 프로젝트를 실행 시킬 때 path가 잘못되면 error가 발생합니다.
프로젝트를 실행시키는 환경이 달라질 수 있기에 절대 경로보다는 상대 경로를 이용하는 것이 더 좋을 것 같고 파일명도 최대한 영어를 사용하는 것이 더 좋아보입니다. (resource 경로를 쉽게 읽어올 수 있는 방법이 있는지 찾아보면 좋을 것 같아요)
In app/src/main/java/Main.java:
> ++import java.io.*;++public class Main {+ public static void main(String[] args) throws IOException {+ Mode mode = selectMode();+ while(true) mode.run();+ }++ public static Mode selectMode() throws IOException {+ BufferedReader bf = new BufferedReader(new InputStreamReader(System.in));+ System.out.println("Q. 모드를 선택해주세요.\r\n" ++ "1. 일반 모드\r\n" ++ "2. 테스트 모드\r\n");+ String num = bf.readLine();+ if(num.equals("1")) {
ModeType enum class를 이용하면 더 가독성이 좋을 것 같습니다.
In app/src/main/java/repository/Repository.java:
> ++public interface Repository {++ public void register(Book book) throws IOException;++ public void printList();+ public void search(String titleWord);++ public void rental(int id) throws IOException;++ public void returnBook(int id) throws IOException;+ public void lostBook(int id) throws IOException;+ public void deleteBook(int id) throws IOException;++ default public void printBookInfo(Book book) {+ System.out.println("\n도서번호 : " + String.valueOf(book.getId())
객체의 toString을 이용하는 것이 더 깔끔할 것 같습니다. 그러면 필요없는 getter도 삭제할 수 있을 것 같아요.
In app/src/main/java/repository/NormalRepository.java:
> ++ public NormalRepository() throws IOException {+ fileToList(books, file);+ countId = books.get(books.size() - 1).getId() + 1;+ organizeState(books);+ updateFile(books, file);+ }++ @Override+ public void register(Book book) throws IOException {+ books.add(book);+ updateFile(books, file);+ }++ @Override+ public void printList() {
repository라는 naming을 했다는 것 자체가 데이터에 대한 접근하는 역할을 가진 객체라고 생각이 되는데 출력까지 하는 것은 하나의 역할만을 가졌다고 생각되지 않습니다. 그래서 하나의 객체가 하나의 책임만을 가지도록 구성하려면 출력을 다른 객체에서 처리하는 것이 좋다고 생각됩니다.
In app/src/main/java/repository/NormalRepository.java:
> @@ -0,0 +1,157 @@+package repository;++import thread.NormalChangeStateThread;++import java.io.*;+import java.util.ArrayList;+import java.util.List;++import static repository.Book.countId;++public class NormalRepository implements Repository {
naming이 normal이라는 naming보다는 file과 memory 이런 식으로 직관적으로 이해할 수 있으면 좋을 것 같습니다.
In app/src/main/java/repository/NormalRepository.java:
> + }++ public static void updateFile(List<Book> books, File file) throws IOException {+ BufferedWriter bw = new BufferedWriter(new FileWriter(file));+ books.forEach(book -> {+ try {+ bw.write(String.valueOf(book.getId()) + "," + book.getTitle() + ","+ + book.getWriter() + "," + String.valueOf(book.getPage()) + "," + book.getState() + "\n");+ } catch (IOException e) {+ throw new RuntimeException(e);+ }+ });+ bw.close();+ }++ private void fileToList(List<Book> books, File file) throws IOException {
Foo 리더님의 강의에 따르면 IOException이라는 checked exception throws하게 되면 상위 계층에서 이를 인지하고 있어야 하기에 캡슐화가 깨지는 문제가 있습니다. checked exception을 외부로 던지지 말고 repository에서 잡아서 unchecked exception을 던지는 것이 좋다고 생각합니다.
In app/src/main/java/service/Service.java:
> +import repository.Repository;++import java.io.*;++public class Service {+ private static Repository repository;+ BufferedReader bf = new BufferedReader(new InputStreamReader(System.in));++ public Service(Repository repository) {+ this.repository = repository;+ }++ public void register() throws IOException {+ Book book = new Book();+ System.out.println("Q. 등록할 도서 제목을 입력하세요.");+ book.setTitle(bf.readLine());
setter가 꼭 필요한 상황이 아니라고 생각하는데 생성자를 활용해보는 것이 더 좋지 않을까요?
In app/src/main/java/service/Service.java:
> + System.out.println("Q. 페이지 수를 입력하세요.");+ book.setPage(Integer.parseInt(bf.readLine()));++ repository.register(book);+ System.out.println("[System] 도서 등록이 완료되었습니다.");+ }++ public void list() {+ System.out.println("[System] 전체 도서 목록입니다.");+ repository.printList();+ System.out.println("[System] 도서 목록 끝");+ }++ public void search() throws IOException {+ System.out.println("Q. 검색할 도서 제목 일부를 입력하세요.");+ String titleWord = bf.readLine();
서비스는 애플리케이션의 중요 로직이나 부가 로직들이 수행되는 책임을 가지고 입력의 책임은 분리되는 것이 좋지 않을까 생각합니다.
In app/src/main/java/thread/NormalChangeStateThread.java:
> + private Book book;+ private File file;+ private List<Book> books;+ public NormalChangeStateThread(Book book, File file, List<Book> books) {+ this.book = book;+ this.file = file;+ this.books = books;+ }+ @Override+ public void run() {+ try {+ Thread.sleep(300000);+ book.setState("대여 가능");+ updateFile(books, file);+ } catch (InterruptedException | IOException e) {+ throw new RuntimeException(e);
더 세부적인 Exception을 사용하던지 custom으로 더 적합한 exception을 만드는 것이 좋을 것 같습니다. Runtime은 너무 넓은 범위의 exception이라 생각합니다.
In app/src/main/java/repository/NormalRepository.java:
> + return;+ } else {+ books.remove(selectedBook);+ updateFile(books, file);+ System.out.println("[System] 도서가 삭제 처리 되었습니다.");+ }+ }++ public static void updateFile(List<Book> books, File file) throws IOException {+ BufferedWriter bw = new BufferedWriter(new FileWriter(file));+ books.forEach(book -> {+ try {+ bw.write(String.valueOf(book.getId()) + "," + book.getTitle() + ","+ + book.getWriter() + "," + String.valueOf(book.getPage()) + "," + book.getState() + "\n");+ } catch (IOException e) {+ throw new RuntimeException(e);
더 세부적인 exception을 사용하는 것이 좋을 것 같습니다.
***@***.***/11-mistakes-java-developers-make-when-using-exceptions-af481a153397
In app/src/main/java/repository/Book.java:
> @@ -0,0 +1,55 @@+package repository;++public class Book {+ static int countId;+ int id;
상태들을 전부 private으로 접근 지정자를 명시하면 좋을 것 같습니다.
In app/src/test/java/repository/NormalRepositoryTest.java:
> + tmp.append("\n도서번호 : ").append(String.valueOf(book.getId())).append("\n제목 : ").append(book.getTitle()).append("\n작가 이름 : ").append(book.getWriter()).append("\n페이지 수: ").append(String.valueOf(book.getPage())).append("페이지").append("\n상태 : ").append(book.getState()).append("\n\n------------------------------\r\n");+ }+ Assertions.assertEquals(tmp.toString(), outputMessage.toString());+ }++ @Test+ void rental() throws IOException {+ String tmp = "";+ repository.rental(32434); //없는 번호+ tmp += "[System] 존재하지 않는 도서 번호입니다.\r\n";+ + repository.rental(713338630); //대여중+ tmp += "[System] 이미 대여중인 도서입니다.\r\n";++ repository.rental(1); //대여 가능+ tmp += "[System] 도서가 대여 처리 되었습니다.\r\n";
대여 가능한 상황과 대여 불가능한 exception이 발생하는 상황은 테스트 코드 작성 시에 분리해서 작성해야 한다고 생각합니다. 테스트 코드에서 하나의 function에서는 하나만을 검증하는 것이 명확하고 테스트 코드가 커지지 않습니다. 테스트 코드를 읽으면 기능에 대한 이해가 갈 수 있어야 하는데 테스트 코드를 읽기가 많이 힘듭니다.
그리고 같은 상황에서 다른 값에 대한 테스트를 수행하고 싶은 경우엔 parameterized test 어노테이션을 찾아보면 좋을 것 같습니다.
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2023-09-28 12:16 UTC, twotwobread commented
1. 늘어져있는 switch문 개선법이 궁금합니다. -> 저번에 보내주신 링크가 사라져서 확인을 못했습니다.
```
강의에서도 나왔던 것처럼 enum을 이용해서 전략 패턴을 구성해도 좋을 것 같고 baeldung에서 찾아본 링크입니다.  
```
https://www.baeldung.com/java-replace-if-statements

2. 5분뒤 상태 변경 테스트코드를 짜는 법이 궁금합니다.
```
수진님께서 짠 코드에서는 해당 시간을 기다리는 테스트 코드를 짤 수 밖에 없을 것 같습니다.  
프록시 패턴 형태로 스케줄링과 관련된 로직과 실제 동작하는 task의 로직을 분리한다면 실제 동작 task만을 테스트할 수 있을 것 같습니다.
```
3. normalRepository 테스트 코드에서 테스트 후 기존 파일의 내용으로 롤백하고 싶은데 테스트 전 도서정리중이었던 도서의 상태를 어떻게 되돌려야할지 모르겠습니다. 프로그램이 시작할 때 도서정리중인 파일을 모두 대여가능한 상태로 바꾸도록 해놔서 도서정리중이었던 도서의 정보를 어떻게 잡아야할지 모르겠습니다.
```
기존 파일의 내용으로 롤백하는 것이 아니라 테스트와 운영 환경을 다르게 가져가면 롤백할 필요가 없을 것 같습니다.  
테스트에 사용하는 csv 파일과 운영에서 사용하는 csv를 분리하면 좋을 것 같습니다.
```

2023-09-29 01:34 UTC, suzzingv commented
감사합니다!!! 궁금했는데 해결됐습니다!

네이버 메일앱에서 보냈습니다.
-----Original Message-----
보낸사람: "Lee ***@***.***>
받는사람: ***@***.***>
참조: ***@***.***>, ***@***.***>
날짜: 2023. 9. 28 21:16:46
제목: Re: [prgrms-be-devcourse/java-library-management] [5기 임수진] 1~2주차 과제 도서관리 어플리케이션 제출합니다. (PR #2)


늘어져있는 switch문 개선법이 궁금합니다. -> 저번에 보내주신 링크가 사라져서 확인을 못했습니다.

강의에서도 나왔던 것처럼 enum을 이용해서 전략 패턴을 구성해도 좋을 것 같고 baeldung에서 찾아본 링크입니다.
https://www.baeldung.com/java-replace-if-statements

5분뒤 상태 변경 테스트코드를 짜는 법이 궁금합니다.

수진님께서 짠 코드에서는 해당 시간을 기다리는 테스트 코드를 짤 수 밖에 없을 것 같습니다. 프록시 패턴 형태로 스케줄링과 관련된 로직과 실제 동작하는 task의 로직을 분리한다면 실제 동작 task만을 테스트할 수 있을 것 같습니다.
normalRepository 테스트 코드에서 테스트 후 기존 파일의 내용으로 롤백하고 싶은데 테스트 전 도서정리중이었던 도서의 상태를 어떻게 되돌려야할지 모르겠습니다. 프로그램이 시작할 때 도서정리중인 파일을 모두 대여가능한 상태로 바꾸도록 해놔서 도서정리중이었던 도서의 정보를 어떻게 잡아야할지 모르겠습니다.

기존 파일의 내용으로 롤백하는 것이 아니라 테스트와 운영 환경을 다르게 가져가면 롤백할 필요가 없을 것 같습니다. 테스트에 사용하는 csv 파일과 운영에서 사용하는 csv를 분리하면 좋을 것 같습니다.
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2023-09-29 06:24 UTC, ksy90101 requested changes
현재 파일이 너무 많아서 리뷰하기가 어렵습니다.
필요한 파일이 무엇인지 한번 생각해보면 좋을거 같습니다

.idea폴더는 무엇일까요?
.gradle폴더는 무엇일까요?
build폴더는 무엇일까요?
out폴더는 무엇일까요?

총 4가지 폴더는 무엇인지 고민해보시고, gitignore를 해서 필요한 파일만 처리한 뒤에 리뷰진행하겠습니다.

마지막으로 app폴더가 있어야 하는 이유를 고민해보세요.

제가 말하는것이 이해가 잘 안된다면 슬랙으로 DM주세요.

2023-09-30 06:59 UTC, ksy90101 requested changes
리뷰를 너무 한번에 많이 남기면 힘들까봐. 중간에 끊었어요.

두가지를 한번 생각해보면 좋겠어요.

1. BufferedReader와 같은 객체를 굳이 재사용할 이유가 없을까?
2. View코드는 하나의 역할이고 예를들어 이 애플리케이션을 웹으로 바꿔야 할때 현재 구조는 바꾸기가 쉬운가?
3. Model의 역할은 무엇일까?

어려운게 있다면 언제든 슬랙 DM주세요!

2023-09-30 06:59 UTC, ksy90101 commented on build.gradle
> +    id 'java'
https://dlee0129.tistory.com/265
https://docs.gradle.org/current/userguide/toolchains.html#sec:consuming
sourceCompatibility & targetCompatibility
toolchain - languageVersion
이거에 대해서도 공부해두면 좋을거 같습니다~

이걸 통해 javaversion을 명시하면 어떨까요?

2023-09-30 06:59 UTC, ksy90101 commented on build.gradle
> +}
https://blog.coderifleman.com/2015/04/04/text-files-end-with-a-newline/

이글을 한번 참고해보면 어떨까요?

2023-09-30 06:59 UTC, ksy90101 commented on src/main/java/Main.java
> +        while(true) mode.run();
while(true)를 하면 무한루프에 빠질거 같아요.

2023-09-30 06:59 UTC, ksy90101 commented on src/main/java/Main.java
> +        System.out.println(SelectMessage.MODE_SELECT_MESSAGE.getMessage());
view코드는 분리하면 어떨까요?

2023-09-30 06:59 UTC, ksy90101 commented on src/main/java/Main.java
> +        BufferedReader bf = new BufferedReader(new InputStreamReader(System.in));
Scanner대신 BufferedReader를 사용해보면 어떨까요?

2023-09-30 06:59 UTC, ksy90101 commented on src/main/java/Main.java
> +        } else {
1,else에 대해서 코드만 보고선 이해가기가 어렵습니다.
1과 같은 매직넘버가 아닌 상수를 사용하면 어덜까요?

2023-09-30 06:59 UTC, ksy90101 commented on src/main/java/domain/BookState.java
> +    private static final Map<String, BookState> BY_STRING =
1. 스트림은 한줄에 한개씩 쓰는게 좋습니다.
2. e라는 변수는 무엇인가요? 저처럼 처음 보는 사람은 e가 무엇인지 알기가 어렵습니다.

2023-09-30 06:59 UTC, ksy90101 commented on src/main/java/domain/BookState.java
> +    BookState(String state) {
상수, 변수, 생성자는 개행으로 분리해둔다면 가독성이 훨씬 올라갑니다.

2023-09-30 06:59 UTC, ksy90101 commented on src/main/java/message/SelectMessage.java
> +    MODE_SELECT_MESSAGE("Q. 모드를 선택해주세요.\r\n" +
Java17에 있는 텍스트 블록 기능을 쓰면 어떨까요?
\n이라는 키워드보단 system.lineseparator()을 쓰면 어떨까요?

2023-09-30 06:59 UTC, ksy90101 commented on src/main/java/repository/Book.java
> +    static int countId;
countId가 book의 상태일까요?

2023-09-30 06:59 UTC, ksy90101 commented on src/main/java/repository/Book.java
> +    BookState state;
default 접근제어자로 지정한 이유가 있나요?

2023-09-30 06:59 UTC, ksy90101 commented on src/main/java/repository/Book.java
> +    }
setter가 필요한 이유가 있을까요?

2023-09-30 06:59 UTC, ksy90101 commented on src/main/java/repository/NormalRepository.java
> +    List<Book> books = new ArrayList<>();
default 접근제어자를 쓸 이유가 있나요?

2023-09-30 06:59 UTC, ksy90101 commented on src/main/java/repository/NormalRepository.java
> +    List<Book> books = new ArrayList<>();
Map이 아닌 List를 선택한 이유가 있나요?

2023-09-30 06:59 UTC, ksy90101 commented on src/main/java/repository/NormalRepository.java
> +                .findAny()
findAny와 findFirst의 차이를 찾아보면 어떨까요?

2023-09-30 06:59 UTC, ksy90101 commented on src/main/java/repository/NormalRepository.java
> +        Book selectedBook = books.stream().filter(book -> book.getId() == id)
book에게 같은 id야? 라고 메시지를 보내서 객체 자체가 답변을 하게 만들면 어떨까요?

2023-09-30 06:59 UTC, ksy90101 commented on src/main/java/repository/NormalRepository.java
> +                .orElse(null);
optional이 왜 있을까요? null을 리턴하기보단 optional의 메서드로 처리하면 어떨까요?

2023-09-30 06:59 UTC, ksy90101 commented on src/main/java/repository/NormalRepository.java
> +            case RENTING -> System.out.println(ExecuteMessage.RENTAL_RENTING.getMessage());
Repository의 역할이 무엇일까요?
View의 코드는 View에 모여잇는게 좋습니다.

전체적인 플로우를 고민해보세요.

2023-09-30 06:59 UTC, ksy90101 commented on src/main/java/repository/Repository.java
> +public interface Repository {
👍

2023-09-30 06:59 UTC, ksy90101 commented on src/main/java/service/Mode.java
> +        switch (num) {
여기도 num이 뭘 의미하는지 맨처음 보는 저는 의미를 알수가 없습니다.
enum을 통해서 한번 처리하면 어떨까요?

2023-09-30 06:59 UTC, ksy90101 commented on src/main/java/service/Service.java
> +    BufferedReader bf = new BufferedReader(new InputStreamReader(System.in));
매번 BufferedReader를 만드는거 같은데 굳이 매번 BufferedReader 객체를 만들 의미가 있을까요?

2023-09-30 07:07 UTC, suzzingv commented
빠른 리뷰 감사합니다! 찬찬히 수정해보겠습니다!
Message ID: ***@***.***>

2023-10-05 10:19 UTC, suzzingv commented on src/main/java/repository/Book.java
> +    static int countId;
고유한 id를 부여해주기 위해 만든 변수입니다. 일반 모드를 실행했을 때 파일에 존재하는 id 다음 수부터 id를 부여하기 위해 만들었습니다.

2023-10-05 10:22 UTC, suzzingv commented on src/main/java/repository/NormalRepository.java
> +    List<Book> books = new ArrayList<>();
문제에서 테스트모드를 List로 관리하라고 명시되어 있어서 일관성을 유지하기 위해 List를 사용했습니다. Map을 이용하면 검색 성능이 좋아질 것 같습니다.

2023-10-08 11:59 UTC, ksy90101 requested changes
마지막 리뷰가 될거 같네요.

마지막까지 파이팅입니다!

2023-10-08 11:59 UTC, ksy90101 commented on src/main/java/domain/Book.java
> +import domain.BookState;
<img width="406" alt="image" src="https://github.com/prgrms-be-devcourse/java-library-management/assets/53366407/890e400c-42d5-4581-af3c-2adb226821bd">
IDE를 도움받아, import가 필요 없는 것들을 없애보면 어떨까요?

2023-10-08 11:59 UTC, ksy90101 commented on src/main/java/domain/Book.java
> +                + System.lineSeparator() + "페이지 수: " + String.valueOf(page) + "페이지"
String.valueOf()를 쓰신 이유가 무엇인가요?

2023-10-08 11:59 UTC, ksy90101 commented on src/main/java/thread/FileChangeStateThread.java
> +    public FileChangeStateThread(Book book, int time) {
time의 인자가 안쓰이는거 같아요.

2023-10-08 11:59 UTC, ksy90101 commented on src/main/java/thread/FileChangeStateThread.java
> +        } catch (InterruptedException e) {
http://happinessoncode.com/2017/10/09/java-thread-interrupt/
해당글을 한번 읽어보시면 어떨까요?

2023-10-08 11:59 UTC, ksy90101 commented on src/main/java/exception/FileReadException.java
> +    public FileReadException() {
기본 생성자가 필요 할까요? 디폴트가 기본생성자라, 굳이 다른 로직이 없다면 코드를 제거해도 될거 같습니다 :)

2023-10-08 11:59 UTC, ksy90101 commented on src/main/java/thread/MemoryChangeStateThread.java
> +            throw new RuntimeException(e);
RuntimeExcpetion은 상위레벨의 예외이기 떄문에 예외 클래스만 보면 어떤 예외인지 로깅하기가 어렵습니다.
의미잇는 예외를 사용하시면 어떨까요?

2023-10-08 11:59 UTC, ksy90101 commented on src/main/java/repository/MemoryRepository.java
> +    public void setThreadForTest() {
해당 메서드가 있는 이유가 무엇인가요?

2023-10-08 11:59 UTC, ksy90101 commented on src/main/java/service/Service.java
> +    private static Repository repository;
repository가 static이여야 하는 이유가 있나요?

2023-10-08 11:59 UTC, ksy90101 commented on src/test/java/repository/FileRepositoryTest.java
> +        Thread.sleep(5000);
더 낮추면 어떨까요?
굳이 5초까지 기다려야 할지 의문이여서요.
전 1초내외도 충분하다고 생각합니다.

시간보단, 이전에 이야기 했지만 저 중요하게 체크해야 하는 테스트 케이스를 고민해보시면 좋을거 같습니다.

2023-10-08 11:59 UTC, ksy90101 commented on src/main/java/Main.java
> +            if(selectNum == 1 || selectNum == 2) mode = SelectMode.valueOfSelectNum(selectNum).run();
1과 2가 무엇을 의미하는지 상수를 사용하면 어떨까요?

2023-10-08 11:59 UTC, ksy90101 commented on src/main/java/Main.java
> +            else throw new NotAppropriateScope();
예외 클래스를 의미하기 위해 뒤에 Exception이라고 적는게 컨벤션입니다.

지금 이 한줄만 볼때 어떤 인스턴스를 만드는지 알수가 없어요 ㅠㅠ

2023-10-08 11:59 UTC, ksy90101 commented on src/main/java/domain/Book.java
> +        return String.valueOf(id) + "," + title + ","
String의 연산은 비싼거 아시나요?
String은 불변이기 때문에 매번 +를 할때마다 새롭게 생성하기 때문에 비싼 연산입니다
그런경우 StringBuffer, StringBuilder를 이용해 해결하곤 하는데요 한번 두개의 키워드를 찾아보시면 어떨까요?

2023-10-08 11:59 UTC, ksy90101 commented on src/main/java/domain/Reader.java
> +    public static Scanner sc = new Scanner(System.in);
sc는 final이여도 될거 같은데요?
아울러 public은 위험합니다. 각 쓰이는 곳에 있는게 좋습니다.
이런 경우 view에 있는게 더 어울릴거 같아요.

2023-10-08 11:59 UTC, ksy90101 commented on src/main/java/repository/FileRepository.java
> +        else countId = books.get(books.size() - 1).getId() + 1;
book을 보니 거기서 ID를 지정하는게 있던데, 여기서 또 countId라는게 필요한 이유가 무엇인지 잘 모르겠어요.

2023-10-08 11:59 UTC, ksy90101 commented on src/main/java/repository/FileRepository.java
> +            if(book.getTitle().contains(titleWord)) {
이런 경우 디미터의 법칙을 위반했다고 하는데요. 
한개의 로직을 위해 두개의 점을 사용할때 객체지향을 위반한것인데요.
book에게 메시지를 보내는 방식으로 하면 getTitle을 사용하지 않아도 되지 않을까요?

2023-10-08 11:59 UTC, ksy90101 commented on src/main/java/repository/FileRepository.java
> +        books.forEach(book -> {
filter을 써서, 한번에 찾고, 그걸 File에 updated를 하면 어떨까요?
forEach보단 filter를 이용해 한번에 찾는게 더 어울리는거 같아서요.

2023-10-08 11:59 UTC, ksy90101 commented on src/main/java/repository/FileRepository.java
> +                .findFirst();
이 로직이 중복되는데, 메서드로 빼둔다면 좀더 깔끔한 코드가 되지 않을까 생각이 들어요.

2023-10-08 11:59 UTC, ksy90101 commented on src/main/java/service/Mode.java
> +            if(selectNum <= 7 && selectNum >= 1) {
7과 1에 대해서 상수화를 하면 어떨까요?

2023-10-08 11:59 UTC, ksy90101 commented on src/main/java/service/Mode.java
> +    public boolean run() {
```suggestion

    public Mode(ModeType mode) {
        if(mode == ModeType.NORMAL_MODE) service = new Service(new FileRepository());
        else if(mode == ModeType.TEST_MODE) service = new Service(new MemoryRepository());
    }

    public boolean run() {
```
이렇게 하는게 더 깔끔해 보일거 같아요.

2023-10-08 11:59 UTC, ksy90101 commented on src/main/java/service/Service.java
> +    public ExecuteMessage lostBook(int id) {
5분이라는 개념이 service에 있어야 하는 로직이 아닐까요?
즉, 5분뒤에 변경되어야 한다는걸 결정해야 하는건 비지니스 로직이라고 생각이 들어서요.

File이던 Memory던 둘다 같은 5분뒤에 상태가 변경된다 이니깐요.

2023-10-10 05:22 UTC, suzzingv commented on src/main/java/domain/Book.java
> +import domain.BookState;
헉 진짜 꿀팁입니다!!

2023-10-10 05:29 UTC, suzzingv commented on src/main/java/thread/FileChangeStateThread.java
> +    public FileChangeStateThread(Book book, int time) {
멘토 기간이 끝나서 보실진 모르겠지만 그래도 남겨봅니다! 테스트 코드에서 변경 시간 설정하려고 넣은 인자입니다. 밑에 Thread.sleep(time)에서 쓰이는데 왜 인텔리제이에서도 안쓰인다고 뜨는지 잘 모르겠습니다. 이 time 선언을 지워버리면 Thread.sleep(time)에서 오류가 납니다.

2023-10-10 05:34 UTC, ksy90101 commented on src/main/java/thread/FileChangeStateThread.java
> +    public FileChangeStateThread(Book book, int time) {
현재 해당 필드의 time과 인자의 tiem과 충돌나서 그렇습니다.
실제 필드의 time은 쓰이나요?

2023-10-10 05:37 UTC, suzzingv commented on src/main/java/thread/FileChangeStateThread.java
> +    public FileChangeStateThread(Book book, int time) {
헉 지금 보니 제가 필드에 인자를 넣어주지 않았네요. 덕분에 궁금증 해결됐습니다. 감사합니다!!

2023-10-10 15:37 UTC, merged