[5기 - 정의진] 1~2주차 과제: 도서 관리 어플리케이션 제출합니다.
prgrms-be-devcourse/java-library-management pull request #22
Opened 2023-09-30 09:36 UTC by uijin-j

## 📌 과제 설명 
### 도서 관리 애플리케이션 
#### 요구 사항 
- [x] 도서 **등록**
- [x] 도서 전체 목록 **조회**
- [x] 제목으로 도서 **검색** 
- [x] 도서 **대여 / 반납 / 분실 / 삭제** 
  - 도서번호 기준 (도서 번호는 중복X)
  - 도서 상태 : [대여 가능, 대여 중, 도서 정리 중, 분실됨]
  - 반납 시 [도서 정리중] -- 5분 뒤 --> [대여 가능]
  - 분실 후 반납 가능
- [x] **테스트 모드** 지원
- [x] 일반 모드 시 **파일**로 저장
  - 애플리케이션 시작 시 파일에서 데이터 로딩

## 👩‍💻 구현 내용 
<img width="812" alt="스크린샷 2023-09-30 17 14 44" src="https://github.com/prgrms-be-devcourse/java-library-management/assets/80446430/cc510d0c-cbe5-4af8-8a25-9bb0f14562d4">

### App
- 실행 모드 정보[일반/테스트]를 받아와 의존성을 주입하고 어플리케이션을 시작합니다. 

### Mode
- 서비스에서 제공해주는 실행 모드들을 모아둔 Enum입니다.
- 각 enum 값들은 1. 번호 2. 이름 3. 해당 모드에서 사용할 Repository 구현체를 가지고 있습니다.

### Console
- 입출력을 담당합니다.
- 사용자의 입력을 받아와 Service의 메서드를 호출합니다.

### Menu
- 사용자가 이용할 수 있는 기능을 모아둔 Enum 입니다.
- 각 enum 값들은 1. 번호 2. 이름 3. 해당 기능 선택 시 호출할 Console 메서드를 가지고 있습니다.

### BookDto
- 도서 등록 시 도서 정보를 전달(Console -> Service)하기 위한 클래스입니다.

### BookService
- 비즈니스 로직 처리합니다.
- 비즈니스 로직에 따라 적절한 Repository 메서드를 호출 합니다.

### Repository
- 저장소(ex. 파일, 메모리...)에서 데이터를 가져와 서비스에게 제공해 줄 기능들을 명시해 놓은 인터페이스입니다.

#### FileRepository
- csv 파일을 저장소로 사용하는 리포지토리입니다. 
- Repository의 공통 기능 외에 파일에서 데이터를 가져오는 기능(loadBooks()), 파일에 변경된 데이터를 저장하는 기능(flush()) 등이 있습니다.
- 어플리케이션 시작 시 지정된 위치에 존재하는 파일로부터 데이터를 가져와 Set\<Book\> book에 캐시합니다. 이후 서비스에서 요청이 들어오면 파일이 아닌 books에서 데이터를 처리해 제공합니다. 
  - books에 변경사항이 발생할때마다 파일을 새로 덮어씌웁니다.

#### MemoryRepository
- 테스트 모드 지원을 위해 메모리를 저장소로 사용하는 리포지토리입니다. 

### Book
- 도서 정보를 가지고 있는 클래스입니다.
- 도서번호를 유니크하게 만들기 위해 존재하는 도서 번호중 가장 큰 값 + 1을 저장하고 있는 sequence라는 static 변수를 사용합니다.
- 멤버 변수가 많기 때문에 Builder 패턴을 사용했습니다. 
  - builder에서 도서번호에 대한 처리를 합니다.
    -  id 설정 X : sequence값 할당 -> sequence++
    -  id를 설정 O : (1) id가 sequence보다 크다면  할당 후 sequence를 업데이트, (2) id가 sequence 작다면 중복될 가능성이 있음으로 id 설정 X 로직 수행
- equals()를 오버라이딩하여 도서명, 작가, 페이지 수가 같으면 동일한 책으로 취급합니다.
- 도서는 복사(copy())할 수 있습니다.

### BookStatus
- 도서 상태를 모아놓은 Enum입니다.
- 각 enum 값들은 1. 이름을 가지고 있습니다. 
-  BookStatus는 canSwitch()라는 staic 메서드를 통해 before 상태에서 after 상태로의 전환 가능여부를 알려줍니다. 

## ✅ PR 포인트 & 궁금한 점 
1. 현재 예외는 자바에서 제공해주는 기본 예외를 사용하고, 예외 메시지를 통해 세부적인 처리를 하고 있는데요. 커스텀 예외를 만드는 것이 더 깔끔할까요?

(참고) 예를 들어, 사용자가 대여 요청을 한 경우 [console: rentMenu -> service: rentBook -> repository: changeStatus -> book: changeStatus -> BookStatus.canSwitch] 로직을 따라갑니다. BookStatus에서 대여 불가능할 경우 해당 이유(BookStatus)를 에러 메시지에 담아 줍니다. 그리고 콘솔에서 예외를 잡아서 e.message()로 넘어온 BookStatus에 따라 예외 처리를 합니다.
이 방법이 너무 원시적인 방법인 것 같아서 고민이 됩니다.. (이렇게 하는 이유는 canSwitch에서는 menu의 어떤 기능을 위해 자신이 호출되었는지 몰라 구체적인 예외 메시지를 작성해 줄 수 없기 때문입니다..)

2. 현재 파일 위치, 파일명, 파일 Header는 고정되어 있습니다. 파일 위치 + 파일명은 Mede.enum에서 FileRepository를 초기화할 때 설정하는데요. FileRepository에 static final 멤버 변수로 고정해 놓는 것이 나을까요?

3. 테스트 코드를 위해 Book 과 FileRepository에 불필요한 메서드가 추가되었습니다. (ex. getId(), getStatus()) 이렇게 해도 될까요.?

4. Console에서 사용하는 메시지가 너무 지저분한 것 같은데, enum으로 만들어서 관리하는 것이 편할까요?

PR을 정신없이 작성했는데 읽어주셔서 감사합니다:)
혹시 PR 작성법에 대한 피드백도 있다면 피드백 부탁드립니다🙇‍♀️

2023-10-02 06:23 UTC, hoon-space commented on library-management/build.gradle
> +    testImplementation 'org.junit.jupiter:junit-jupiter'
요거 둘 다 필요한가요 ???

2023-10-02 06:24 UTC, hoon-space commented on library-management/src/main/java/devcourse/backend/Mode.java
> +    private final int num;
축약어보다는 풀네임으로 작성하며 좀 더 읽기 좋은 코드가 될 것 같아요

2023-10-02 06:26 UTC, hoon-space commented on library-management/src/main/java/devcourse/backend/Mode.java
> +    TEST(2, "테스트 모드", new MemoryRepository());
Enum 타입은 보통 타입을 명시하는 경우가 많아서 ModeType 같은 네이밍이 좀 더 좋습니다.

2023-10-02 06:27 UTC, hoon-space commented on library-management/src/main/java/devcourse/backend/business/BookService.java
> +        }, 5 * 60 * 1000);
요건 팀 미팅때 이야기해서 넘아갈게요 ~~

2023-10-02 06:49 UTC, hoon-space reviewed
첫 과제 고생 많으셨습니다. 👍

2023-10-02 06:49 UTC, hoon-space commented on library-management/build.gradle
> +    testImplementation 'org.junit.jupiter:junit-jupiter'
요거 둘 다 필요한가요 ???

2023-10-02 06:49 UTC, hoon-space commented on library-management/src/main/java/devcourse/backend/Mode.java
> +public enum Mode {
Enum 타입은 보통 타입을 명시하는 경우가 많아서 ModeType 같은 네이밍이 좀 더 좋습니다.

2023-10-02 06:49 UTC, hoon-space commented on library-management/src/main/java/devcourse/backend/Mode.java
> +    private final int num;
축약어보다는 풀네임으로 작성하며 좀 더 읽기 좋은 코드가 될 것 같아요

2023-10-02 06:49 UTC, hoon-space commented on library-management/src/main/java/devcourse/backend/business/BookService.java
> +        }, 5 * 60 * 1000);
요건 팀 미팅때 이야기해서 넘어갈게요 ~~

2023-10-02 06:49 UTC, hoon-space commented on library-management/src/main/java/devcourse/backend/medel/Book.java
> +
아래 글 읽어봤을 땐 생성자를 private 로 선언할 수 있을 것 같은데, 한 번 체크 부탁드려요 ~ 
![image](https://github.com/prgrms-be-devcourse/java-library-management/assets/101714618/5683ac14-f903-490a-b0ae-0ba713aa984c)

https://inpa.tistory.com/entry/GOF-%F0%9F%92%A0-%EB%B9%8C%EB%8D%94Builder-%ED%8C%A8%ED%84%B4-%EB%81%9D%ED%8C%90%EC%99%95-%EC%A0%95%EB%A6%AC

2023-10-02 06:49 UTC, hoon-space commented on library-management/src/main/java/devcourse/backend/medel/BookStatus.java
> +        }
이 부분은 좀 더 개선을 해볼 수 있을 것 같아요.

if 문의 조건을 Boolean 을 리턴하는 private 함수로 묶으면 if 문 블록안에서는 return true 정도만 반환할 수 있을 것 같아요. 

좀 더 복잡하게는 각 타입마다 클래스로 뽑으면 if 문 분기는 없앨 수 있을 것 같지만 단순한 로직인데 너무 복잡해질 것 같으니 이건 선택 ...

2023-10-02 06:49 UTC, hoon-space commented on library-management/src/main/java/devcourse/backend/repository/MemoryRepository.java
> +    List<Book> books = new ArrayList<>();
List 보다는 Map ??

2023-10-02 06:49 UTC, hoon-space commented on library-management/src/main/java/devcourse/backend/view/Console.java
> +        Menu.selected(intInput(prompt.toString()));
StringBuffer 를 사용하신 이유가 궁금합니다. 
비슷한 걸로는 StringBuilder 도 있고 단순 + 하는 방식도 있을 것 같아요

2023-10-02 06:49 UTC, hoon-space commented on library-management/src/main/java/devcourse/backend/medel/Book.java
> +        private static long sequence = 1;
sequence 는 무조건 1 보장인가요 ?

2023-10-02 06:49 UTC, hoon-space commented on library-management/src/main/java/devcourse/backend/view/BookDto.java
> +    private int totalPages;
Book 이라는 엔티티는 연관 된 N 개의 DTO 를 가질 수 있어요.

BookDto 로 네이밍을 하게 되면, 여러 기능들을 단일 DTO 로 사용하실 것 같은데, 그렇게 되면 몇몇 필드들은 null 이 들어가게 되면서 특정 기능에는 불필요한 필드들이 많이 생길거에요.

그래서 저는 보통 기능별로 DTO 를 정의합니다.

2023-10-02 09:58 UTC, ordilov requested changes
과제 고생하셨습니다~
이번에 의진님은 dto에서 validation을 해주셨는데 service나 model에서 하는 것과 비교해서 어디서 하는게 좋은지 팀원분들하고도 의견 나누면서 생각해보면 좋을 것 같습니다!

테스트를 보기 쉽게 작성해주신 부분이 좋았습니다 🙇 
그래도 조금 고치자면 구두로 설명드린 것처럼 하나를 테스트하더라도 경우가 여러가지면 나눠서 작성해주시는게 좋습니다. 중복이 많은 것 같으면 [parameterized](https://www.baeldung.com/parameterized-tests-junit-5) 등을 써서 줄일 수 있습니다!

2023-10-02 09:58 UTC, ghost commented on .gitignore
> +.DS_Store
구두로 설명드린 `.idea` 추가해주세요!

2023-10-02 09:58 UTC, ghost commented on library-management/src/main/java/devcourse/backend/Mode.java
> +    private static Optional<Mode> get(int num) {
NIT) 흔히 `get`을 사용할 때는 `Optional`이 아닌 객체 타입으로 반환하는 편이에요. ([예시 JPA](https://www.baeldung.com/spring-data-findbyid-vs-getbyid))
- `get` -> `Null` 이면 예외 반환
- `find` -> `Optional`로 반환

2023-10-02 09:58 UTC, ordilov commented on library-management/src/main/java/devcourse/backend/medel/BookStatus.java
> +    public static final boolean canSwitch(BookStatus before, BookStatus after) {
질문) 이 부분을 static 메서드로 선언하신 이유가 있을까요?
before 객체에서 after를 인자로 받아서 가능한지 확인할 수도 있었을 것 같습니다.

2023-10-02 09:58 UTC, ordilov commented on library-management/src/main/java/devcourse/backend/repository/FileRepository.java
> +    public Set<Book> getBooks() {
질문) 테스트 시에 `findAll()`로는 테스트 못했던 이유가 있을까요?

2023-10-02 09:58 UTC, ordilov commented on library-management/src/test/java/BookServiceTest.java
> +        book2.setTotalPages(560);
질문) 1. 생성자에서 만들지 않고 set으로 다 할당해주신 이유가 있을까요?
2. 빈 값이 들어왔는지 validation 부분들도 dto에서 하도록 만들어주셨는데 여기서 하나가 빠졌을 때 문제가 생길까요?
ex) `setAuthor`가 빠졌다면 실제 book 객체가 생성이 될까요?

2023-10-02 09:58 UTC, ordilov commented on library-management/src/test/java/BookServiceTest.java
> +        verify(repository, times(1)).addBook(any());
질문) `addBook()`메서드가 호출된 걸 테스트한 걸로 book 객체가 생성된 걸 확인할 수 있을까요?

2023-10-02 09:58 UTC, ordilov commented on library-management/src/test/java/BookServiceTest.java
> +        verify(repository, times(1)).deleteById(bookId);
질문) mock으로 테스트하신 이유가 궁금합니다

2023-10-02 09:58 UTC, ordilov commented on library-management/src/main/java/devcourse/backend/repository/Repository.java
> +    void changeStatus(long id, BookStatus status);
NIT) `changeStatus`가 `repository`에 있으면 살짝 어색한 것 같습니다.
맥락을 이해하고 있으니 책의 상태를 변경하는구나 이해가 가지만 보통의 경우라면 `repository`의 상태를 변경하는 메소드라고 유추하기 쉬울 거 같아요.

책 객체 자체의 값을 변경하는 건 책 모델에 있는게 자연스러운 것 같습니다.
요번 구현에선 나오진 않았지만 `repository`에 있으면 `book`의 값을 바꾸는데 `repository`를 확장해야 합니다. 
지금 같은 구조에서 일관성을 가져가려면 제목을 바꿀 때도 `changeTitle` 같은 메소드가 매번 추가가 필요합니다!

2023-10-02 09:58 UTC, ordilov commented on library-management/src/main/java/devcourse/backend/business/BookService.java
> +public class BookService {
대부분 service 메서드들이 repository 메서드들을 호출하고만 있습니다.
이런 형태면 service 대신 repository를 그대로 쓰는 것과 다른 부분이 있을까요?
service랑 repository를 분리하셨으니 service에서 해야하는 게 무엇일지? 고민해보면 좋을 것 같습니다!

2023-10-02 13:42 UTC, uijin-j commented on library-management/build.gradle
> +    testImplementation 'org.junit.jupiter:junit-jupiter'
기본 설정을 그대로 사용해서 신경을 못 쓴 부분인 것 같습니다! 찾아보니, 'org.junit:junit-bom:5.9.1'가  jupiter 모듈을 포함하고 있어서 2번째 줄은 생략해도 될 것 같습니다!

2023-10-02 14:14 UTC, uijin-j commented on library-management/src/main/java/devcourse/backend/Mode.java
> +    private static Optional<Mode> get(int num) {
유용한 정보 감사합니다!
예외를 발생시키는 것이 맞는 것 같아 `getByNumber` 로 바꾸었습니다:)

2023-10-02 16:24 UTC, uijin-j commented on library-management/src/main/java/devcourse/backend/medel/Book.java
> +        private static long sequence = 1;
도서 번호가 1부터 시작해서 클래스가 로드될 때 1로 초기화 되면 좋을 것 같다고 생각했습니다! 그런데 다시보니 id 관련해서는 Builder에서 처리해주기 때문에 굳이 Book이 sequence를 가지고 있을 이유가 없는 것 같습니다!

2023-10-02 16:50 UTC, uijin-j commented on library-management/src/main/java/devcourse/backend/medel/BookStatus.java
> +    public static final boolean canSwitch(BookStatus before, BookStatus after) {
처음에는 인스턴스에 상관없이 확인 가능한 내용이니 static 메서드로 해도 되겠다 싶었는데, 인스턴스 메서드로 변경하고 인자를 하나만 받는 게 사용하는 입장에서 더 편할 것 같습니다!

2023-10-03 12:51 UTC, uijin-j commented on library-management/src/main/java/devcourse/backend/view/Console.java
> +        Menu.selected(intInput(prompt.toString()));
자바에서 불변 객체인 String의 특성상 '+' 연산을 할때마다 새로운 객체가 생성되기 때문에 '+' 연산이 많은 메뉴 출력 부분에서 String 대신 StringBuffer을 사용했습니다! 
StringBuilder와 StringBuffer는 멀티 쓰레드를 환경인지 여부(StringBuilder X, StringBuffer O)에 따라 어떤 것을 사용할지 결정하면 되는데, 저희 서비스에서는 현재 멀티 쓰레드 환경이 아니지만 혹시나 하는 마음에 StringBuffer을 사용했습니다!

2023-10-03 12:52 UTC, uijin-j commented on library-management/src/main/java/devcourse/backend/view/BookDto.java
> +    private int totalPages;
알려주셔서 감사합니다:) CreateBookDto로 수정하겠습니다!

2023-10-04 11:02 UTC, uijin-j commented on library-management/src/main/java/devcourse/backend/repository/FileRepository.java
> +    public Set<Book> getBooks() {
🙋🏻‍♀️ FileRepository 클래스의 단위 테스트에서 findAll() 메서드에 대한 테스트가 아닌 경우에도 findAll() 메서드를 써도 될까요? 
(예를 들어 deleteById() 메서드를 테스트 하는 코드에 FileRepository의 다른 메서드를 호출해도 되는걸까요?)

2023-10-04 11:09 UTC, uijin-j commented on library-management/src/test/java/BookServiceTest.java
> +        book2.setTotalPages(560);
1. 콘솔에서 도서 정보를 입력받는 과정에서 setter가 있으면 굳이 String title과 같은 변수를 만들 필요 없이 바로바로 title, author, totalPages를 dto에 설정할 수 있어서 이런 방식으로 했습니다!
2. 콘솔에서 `dto.setTitle(stringInput("등록할 도서 제목을 입력하세요."));`와 같이 setter 호출을 강제하기 때문에 빈값이 들어가는 경우는 없을 것이라고 생각했습니다..!
🙋🏻‍♀️ 그래도 데이터에 무결성을 지킬려면 안전하게 생성자에 모아서 유효성 검사를 하는게 맞는걸까요?

2023-10-04 11:14 UTC, uijin-j commented on library-management/src/test/java/BookServiceTest.java
> +        verify(repository, times(1)).addBook(any());
Repository에 대한 단위테스트가 따로 있으니, 서비스에서는 적절한 Repository의 메서드를 호출하는 것만 확인하면 요구사항을 만족한다고 생각했습니다! (멘토님이 언급 주신것 처럼 저의 Service 계층이 단순히 Repository 메서드를 호출하는 부분이 많았던터라..이런 단순한 테스트가 되었던 것 같습니다..!) 
🙋🏻‍♀️ 이 경우에는 repository의 findAll() 메서드를 호출해 입력한 도서가 있는지 확인하는게 더 좋은 테스트일까요?

2023-10-04 11:17 UTC, uijin-j commented on library-management/src/test/java/BookServiceTest.java
> +        verify(repository, times(1)).deleteById(bookId);
Service 클래스의 단위테스트에서 Repository와의 의존성을 없애기 위해 mockito 프레임워크를 사용했습니다!

2023-10-04 11:23 UTC, uijin-j commented on library-management/src/main/java/devcourse/backend/repository/Repository.java
> +    void changeStatus(long id, BookStatus status);
repository가 model의 변경사항을 알고 반영할 수 있도록 하려면 변경을 알려줄 메서드를 만들어야된다고 생각했습니다..!
🙋🏻‍♀️ 그렇다면 Spring Data JPA의 변경 감지처럼 repository에서 findById()로 도서 객체를 반환할 때, 객체의 레퍼런스를 바로 주는 방식으로 해도 될까요? (현재는 원치않은 변경을 차단하기 위해 객체를 복사해서 반환하고 있습니다!)

2023-10-04 11:35 UTC, uijin-j commented on library-management/src/main/java/devcourse/backend/business/BookService.java
> +public class BookService {
저도 서비스 계층에서 단순히 repository의 메서드를 호출하니 서비스 계층이 무슨 의미가 있는 것인지.. 애플리케이션이 작아서 그런건가?하고 의문이 들었는데, 제가 비즈니스 로직부분도 다른 계층에 넘겨버려서 그런 것 같습니다.. 서비스 계층의 역할을 생각해보고 수정하겠습니다! 감사합니다:)

2023-10-05 02:53 UTC, uijin-j commented on library-management/src/main/java/devcourse/backend/repository/MemoryRepository.java
> +    List<Book> books = new ArrayList<>();
id로 접근하는 경우가 많아서 Map이 성능상 더 좋을 것 같습니다! 수정해놓겠습니다 감사합니다:)

2023-10-06 16:05 UTC, hoon-space commented on library-management/build.gradle
> +    testImplementation 'org.junit.jupiter:junit-jupiter'
개인적인 생각으로 하나의 프로젝트에 Junit4,5 가 섞이는 케이스는 딱 한가지인 것 같아요.
=> 기존에 개발 된 코드가 이미 Junit4 를 사용하고 있는 상황에서 Junit5 를 도입하였지만, 4 는 못 걷어낸경우
=> 그렇기 때문에 없어도 된다고 생각해요 !

2023-10-06 16:09 UTC, hoon-space commented on library-management/src/main/java/devcourse/backend/view/Console.java
> +        Menu.selected(intInput(prompt.toString()));
개인적으로 StringBuffer 는 Deprecated 되어야 된다고 생각을 합니다 😅
(1) 문자열 + 연산을 하면서 경합이 발생하는 경우가 언제일까 ?? <- 떠오르지가 않네요 ㅠㅠ 그만큼 일어날 케이스가 거의 없음
(2) 연산자 단위에서 쓰레드 안전을 보장하는게 의마가 있나 ?? <- 메소드가 쓰레드 보장이 안되면 무슨 의미인가 
(3) 더 나아가 애플리케이션이 여러개인 경우 하나의 애플리케이션에서 블락 거는 행위가 무슨 소용인가 ...

암튼 이러한 이유로 Syncronized 키워드 혹은 자체 그걸 가지고 있는 ... StringBuffer 는 사용할 일이 없는 것 같아요 🥲

2023-10-06 16:17 UTC, hoon-space commented on library-management/src/main/java/devcourse/backend/medel/BookStatus.java
> +    public final boolean canSwitch(BookStatus after) {
final ??

2023-10-06 16:46 UTC, hoon-space approved these changes
과제 리뷰 반영 해주시느라 고생 많으셨습니다.  🙇‍♂️
인후님이 피드백을 잘해주셔서 그 전 보다 퀄리티가 많이 좋아졌네요 !

2023-10-06 16:46 UTC, hoon-space commented on library-management/src/main/java/devcourse/backend/medel/BookStatus.java
> +    public final boolean canSwitch(BookStatus after) {
final ??

2023-10-06 16:46 UTC, hoon-space commented on library-management/src/main/java/devcourse/backend/view/CreateBookDto.java
>          if (totalPages <= 0) throw new IllegalArgumentException("페이지 수는 0보다 커야 합니다.");
DTO 에는 굳이 값 검증 로직이 있을 필요는 없을 것 같아요.

2023-10-06 16:46 UTC, hoon-space commented on library-management/src/main/java/devcourse/backend/repository/MemoryRepository.java
> +        // DO NOTHING
인터페이스의 단점인데 .. // DO NOTHING 인 메소드가 있으면 클라이언트 입장에서는 구현이 되었는지 안되었는지 내부를 들여다봐야되요. 인터페이스를 사용하는 이유 중 하나가 명세만 보고 내부 구현 추상화함이 목적인데 어긋나는 것 같아요 ㅠ

2023-10-06 16:46 UTC, hoon-space commented on library-management/src/main/java/devcourse/backend/business/BookService.java
> +        if(!scheduler.isRunning()) scheduler.startScheduler();
리턴 메소드가 콜 될 떄가 아닌 백그라운드로 1분에 한 번씩 로직이 수행되는 식으로 구현할 수는 없을까요 ??
동시에 요청 날리면 두 번 실행될 수 있을 것 같아요.

2023-10-06 16:46 UTC, hoon-space commented on library-management/src/main/java/devcourse/backend/model/Book.java
> +            this.status = BookStatus.get(status).orElseThrow();
status Enum 이 정의가 되어 있는데 스트링으로 받는 이유는 무엇인가요 ??

2023-10-06 16:46 UTC, hoon-space commented on library-management/src/main/java/devcourse/backend/view/CreateBookDto.java
>          if (totalPages <= 0) throw new IllegalArgumentException("페이지 수는 0보다 커야 합니다.");
아 이 커밋에서 날리셨군요. https://github.com/prgrms-be-devcourse/java-library-management/pull/22/commits/b4cd7a5587f17643287163311a904df745846628

흠 그런데 이 로직이 도메인 빌더에 있는 거랑 같아보여요

2023-10-06 16:46 UTC, hoon-space commented on library-management/src/main/java/devcourse/backend/business/BookService.java
> +        if(!scheduler.isRunning()) scheduler.startScheduler();
여기 커밋에서 확인 https://github.com/prgrms-be-devcourse/java-library-management/pull/22/commits/18e4475bbbf2affc05b7fcd43191ae4af79369ef

2023-10-07 01:28 UTC, ordilov approved these changes

2023-10-07 01:28 UTC, ghost commented on library-management/src/main/java/devcourse/backend/model/Book.java
> +    private LocalDateTime updateAt;
사소하지만 보통 `updateAt` -> `updatedAt`으로 네이밍을 합니다!

+ `updatedAt`은 객체 전체 필드 값의 변화가 있을 때마다 기록하는 용도로 많이 쓰입니다.
특정 필드 값이 변화하는 것만 기록할 때는 더 상세한 네이밍으로 사용하면 좋습니다!

2023-10-07 01:28 UTC, ghost commented on library-management/src/test/java/BookServiceTest.java
> +        verify(repository, times(1)).addBook(any());
상황에 따라 다르지만 구현이 변경되었을 때 findAll()로 비교하는 거보다 변경에 취약하고 고려할 부분이 있습니다.
1. addBook() 네이밍을 registerBook()으로 바꾼다면? (구현도 바꾸고 테스트도 바꿔야합니다. findAll()은 유지가능)
2. 책을 추가하면서 재고를 추가하는등 추가작업이 생긴다면? (모든 메소드들을 호출 검증해주도록 추가해줘야합니다.)
3. 트랜잭션으로 묶여있고 뒤에 특정 조건에 롤백하는 부분이 있었다면? (호출은 되었지만 생성은 되지 않습니다.)

2023-10-07 01:28 UTC, ghost commented on library-management/src/main/java/devcourse/backend/repository/FileRepository.java
> +    public Set<Book> getBooks() {
서순에 따라 다른 것 같습니다! 말씀해주신대로 A를 테스트할 때 B가 필요한 경우라면 B가 테스트된 상태면 문제가 없겠죠..?

2023-10-07 01:28 UTC, ordilov commented on library-management/src/main/java/devcourse/backend/repository/Repository.java
> +    void changeStatus(long id, BookStatus status);
원치않은 변경이 어떤 부분을 우려하신건지 정확히 판단은 안되서 답변 드리기가 조금 조심스럽습니다..!
일단 생각해보시면 좋을 부분이 그럼 객체가 라이프사이클을 가지고서 존재할 수 있는 레이어는 어디까지일까? 입니다.
지금 말씀해주신 부분으로 생각해보면 값을 변경할 때는 레포지토리까지만 있어야 되는 걸로 보입니다.
이건 전에 질문 답변드린 것처럼 서비스 역할이 단순히 레포지토리에 인자를 넘겨주기위한 용도인가 다시 고민해보시보면 좋습니다!

2023-10-08 08:52 UTC, uijin-j commented on library-management/src/main/java/devcourse/backend/model/BookStatus.java
> +    LOST("분실됨", (after) -> after == "ARRANGING");
🙋🏻‍♀️ [훈님이 남겨주신 리뷰](https://github.com/prgrms-be-devcourse/java-library-management/pull/22#discussion_r1342325555) 를 보고 이런식으로 바꿔보았는데 괜찮을까요?
조언해주신 방법 (1) IF문의 조건을 private 메서드로 추출, (2) 각각의 Enum Type을 클래스로 빼서 처리의 중간 방법인 것 같아서 이런 방식으로 해보았습니다! IF문에 사라져 가독성이 올라가고, 코드도 크게 복잡해지진 않았지만 **enum이 또다른 enum type을 참조하는 데에 제약이 있어 "BORROWED"와 같이 리터럴로 비교를 하는 것이 마음에 걸립니다**..

2023-10-08 08:52 UTC, uijin-j commented on library-management/src/main/java/devcourse/backend/Mode.java
> +public enum Mode {
ModeType으로 수정하였습니다:)

2023-10-08 08:52 UTC, uijin-j commented on library-management/src/main/java/devcourse/backend/Mode.java
> +    private final int num;
NORMAL_MODE, TEST_MODE로 수정하였습니다:)

2023-10-08 08:52 UTC, uijin-j commented on library-management/src/main/java/devcourse/backend/business/BookService.java
> +        }, 5 * 60 * 1000);
BookOrganizingScheduler 클래스를 만들어 싱글 쓰레드로 해당 로직을 구현하도록 변경했습니다:)

2023-10-08 08:52 UTC, uijin-j commented on library-management/src/main/java/devcourse/backend/medel/Book.java
> +
private으로 변경했습니다:)

2023-10-08 08:52 UTC, uijin-j commented on library-management/src/main/java/devcourse/backend/medel/BookStatus.java
> +        }
두 방법의 중간 지점(?)으로 BookStatus의 Type들이 각각 `private final Predicate<String> canSwitchTo;`를 구현하도록 변경해 보았습니다!

2023-10-08 08:52 UTC, uijin-j commented on .gitignore
> +.DS_Store
.gitignore 업데이트 했습니다:)

2023-10-08 08:52 UTC, uijin-j commented on library-management/src/main/java/devcourse/backend/model/Book.java
> +            this.status = BookStatus.get(status).orElseThrow();
도서 상태와 함께 도서를 등록하는 경우는 어플리케이션이 시작될 때 파일에 있는 정보를 가지고 도서 객체를 생성할 때뿐이라고 생각했습니다.! 그 경우, 파일에는 도서 상태가 string으로 저장되어 있어서 이렇게 빌더를 만들었는데, 다시 생각해보니 string -> BookStatus로 바꿔주는 로직을 도메인이 아닌 리포지토리에서 해야 될 것 같습니다!
https://github.com/prgrms-be-devcourse/java-library-management/pull/22/commits/1e9ce26682dde56e8941eb900294571190220d01 수정해 놓았습니다!

2023-10-08 10:09 UTC, uijin-j commented on library-management/src/main/java/devcourse/backend/medel/BookStatus.java
> +    public final boolean canSwitch(BookStatus after) {
enum은 어차피 상속이 불가능하고, canSvitch를 런타임에 변경할 일이 없다고 생각해서 final을 붙였는데 final을 굳이 사용할 필요가 없다면 사용하지 않는게 나을까요?

2023-10-08 10:39 UTC, uijin-j commented on library-management/src/main/java/devcourse/backend/model/Book.java
> +    private LocalDateTime updateAt;
https://github.com/prgrms-be-devcourse/java-library-management/pull/22/commits/19ec58428c929c8fae5208c916d6d52ec90b865f 반영해 놓았습니다:)

2023-10-08 10:39 UTC, uijin-j commented on library-management/src/main/java/devcourse/backend/model/Book.java
> +            this.status = BookStatus.get(status).orElseThrow();
https://github.com/prgrms-be-devcourse/java-library-management/pull/22/commits/1e9ce26682dde56e8941eb900294571190220d01 반영해 놓았습니다!

2023-10-08 10:41 UTC, uijin-j commented on library-management/src/main/java/devcourse/backend/view/CreateBookDto.java
>          if (totalPages <= 0) throw new IllegalArgumentException("페이지 수는 0보다 커야 합니다.");
https://github.com/prgrms-be-devcourse/java-library-management/pull/22/commits/229c0759be6ca4d9beb1e78644ea661eab5ae6e9 
해당 부분은 글로벌한 유효성 검사라 판단해서  컨트롤러에 있는 것은 삭제하고 도메인에 있는 것만 남겼습니다!

2023-10-08 10:45 UTC, uijin-j commented on library-management/src/main/java/devcourse/backend/model/BookStatus.java
> +    LOST("분실됨", (after) -> after == "ARRANGING");
@hoon-space @ordilov 
지난 커밋에 제가 궁금한 점을 코멘트로 남겨봤는데, 제출을 안해서 이제서야 제출합니다..!
이미 과제 기간은 지났지만, 가능하다면 이 부분에 대한 피드백을 받아봐도 괜찮을까요?

2023-10-08 13:03 UTC, ordilov commented on library-management/src/main/java/devcourse/backend/model/BookStatus.java
> +    LOST("분실됨", (after) -> after == "ARRANGING");
수정해주신 방향성은 좋은 것 같습니다!
enum이 또다른 enum type 참조하는데 제약이 있는 부분은 찾아보셨겠지만 정답이 있지는 않고 우회하는 방법이 몇가지 있습니다.
1. `AVAILABLE` 같은 enum 값 들만 먼저 정의한 enum을 따로 빼서 사용하기
2. 생성자에서  `canSwitchTo`를 넣어주는 대신, static 블럭에서 필드 값 넣어주기

혹은 필드로 관리하지 않고 저번이랑 비슷한 방식으로 회귀하되 switch문으로 위에서 명시해주신 부분들을 메서드 하나에서 관리하는 것 정도가 방법이 될 것 같습니다!

2023-10-08 17:58 UTC, hoon-space commented on library-management/src/main/java/devcourse/backend/model/BookStatus.java
> +    LOST("분실됨", (after) -> after == "ARRANGING");
저도 인후님이 작성해주신 것처럼 이전 코드보다 훨씬 좋은 것 같습니다. 
(1), (2) 번 동시에 적용하시기 위해 노력하신 흔적이 보이네요 😮

다만, 작성해주신 코드의 단점으로는 두가지 정도가 있을 것 같아요.
(1) 위에서 말씀해주신 리터럴 비교 
(2)`Predicate<String> canSwitchTo;` 가 변경이 되면 사용하고 있는 코드 전체에 영향이 감 
- (2) 번이 어떻게 보면 로직을 한 곳에 모으니 장점일 수도 있지만, 다르게 보면 변경에 취약한 코드가 될 수 있을 것 같아요. 
- (3) 예를들어 현재 요구사항에는 딱 맞는 코드이지만, 어떤 책들은 임시로 대여를 불가능하게 한다는가 하는 비즈니스 요구 사항(책 종류 별로 상태 관리가 달라지는 케이들)이 추가 된다. BookStatus 를 사용하는 모든 코드가 변경이 될 수도 있어요.
- 그래서 개인적으로 이러한 상태 관리는 `BookStatusHandler` or `BookStatusService` 이런 네이밍으로 클래스 하나 만든 다음에 이러한 클래스에 다 모와두고 사용하는걸 선호합니다. 
- 다른 케이스가 추가 된다면 예를 들어 `XXXBookStatusHandler`이런 클래스 만들고 또 여기에 로직을 넣는 방식으로 하고 있어요.

2023-10-08 18:11 UTC, hoon-space approved these changes
리뷰 완 ~

2023-10-08 18:11 UTC, hoon-space commented on library-management/src/main/java/devcourse/backend/business/BookOrganizingScheduler.java
> +            scheduler.scheduleAtFixedRate(new BookOrganizingTask(), 0, period, TimeUnit.MILLISECONDS);
👍

2023-10-08 18:11 UTC, hoon-space commented on library-management/src/main/java/devcourse/backend/business/BookOrganizingScheduler.java
> +    private ScheduledExecutorService scheduler;
클래스 이름은 Service 이지만 변수명은 scheduler ??

2023-10-08 18:11 UTC, hoon-space commented on library-management/src/test/java/BookOrganizingSchedulerTest.java
> +    }
객체 초기화는 `@BeforeEach` 에서 하기보다는 생서자에서 하는 건 어떤가요 ??
데이터를 클리어하는 목적이 아니라면 `@BeforeEach` 로 하지 않아도 될 것 같아요.

2023-10-08 18:11 UTC, hoon-space commented on library-management/src/main/java/devcourse/backend/repository/MemoryRepository.java
> +        // Memory Repository는 데이터를 스토리지에 저장하지 않습니다(휘발성)
MemoryRepository 라도 데이터 저장은 하기 때문에 save 라는 메서드로 인터페이스를 통일해도 좋을 것 같아요.
위에 addBook 이 사실 메모리에 값을 넣는다(= save) 이기 떄문에 flush = addBook 인 것 같아요.

2023-10-09 06:20 UTC, uijin-j commented on library-management/src/main/java/devcourse/backend/model/BookStatus.java
> +    LOST("분실됨", (after) -> after == "ARRANGING");
헉 두 분 모두 답변 감사합니다..!🥺🙇🏻‍♀️ 
enum에서 다른 enum을 참조할 일이 있을 때, 인후 멘토님이 말씀해주신 방법을 사용해 보겠숩니다ㅎㅎ 
그리고 도서 상태의 경우에 비즈니스적으로 중요하고 변경 가능성이 높아서 말씀 주신 것처럼 Handler나 Service를 만드는 것이 좋을 것 같습니당!

2023-10-09 13:59 UTC, uijin-j commented on library-management/src/main/java/devcourse/backend/repository/MemoryRepository.java
> +        // Memory Repository는 데이터를 스토리지에 저장하지 않습니다(휘발성)
https://github.com/prgrms-be-devcourse/java-library-management/pull/22/commits/e8a2207775c6b49d3215da3b19abbf6f1799b4bb 반영했습니다:)

2023-10-09 14:00 UTC, uijin-j commented on library-management/src/main/java/devcourse/backend/business/BookOrganizingScheduler.java
> +    private ScheduledExecutorService scheduler;
https://github.com/prgrms-be-devcourse/java-library-management/pull/22/commits/03cdbec2eb6eb4232993db2ebb8a3e2a9ddcb7fc 반영했습니다:)

2023-10-09 14:01 UTC, uijin-j commented on library-management/src/main/java/devcourse/backend/model/BookStatus.java
> +    LOST("분실됨", (after) -> after == "ARRANGING");
https://github.com/prgrms-be-devcourse/java-library-management/pull/22/commits/53bf2032d6d2ad5e7bb76264ba18bf13586212e1
말씀하신 의도대로 했는지는.. 확신이 없지만 Handler 클래스 만들어서 처리해 보았습니다:)

2023-10-09 14:06 UTC, uijin-j commented on library-management/src/test/java/BookOrganizingSchedulerTest.java
> +    }
https://github.com/prgrms-be-devcourse/java-library-management/pull/22/commits/ddf93f9951a07a07c49f32d336f439f3f33c2fc3 반영했습니다:)

2023-10-13 09:36 UTC, merged