Sehee lee 01
prgrms-be-devcourse/java-library-management pull request #24
Opened 2023-09-30 16:47 UTC by Sehee-Lee-01

### ✉️ 안녕하세요, 도찌 멘토님, 무송 멘토님! 
예정 시간 보다 조금 늦게 제출하게 되어서 우선 죄송하다는 말씀부터 드립니다.🥲 자바를 깊게 이해하고 제대로 써본 경험도 없고, 스프링도 거의 살짝 이론으로만 공부하고 와서 최대한 기존의 경험 중심으로 과제를 구현하려다 보니 시행착오가 조금 많았습니다...😭 
이 없는 실력에 어떤 맛(?)을 고를까 스스로 고민하다가, 실력 향상을 위해 매운맛을 선택했습니다. 고칠 점이 보이신다면 편하게 말씀해주시면 감사하겠습니다! 

## 📌 과제 설명 

- 도서 관리 애플리케이션입니다.
- 인메모리로 도서를 임시로 관리하는 테스트 모드와 JSON 파일에서 직접 데이터를 불러오고 관리하여 저장하는 일반 모드를 선택할 수 있습니다.
- 도서 등록, 전체 조회, 도서 이름 검색, 대여, 반납, 분실, 삭제 기능을 제공합니다.

## 👩‍💻 요구 사항과 구현 내용 

### 🗺️ 프로젝트 구조

<img width="811" alt="스크린샷 2023-09-30 202855" src="https://github.com/prgrms-be-devcourse/java-library-management/assets/85275893/15cd9c74-7815-494a-9a01-7d9eac40e7fd">

### 📝 과제 구현 기능

- [X] 도서를 등록
- [X]  도서 전체 목록 조회
- [X]  도서 제목을 기준으로 도서를 검색
- [X]  도서 번호를 기준으로 도서를 대여
  - [X] '대여 가능' 상태가 아닌 경우, 해당 도서를 대여할 수 없는 이유 알림
- [X]  도서 번호를 기준으로 도서를 반납
  - [x]  반납 후 '도서 정리중' 변경. 5분 후 '대여 가능' 변경.
    - 데이터 조회 때마다 정리 완료 예정 시간과 비교 후 업데이트하는 방식(스레드 X)
  - [X] 분실 도서  반납 처리
- [X]  도서 번호를 기준으로 도서를 분실 처리
- [X]  도서 번호를 기준으로 도서를 삭제
- 그 외 구현해야 할 기능 
  - 모드
    - [X] 테스트 모드(인메모리: LinkedHashMap)
    - [X] 일반 모드(JSON 파일)
  - 테스트 코드 
    - [X] 도서 상태에 따른 BookService 메서드 테스트 코드 작성
    - [X] 콘솔 입력값 유효성 검사 테스트 코드 작성

## ✅ PR 포인트 & 궁금한 점 

### 1.  Client, Server 분리 구조
- 프론트엔드와 백엔드를 나누어서 각각 개발하는 것처럼 최대한 Client, Server 부분의 의존성을 약하게 하도록 구현했습니다. 그리고 HTTP 통신 기반으로 서로 데이터를 교환하듯, Request(요청)/String(응답) 객체를 통해 데이터를 교환하는 형식으로 구현했습니다. 
  - `Client`: 요청을 입력 받는 콘솔 입력 부분 
  - `Server`: 데이터를 가공하고 관리하는 부분
 - 클래스 선언/사용 방식이 적절한지, 클래스 간의 의존성은 어떻게 보이시는지 궁금합니다! 요약하자면 전체적인 구조에 대한 피드백을 받고 싶습니다! 아래는 특히 궁금한 사항입니다!
   - Client, Server를  싱글톤 방식으로 사용한다고 나름 적용해봤는데, 이렇게 적용해서 구현하는 것이 적절해보이는지 궁금합니다.
   - 클라이언트에서 사용하는 클래스 간의 의존성 개선 희망 사항이 있는지 궁금합니다.

### 2. 매서드 매핑용도로의 enum 활용
- enum을 함수 및 메서드 매핑 용도로 활용을 했는데 적절하게 사용한 것인지 파악이 잘 안됩니다! 혹시 더 좋은 방법이나 더 생각나는 부분이 있다면 편하게 말씀해주시면 감사하겠습니다!
- 아래 링크에서 코드 보면서 주석(`Q.~`) 확인해주시면 보기 편하실 겁니다!
  - [과제 코드 1](https://github.com/Sehee-Lee-01/java-library-management/blob/Sehee-Lee-01/src/main/java/org/example/client/console/ModeConsole.java)
  - [과제 코드 2(코드 1 주석에서 말하는 MethodConsole 클래스)](https://github.com/Sehee-Lee-01/java-library-management/blob/Sehee-Lee-01/src/main/java/org/example/client/console/MethodConsole.java)
  - [과제 코드 3](https://github.com/Sehee-Lee-01/java-library-management/blob/Sehee-Lee-01/src/main/java/org/example/server/controller/BookController.java)

### 3. [반납 5분 후 대여 가능 변경 기능(코드)](https://github.com/Sehee-Lee-01/java-library-management/blob/Sehee-Lee-01/src/main/java/org/example/server/repository/Repository.java)
- 제대로 구현하려면 Thread를 사용해서 book 상태를 변경하고 업데이트 해야할 것 같은데 실제 서버를 사용할 때 이 기능을 구현한다면 어떤 방식으로 구현하는 것이 일반적인지 궁금합니다!
  - 서버 단에서 어떻게 관리하는지, 중간에 서버가 멈춘다면 어떤 조치를 취하는지
  - DB단에서 관리할 수는 없는지
  
### 4. 커스텀 예외 사용 방식
- Client, Server에서 발생하고 처리하는 예외를 분리시키기 위해 아래처럼 크게 두 개의 예외를 만들었습니다. 아래처럼 예외를 사용하는 것이 적절하게 사용하고 있는 것인지 궁금합니다.
  - `Client` : ValidateException 
    - Client는 각 필요한 정보에 맞는 입출력이 중요한 요소인 것 같아 해당 예외만 구현했습니다.
  - `Server` : ServerException
    - 서버 실행 중 조건이 안 맞아(ex. 도서 대여중인데 대여하려고 하는 경우) 발생하는 예외는 이 예외를 상속 받습니다.
  - `그 외 예외`: 가장 바깥인 Application에서 관리하고 프로그램을 종료 하도록 처리합니다. 

### 5.  예외 처리 방식
- [BookService 클래스](https://github.com/Sehee-Lee-01/java-library-management/blob/Sehee-Lee-01/src/main/java/org/example/server/service/BookService.java)에서 조건이 맞지 않으면 예외를 보냅니다. 이런 처리 방식이 괜찮은지, 더 나은 방법이 있는지 궁금합니다! 
  - 이렇게 하면 간단하게 응답을 반환할 수 있긴하지만 적절한 방법인지 모르겠습니다.
- [메뉴 정보를 입력받는 콘솔 부분](https://github.com/Sehee-Lee-01/java-library-management/blob/1e5ae885580a6ee64deebf5f0dab290f817e87c9/src/main/java/org/example/client/console/MethodConsole.java#L98)에서 유효하지 않은 값을 입력하면 다시 한 번 입력할 수 있는 방식으로 예외를 처리해주었습니다. 이런 방식은 어떻게 생각하시는지 궁금합니다!

### 6. 테스트 코드
- 테스트 코드를 작성해본 경험이 거의 없습니다. 🥲 항상 궁금했지만 프로젝트를 진행할 때 무엇을 중점으로 테스트를 진행해야 하는지 궁금합니다. 
- 제가 작성한 테스트 코드 외에도 더 작성하면 좋을 것 같은 테스트 코드가 있는지 궁금합니다!

2023-10-03 17:38 UTC, moosongsong reviewed
세희님! 명절에 과제하시느라 고생하셨습니다! 전반적으로 주석을 엄~청 달아 주셔서 혹시 코드에 자신이 없어서 그러신가 걱정이군요ㅠㅠ 많이 고민하시고 작성해주신 것 충분히 느껴집니당.

cf) 제가 코멘트한 사항이 모두 정답은 아닙니다^^ 이해가 안되는 부분, 반박할 부분이 있다면 편하게 코멘트 남겨주세요~

### # 질문 주신 사항에 대한 제 답변

> 4. 커스텀 예외 사용 방식
> Client, Server에서 발생하고 처리하는 예외를 분리시키기 위해 아래처럼 크게 두 개의 예외를 만들었습니다. 아래처럼 예외를 사용하는 것이 적절하게 사용하고 있는 것인지 궁금합니다.

느낌이라면 적절하게 잘 사용하셨습니다. 저는 크게 동일하게 처리해야 하는 예외를 상위로 두고, 만약 해당 로직에서 파생되는 예외로 인해 처리에 대한 분기 점이 발생한다면 하위 예외를 추가하는 느낌으로 구현하고 있습니다. 커스텀 예외 사용하려고 노력하신 부분 👍 

> 5. 예외 처리 방식
> [BookService 클래스](https://github.com/Sehee-Lee-01/java-library-management/blob/Sehee-Lee-01/src/main/java/org/example/server/service/BookService.java)에서 조건이 맞지 않으면 예외를 보냅니다. 이런 처리 방식이 괜찮은지, 더 나은 방법이 있는지 궁금합니다!
> 이렇게 하면 간단하게 응답을 반환할 수 있긴하지만 적절한 방법인지 모르겠습니다.
> [메뉴 정보를 입력받는 콘솔 부분](https://github.com/Sehee-Lee-01/java-library-management/blob/1e5ae885580a6ee64deebf5f0dab290f817e87c9/src/main/java/org/example/client/console/MethodConsole.java#L98)에서 유효하지 않은 값을 입력하면 다시 한 번 입력할 수 있는 방식으로 예외를 처리해주었습니다. 이런 방식은 어떻게 생각하시는지 궁금합니다!

저도 이렇게 처리합니다~ 

> 테스트를 위해 Private으로 선언한 객체나 메서드를 사용할 일이 있을 때는 어떤 방식으로 하는지 궁금합니다.
> 기록이 안 남아있을 수 있지만 위 상황이 생겼을 때 방법을 잘 몰라서 public으로 바꾸고 테스트를 진행하기도 했습니다....

private 메서드는 해당 메서드를 호출하는 public&protected 메서드를 통해 간접 테스트를 진행합니다. 이때 정말 private 테스트가 필요한 상황이라면, 코드 설계가 잘못되었다고 판단하고 코드를 수정하는게 바람직하다고 보는데요. 아마 private 메서드를 테스트해야하는 필요성이 느껴진다는 건, 해당 메서드에 책임이 많아졌다는 뜻이겠죠?

> public/private/protected를 어떻게 적절히 써야 하는지 스스로 헷갈리는 부분이 좀 있는 것 같습니다! 멘토님들은 현업에서 접근 제어자를 사용할 때 중요하게 생각하는 부분이 있는지 여쭤보고 싶습니다!

- method
  - 외부에서 사용한다 -> publid
  - 내부에서만 사용한다 -> 바로 private
  - 쓰다보니 갑자기 자식객체에서 필요함 -> 그때 private을 proteced로 열음
- field
  - 닥 private 
  - 외부에서 사용하려고 만든 Const인 경우 public
  - 내부에서 쓰려고 만든 상수인데 자식이 쓰게 되었음 -> 그때 private을 proteced로 열음

이 순서로 저는 작성하는데 너무 당연한 걸 알려드린 것 같아서 챙피하네유;;ㅜㅠ

> 테스트 코드 관련 부분에서는 기초적인 지식이 많이 없습니다! 앞으로 사용할 스프링에서도 작성해야 한다고 알고 있는데, 계속 더 접해보려고 노력하고 공부하겠습니다!

많이 작성해보시면 늘어요! 홧팅 👍

2023-10-03 17:38 UTC, moosongsong commented on src/main/java/org/example/client/console/MethodConsole.java
> +    public static RequestData scanAndSetBookInfo(IO io) {
세희님 꼼꼼한 주석 좋습니다~ 다만 주석이 필요할 때는 요 [Link](https://www.oracle.com/kr/technical-resources/articles/java/javadoc-tool.html)의 방식으로 주석을 작성합니다. 해당 방식을 지켰을 때 가지는 이점도 있는데 이것도 한번 찾아보시면 좋을 것 같아요~

그리고 과제라서 하나하나 왜 이렇게 구현했는지 설명하려고 주석을 작성하신 것 같은데, 메소드명으로도 충분이 표현이 가능하니까 꼭 필요하다고 생각하는 부분에 작성해주시는 습관을 가지셔도 좋을 듯 싶습니다.

물론 주석 작성을 권장하는 팀이 있고, 주석 작성을 지양하는 팀이 있는데, 두 곳 다 몸담아본 바로는 
 
- 일단 메서드가 하나의 역할만 수행하게 작성하고, 메서드 명으로 충분히 표현한다.
- 근데 사용의 의미가 잘 드러나지 않는 것 같고, 복잡한 로직이 포함되어 있다. -> 주석을 작성한다.

요런식의 느낌이다로 가져가주시면 👍

2023-10-03 17:38 UTC, moosongsong commented on .gitignore
> +<<<<<<< HEAD
conflict 해결하다가 미쳐 확인하지 못한 부분 같은데, branch 충돌시 어떻게 해결하고 계실까용??

추가) 그리고 idea 디렉토리는 작업자 환경에 따른 설정이기 때문에 제외해주시는 것도 좋을 것 같아요~

2023-10-03 17:38 UTC, moosongsong commented on src/main/java/org/example/client/Client.java
> +    private static final IO io = new IO();
Client 클래스를 싱글톤으로 구현했지만, IO 클래스는 싱글톤으로 생성하지 않은 이유가 있을까요?

2023-10-03 17:38 UTC, moosongsong commented on src/main/java/org/example/client/console/Validator.java
> +            public String getMessage() {
Exception Message를 생성자에서 설정하지 않고, 오버라이딩한 이유가 있을까요? 

Exception에서 getMessage()로 가져오는 값은 Throwable의 detailMessage 인데, 만약에 e 객체를 찍거나 디버깅 할 때 메시지의 값이 null로 노출될 것 같은데요???

2023-10-03 17:38 UTC, moosongsong commented on src/main/java/org/example/packet/Request.java
> +public class Request {
과제여서 간단하게 네이밍을 하신 것 같은데, 이름들이 많이 아쉽네요. 네이밍 신경 써주세요 ^^

2023-10-03 17:38 UTC, moosongsong commented on src/main/java/org/example/client/console/Validator.java
> +public class Validator {
Input 메시지를 검증하려고 하신 건 좋습니다. 다만 이게 여기서 처리해야 할 항목인지 의문이 드는데요.

작성해주신 코드 중 일부를 예로, 이름의 최대 문자열 길이를 100으로 설정해두고, 여기서 검증을 하는데 이름의 최대 문자열 길이는 누구만 알고 있으면 되는 정보일까요? Book 객체만 알고 있으면 되는 정보겠죠?

그렇다면 유효성 검증은 어디서 이루어져야 하는 걸까요? Book? 아니면 Book 외부에서 따로? 각 도메인에만 귀속되어야 하는 지식이 외부로 넘어가게 된다면 개발 시 고려해야 할 범위 또한 넓어지게 됩니다. 

잘만하면 Validator 라는 클래스. 없앨 수 있을 것 같지 않나요~?

2023-10-03 17:38 UTC, moosongsong commented on src/main/java/org/example/server/entity/Book.java
> +/* Q. 날짜는 보통은 DB에 저장할 때 어떤 형식으로 저장하는지 궁금합니다! */
LocalDateTime, Long 이렇게 두가지 형태로 저장하고 있습니다. 범위 검색이 잦은 데이터의 경우 Long으로  처리하고 있어요~

추가) 질문은 코드에 남기는 것보다 comment로 남겨주시면 좋을 것 같아요~

2023-10-03 17:38 UTC, moosongsong commented on src/main/java/org/example/server/entity/Book.java
> +    public String toString() {
toString 오버라이드 한 것 좋아요 👍 다만 나중에 로그를 찍어야 할 때 toString이 call 되는데, 이때 오버라이딩 된 toString의 형태로 로그가 찍힐 것 같은데 의도하신 상황이 맞을까용?

2023-10-03 17:38 UTC, moosongsong commented on src/main/java/org/example/server/entity/BookState.java
> +    private final ServerException statusException;
Exception 자원 재사용성 높인 것 GOOD 👍

2023-10-03 17:38 UTC, moosongsong commented on src/main/java/org/example/server/exception/BookNotFoundException.java
> +public class BookNotFoundException extends ServerException {
ServerException 으로 그룹화 한 것 Good 👍

2023-10-03 17:38 UTC, moosongsong commented on src/main/java/org/example/server/repository/Repository.java
> +    그리고 실제 스프링을 사용하는 서버에서는 중간에 서버가 오류로 인해 중단될 경우, 일정 시간이 지난 후 업데이트 되는 데이터들은 어떻게 처리를 하는지도 궁금합니다.
> 3. 제대로 구현하려면 Thread를 사용해서 book 상태를 변경하고 업데이트 해야할 것 같은데 실제 서버를 사용할 때 이 기능을 구현한다면 어떤 방식으로 구현하는 것이 일반적인지 궁금합니다!
> 서버 단에서 어떻게 관리하는지, 중간에 서버가 멈춘다면 어떤 조치를 취하는지, DB단에서 관리할 수는 없는지 궁금합니다!

이런 비슷한 사례가 제가 작업했던 코드 중에 있는데, 제가 구현했던 방식으로 해당 문제를 풀어본다면

- 반납 완료 시간 저장
- 대여 시도 시, 반납 완료 시간과 정리 시간 더한 값으로 대여 가능 여부 확인

이렇게 구현한 이유는 비지니스 상 정리 시간이 변경될 수 있기 때문에 확장성을 고려하면, 반납 완료 시간을 저장하고 비교하는 형태가 바람직하다가 판단했기 때문인데요.

왜 쓰레드를 사용하지 않았냐, 일단 서버를 하나만 올리는 게 아니라 기본 2개 이상 올리기에 각 서버만 지니고 있는 값을 타 서버에서 공유할 수 없다는 단점 때문☺️

만약에 모든 서버에서 공유해야 하는 값이 필요하다면 Redis와 같은 공통 저장소를 두어 관리합니다. 아니면 기존 DB에서 관리가 가능하다면 상관없구용.

> 그리고 실제 스프링을 사용하는 서버에서는 중간에 서버가 오류로 인해 중단될 경우, 일정 시간이 지난 후 업데이트 되는 데이터들은 어떻게 처리를 하는지도 궁금합니다.

이게 제가 잘 이해한 건지 모르겠는데 서버에서 작업하던 게 오류로 중단된 경우를 말씀하시는 거라면

- API라면 500이 떨어졌을 거기 때문에 아마 클라에서 재요청을 해서 재시도가 가능할 것 같고

일정 시간이 지난 후 업데이트 되는 데이터는 배치 돌리기는 하는데, 
이거 여쭤보신 것 맞나요?

2023-10-03 17:38 UTC, moosongsong commented on src/main/java/org/example/server/service/BookService.java
> +    멘토님들은 어떻게 생각하시는지 궁금합니다! */
일부러 예외를 직접 만들어 던지는 것이 조금은 안정적이지 않은 것 같다는 생각이 드는 이유가 무엇인가요????? 혹시 예외라는 이름 때문에? 너무 궁궁하네용

이미 세희님도 아시겠지만 분기문이 정리됨으로써 가독성이 향상된다는 이점이 있죠? 이 외에도, 동일한 예외에 대해서 일괄처리 가능, 조건에 따른 예외를 미리 던져 버그를 감지하는 등 오히려 안정성에 도움이 되는 방식이라고 생각합니다. ☺️

2023-10-03 17:38 UTC, moosongsong commented on src/test/java/org/example/client/console/ValidatorTest.java
> +class ValidatorTest {
> 제가 작성한 테스트 코드 외에도 더 작성하면 좋을 것 같은 테스트 코드가 있는지 궁금합니다!

테스트는 실패에 대한 테스트도 중요하지만 성공에 대한 테스트 코드도 중요합니다! 

저도 실패 테스트는 다 통과했는데 성공 테스트에서 막혀서 장애를 사전에 막을 수 있었던 경험이 정말 많아요.
성공하는 테스트 시나리오 별로 테스트가 추가되면 좋을 듯 싶어요~

2023-10-03 17:38 UTC, moosongsong commented on src/test/java/org/example/server/service/BookServiceTest.java
> +    static void beforeAll() {
음 각 테스트 마다  테스트 스테이지가 마련되는 것이 아니라, 하위의 모든 테스트들이 같은 데이터를 공유하는 상황으로 보이는데요. 

만약에 다른 테스트에서 공용 데이터 중 하나의 상태값을 변경했다면 테스트가 깨질 수도 있을 것 같은데, 어떻게 구현하면 각 테스트의 독립성을 확보할 수 있을까요?

2023-10-04 00:32 UTC, Sehee-Lee-01 commented on src/main/java/org/example/client/console/MethodConsole.java
> +    public static RequestData scanAndSetBookInfo(IO io) {
넵! 첫 코드리뷰이다보니 걱정되어서 이것저것 적다보니 많아진 것 같습니다! ㅠㅠ
이후 올리는 PR에는 대부분 주석을 지우고 올릴 예정입니다! 말씀해주신 내용 적극 반영하겠습니다! 😊

2023-10-04 00:42 UTC, Sehee-Lee-01 commented on .gitignore
> +<<<<<<< HEAD
충돌이 일어나면 수동으로 남겨야 할 것을 복사/붙여넣기 해서 커밋 했습니다! 원래 vscode에서 기본으로 제공해주는 충돌 해결 툴을 쓰다가 이번에 인텔리제이를 처음 쓰게 되어서 이렇게 하게 되었는데 저런 과정에서 충돌 표시가 남게 된 것 같습니다ㅠㅠ 
앞으로는 더 꼼꼼히 확인하고 인텔리제이 확실히 적응하겠습니다!

그리고 저도 .idea 관련 글을 찾아보니 남겨야한다는 글도 있어서 정말 궁금했는데 알려주셔서 감사합니다! 앞으로는 적극 반영하겠습니다!

2023-10-04 00:52 UTC, Sehee-Lee-01 commented on src/main/java/org/example/client/Client.java
> +    private static final IO io = new IO();
IO를 싱글톤으로 사용하면 다른 구간에서도 전역으로 사용할 수 있을 것 같다는 생각이 들었습니다! 그래서 클라이언트 안에서만 한 번 정의해서 사용할 수 있도록 저렇게 안에 필드로 설정을 했습니다! 
사실 IO도 싱글톤으로 구현하고 Client에서만 사용하도록 코드를 작성하면 비슷한데, 싱글톤에 대한 이해가 조금 부족했던 것 같습니다! 사실 과제 할 때 저 부분에 대한 해답을 찾기가 조금 어려워서 저 부분에서 많이 방황했던 것 같습니다ㅠㅠ

2023-10-04 01:00 UTC, Sehee-Lee-01 commented on src/main/java/org/example/packet/Request.java
> +public class Request {
넵! 좀 더 신경써서 작성하겠습니당!!!

2023-10-04 01:09 UTC, Sehee-Lee-01 commented on src/main/java/org/example/client/console/Validator.java
> +            public String getMessage() {
지금 바로 이해했습니다... 제가 추상 클래스로 익명클래스 정의해서 인스턴스를 만드는 것하고 헷갈렸습니다... 이 부분도 바로 수정하겠습니다!!!!

2023-10-04 01:13 UTC, Sehee-Lee-01 commented on src/main/java/org/example/server/repository/Repository.java
> +    그리고 실제 스프링을 사용하는 서버에서는 중간에 서버가 오류로 인해 중단될 경우, 일정 시간이 지난 후 업데이트 되는 데이터들은 어떻게 처리를 하는지도 궁금합니다.
넵! 제가 딱 궁금해하던 답변이었습니다! 감사합니다! 
사실 반납 5분 후 시간을 저장하면서 찜찜한 느낌이 있었는데 좋은 방안 말씀해주셔서 감사합니다! :)

2023-10-04 01:16 UTC, Sehee-Lee-01 commented on src/main/java/org/example/server/service/BookService.java
> +    멘토님들은 어떻게 생각하시는지 궁금합니다! */
딱 멘토님이 말씀해주신 것처럼 "예외"라는 이름 때문에 그랬습니다! 뭔가 사용하면 편할 것 같은데 예외를 일부러 만들어서 보내는 것이니 스스로 고민이 많이 되었던 부분이었습니다! 
알려주셔서 감사합니당!!🤩

2023-10-04 01:17 UTC, Sehee-Lee-01 commented on src/test/java/org/example/client/console/ValidatorTest.java
> +class ValidatorTest {
넵! 성공 테스트도 꼼꼼히 적도록 하겠습니다!

2023-10-04 01:19 UTC, Sehee-Lee-01 commented on src/main/java/org/example/server/exception/BookNotFoundException.java
> +public class BookNotFoundException extends ServerException {
😊

2023-10-04 01:22 UTC, Sehee-Lee-01 commented on src/test/java/org/example/server/service/BookServiceTest.java
> +    static void beforeAll() {
앗 혹시 BeforeAll이 아니라 BeforeEach를 사용하면 될 것 같은데 맞을까요?

2023-10-04 01:25 UTC, Sehee-Lee-01 commented on src/main/java/org/example/client/console/MethodConsole.java
> +    public static RequestData scanAndSetBookInfo(IO io) {
PR 코멘트 모두 확인했습니다! 
늦은 시간에 작성해주셔서 피곤하셨을텐데 꼼꼼한 피드백 해주셔서 너무 너무 감사합니다! 😭😭

2023-10-04 01:33 UTC, Sehee-Lee-01 commented on src/main/java/org/example/client/console/Validator.java
> +            public String getMessage() {
앗 바로 이해했습니다! 제가 한 것은 Exception detailMessage의 본질적인 값을 바꾸는 것이 아니라 그저 getMessage의 리턴 값만 바꿔서 주는 것이네요! 예외 만드는 데에 익숙하지 않아서 그랬던 것 같습니다 ㅠㅠ 
하나 다시 배워갑니다!

2023-10-09 03:05 UTC, SangHyunGil requested changes
반영해주시느라 고생많으셨어요! 
몇 가지 코멘트 남겼어요.

---
`refactor: 네이밍 수정 및 bookDto 용도별로 분리`
위 커밋에서 실제로는 3가지 작업이 발생한 것 같아요.
- 상수로 표현한 잘못된 네이밍 변경
- DTO 분리
- get/find 네이밍 수정

추후에 실제 커밋을 진행할때는 각각을 분리해서 진행해봐도 좋을 것 같아요 ㅎㅎ

2023-10-09 03:05 UTC, SangHyunGil commented on src/main/java/org/example/client/console/ModeRequester.java
> +        private static final String BASIC_QUESToutN = "Q. 모드를 선택해주세요." + System.lineSeparator() + String.join(System.lineSeparator(), Stream.of(values()).map(type -> type.NUMBER + ". " + type.NAME).t
네이밍 수정 부탁드려요 😄

2023-10-09 03:05 UTC, SangHyunGil commented on src/test/java/org/example/client/console/ValidatorTest.java
>          in = mock(In.class);
Validator에 더이상 In에 대한 의존성을 가져가지 않으니 제거해도 좋을 것 같아요.

2023-10-09 03:05 UTC, SangHyunGil commented on src/test/java/org/example/client/console/ValidatorTest.java
>          when(in.scanLine()).thenReturn(input);
마찬가지로 불필요한 mocking은 제거해도 될 것 같아요.

2023-10-09 03:05 UTC, SangHyunGil commented on src/test/java/org/example/client/console/ValidatorTest.java
> +        Assertions.assertEquals(validator.scanAndValidateString(in.scanLine()), input);
더이상 in에 대한 scanLine을 통해 처리하는 것이 아닌 상수값을 직접 입력해서 테스트해보면 될 것 같아요.
각 메서드에서 검증하는 케이스들이 다양하게 존재할 수 있을 것 같은데 이럴땐 @ParameterizedTest를 이용해보면 좋습니다. 👍

2023-10-09 03:05 UTC, SangHyunGil commented on src/test/java/org/example/server/repository/RepositoryTest.java
> +class RepositoryTest {
현재 Repository에 대한 구현체는 총 2개인데 하나의 테스트 파일로 작성된 것 같아요.
각 구현체에 대한 테스트를 분리해서 작성하면 좋을 것 같아요.
나중에는 더 다양한 테스트를 작성해보면 좋겠네요 👍

2023-10-09 04:16 UTC, Sehee-Lee-01 commented on src/main/java/org/example/client/console/ModeRequester.java
> +        private static final String BASIC_QUESToutN = "Q. 모드를 선택해주세요." + System.lineSeparator() + String.join(System.lineSeparator(), Stream.of(values()).map(type -> type.NUMBER + ". " + type.NAME).t
헉 저번에 잘 못쓰고 커밋이 꼬여서 그런 것 같은데 커밋할 원본 브랜치에서 [여기](https://github.com/Sehee-Lee-01/java-library-management/blob/04efdb339d156886b6a3b4901639c889b5cf4c18/src/main/java/org/example/client/console/ModeRequester.java#L43)에는 수정 되어있습니다!
제가 머지나 커밋을 잘못한 것 같습니다...

2023-10-09 04:17 UTC, Sehee-Lee-01 commented on src/test/java/org/example/client/console/ValidatorTest.java
>          in = mock(In.class);
앗 코드가 많다 보니 확인을 못했습니다! 바로 반영하겠습니다! 감사합니다!

2023-10-09 04:20 UTC, Sehee-Lee-01 commented on src/test/java/org/example/server/repository/RepositoryTest.java
> +class RepositoryTest {
넵! 이번에 처음 써봐서 제대로 써보지 못했던 것 같습니다! ㅠㅠ 나중에는 더 연습해보겠습니다!

2023-10-09 04:26 UTC, Sehee-Lee-01 commented on src/main/java/org/example/client/console/ModeRequester.java
> +        private static final String BASIC_QUESToutN = "Q. 모드를 선택해주세요." + System.lineSeparator() + String.join(System.lineSeparator(), Stream.of(values()).map(type -> type.NUMBER + ". " + type.NAME).t
커밋을 좀 더 신경써서 나누겠습니다! 전체적으로 수정하다보니 다른 커밋에 수정 내용이 들어간 것 같습니다ㅠㅠㅠ

2023-10-09 04:26 UTC, Sehee-Lee-01 commented on src/test/java/org/example/client/console/ValidatorTest.java
>          when(in.scanLine()).thenReturn(input);
바로 반영하겠습니다!

2023-10-09 04:34 UTC, Sehee-Lee-01 commented on src/test/java/org/example/client/console/ValidatorTest.java
> +        Assertions.assertEquals(validator.scanAndValidateString(in.scanLine()), input);
좋은 정보 감사합니다!! 바로 반영하겠습니다!

2023-10-10 13:34 UTC, SangHyunGil approved these changes
그동안 과제 수행해주시고 반영해주시느라 고생많으셨습니다
요구사항의 변화에 대한 유연한 대응에서 프로토콜 변화에 대한 유연한 대응까지 많은 고민을 해주셨었는데요.
이번 고민들 그리고 리뷰하면서 구두로 얘기나누었던 부분들을 통해 많은걸 얻어가셨으면 해요!
이제 머지해주셔도 좋습니다!

2023-10-10 13:34 UTC, SangHyunGil commented on src/test/java/org/example/client/console/ValidatorTest.java
> +    void validateNameAndAuthor(String input) {
👍

2023-10-10 13:34 UTC, SangHyunGil commented on src/main/java/org/example/server/service/BookService.java
> +        repository.save(book);
👍

2023-10-10 13:50 UTC, merged