[5기 - 송인재] 1~2주차 과제: 도서 관리 어플리케이션 제출합니다.
prgrms-be-devcourse/java-library-management pull request #25
Opened 2023-10-01 03:39 UTC by IjjS

## 📌 과제 설명 
* 사용자와의 소통을 통해 도서를 등록/관리/저장하는 도서 관리 어플리케이션입니다.
* 실제 `json`파일을 저장하는 일반 모드와 인메모리에 저장하는 테스트 모드가 있습니다.
## 👩‍💻 요구 사항과 구현 내용 
#### 요구사항
* 신규 도서 등록
* 도서 조회
* 도서 제목으로 검색
* 도서 상태 관리 (대여 가능, 대여중, 분실중, 도서 정리중)
* 도서 삭제
* 도서 정보 저장

#### 구현 내용
* book
  * 기능 별로 서비스를 매핑하고, 비즈니스 로직을 실행합니다.

* config
  * 객체 들의 인스턴스 생성과 주입을 합니다.

* console
  * 필요한 정보를 출력하고 입력을 받아들이며 사용자와 소통을 하는 `CommunicationAgent`가 있습니다.

* exception
  * 커스텀 예외들과 예외 메세지들의 `Enum`이 있습니다.

* file
  * 파일의 입출력을 관리하는 파일 매니저가 있습니다.

* menu
  * 메뉴들의 `Enum`, 메뉴를 선택해 메뉴를 반환하는 `MenuSelector`, 그리고 메뉴를 실행시키는 역할을 하는 `MenuExecuter`가 있습니다.

* mode
  * 모드들의 `Enum`, 그리고 모드를 선택해 모드를 반환하는 `ModeSelector`가 있습니다.

* timer
  * 도서 번호와 해당 도서 정리 시작 시간을 기록하는 타이머가 있습니다. 
  * 타이머들을 생성/삭제 시키는 타이머 매니저가 있습니다.
  * `books.json`에 도서 정리 시작 시간을 포함시키려 했는데, `null`이 포함되는게 싫어서 타이머를 따로 파일로 저장했습니다.

## ✅ PR 포인트 & 궁금한 점
1. 객체지향에 신경쓰려고 했는데, SOLID를 온전히 지키지 못한 것 같습니다. 그러면서도 동시에, 클래스가 너무 많은가 싶기도 합니다. 이에 대한 조언을 해주시면 감사하겠습니다.
2. 레포지토리 부분에서 일반 모드와 테스트 모드가 기능적으로 거의 차이가 없습니다. 인터페이스에 디폴트 메소드로 빼자니, 레포지토리 구현체가 데이터들을 들고있는게 아니라, 데이터들을 외부에서 주입해야 할 것 같고 디폴트 메소드도 많아질 것 같아서 일반 모드와 테스트 모드 따로 구현했지만, 거의 비슷합니다. 일반 모드 레포지토리가 테스트 모드 레포지토리를 상속하게 할까 했지만, 테스트 모드 레포지토리에 로드된 책들의 접근 제한자를 바꿔야 하는게 별로일 것 같고, 상속의 의미도 떨어지는 것 같아서 그러지 않았습니다. 이럴 땐 어떻게 하면 좋을지 궁금합니다.
3. 처음 이렇게 객체지향을 신경쓰며 구현해봤습니다. 고민도 길어지고 많이 부족하지만, 궁금했던 점들 말고도 조언을 주시면 감사히 받겠습니다.

2023-10-01 13:49 UTC, aegis1920 requested changes
안녕하세요 인재님! 빙봉입니다 🙂 

코멘트 드렸으니 확인해주세요! 추후 PR에는 테스트 코드도 포함해주세요~

2023-10-01 13:49 UTC, aegis1920 commented on build.gradle
> +    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.8.1'
api와 engine을 모두 포함하는 `org.junit.jupiter:junit-jupiter:5.8.1`은 어떠신가요?

2023-10-01 13:49 UTC, aegis1920 commented on settings.gradle
> +rootProject.name = 'Librarian'
프로젝트 네이밍의 경우 모듈명과 동일한 컨벤션으로 가져가는 것 같습니다. (참고 [링크](https://docs.gradle.org/current/userguide/multi_project_builds.html#sec:adding_subprojects), 여기서 만약 적용한다면 librarian이 될 것 같네요)

2023-10-01 13:49 UTC, aegis1920 commented on src/main/java/com/programmers/app/mode/ModeSelector.java
> +                }
java 14에 나온 enhanced switch를 사용해도 좋겠네요!
```
                return switch (modeCode) {
                    case 1 -> Mode.NORMAL;
                    case 2 -> Mode.TEST;
                    default -> throw new InvalidInputException();
                };
```

2023-10-01 13:49 UTC, aegis1920 commented on src/main/java/com/programmers/app/mode/Mode.java
> +    private final String modeString;
modeString이라는 이름보다는 보여주기 용 필드니까 displayName이라는 변수명은 어떠신가요?

2023-10-01 13:49 UTC, aegis1920 commented on src/main/java/com/programmers/app/config/AppConfig.java
> +    public static final int MINUTES_FOR_BOOK_ARRANGEMENT = 5;
- AppConfig가 아닌 Timer 클래스에 있어야 하는 거 아닐까요?
- 만약 Timer로 옮긴다면 private 이어도 될 것 같습니다!

2023-10-01 13:49 UTC, aegis1920 commented on src/main/java/com/programmers/app/menu/MenuExecuter.java
> +public class MenuExecuter {
```suggestion
public class MenuExecutor {
```

2023-10-01 13:49 UTC, aegis1920 commented on src/main/java/com/programmers/app/menu/Menu.java
> +public enum Menu {
이쪽 [코드](https://github.com/prgrms-be-devcourse/java-library-management/blob/72e25a03bf2e9a45cd0a6bd08ddb72c30c5a2240/src/main/java/com/programmers/app/console/CommunicationAgent.java#L91-L97)를 보고 enum Mode에 displayName 필드를 넣으면 어떨까 했습니다. 여기서 `[System] 도서 등록이 완료되었습니다`와 같은 문구가 들어가는 게 아니고 enum Menu가 메뉴 이름을 나타내는 속성을 갖는 것이라 메뉴의 역할이라고 생각들기도 하고요. 인재님 생각은 어떠신가요?

2023-10-01 13:49 UTC, aegis1920 commented on src/main/java/com/programmers/app/book/service/BookService.java
> +public interface BookService {
BookService는 인터페이스가 없어도 되지 않을까요? 다형성을 활용하는 부분도 없고 class로 만들어도 충분할 것 같습니다.

2023-10-01 13:49 UTC, aegis1920 commented on src/main/java/com/programmers/app/book/service/BookServiceImpl.java
> +    public boolean updateArrangementCompleted() {
- 반환 값으로 boolean을 리턴하고 있다면 isXX로 함수명을 작성해주시는 것이 관례입니다.
- 그리고 함수명도 update시 어떤 것을 update하고 있는지 명확하게 적어주시는 것이 좋습니다.

2023-10-01 13:49 UTC, aegis1920 commented on src/main/java/com/programmers/app/book/service/BookServiceImpl.java
> +        AtomicBoolean changed = new AtomicBoolean(false);
AtomicBoolean을 사용하신 이유가 있을까요?

2023-10-01 13:49 UTC, aegis1920 commented on src/main/java/com/programmers/app/book/domain/BookStatus.java
> +    ON_LOAN("대여중"),
- 책을 대여한다고 했을 때 loan이라는 단어를 쓰나요..?
- 이전에 대여하는 것을 borrow라는 용어를 썼다면 여기에서도 동일한 용어로 사용하는 것이 덜 헷갈릴 것 같습니다.

2023-10-01 13:49 UTC, aegis1920 commented on src/main/java/com/programmers/app/book/dto/BookRequest.java
> +    private int totalPages;
final을 붙여주면 더 좋을 것 같습니다!

2023-10-01 13:49 UTC, aegis1920 commented on src/main/java/com/programmers/app/book/domain/Book.java
> +    private int totalPages;
여기도 final을 붙이면 더 좋을 것 같습니다!

2023-10-01 13:49 UTC, aegis1920 commented on src/main/java/com/programmers/app/book/domain/Book.java
> +    public void setStatus(BookStatus bookStatus) {
객체 상태 변경 가능성을 줄이기 위해 setter를 사용하지 않고 새로운 객체를 생성하는 건 어떨까요?

2023-10-01 13:49 UTC, aegis1920 commented on src/main/java/com/programmers/app/book/domain/Book.java
> +    public String toString() {
현재 요구사항에서는 이대로도 상관없을 것 같은데요. 객체의 상태를 toString()으로 오버라이딩하고자 한다면 유지보수를 위해 포맷을 잘 정의해줘야하는 것도 기억해주면 좋을 것 같습니다. (lombok의 `@toString`을 사용하는 것처럼)

2023-10-01 13:49 UTC, aegis1920 commented on src/main/java/com/programmers/app/book/domain/Book.java
> +        return status.equals(BookStatus.ON_ARRANGEMENT);
enum 끼리는 주소값이 같아 `==`을 써도 무방합니다.

2023-10-01 13:49 UTC, aegis1920 commented on src/main/java/com/programmers/app/book/service/BookServiceImpl.java
> +        timerManger.add(new Timer(bookNumber, LocalDateTime.now()));
책이 반납된 시간은 데이터로서도 의미가 클 것 같은데요. timeManager를 둘 필요 없이 Book 도메인에 반납시간이 포함되는 건 어떻게 생각하실까요?

2023-10-01 13:49 UTC, aegis1920 commented on src/main/java/com/programmers/app/book/service/BookServiceImpl.java
> +    public boolean updateArrangementCompleted() {
- 이렇게 된다면 조회할 때만 상태가 변경되는 거 아닐까요? (반납 처리를 하고 난 뒤에 조회를 하지 않고 대여를 하면 이 메서드가 실행되지 않아서 계속 정리중 상태가 되는 거 아닐까요?)
- e.g. 1번 책 대여 -> 1번 책 반납 -> 5분 뒤 1번 책 대여 불가 (조회를 하지 않았으므로)

2023-10-01 13:49 UTC, aegis1920 commented on src/main/java/com/programmers/app/console/ConsoleReader.java
> +        }
요 부분은 왜 있나요?

2023-10-01 13:49 UTC, aegis1920 commented on src/main/java/com/programmers/app/file/BookFileManager.java
> +        try {
FileWriter를 타고 들어가보면 AutoCloseable이 있어 try with resource를 사용할 수 있는 걸로 보입니다. 이용해보시죠!

2023-10-01 13:49 UTC, aegis1920 commented on src/main/resources/books.json
> +]
마지막 줄 개행(EOF의 개행)에 신경써주시면 좋을 것 같습니다!
참고로 유닉스 시스템의 표준이 한 줄에 대한 정의가 개행으로 끝납니다. ([링크](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_206))

intellij에서 아래 설정으로 자동으로 넣어줄 수 있습니다 🙂 

<img width="430" alt="image" src="https://github.com/prgrms-be-devcourse/java-library-management/assets/22311557/2fee0f24-e557-454a-a24d-e9d41db11b3d">

2023-10-01 13:49 UTC, aegis1920 commented on src/main/java/com/programmers/app/book/controller/BookControllerImpl.java
> +    }
```suggestion
    @Override
    public void deleteBook() {
        printCatchException(() -> {
            bookService.deleteBook(communicationAgent.instructDelete());
            communicationAgent.printOperationCompleted("삭제");
        });
    }

    public void printCatchException(Runnable runnable) {
        try {
            runnable.run();
        } catch (RuntimeException e) {
            communicationAgent.printError(e);
        }
    }
```

이런 식으로 중복 코드를 줄일 수도 있겠네요

2023-10-02 01:23 UTC, IjjS commented on build.gradle
> +    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.8.1'
옙!

2023-10-02 01:23 UTC, IjjS commented on settings.gradle
> +rootProject.name = 'Librarian'
감사합니다!

2023-10-02 01:24 UTC, IjjS commented on src/main/java/com/programmers/app/mode/Mode.java
> +    private final String modeString;
명확한 네이밍이라고 생각합니다. 수정하겠습니다!

2023-10-04 04:03 UTC, IjjS commented on src/main/java/com/programmers/app/config/AppConfig.java
> +    public static final int MINUTES_FOR_BOOK_ARRANGEMENT = 5;
옙!!

2023-10-04 04:05 UTC, IjjS commented on src/main/java/com/programmers/app/menu/Menu.java
> +public enum Menu {
동의합니다! 수정하겠습니다

2023-10-04 04:09 UTC, IjjS commented on src/main/java/com/programmers/app/book/domain/BookStatus.java
> +    ON_LOAN("대여중"),
제 경험으로는 사용하긴 했습니다. 행위보단 상태나 short loan같은 조건을 나타낼 때 사용했었습니다.
하지만 말씀대로 여기서는 `BORROWED`로 고치는 것이 더 낫다고 생각합니다

2023-10-04 04:12 UTC, IjjS commented on src/main/java/com/programmers/app/book/domain/Book.java
> +    public void setStatus(BookStatus bookStatus) {
setter를 최대한 사용 안하려고 신경 써보긴 했는데, 이 부분이 저도 좀 걸렸습니다. 말씀대로 업데이트된 status로 새로운 객체를 생성하는 메소드를 `Book`에 만들어 필요한 곳에 tell 하도록 하겠습니다!

2023-10-04 04:15 UTC, IjjS commented on src/main/java/com/programmers/app/book/domain/Book.java
> +    public String toString() {
안일하게 생각했던 부분인 것 같습니다. 감사합니다!

2023-10-04 04:17 UTC, IjjS commented on src/main/java/com/programmers/app/book/service/BookServiceImpl.java
> +        timerManger.add(new Timer(bookNumber, LocalDateTime.now()));
null이나 무의미한 데이터가 포함될 수도 있다는 점이 마음에 걸려서 매니저를 따로 뒀었습니다. 하지만 역시 timeManager를 두고 관리하는 것이 과하기도 하단 생각이 들어서,,수정하겠습니다!

2023-10-04 04:21 UTC, IjjS commented on src/main/java/com/programmers/app/book/service/BookServiceImpl.java
> +    public boolean updateArrangementCompleted() {
예 맞습니다. 생각 못 했던 부분이었는데, 레포지토리에서 `findByBookNumber`에서도 업데이트를 시켜주도록 하겠습니다!

2023-10-04 04:22 UTC, IjjS commented on src/main/java/com/programmers/app/console/ConsoleReader.java
> +        }
실수로 아무것도 안치고 엔터 쳤을 때, 입력을 다시 받으려고 넣었습니다

2023-10-04 04:22 UTC, IjjS commented on src/main/java/com/programmers/app/file/BookFileManager.java
> +        try {
앗 처음 알았습니다.. 감사합니다!!!

2023-10-04 04:24 UTC, IjjS commented on src/main/resources/books.json
> +]
설정은 해놨는데, 리소스에 넣어둔 json파일들만 적용이 안됐던 것 같습니다..신경쓰겠습니다!! 감사합니다

2023-10-04 04:25 UTC, IjjS commented on src/main/java/com/programmers/app/book/controller/BookControllerImpl.java
> +    }
앗 이렇게 할 수 있겠네요!! 감사합니다!!!

2023-10-04 04:33 UTC, IjjS commented
코멘트 주신 것에 답변을 다 달았었는데, Pending으로 있다가 Files Changed에서 제 리뷰를 닫았더니 날아갔습니다..
말씀해주신 피드백들 반영하고 테스트코드 포함해서 리뷰 요청 드립니다!
궁금한 부분들에도 코멘트 남겨 놓겠습니다
감사합니다!!

2023-10-04 04:38 UTC, IjjS commented on src/main/java/com/programmers/app/config/AppConfig.java
> +    private static final String FILE_PATH = "src/main/resources/books.json";
상수가 `FILE_PATH`와 Book에 있는 `MINUTES_FOR_BOOK_ARRANGEMENT`이렇게 두 개 있는데, 한 군데로 모아 놓는 것이 나은 선택인지 궁금합니다

2023-10-04 04:41 UTC, IjjS commented on src/main/java/com/programmers/app/mode/ModeSelector.java
> +                }
사실 저번에 java 17로 바꾸다가 자꾸 에러가 떠서 11을 사용하고 있었습니다..! 얼른 해결해서 업그레이드하고 적용시키겠습니다!!

2023-10-04 04:55 UTC, IjjS commented on src/main/java/com/programmers/app/menu/Menu.java
> +public enum Menu {
추가적으로 질문 있습니다!
`MenuSelector`와 `ModeSelector`가 비슷해서 Selectable이라는 인터페이스를 만들어 구현체를 두거나 함수형 인터페이스로 활용하는 것이 괜찮지 않을까?라는 생각이 들었습니다. 이게 괜찮은 생각인지 궁금하고, 만약 만든다면 패키지를 selectable 패키지를 만들어 하위에 Menu와 Mode를 두는게 괜찮은지 궁금합니다

2023-10-04 06:42 UTC, cloudwi commented on src/main/java/com/programmers/LibrarianApplication.java
> +        app.run();
LibrarianApplication 안에 app이라는 이름은 의도를 나타내는 이름은 아닌것 같아요.

app >>> LibrarianApplication 이런 느낌이 강하고 

app.run() 은 무엇을 실행시키는지 명확하게 알 수 없다고 생각해요.

2023-10-04 06:43 UTC, cloudwi commented
먼저 과제 하신다고 고생많으셨어요. !!!

2023-10-04 08:03 UTC, cloudwi commented on src/main/java/com/programmers/app/book/controller/BookControllerImpl.java
> +        System.exit(0);
프로그램을 종료하는 방법을 조금 더 생각했으면 좋겠어요.

System.exit(0) 는 다른 프로그램에 문제가 발생할 수 있어요.

2023-10-04 08:03 UTC, cloudwi commented on src/main/java/com/programmers/app/book/controller/BookControllerImpl.java
> +        printCatchException(() -> communicationAgent.printFindResult(bookService.findAllBooks()));
가독성을 생각한다면 bookService.findAllBooks() 부분을 변수로 빼서 사용하시는게 좋아보여요.

2023-10-04 08:03 UTC, cloudwi commented on src/main/java/com/programmers/app/book/controller/BookControllerImpl.java
> +        printCatchException(() -> communicationAgent.printFindResult(bookService.findAllBooks()));
예시로 이런 느낌일 것 같아요.
어떤것이 더 좋나요?

```
@Override
    public void findAllBooks() {
        printCatchException(() -> {
            List<Book> allBooks = bookService.findAllBooks();
            communicationAgent.printFindResult(allBooks);
        });
    }
```

2023-10-04 08:03 UTC, cloudwi commented on src/main/java/com/programmers/app/book/repository/NormalBookRepository.java
> +        return Optional.of(foundBooks);
List를 생성하지고 해당 리스트를 Optional에 담아서 처리하는 이유가 있을까요?

2023-10-04 08:03 UTC, cloudwi commented on src/main/java/com/programmers/app/book/repository/NormalBookRepository.java
> +        return Optional.of(foundBooks);
제가 보이기에는 List 자체는 존재하지만 List 속에 아무런 값이 없을때를 대비한 것으로 보이는데 
여기서 처리가 가능할까요?

2023-10-04 12:11 UTC, IjjS commented on src/main/java/com/programmers/LibrarianApplication.java
> +        app.run();
맞습니다. 세세한 네이밍을 놓치게 되는 것 같습니다..`librarianSystem.run()`이나 `librarian.start()`등으로 바꾸겠습니다!

그리고 별개로 궁금한게 있습니다.
App이나 oooSystem같이 run하라는 메세지를 전달 받는 객체 대신, 메인 함수에서 직접 로직이 있다면 그게 좋지 못한 것인지, 좋지 못한 것이라면 메인 함수가 하는 일이 많아져서 인지 궁금합니다..!

2023-10-04 12:15 UTC, IjjS commented on src/main/java/com/programmers/app/book/controller/BookControllerImpl.java
> +        System.exit(0);
생각이 짧았습니다! 루프를 벗어나 종료시키도록 하겠습니다

2023-10-04 12:18 UTC, IjjS commented on src/main/java/com/programmers/app/book/controller/BookControllerImpl.java
> +        printCatchException(() -> communicationAgent.printFindResult(bookService.findAllBooks()));
맞습니다. 가독성을 생각하며 더 세세하게 신경 쓰도록 노력하겠습니다!

2023-10-04 12:23 UTC, IjjS commented on src/main/java/com/programmers/app/book/repository/NormalBookRepository.java
> +        return Optional.of(foundBooks);
emptyList를 반환하기보단, 서비스 레이어에서 if-else statement보단 `orElseThrow()`로 가독성이 더 나아질 수 있다고 생각해서 Optional로 처리했습니다. Optional을 이용하기보단 emptyList를 반환하거나, 다른 방식으로 처리하는게 나을까요?

2023-10-07 10:04 UTC, aegis1920 commented on src/main/java/com/programmers/app/menu/Menu.java
> +public enum Menu {
메뉴 선택이나 모드 선택 말고도 다른 의미의 선택지가 나온다면 그 인터페이스를 활용할 수 있기에 좋아보이나 개인적으로는 지금 효용성이 없다고 생각들어서 만들진 않을 것 같습니다. 만약 패키지를 만든다고 했을 때는 selector 라는 식으로 패키지를 만들어서 활용하면 될 것 같아요. (selector 하위에 mode와 menu 패키지, 도서 관리 어플리케이션에 선택할 수 있는 게 있다라는 느낌으로)

2023-10-07 10:05 UTC, aegis1920 commented on src/main/java/com/programmers/app/book/domain/BookStatus.java
> +    ON_LOAN("대여중"),
아.. 그렇군요 제가 오히려 몰랐던 부분이 있었네요 🙇 네넵! 일관성을 위해서 loan이든 borrow든 하나로 맞춰주는 게 나아보입니다.

2023-10-07 10:07 UTC, aegis1920 commented on src/main/java/com/programmers/app/console/ConsoleReader.java
> +        }
오 그렇군요..? 그러면 이런 식으로 수정해봐도 좋을 것 같습니다.

```suggestion
        while (input.strip().isBlank()) {
            input = sc.nextLine();
        }
```

2023-10-07 10:10 UTC, aegis1920 commented on src/main/java/com/programmers/app/config/AppConfig.java
> +    private static final String FILE_PATH = "src/main/resources/books.json";
구두로 말씀드렸다시피 직관적으로 바로 알아보기 쉽게끔 가급적이면 관련된 파일에 두는 게 좋습니다. 아주 큰 범위로 BookConstant 라는 클래스 파일 안에 넣어둬도 되긴 하나 이러면 너무 광범위하게 BookConstant라는 클래스가 모든 곳에 의존되게 될 수도 있습니다.

2023-10-07 22:42 UTC, IjjS commented on src/main/java/com/programmers/app/menu/Menu.java
> +public enum Menu {
이해됐습니다. 확장 가능성이란 것도 상황을 보며 결정해야 하는 것을 신경써야겠군요..감사합니다!!

2023-10-07 22:44 UTC, IjjS commented on src/main/java/com/programmers/app/console/ConsoleReader.java
> +        }
의미가 명확해진다고 생각합니다. 감사합니다!

2023-10-08 20:51 UTC, cloudwi commented on src/main/java/com/programmers/LibrarianApplication.java
> +        app.run();
프로젝트 이름부터 너무 명확하게 나와 있어서 인재님의 말씀처럼 main에서 실행하는 것도 좋다고 생각해요.

2023-10-08 20:52 UTC, cloudwi commented on src/main/java/com/programmers/app/book/repository/NormalBookRepository.java
> +        return Optional.of(foundBooks);
넵 그게 좋다고 생각합니다.

2023-10-09 10:56 UTC, aegis1920 approved these changes
피드백 끝까지 반영하시느라 고생 많으셨습니다! 👍 
아주 약간의 피드백 추가했어요! 과제는 여기서 머지하겠습니다!
이후에 궁금한 점이 있으시면 DM주시거나 코멘트 따로 남겨주세요!

2023-10-09 10:56 UTC, aegis1920 commented on src/test/java/com/programmers/app/LibrarianTest.java
> +    final BookRepository bookRepository = new TestBookRepository();
테스트 모드에 대해서 테스트 코드를 작성하신 이유는 일반 모드와 똑같다고 생각하셔서 테스트 모드에 대해서만 작성하신 걸까요?

2023-10-09 10:56 UTC, aegis1920 commented on src/test/java/com/programmers/app/LibrarianTest.java
> +    @DisplayName("도서 반납 후 5분이 지난 도서 대여에 성공한다.")
👍 👍

2023-10-09 10:56 UTC, aegis1920 commented on src/test/java/com/programmers/app/LibrarianTest.java
> +        sleep(1000);
이 테스트를 실행할 때마다 1초동안 sleep되어야하는데요. 이런 sleep없이 테스트하는 방법을 고민해보는 것도 좋을 것 같네요.

2023-10-09 10:56 UTC, merged