[5기 - 김현우] 1~2주차 과제: 도서 관리 어플리케이션 코드 리뷰 요청드립니다!
prgrms-be-devcourse/java-library-management pull request #30
Opened 2023-10-02 00:46 UTC by ASak1104

## 📌 과제 설명 

- **도서 관리 애플리케이션**
- 도서 등록, 대여, 반납, 분실, 삭제 기능 지원
- 테스트 모드와 일반 모드 지원
	- 테스트 모드 : 실행 도중 생성한 도서 정보를 종료 시 유지하지 않음
	- 일반 모드 : 이전 도서 정보를 불러오고 저장할 수 있음

## 👩‍💻 구현 내용 

#### 프로젝트 구조
![프로젝트 클래스 다이어그램](https://github.com/prgrms-be-devcourse/java-library-management/assets/31983961/13bd7e3e-2e84-4fe2-ad08-f80a35f8a94f)

1. **LibrarySystem**
	- 도서 관리 애플리케이션
	- 사용자의 입력을 받고 요청을 수행한 결과를 출력
	- 출력하는 결과는 LibraryMessage Enum에 정의됨

2. **Reader**
	- 사용자의 입력을 읽는 역할
	- 구현체는 ConsoleBufferedReader
		- EOF 같은 값을 읽었을 때 EmptyInputException을 반환

3. **Writer**
	- 결과를 출력하는 역할
	- 구현체는 ConsoleSystemWriter

4. **DataManager**
	- 애플리케이션을 시작할 때 데이터를 불러오고 종료할 때 데이터를 저장하는 역할
	- 구현체는 EmptyDataManager, JSONDataManager

5. **BookManager**
	- 도서에 대한 모든 요청을 처리
	- 수행 결과는 문자열로 반환
	- 수행 결과는 BookManagerMessage Enum에 정의됨
	- 구현체는 ListBookManager

6. **LibraryMode**
	- 도서관 애플리케이션의 모드를 정의한 Enum
	- LibrarySystem에서 사용하는 DataManager, BookManager 인터페이스의 구현체를 생성 및 반환
	- Enum value에 따라 반환하는 구현체는 다를 수 있음

## ✅ PR 포인트 & 궁금한 점 

1. 첫 자바 프로젝트여서 그런지 전체적인 **프로젝트 구조**를 계속해서 생각하면서 코드를 작성했지만 엉성한 부분이 상당히 많은 것 같습니다. 프로젝트에서 사용하는 인터페이스, 클래스, 메서드, 필드 명 등 **기본적인 내이밍**과 **패키지를 나누는 기준** 같은 것이 모호해서 이 부분에 대한 피드백을 부탁드리고 싶습니다!

2. 코드를 작성하면서 커밋을 하다보니 특정 커밋은 많은 파일이 수정되고 브랜치와 커밋 내용이 조금 엇나가는 등 버전 컨트롤을 위해 깃을 사용하기 보다는 **개발 일기를 쓰는 느낌으로 커밋**을 한 것 같습니다. 명확하게 커밋 단위를 나누고 좋은 메시지를 작성하는 등 **올바른 버전 관리**를 위해 깃을 사용하려면 **어떤 부분을 개선**해야할지 알고 싶습니다!

3. 설계를 하고 기능을 개발하는 과정에서 **역할 분배**에 대한 고민을 정말 많이 했습니다. 그 중 계속해서 고민했던 것은 'BookManager가 도서 관리와 메시지 반환이라는 **2가지의 책임**을 지고 있다는 것을 **분리할 것이냐**' 였습니다. 중간 계층으로 QueryManager와 같은 클래스를 추가하거나 MVC 패턴 느낌으로 **리팩토링**을 진행할까 고민했지만 시간 대비 효율, 테스트 용이성, 리팩토링으로 인한 연쇄 수정 등 정확한 판단이 어려워 멘토님의 견해를 묻고 싶습니다. 현재 BookManager이 **정말 좋지 못한 것인지** 그리고 수정해야 한다면 **그 이유와 방향성**이 어떤 것일까요?

4. LibrarySystem이 **Book 클래스에 대한 의존없이** 실행되는 것을 의도한 애플리케이션이지만  `bookManager.init(dataManager.load());`과 같이 실제 List<Book>을 반환하는 메서드를 사용하면서 보이지 않는 의존성이 생기는 등 개선해야 할 부분이 많다고 생각합니다. 아래와 같이 역할을 나누면서 애플리케이션을 개발하고 싶었는데 해당 코드를 어떻게 개선하면 좋을까요? (해당 코드에 코멘트 남기겠습니다!) 
		
		LibrarySystem은 입출력
		DataManager는 파일 로드와 저장
		BookManager는 도서 관리

5. **LibarayMode Enum**은 LibrarySystem에서 사용하는 DataManager와 BookManager의 **구현체를 생성하는 역할**을 합니다. 초기엔 Factory를 통한 주입을 생각했지만 LibrarySystem에서 모드를 선택하는 과정에서 Enum을 사용하고 있고 특정 모드에 따라 사용하는 Manager가 다르니 이를 Enum에서 관리하고 주입하면 어떨까? 라는 생각으로 개발했습니다. 이렇게 **Enum에서 구현체의 생성을 관리하는 방식**이 괜찮은지 그리고 개선할 부분은 어디인지 여쭤보고 싶습니다!

6. LibrarySystem과 BookManager는 **Enum을 통해 메시지를 출력**하고 있습니다. 문자열 하드 코딩이 아니라 메시지 내용을 바꿀 때 전체 문자열이 수정되는 방식으로 하고자 Enum을 사용했는데 이러한 방식은 **좋다고 볼 수 있을까**요? 그리고 LibraryMessage Enum은 BookManagerMessage Enum과 달리 **toString()을 오버라이드하는 방식**으로 해봤는데 두 문자열 관리 Enum의 방식 중 **어떤 것이 더 바람직한 방법인지도 궁금합니다!**

2023-10-03 12:22 UTC, aegis1920 requested changes
안녕하세요 현우님~ 빙봉입니다 🙂 

코멘트드렸으니 확인해주세요!

> 첫 자바 프로젝트여서 그런지 전체적인 프로젝트 구조를 계속해서 생각하면서 코드를 작성했지만 엉성한 부분이 상당히 많은 것 같습니다. 프로젝트에서 사용하는 인터페이스, 클래스, 메서드, 필드 명 등 기본적인 내이밍과 패키지를 나누는 기준 같은 것이 모호해서 이 부분에 대한 피드백을 부탁드리고 싶습니다!

넵 드렸습니다! 일단 먼저 반영해주시고 추가적으로 반영할 부분은 추후 다시 피드백 드릴게요!

> 코드를 작성하면서 커밋을 하다보니 특정 커밋은 많은 파일이 수정되고 브랜치와 커밋 내용이 조금 엇나가는 등 버전 컨트롤을 위해 깃을 사용하기 보다는 개발 일기를 쓰는 느낌으로 커밋을 한 것 같습니다. 명확하게 커밋 단위를 나누고 좋은 메시지를 작성하는 등 올바른 버전 관리를 위해 깃을 사용하려면 어떤 부분을 개선해야할지 알고 싶습니다!

커밋은 기능 단위나 수정 단위 등으로 의미있게 최대한 분리하는 게 좋습니다. 그리고 커밋 메시지는 회사마다 달라서요. 지금 충분히 잘 나누고 잘 작성해주셨습니다. 이와 별개로 올바른 버전 관리를 위해서라면 브랜치 관리나 git flow 커밋 단위, PR 단위 등등이 있을텐데요. 이걸 여기에 적기에는 양이 너무 많을 것 같아서 나중에 온라인으로 이야기 나눠보시죠!ㅎㅎ

> 설계를 하고 기능을 개발하는 과정에서 역할 분배에 대한 고민을 정말 많이 했습니다. 그 중 계속해서 고민했던 것은 'BookManager가 도서 관리와 메시지 반환이라는 2가지의 책임을 지고 있다는 것을 분리할 것이냐' 였습니다. 중간 계층으로 QueryManager와 같은 클래스를 추가하거나 MVC 패턴 느낌으로 리팩토링을 진행할까 고민했지만 시간 대비 효율, 테스트 용이성, 리팩토링으로 인한 연쇄 수정 등 정확한 판단이 어려워 멘토님의 견해를 묻고 싶습니다. 현재 BookManager이 정말 좋지 못한 것인지 그리고 수정해야 한다면 그 이유와 방향성이 어떤 것일까요?

메시지 반환은 View와 아주 강한 결합도로 연관되어 있습니다. 예를 들어, 메시지가 수정되면 ListBookManager도 수정되겠죠. ListBookManager는 책에 대한 관리만 책임져야 하는데 그러지 못하고 있습니다. 수정해야한다면 View를 위한 클래스를 새롭게 생성해서 결합도를 낮추는 쪽으로 방향성을 잡으면 어떨까 싶습니다.

> LibrarySystem이 Book 클래스에 대한 의존없이 실행되는 것을 의도한 애플리케이션이지만 bookManager.init(dataManager.load());과 같이 실제 List을 반환하는 메서드를 사용하면서 보이지 않는 의존성이 생기는 등 개선해야 할 부분이 많다고 생각합니다. 아래와 같이 역할을 나누면서 애플리케이션을 개발하고 싶었는데 해당 코드를 어떻게 개선하면 좋을까요? (해당 코드에 코멘트 남기겠습니다!)

 LibrarySystem은 입출력
 DataManager는 파일 로드와 저장
 BookManager는 도서 관리

위 질문와 비슷한 맥락으로 보이긴 하는데요. 현재 클래스가 이름대로 책임을 잘 갖고 있는가 살펴보시면 좋을 것 같습니다. JSONDataManager같은 경우도 정말 입출력만 담당해야 하는데 Book에 대한 도메인과 직접적으로 연관되어 있습니다. 이 연관(의존성)을 해결하기 위한 고민을 해보시죠! (지금 당장은 중간에 매핑을 위한 DTO를 넣어주는 방법이 떠오르네요)

> LibarayMode Enum은 LibrarySystem에서 사용하는 DataManager와 BookManager의 구현체를 생성하는 역할을 합니다. 초기엔 Factory를 통한 주입을 생각했지만 LibrarySystem에서 모드를 선택하는 과정에서 Enum을 사용하고 있고 특정 모드에 따라 사용하는 Manager가 다르니 이를 Enum에서 관리하고 주입하면 어떨까? 라는 생각으로 개발했습니다. 이렇게 Enum에서 구현체의 생성을 관리하는 방식이 괜찮은지 그리고 개선할 부분은 어디인지 여쭤보고 싶습니다!

LibraryMode가 Enum에 따라 구현체를 생성해주는 건 좋아보입니다! 다만 Enum 명이 구현체를 생성해주는 역할을 담고 있도록 작성해줘야할 것 같은데요. 말씀대로 Factory라는 이름을 넣어주도 좋을 것 같습니다. e.g. LibarayModeFactory

> LibrarySystem과 BookManager는 Enum을 통해 메시지를 출력하고 있습니다. 문자열 하드 코딩이 아니라 메시지 내용을 바꿀 때 전체 문자열이 수정되는 방식으로 하고자 Enum을 사용했는데 이러한 방식은 좋다고 볼 수 있을까요? 그리고 LibraryMessage Enum은 BookManagerMessage Enum과 달리 toString()을 오버라이드하는 방식으로 해봤는데 두 문자열 관리 Enum의 방식 중 어떤 것이 더 바람직한 방법인지도 궁금합니다!

Enum으로 관리한다면 한 곳에서 메시지를 관리할 순 있겠지만 메시지 내용이 바뀔 때마다 의미에 따라 ENUM명 바뀌어야 합니다. 어떻게 보면 의존도가 생기는거죠. 그래서 저는 이런 메시지 출력에 있어서 굳이 메시지를 enum으로 관리하진 않는 편입니다. toString() 관련해서는 코멘트 드렸습니다!

2023-10-03 12:22 UTC, aegis1920 commented on app/build.gradle
- 혹시 ASak1104:pr-ASak1104-hwkim 브랜치를 기준으로 실행시켰을 때 잘 되실까요?
- 디렉토리가 app부터 시작하는데 의도하신 바일까요?

2023-10-03 12:22 UTC, aegis1920 commented on app/build.gradle
> +}
마지막 줄 개행(EOF의 개행)에 신경써주시면 좋을 것 같습니다!
참고로 유닉스 시스템의 표준이 한 줄에 대한 정의가 개행으로 끝납니다. ([링크](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_206))

intellij에서 아래 설정으로 자동으로 넣어줄 수 있습니다 🙂 

<img width="430" alt="image" src="https://github.com/prgrms-be-devcourse/java-library-management/assets/22311557/2fee0f24-e557-454a-a24d-e9d41db11b3d">

2023-10-03 12:22 UTC, aegis1920 commented on app/build.gradle
> +    testImplementation 'org.junit.jupiter:junit-jupiter'
bom으로 명시해주신 이유가 있을까요?
`testImplementation 'org.junit.jupiter:junit-jupiter:5.8.1'`만 있어도 충분했을 것 같습니다!

2023-10-03 12:22 UTC, aegis1920 commented on app/src/main/java/com/dev_course/Main.java
> +public class Main {
Main이라는 클래스 명보단 어플리케이션에 해당하는 이름이면 더 나을 것 같군요. 단순히 Application 이라도 좋을 것 같습니다!

2023-10-03 12:22 UTC, aegis1920 commented on app/src/main/java/com/dev_course/book/Book.java
> +    private long updateAt;
updateAt을 long으로 준 이유는 System.currentTimeMillis()을 사용함이 가장 클까요? 좀 더 직관적인 LocalDateTime 같은 건 어떠실까요?

2023-10-03 12:22 UTC, aegis1920 commented on app/src/main/java/com/dev_course/book/Book.java
> +    }
toString은 객체의 상태를 나타내줄 때 사용하는데요. 지금은 혼자 개발하기 때문에 상관은 없겠지만 함께 개발할 때는 예상했던 포맷(e.g. lombok을 사용한 toString)과는 다르기 때문에 직접 오버라이딩하실 때는 주의하셔야 합니다 🙂

2023-10-03 12:22 UTC, aegis1920 commented on app/src/main/java/com/dev_course/book/BookManager.java
> +public interface BookManager {
현재 상황에서 BookManager라는 인터페이스가 필요한 이유가 있을까요?

2023-10-03 12:22 UTC, aegis1920 commented on app/src/main/java/com/dev_course/book/BookManagerMessage.java
> +public enum BookManagerMessage {
메시지를 한 곳에서 관리한다는 측면에서 enum으로 관리하게 해주신 걸까요?

2023-10-03 12:22 UTC, aegis1920 commented on app/src/main/java/com/dev_course/book/ListBookManager.java
> +    private static final int PROCESSING_COST = 300_000;
- 상수와는 개행으로 구분해주세요!
- 300_000이라는 숫자보다는 5 * 60 * 1000 이라든지, MINUTES라는 다른 상수를 만들어서 5 * MINUTES 이라든지 좀 더 가독성 좋게 만들어보는 게 좋을 것 같아요!

2023-10-03 12:22 UTC, aegis1920 commented on app/src/main/java/com/dev_course/book/ListBookManager.java
> +    private final String infoDelim = "\n------------------------------\n";
이 필드는 왜 상수가 아닐까요?

2023-10-03 12:22 UTC, aegis1920 commented on app/src/main/java/com/dev_course/book/ListBookManager.java
> +        id = bookList.stream()
어차피 data에 있는 컬렉션을 가지고 새로운 List에 addAll하는 거라면 bookList를 사용할 필요 없이 data.stream().toList()로 바로 list에 있는 함수를 사용할 수 있지 않을까요?

2023-10-03 12:22 UTC, aegis1920 commented on app/src/main/java/com/dev_course/book/ListBookManager.java
> +    private final List<Book> bookList = new ArrayList<>();
자료구조에 한정된 bookList라는 변수명보다는 books라는 변수명이 좀 더 유연하지 않을까요?

2023-10-03 12:22 UTC, aegis1920 commented on app/src/main/java/com/dev_course/book/ListBookManager.java
> +    }
반환 값이 View에 해당하는 String이 반환되고 있습니다. View 레이어를 분리해보는 건 어떨까요? BookManager에서는 정말 책에 대한 관리만 할 수 있도록 해보는 건 어떨까요?

2023-10-03 12:22 UTC, aegis1920 commented on app/src/main/java/com/dev_course/book/ListBookManager.java
> +                .filter(book -> book.getId() == id)
book에 있는 것을 get 해서 비교하는 것이 아닌 isSame과 같이 tell 해보는 건 어떨까요?

2023-10-03 12:22 UTC, aegis1920 commented on app/src/main/java/com/dev_course/book/ListBookManager.java
> +                .filter(book -> book.getId() == id)
hasNotId 메서드가 존재하지 않아도 어차피 여기서 걸러질 것 같긴 하네요. 대신 예외를 잘 던져야겠네요

2023-10-03 12:22 UTC, aegis1920 commented on app/src/main/java/com/dev_course/book/ListBookManager.java
> +        if (target.getState() != AVAILABLE) {
이 부분도 Book 클래스에 메서드를 만들어서 tell해보는 건 어떨까요?

2023-10-03 12:22 UTC, aegis1920 commented on app/src/main/java/com/dev_course/book/ListBookManager.java
> +    private long getCurrentTime() {
이미 System.currentTimeMillis()만으로 명확해서 굳이 메서드로 뺄 필요 있을까? 싶은 생각이 듭니다ㅎㅎ

2023-10-03 12:22 UTC, aegis1920 commented on app/src/main/java/com/dev_course/book/ListBookManager.java
> +    }
이것도 Book 클래스 내부에 만들어주는 게(tell하는 게) 더 좋을 것 같아요!

2023-10-03 12:22 UTC, aegis1920 commented on app/src/main/java/com/dev_course/book/BookState.java
> +    public boolean isReturnable() {
tell 👍

2023-10-03 12:22 UTC, aegis1920 commented on app/src/main/java/com/dev_course/data_module/DataManager.java
> +public interface DataManager {
인터페이스 분리 👍

2023-10-03 12:22 UTC, aegis1920 commented on app/src/main/java/com/dev_course/data_module/EmptyDataManager.java
> +        return new ArrayList<>();
empty한 list라면 Collections.emptyList()를 활용해도 좋을 것 같습니다!

2023-10-03 12:22 UTC, aegis1920 commented on app/src/main/java/com/dev_course/data_module/EmptyDataManager.java
> +    public void save(List<Book> books) {
무시되는 로직이라면 변수명에 ignored라고 적어두거나 주석을 적어둬도 좋을 것 같습니다~

2023-10-03 12:22 UTC, aegis1920 commented on app/src/main/java/com/dev_course/data_module/JSONDataManager.java
> +    private final String path = "./src/main/resources/library_data.json";
이 경로는 상수가 맞을까요?

2023-10-03 12:22 UTC, aegis1920 commented on app/src/main/java/com/dev_course/data_module/JSONDataManager.java
> +    private final ObjectMapper objectMapper = new ObjectMapper().enable(INDENT_OUTPUT);
보통 포맷팅 자체는 외부 에디터에서 하기 때문에 코드 내에서 이 설정이 필요있을까?하는 의문은 듭니다ㅎㅎ

2023-10-03 12:22 UTC, aegis1920 commented on app/src/main/java/com/dev_course/data_module/JSONDataManager.java
> +    private void createDirectory() {
여기도 굳이 메서드로 빼지 않아도 의미가 충분히 전달되는 것 같습니다!

2023-10-03 12:22 UTC, aegis1920 commented on app/src/main/java/com/dev_course/io_module/ConsoleSystemWriter.java
> +public class ConsoleSystemWriter implements Writer {
System.out.println 자체로도 너무 명시적이어서 ConsoleSystemWriter라는 클래스가 직접적으로 필요있을까 싶은 생각이 듭니다. Console 뿐만 아니라 다른 Writer가 추가 구현 될 수 있으니 이렇게 작성해놓으신 걸까요?

2023-10-03 12:22 UTC, aegis1920 commented on app/src/main/java/com/dev_course/library/LibraryMode.java
> +public enum LibraryMode {
👍

2023-10-03 12:22 UTC, aegis1920 commented on app/src/main/java/com/dev_course/library/LibrarySystem.java
> +            case "1" -> LibraryMode.NORMAL;
0과 1이라는 문자열을 LibraryMode Enum에 넣는 건 어떨까요?

2023-10-03 12:22 UTC, aegis1920 commented on app/src/test/java/com/dev_course/book/ListBookManagerTest.java
> +class ListBookManagerTest extends BookManagerTest {
뭔가 BookManagerTest가 추상 클래스이고 ListBookManagerTest에 테스트코드가 있어야할 것 같은데 아닐까요? 이렇게 작성해주신 의도가 있으실까요?

2023-10-03 12:22 UTC, aegis1920 commented on app/src/test/java/com/dev_course/book/BookManagerTest.java
> +    @Order(1)
테스트 실행에 Order를 주신 이유가 있을까요?

2023-10-04 18:07 UTC, cloudwi commented on app/build.gradle
저도 ASak1104:pr-ASak1104-hwkim 브랜치를 기준 실행이 제대로 되지 않아요.

2023-10-04 18:30 UTC, cloudwi commented
현우님 과제 하신다고 고생하셨습니다.

추가로 프로그램을 실행시키면서 파일로 저장이 잘되는지 저장된 데이터가 잘 불러와지는지 테스트가 되었을까요?

2023-10-04 18:32 UTC, cloudwi commented on app/src/main/java/com/dev_course/book/Book.java
> +    public Book() {
기본 생성자를 사용하는 곳이 있을까요?

없다면 private, protected으로 변경하면 조금 더 안전한 코드가 될 수 있을 것 같아요!

2023-10-04 18:32 UTC, cloudwi commented on app/src/main/java/com/dev_course/book/Book.java
> +    public void setState(BookState state) {
이미 잘 알고 있는 내용 이시겠지만 set 사용은 지양하면 좋은 것 같아요!

2023-10-04 18:32 UTC, cloudwi commented on app/src/main/java/com/dev_course/book/ListBookManager.java
> +
위 현재 시간을 가지고 와서 processedTime을 만드는 과정이 더 구체적인 곳에 존재하면 좋지 않을까요?

2023-10-04 18:32 UTC, cloudwi commented on app/src/main/java/com/dev_course/book/ListBookManager.java
> +                .filter(book -> isProcessed(book, processedTime))
book.isProcessed() 기능을 만들면 좋지 않을까요?

2023-10-04 18:32 UTC, cloudwi commented on app/src/main/java/com/dev_course/book/ListBookManager.java
> +                    book.setState(AVAILABLE);
set를 사용해서 지정된 상태를 변경하는 것 보단

book.toAVAILABLE() 과 같은 매서드를 이용해서 book 내부에 정의되어있는 상태로 변환 시키는 것이 좋지 않을까요?

2023-10-04 18:32 UTC, cloudwi commented on app/src/main/java/com/dev_course/book/ListBookManager.java
> +                    book.setUpdateAt(currentTime);
여기도 위와 동일 합니다.

2023-10-04 18:32 UTC, cloudwi commented on app/src/main/java/com/dev_course/book/ListBookManager.java
> +        if (hasTitle(title)) {
해당 if 문은 중복된 제목을 찾는 기능을 하고 있는 것 같아요.

그렇다면 if문을 작성하는 것 보단 매서드로 뺴서 보다 명확한 이름을 사용하면 좋지 않을까요?

2023-10-04 18:32 UTC, cloudwi commented on app/src/main/java/com/dev_course/book/ListBookManager.java
> +        bookList.add(newBook);
해당 기능은 리스트에 데이터를 추가하는 작업을 하고 파일을 작성하는 기능은 빠져있나요?

2023-10-08 01:56 UTC, ASak1104 commented
> 현우님 과제 하신다고 고생하셨습니다.
> 
> 추가로 프로그램을 실행시키면서 파일로 저장이 잘되는지 저장된 데이터가 잘 불러와지는지 테스트가 되었을까요?

이 부분에 대해서도 고민을 정말 많이 했었는데요
파일을 저장하고 불러오는 과정에 대한 테스트가 정말 필요하고 투자한 시간 대비 효과가 있는가? 에 대해 저는 아니라고 생각했고 기본적인 애플리케이션을 위해선 당연히 파일 입출력이 정상적으로 동작하는 것이 필요하기에 따로 테스트 코드를 작성하진 않았습니다

이전에 인턴십에서 비슷한 상황이 있었는데 테스트 코드에서 파일을 생성하고 제거하는 함수를 추가로 구현해 파일 입출력 모듈의 테스트를 진행했었지만 테스트 코드를 작성하는 번거로운 과정에 비해 좋은 효과를 기대하기엔 어려웠습니다. 테스트 환경에 따라 path가 변경될 수도 있고 동일한  path에 대한 권한을 안한 문제 등 고려해야할 것이 정말 많다는 것과 이런 것을 모두 고려해서 테스트한 결과물이 단순한 파일의 Read/Write라는 점이 큰 이유였던 것 같습니다.

과제의 deadline은 지났지만 서브 멘토님께서 `파일로 저장이 잘되는지 저장된 데이터가 잘 불러와지는지 테스트`할 수 있는 방법이나 방향성을 제시해주신다면 좋은 프로젝트 결과물을 위해 노력해보겠습니다!!!
좋은 피드백 감사합니다!

2023-10-08 20:53 UTC, ASak1104 commented on app/src/main/java/com/dev_course/library/LibrarySystem.java
> +    }
Book 클래스에 대한 의존없이 실행되는 것을 의도했지만 실제 List<Book>을 반환하는 메서드를 사용하면서 보이지 않는 의존성이 생기는 등 개선해야 할 부분이 많다고 생각합니다. 해당 코드를 어떻게 개선하면 좋을까요? (41번행 init() 메서드도 동일합니다!)

2023-10-08 20:53 UTC, ASak1104 commented on app/src/main/java/com/dev_course/book/ListBookManager.java
> +    private final String infoDelim = "\n------------------------------\n";
여러 메서드에서 사용하는 문자열을 이렇게 필드로 빼는 것과 사용할 때 마다 직접 입력하는 것을 고민했는데 어떤 것이 해당 BookManager 클래스에서 사용하기 좋은 방식일까요? 그리고 Interface에 default 메서드로 joinBookInfo() 같은 메서드를 추가하는 방식은 어떨까요?

2023-10-08 20:53 UTC, ASak1104 commented on app/src/test/java/com/dev_course/book/BookManagerTest.java
> +abstract class BookManagerTest {
첫 테스트 코드 작성이라 개선했으면 하는 부분을 모두 말씀해주셨으면 합니다!!
시간 대비 효율적이고 핵심적인 로직만 테스트하자는 생각으로 해당 테스트 클래스만 작성했는데 추가해야될 테스트 케이스나 다른 클래스가 있다면 조언 부탁드립니다!

2023-10-08 20:53 UTC, ASak1104 commented on app/src/main/java/com/dev_course/data_module/JSONDataManager.java
> +    private final String path = "./src/main/resources/library_data.json";
path 정보를 관리하는 좋은 방법이 있을까요? 추가적인 Enum 클래스에서 필요한 상수들을 정의하는 방식으로 수정하는 건 어떻게 생각하시는지 궁금합니다!

2023-10-08 20:53 UTC, ASak1104 commented on app/src/main/java/com/dev_course/data_module/JSONDataManager.java
> +    }
정의한 path 디렉토리가 없을 때 사용하는 함수입니다. 이런 부분까지 고려할 필요가 있었는지 의문이 듭니다.. 필요한 메서드일까요? 아니면 불필요한 케이스 처리일까요?

2023-10-08 20:53 UTC, ASak1104 commented on app/build.gradle
> +}
평소에 잘 지키지 못 한 내용이었습니다. 감사합니다!

commit 1f488a49e776a4088a40568b359ca65bf31ea646

2023-10-08 20:53 UTC, ASak1104 commented on app/build.gradle
> +    testImplementation 'org.junit.jupiter:junit-jupiter'
intellj 프로젝트 생성 때 junit 사용을 위해 dependency를 자동으로 추가한 부분으로 명시한 직접적인 이유는 없습니다.
해당 부분은 추후에 직접 공부해보겠습니다!

commit c216b3f07b3e6c039ea708d178f430727810a074

2023-10-08 20:53 UTC, ASak1104 commented on app/src/main/java/com/dev_course/Main.java
> +public class Main {
넵 코멘트 감사합니다!!

commit e4f354885f98d207eb8d43410df337bb002ccf6f

2023-10-08 20:53 UTC, ASak1104 commented on app/src/main/java/com/dev_course/book/Book.java
> +    private long updateAt;
말씀하신대로 `System.currentTimeMillis()` 메서드를 사용함과 초기에 unixtime 또는 timestamp 형식을 의도했기에 updateAt 픽드를 long 타입으로 정의했습니다.
확실히 코드와 데이터 단에서 직관적이라고 볼 수는 없는 것 같습니다.
멘토님의 말씀처럼 직관성을 위해 LocalDateTime 을 적용하는 방식으로 코드를 수정해보겠습니다!

commit 85ece727d45f6c30625824b1ced0f2420d83f658

2023-10-08 20:53 UTC, ASak1104 commented on app/src/main/java/com/dev_course/data_module/JSONDataManager.java
> +    private final ObjectMapper objectMapper = new ObjectMapper().enable(INDENT_OUTPUT);
해당 설정은 파일 저장 시 보기 좋은 포맷으로 저장하고자 사용했습니다.
멘토님의 말씀처럼 포맷팅을 외부 에디터에서 한다면 확실히 해당 설정은 불필요한 것 같습니다!

2023-10-08 20:53 UTC, ASak1104 commented on app/src/main/java/com/dev_course/book/Book.java
> +    }
넵 멘토님의 피드백 덕분에 toString 오버라이딩에 대한 경각심을 갖을 수 있었습니다!
그래서 도서 정보 표시를 toString() 오버라이딩이 아닌 info() 메서드를 호출하는 방식으로 변경해봤습니다.

commit 91d8dd6f29b00e0e30477b6a3ac44ebebbcdf816

2023-10-08 20:53 UTC, ASak1104 commented on app/src/main/java/com/dev_course/book/ListBookManager.java
> +    private final List<Book> bookList = new ArrayList<>();
초기부터 필드명을 `books` 와 `bookList` 중 어떤 것을 사용할 지 정말 고민을 많이 했었습니다.
pr을 올린 버전 (`v1.0.0`)에서는 해당 클래스가 List 구현체를 사용하기에 이를 명시하는 목적을 병행하고자 필드를 `bookList`라 명명했지만 멘토님께서 언급해주신 유연성을 고려하면 `books`라는 필드명을 사용하는 것이 타당해보입니다.
감사합니다!

commit b9ab0bc32e79013d15372c88d8bf587d393869d5

2023-10-08 20:53 UTC, ASak1104 commented on app/src/main/java/com/dev_course/book/BookManager.java
> +public interface BookManager {
멘토님 말씀처럼 현재 애플리케이션은 `ListBookManager` 클래스의 인스턴스만 사용하고 있기에 `BookManager` 인터페이스가 필요한 이유는 없다고 생각합니다.
`BookManager` 인터페이스를 사용한 이유는 추후에 `HashMapBookManager`와 같은 또 다른 구현체의 생성과 테스트 코드 작성을 염두했기 때문인대요. 만약 이 부분이 지나친 인터페이스 분리이거나 불필요한 변경점을 고려한 것이라면 코멘트 부탁드립니다!
과제의 deadline은 지났지만 추후에 개인적으로 코드를 수정하면서 프로젝트 완성도를 높이고 싶습니다!

2023-10-08 20:53 UTC, ASak1104 commented on app/src/main/java/com/dev_course/book/BookManagerMessage.java
> +public enum BookManagerMessage {
말씀해주신 의도와 스트링 하드 코딩을 회피하고자 메시지를 enum으로 관리를 했습니다.

> 메시지 반환은 View와 아주 강한 결합도로 연관되어 있습니다. 예를 들어, 메시지가 수정되면 ListBookManager도 수정되겠죠. ListBookManager는 책에 대한 관리만 책임져야 하는데 그러지 못하고 있습니다. 수정해야한다면 View를 위한 클래스를 새롭게 생성해서 결합도를 낮추는 쪽으로 방향성을 잡으면 어떨까 싶습니다.

> Enum으로 관리한다면 한 곳에서 메시지를 관리할 순 있겠지만 메시지 내용이 바뀔 때마다 의미에 따라 ENUM명 바뀌어야 합니다. 어떻게 보면 의존도가 생기는거죠. 그래서 저는 이런 메시지 출력에 있어서 굳이 메시지를 enum으로 관리하진 않는 편입니다. toString() 관련해서는 코멘트 드렸습니다!

enum으로 관리 중인 메시지는 어떻게 개선할 수 있을지 다시 한 번 고민해보겠습니다!

2023-10-08 20:53 UTC, ASak1104 commented on app/src/main/java/com/dev_course/book/ListBookManager.java
> +        id = bookList.stream()
`addAll()` 메서드를 사용한 것은 init 단계에서 `stream`을 통해 추가적인 list 객체가 생성되는 것을 회피하고 해당 클래스의 필드를 `final`로 선언하면서 해당 필드를 통해 데이터의 CRUD 로직을 수행하고자 한 것인데요.

개발 초기엔 `init()` 메서드가 런타임을 포함해 언제든지 호출해도 정상적으로 작동하는 것을 의도했습니다. `addAll()` 메서드를 사용하면 저장 중인 데이터에 추가되는 형식으로 사용이 가능하니까요.

하지만 런타임 중 생성된 도서들과 해당 메서드를 통해 들어오는 도서의 id가 중복될 수 있다는 것을 고려해서 '사용할거면 초기에 사용해라'는 의미로 `init()`으로 지정을 했습니다.

그렇기 때문에 기능적인 초점에서는 (이전 데이터를 불러오고 id를 설정하기에) `load()`라는 메서드명이 적합할 정도로 메서드의 이름과 기능 그리고 설계 의도가 많이 꼬여버린 느낌도 듭니다.

서론이 너무 길었지만 결과적으로 멘토님께서 제시해주신 `stream().toList()`를 사용하는 것이 `init()` 이라는 메서드 명에 부합하는 방식인 것 같습니다. 하지만 `stream().toList()`사용하면 `add()` 함수를 통한 도서 생성이 불가능해 전체적인 도서 CRUD 로직을 변경해야된다는 점에서 `final`한 Arraylist 대신 stream API 수정했을 때의 이점이 확실한지 판단하기 어려운 것 같습니다.

멘토님께선 제가 고민한 내용에 대해 어떻게 생각하시는지 궁금합니다!
좋은 피드백 감사합니다.

2023-10-08 20:53 UTC, ASak1104 commented on app/src/main/java/com/dev_course/data_module/EmptyDataManager.java
> +        return new ArrayList<>();
commit 4f622c8d5a404505f1c80721a568302ce5239f8d

2023-10-08 20:53 UTC, ASak1104 commented on app/src/main/java/com/dev_course/data_module/EmptyDataManager.java
> +    public void save(List<Book> books) {
commit 4f622c8d5a404505f1c80721a568302ce5239f8d

2023-10-08 20:53 UTC, ASak1104 commented on app/src/main/java/com/dev_course/io_module/ConsoleSystemWriter.java
> +public class ConsoleSystemWriter implements Writer {
말씀해주신 `다른 Writer가 추가 구현 될 수 있으니`를 의도해서 생성한 클래스 입니다.
이 부분도 앞선 `BookManager` 인터페이스 피드백과 같이 과도하게 변경점을 고려한 것일까요?
멘토님의 생각을 말씀해주시면 해당 부분에 대해서도 수정하도록 하겠습니다!!

2023-10-08 20:53 UTC, ASak1104 commented on app/src/test/java/com/dev_course/book/ListBookManagerTest.java
> +class ListBookManagerTest extends BookManagerTest {
> 멘토님 말씀처럼 현재 애플리케이션은 ListBookManager 클래스의 인스턴스만 사용하고 있기에 BookManager 인터페이스가 필요한 이유는 없다고 생각합니다.
BookManager 인터페이스를 사용한 이유는 추후에 HashMapBookManager와 같은 또 다른 구현체의 생성과 테스트 코드 작성을 염두했기 때문인대요. 만약 이 부분이 지나친 인터페이스 분리이거나 불필요한 변경점을 고려한 것이라면 코멘트 회신 부탁드립니다!
과제의 deadline은 지났지만 추후에 개인적으로 코드를 수정하면서 프로젝트 완성도를 높이고 싶습니다!

앞선 `BookManager` 인터페이스에서 말씀드린대로 제 의도는 `새로운 구현체가 추가될 수 있다.` 였습니다.
그래서 도서 관리 기능에 대한 테스트 또한 구현체의 상관없이 모두 동일하기 때문에 이를 하나의 추상 클래스인 `BookManagerTest`에서 관리하도록 했습니다.

그래서 `BookManager` 인터페이스의 모든 구현체는 `BookManagerTest` 추상 클래스를 상속 받은 `테스트 클래스`를 생성하고 추상 메서드인 `protected BookManager createBookManager()`만 오버라이드하면 간편하게 도서 관리 로직의 테스트가 가능하도록 구성을 해봤습니다.

개인적으로 생각했을 때 이러한 방식을 사용하는 것이 좋은 방식인 것 같았지만 현재 애플리케이션이 하나의 구현체만을 사용하고 있다는 점에서는 오버 엔지니어링인가? 라는 생각도 드는 것 같습니다.

2023-10-08 20:53 UTC, ASak1104 commented on app/src/test/java/com/dev_course/book/BookManagerTest.java
> +    @Order(1)
개발 과정에서 구현한 기능의 순서와 복잡한 정도를 고려해서 Order를 작성했었습니다. (ex. 도서가 생성 기능 -> 도서 조회 기능 -> 도서 삭제 기능)
돌이켜 생각해보면 TDD 방식으로 개발 중인 것이 아니고 특정 테스트가 다른 테스트에 의존하는 것도 아니기 때문에 굳이 테스트의 Order를 지정할 필요가 없는 것 같습니다.
감사합니다!

commit dd71233f905e81108a5d91626746644acfbb14a2

2023-10-08 20:53 UTC, ASak1104 commented on app/src/main/java/com/dev_course/library/LibrarySystem.java
> +            case "1" -> LibraryMode.NORMAL;
`LibraryMode` (현 `ModeFactory`) Enum의 경우, 도서관 애플리케이션의 모드를 정의하고 사용하는 모듈을 주입하는 역할을 하고 있기 때문에 사용자가 입력하는 0 또는 1의 문자열과 직접적인 관련이 없고 잘못된 번호를 입력했을 때 매끄럽게 처리하는 것이 어려울 것 같다는 생각으로 이렇게 구성을 해봤습니다!

혹시 멘토님께서 제시하고 싶은 방식이 있으시다면 조언 부탁드립니다!!

2023-10-08 20:53 UTC, ASak1104 commented on app/src/main/java/com/dev_course/book/ListBookManager.java
> +        if (target.getState() != AVAILABLE) {
commit b0b6541f7c485e53ff24994cb2594e9578613661

2023-10-08 20:53 UTC, ASak1104 commented on app/src/main/java/com/dev_course/book/ListBookManager.java
> +    }
commit b0b6541f7c485e53ff24994cb2594e9578613661

2023-10-08 20:53 UTC, ASak1104 commented on app/src/main/java/com/dev_course/book/ListBookManager.java
> +                .filter(book -> book.getId() == id)
조언해주신 방식으로 수정해보겠습니다
감사합니다!

commit b0b6541f7c485e53ff24994cb2594e9578613661

2023-10-08 20:53 UTC, ASak1104 commented on app/src/main/java/com/dev_course/data_module/JSONDataManager.java
> +    private final String path = "./src/main/resources/library_data.json";
확실히 상수는 아닌 것 같습니다.. 😢 경로는 언제든지 변경될 수 있으니까요

개인적으로 파일이 저장되는 경로가 클래스 내부에 정의되는 것이 괜찮은 방식인지 궁금합니다.
main 메서드나 ModeFactory에서 생성할 때 주입한다고 해도 사실상 하드 코딩인 것은 마찬가지이기 때문에 그럴거면 직접 사용하는 해당 클래스에 정의하자고 생각했습니다.

번외로 Node.js을 사용할 때 .env 같은 파일에 이러한 설정을 자주 정리를 했는데 만약 `JSONDataManager`가 파일을 저장하는 경로를 config 파일처럼 어딘가에서 설정해줘야 한다면 어떻게 구성하는 것이 좋을까요? 가볍게 설정을 관리하고 싶지만 인터넷 블로그들은 spring-boot나 기타 라이브러리를 사용하는 방식이 대부분이라 아직 마음에 드는 방식을 찾지 못했습니다.

2023-10-08 20:53 UTC, ASak1104 commented on app/src/main/java/com/dev_course/book/Book.java
> +    public Book() {
주석으로 작성한 내용처럼 ObjectMapper를 사용할 때 역직렬화를 위한 생성자가 필요했는데
private이나 protected로 선언한 생성자도 가능하군요
좋은 피드백 정말 감사합니다!

commit b5c0858a19bdea2039bc81c3660c53cf1ed57d28

2023-10-08 20:53 UTC, ASak1104 commented on app/src/main/java/com/dev_course/book/ListBookManager.java
> +                .filter(book -> isProcessed(book, processedTime))
멘토님과 같은 부분을 조언해주셨군요!
감사합니다!

commit b0b6541f7c485e53ff24994cb2594e9578613661

2023-10-08 20:53 UTC, ASak1104 commented on app/src/main/java/com/dev_course/book/ListBookManager.java
> +        bookList.add(newBook);
파일 작성은 DataManager 인터페이스의 구현체들이 하고 있습니다
제가 구현 방식은 애플리케이션이 시작할 때 로드하고 종료될 때 파일에 저장해서
중간 단계에서는 파일에 접근하는 일은 없습니다

스케줄러를 통한 파일 저장이나 쿼리 사이사이에 데이터를 저장할 필요가 있다고 생각하시나요?

2023-10-08 20:53 UTC, ASak1104 commented on app/src/main/java/com/dev_course/book/ListBookManager.java
> +        if (hasTitle(title)) {
`if` 문을 메서드로 빼고 명확한 이름을 사용한다는 것이 말씀이 어떤 말씀인지 잘 모르겠습니다
중복 제목을 찾는 기능이라기 보다는 중복 제목의 존재 여부를 확인하는 메서드이기 때문에 수행하는 기능과 이름의 뜻이 명확하지 않나요?

아니면 예외를 반환하는 메서드를 추가하고 이를 사용하는 outer 메서드에서 처리를 하라는 말씀이실까요?

2023-10-08 20:53 UTC, ASak1104 commented on app/src/main/java/com/dev_course/book/Book.java
> +    public void setState(BookState state) {
서브멘토님께서 말씀해주신대로 setter를 통한 필드 값 변환은 지양하는 것이 좋은 것 같습니다!
하지만 애플리케이션에서 요구하는 도서의 상태는 현재 4개이기 때문에 이를 만족하는 기능을 위해선 각각의 상태 변환을 위한 추가적인 메서드가 4개 이상 필요한 것 같습니다.
그래서 저는 도서의 상태 정보가 자주 변경될 수 있고 `BookState`라는 enum에 정의되어 있다는 점에서 setter를 사용하는 방식으로 구현을 했습니다.

개인적으로 생각해봤을 때 각각의 상태로 변환하기 위한 메서드를 사용하면 추후에 상태가 추가되거나 상태를 정의하는 이름이 변경되었을 때 수정해야되는 부분이 setter 사용에 비해 월등히 많아질 수 있고 `BookState` enum에 의존한 setter라면 해당 코드의 유지보수와 가독성 측면에서도 충분히 좋은 코드라고 판단했습니다.

서브멘토님께서는 어떻게 생각하실 지 궁금합니다.
좋은 코멘트 감사합니다!!

2023-10-08 20:53 UTC, ASak1104 commented on app/src/main/java/com/dev_course/book/ListBookManager.java
> +
해당 코드 다음에 도서의 상태를 변경하는 부분이 나오는데요

그 과정에서 updateAt의 필드를 현재 시간으로 변경하는 부분도 존재합니다
그래서 `getProcessedTime()` 같은 메서드를 사용하면 파라미터로 현재 시간을 전달하거나 다시 계산하는 작업이 필요할 것 같습니다.

그리고 제가 생각해 봤을 때 필요한 현재 시간을 미리 구하고 `processedTime` 계산하는 것도 `getProcessedTime()` 같은 메서드를 추가로 선언했을 때 처럼 충분히 의도가 명확하게 전달되고 불필요한 메서드 선언이 없다는 점에서 메리트가 있다고 생각하는데 서브 멘토님께서는 이 부분에 대해서 어떻게 생각하시는지 궁금합니다!

2023-10-08 20:53 UTC, ASak1104 commented on app/src/main/java/com/dev_course/book/ListBookManager.java
> +    }
멘토님께서 제시해주신 것처럼 메시지와 도서 관리라는 기능을 분리하면서 메시지 반환을 담당하는 다른 클래스를 도입하는 방식으로 책임을 분리하는 방향을 수정해보겠습니다!

commit (main) 690b616516e310a9d8666d9fcc0bd5fbc8146295
commit (test) 5376d60081e7a35d78a2c94ed17f47428e59cd68

2023-10-08 20:53 UTC, ASak1104 commented on app/build.gradle
애플리케이션과 다른 파일들을 분리하고자 `app` 디렉토리를 최상위로 하는 자바 프로젝트를 생성했습니다.
리뷰어에게 혼동을 준다는 점에서 좋은 방식은 아니었던 것 같습니다.
감사합니다.

commit 24c2f19390e38e9b68bf2777d0beebf9aa7e4079

2023-10-08 20:53 UTC, ASak1104 commented on app/src/main/java/com/dev_course/book/ListBookManager.java
> +                .filter(book -> book.getId() == id)
commit https://github.com/prgrms-be-devcourse/java-library-management/commit/690b616516e310a9d8666d9fcc0bd5fbc8146295

2023-10-08 21:05 UTC, ASak1104 commented
제가 pending 상태에서 리뷰를 올리질 않았네요.. 죄송합니다!!

2023-10-09 11:01 UTC, aegis1920 commented on app/src/main/java/com/dev_course/book/Book.java
> +    private long updateAt;
따로 의도가 있으셨군요 👍 설명 감사합니다!

2023-10-09 11:06 UTC, aegis1920 commented on app/src/main/java/com/dev_course/book/BookManager.java
> +public interface BookManager {
개인적으로 생각하기에는 BookManager라는 인터페이스가 이후에 다른 구현체로 사용될 일이 특별히 없어보여서요! 그리고 지금 메서드가 많은 편도 아니라 나중에 작성해도 충분할 거라는 생각이 들었습니다 🙂 말씀해주신 부분 중에 테스트 코드의 경우에는 아마 mocking 때문에 인터페이스로 뺐다고 이해가 되는데요. 인터페이스가 아니더라도 mocking할 수 있는 방법은 있으니 크게 걱정하지 않으셔도 될 것 같습니다!

2023-10-09 11:22 UTC, aegis1920 commented on app/src/main/java/com/dev_course/book/ListBookManager.java
> +        id = bookList.stream()
고민한 내용 너무 좋군요 👍 일단 말씀주신대로 streamI().toList()를 사용하면 수정이 불가능한 리스트를 반환합니다. 그래서 add 함수를 사용하면 에러가 발생합니다. 지금은 말씀해주신대로 로컬에서 혼자 사용하는 프로그램이니 final한 ArrayList를 사용해도 문제가 되지 않지만 웹 서버와 같은 멀티스레드 환경으로 가게 된다면 race condition을 방지하는 것이 필요합니다. ArrayList()는 스레드 세이프하지 않기에 CopyOnWriteArrayList를 사용해야하며 pk로 사용했던 int도 AtomicInteger를 사용해줘야 합니다. 멀티스레드 환경에서는 Immutable한 자료구조를 만들기 위해 stream().toList() 같은 것도 필연적이게 될거구요. 이런 부분은 다음 미션에서 고민해보시면서 작성해주시면 좋을 것 같습니다.

2023-10-09 11:29 UTC, aegis1920 commented on app/src/main/java/com/dev_course/data_module/JSONDataManager.java
> +    private final String path = "./src/main/resources/library_data.json";
지금 상황에서는 클래스 내부에 정의되어도 상관없을 것 같긴합니다만 만약 외부로 넣어주고 싶다면 지금 바로 생각나는 방법은.. 직접 main함수의 args로 넣어주는 방법으로도 가능할 것 같습니다. 실행할 때 경로를 함께 적어서 실행시키는 방식으로요. 만약 SpringBoot를 쓸 경우에는 application.properties 같은 외부 설정을 넣어주면 됩니다.

2023-10-09 11:29 UTC, aegis1920 commented on app/src/main/java/com/dev_course/io_module/ConsoleSystemWriter.java
> +public class ConsoleSystemWriter implements Writer {
넵 맞습니다! 지금으로선 필요하지 않고 만약 필요하다면 바로 생성가능할 정도의 변경으로 생각됩니다!

2023-10-09 11:31 UTC, aegis1920 commented on app/src/main/java/com/dev_course/library/LibrarySystem.java
> +            case "1" -> LibraryMode.NORMAL;
ModeFactory라면 충분히 의미 전달이 될 것 같습니다! 좋습니다!

2023-10-09 11:41 UTC, aegis1920 commented on app/src/test/java/com/dev_course/book/ListBookManagerTest.java
> +class ListBookManagerTest extends BookManagerTest {
자세한 설명 감사합니다! 👍 개인적으로는 오버엔지니어링이라고 생각되지만 이런 인터페이스로 구현해놨으니 추후에도 이걸 꼭 지키면서 구현해라!라는 의도가 보여서 좋기도 하네요. 다만 여러 구현체(XXXBookManager)에 대해서 전부 맞는 테스트를 작성해야하니 어려울 것 같기도 하고요? (단순히 List, HashMap처럼 자료구조 변형에 대한 구현체가 아니라 Book의 하위 도메인에 대한 구현체일 때)

2023-10-09 12:21 UTC, ASak1104 commented on app/src/main/java/com/dev_course/book/BookManager.java
> +public interface BookManager {
deadline 이후에도 코드 리뷰를 남겨주셔서 정말 감사드립니다!
말씀해주신 방향으로 코드를 개선했습니다!

commit 7f8156cde5506b65f4b3328c3fa6f2d1b50af6cf

2023-10-09 12:27 UTC, aegis1920 commented
피드백 끝까지 반영하시느라 고생 많으셨습니다! 👍 
과제는 여기서 머지하겠습니다! 이후에 궁금한 점이 있으시면 DM주시거나 코멘트 따로 남겨주세요!

2023-10-09 12:27 UTC, merged

2023-10-09 13:14 UTC, ASak1104 commented
> 피드백 끝까지 반영하시느라 고생 많으셨습니다! 👍 과제는 여기서 머지하겠습니다! 이후에 궁금한 점이 있으시면 DM주시거나 코멘트 따로 남겨주세요!

추석 연휴와 가족 행사가 많은 주간이라 적극적으로 참여할 수 없었지만
멘토님과 서브 멘토님의 배려와 가르침 덕분에 많은 것을 배우고 경험할 수 있었습니다.
코드 리뷰 및 멘토링에 정말 감사드립니다!!