[5기 - 손가현] 1~2주차 과제: 도서 관리 어플리케이션 제출합니다.
prgrms-be-devcourse/java-library-management pull request #33
Opened 2023-10-02 03:41 UTC by hyun2371

## 📌 과제 설명

도서의 정보를 저장하고 변경할 수 있는 도서 관리 애플리케이션입니다.
콘솔로 사용자의 입력을 받아 도서를 등록, 조회, 검색, 반납, 분실, 삭제할 수 있습니다.
도서를 반납하면 정리중인 상태로 변하고, 5분이 지난 후에 대여 가능 상태로 바뀌면 대여할 수 있습니다.
일반 모드로 실행 시 도서 정보가 파일에 저장되고, 테스트 모드로 실행 시 파일에 저장되지 않습니다.
<br/><br/>

## 👩‍💻 요구 사항과 구현 내용

프로젝트의 패키지 구조는 다음과 같습니다.

domain

- Book: 도서 엔티티입니다. 기존 요구 사항에서 반환시간 필드를 추가로 정의했습니다. 도서 상태 변경 메서드와 도서 출력 메서드를 엔티티 내에 정의하여 응집도를 높이고자 하였습니다.
- Status: 도서 상태를 담은 Enum 클래스입니다.

repository

- Repository: 저장소의 기능을 추상화한 인터페이스입니다.
- FileRepository: 일반 모드 저장소로 구현한 레포지토리입니다. 프로덕션 코드와 테스트 코드에서 생성자로 각각 다른 파일 경로를 주입 받습니다.
- TestRepository: 테스트 모드 저장소로 구현한 레포지토리입니다.

service

- BookService: 레포지토리 내 메서드를 호출하며 비즈니스 로직을 처리합니다. 커스텀 예외를 발생시켜 컨트롤러에게 해당 예외를 던집니다.

controller

- BookController: 콘솔로 입출력을 받고 그에 대한 동작을 처리합니다. 예외 메세지를 출력하여 예외 처리를 해줍니다.

exception

- EmptyInputException: 입력값이 공백이거나 null일 때 발생하는 사용자 정의 예외 클래스입니다.
- NotExistBookIdException: 존재하지 않는 책 아이디로 레포지토리 접근 시 발생하는 사용자 정의 예외  클래스입니다.
- UnchangeableStatusException: 도서 상태를 변경할 수 없을 때 발생하는 사용자 정의 예외 클래스입니다.  상태 변경 불가 원인을 생성자 매개 변수로 설정할 수 있습니다.

manager

- FileManager: .csv 파일을 읽어와 리스트에 저장 및 리스트 값을 파일에 저장하는 클래스입니다.
- PrintManager: 컨트롤러 내 출력 관련 로직들을 추출한 클래스입니다.

일반 모드, 테스트 모드의  테스트 코드를 각각 작성했습니다.

일반모드 테스트용 csv 파일을 별도로 생성하였고, 각 테스트 함수 호출이 끝날 때마다 데이터 파일을 초기화했습니다.
<br/><br/>

## ✅ PR 포인트 & 궁금한 점

- 테스트 코드
    - 각 메서드마다 공통적으로 책을 저장하는데 해당 부분을 메서드로 추출하는 것이 좋을까요?
    - T*반납 후 5분 뒤 대여가능*을 검증하려고 했으나 실제 함수 호출 시간도 5분이 걸려 해당 테스트 코드를 삭제했습니다. 해당 기능을 어떻게 검증하면 좋을지 알고 싶습니다.
    - 일반 모드 테스트에서 도서 CRUD가 잘 되면 파일에서의 입출력도 잘 이뤄진 것이라고 가정하였습니다. 그래서 입출력 관련 테스트 코드를 작성하지 않았는데 작성하는게 맞는걸까요?
    - 테스트 코드를 처음 작성해보는데 추가적으로 구현하지 못했거나 잘못 구현한 로직이 있다면 말씀 부탁드립니다.

- 예외 처리
    - 콘솔창 출력 메세지가 중복되지 않아 enum 클래스로 정의하지 않아도 된다고 말씀해주셨습니다. 이와 비슷한 맥락으로 에러 메세지도 중복되지 않으면 enum 클래스로 정의할 필요 없다고 이해하면 될까요?
    - 가독성을 고려해 Service에서 발생시키는 예외들을 Controller에서 처리하였습니다. 이렇게 Controller에서 처리해도 되는지, 아니면 Service에서 try-catch를 하는게 단일 책임 원칙에 더 부합하는건지 알고 싶습니다.
    
- 기타
    - 각 클래스의 역할이 잘 분리되어 있는지 알고 싶습니다.
    - 변수, 함수 네이밍 관련해 고칠 부분이 있는지 알고 싶습니다.

2023-10-03 14:16 UTC, aegis1920 requested changes
> 각 메서드마다 공통적으로 책을 저장하는데 해당 부분을 메서드로 추출하는 것이 좋을까요?

이 부분 이해를 잘 못했는데요. 부연설명 가능할까요?

> 반납 후 5분 뒤 대여가능을 검증하려고 했으나 실제 함수 호출 시간도 5분이 걸려 해당 테스트 코드를 삭제했습니다. 해당 기능을 어떻게 검증하면 좋을지 알고 싶습니다.

호출하는 시간을 파라미터로 빼는 방식으로 진행할 수 있을 것 같습니다. 실제로 테스트할 때는 그 부분을 조정해서 짧은 시간 안에 검증할 수 있도록 해주세요!

> 일반 모드 테스트에서 도서 CRUD가 잘 되면 파일에서의 입출력도 잘 이뤄진 것이라고 가정하였습니다. 그래서 입출력 관련 테스트 코드를 작성하지 않았는데 작성하는게 맞는걸까요?
테스트 코드를 처음 작성해보는데 추가적으로 구현하지 못했거나 잘못 구현한 로직이 있다면 말씀 부탁드립니다.

테스트의 범위 관련된 이야기인데요. 가장 중요한 건 비즈니스 로직 부분으로 서비스 레이어가 있는 곳입니다. 서비스 레이어를 테스트하셨으니 잘 해주셨습니다. 물론 모든 레이어를 테스트하려고 한다면 할 수는 있습니다만.. 입출력은 쉽게 바뀔 수 있기도 하고 테스트 코드를 추가하면 테스트 시간도 오래 걸리기 때문에 유지보수 측면에서 잘 작성하진 않습니다. 이외에도 통합 테스트, 단위 테스트, mocking 등 관련해서 할 이야기가 많은데 나중에 기회된다면 해볼게요ㅎㅎ

> 콘솔창 출력 메세지가 중복되지 않아 enum 클래스로 정의하지 않아도 된다고 말씀해주셨습니다. 이와 비슷한 맥락으로 에러 메세지도 중복되지 않으면 enum 클래스로 정의할 필요 없다고 이해하면 될까요?

음.. 중복되지 않는다는 것도 있지만 enum으로 정의 해봤자 출력 메시지가 바뀌면 그에 해당하는 메시지와 enum 값도 바뀌기 때문에 메시지에 의존을 하지 않도록 정의하지 않는다는 의미가 큽니다. 다만 관리하는 니즈가 크다면 enum으로 정리할 수도 있고요. 상황에 따라 다르게 가져가는 것 같습니다. enum 메시지도 비슷한 맥락으로 이해해주시면 됩니다.

> 가독성을 고려해 Service에서 발생시키는 예외들을 Controller에서 처리하였습니다. 이렇게 Controller에서 처리해도 되는지, 아니면 Service에서 try-catch를 하는게 단일 책임 원칙에 더 부합하는건지 알고 싶습니다.

이것도 상황에 따라 다릅니다. 서비스에서 catch하고 에러 로그로만 남기고 싶다면 로그로만 남기고 다른 에러를 리턴하지 않는 경우도 있고, 다른 에러로 전환해서 에러를 던지기도 합니다. 사실 지금 상황으로만 봤을 때는 서비스에서 에러를 던지고 그에 대한 에러 메시지를 밖으로 내보내고(out.print), 다시 입력을 받고있기 때문에 요구사항에 충족해서 잘 작성해주셨다고 생각합니다.

> 정리중인 책이 5분이 지났을 경우 대여가능 상태로 바꾸고 true를 반환하는 isStillCleaning() 함수를 정의했습니다. 함수명과 로직이 어색하지 않은지 알고 싶습니다.

함수명 자체는 좋아보이는데요. 중간에 status를 update하는 게 있어 이를 분리하면 좋을 것 같습니다. 중간에 update 하는 것을 밖으로 빼서 먼제 isStilCleaning으로 체크한다음에 update 하도록이요. 그래야 그 메서드에 대한 역할이 확실해질 것 같습니다.

> 각 클래스의 역할이 잘 분리되어 있는지 알고 싶습니다.

어느정도 잘 분리되어있습니다! FileManager는 도메인과 상관없이 파일 매니저 역할만 해야될 것 같은데 book 도메인에 의존하고 있습니다. 이 의존성을 떨어뜨리는 고민도 해보시면 좋을 것 같고 입출력 (view)에 대한 부분도 분리해보면 좋을 것 같습니다.

2023-10-03 14:16 UTC, aegis1920 commented on .DS_Store
맥을 사용하시나보군요ㅎㅎ 이것도 gitignore에 추가해주시죠!

2023-10-03 14:16 UTC, aegis1920 commented on build.gradle
> +}
마지막 줄 개행(EOF의 개행)에 신경써주시면 좋을 것 같습니다!
참고로 유닉스 시스템의 표준이 한 줄에 대한 정의가 개행으로 끝납니다. ([링크](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_206))

intellij에서 아래 설정으로 자동으로 넣어줄 수 있습니다 🙂 

<img width="430" alt="image" src="https://github.com/prgrms-be-devcourse/java-library-management/assets/22311557/2fee0f24-e557-454a-a24d-e9d41db11b3d">

2023-10-03 14:16 UTC, aegis1920 commented on src/main/java/controller/BookController.java
> +    public void selectMode(){
selectMode 이후에 selectFunction까지 가면 도서 관리 어플리케이션 자체를 run하는 것과 다를 바가 없어보이는데요. 메서드 수정이나 메서드 분리가 필요하지 않을까요?

2023-10-03 14:16 UTC, aegis1920 commented on src/main/java/controller/BookController.java
> +        String mode = "";
빈 문자열로 초기화해주신 이유가 있을까요? 기본 값이나 null이나 default로 가는 건 똑같을 것 같습니다.

2023-10-03 14:16 UTC, aegis1920 commented on src/main/java/controller/BookController.java
> +            mode = getInput();
출력하는 역할은 PrintManager로 분리되어있지만 입력은 Controller 클래스에 있네요. 분리해주면 Controller의 책임이 좀 더 명확해지지 않을까요?

2023-10-03 14:16 UTC, aegis1920 commented on src/main/java/controller/BookController.java
> +                String path = "/src/main/resources/book_data.csv";
상수로 봐도 괜찮을까요? 괜찮다면 상수로 빼도 좋을 것 같습니다!

2023-10-03 14:16 UTC, aegis1920 commented on src/main/java/controller/BookController.java
> +            case "1"->{
1과 2 모두 명확해서 enum으로 생성해도 좋을 것 같아요!

2023-10-03 14:16 UTC, aegis1920 commented on src/main/java/controller/BookController.java
> +        String function="";
여기도 빈 문자열로 초기화되어있네요ㅎㅎ

2023-10-03 14:16 UTC, aegis1920 commented on src/main/java/domain/Book.java
> +    @Builder
builder 어노테이션을 사용하신 이유를 알 수 있을까요?

2023-10-03 14:16 UTC, aegis1920 commented on src/main/java/domain/Book.java
> +    public void printBookInfo() {
Book 클래스에서 자신의 정보를 출력하는 것이 Book의 역할일 지 고민해보셨으면 좋겠습니다!

2023-10-03 14:16 UTC, aegis1920 commented on src/main/java/domain/Book.java
> +    public boolean isStillCleaning(){
returnTime이 null일 때 이 함수가 호출될 가능성은 없을까요?

2023-10-03 14:16 UTC, aegis1920 commented on src/main/java/domain/Status.java
> +public enum Status {
전반적으로 컨벤션 맞춰주시면 감사하겠습니다! (개행)

2023-10-03 14:16 UTC, aegis1920 commented on src/main/java/manager/FileManager.java
> +    private String PATH = System.getProperty("user.dir");
변수명이 왜 path가 아닌 PATH일까요? 상수처럼 보였네요ㅎㅎ

2023-10-03 14:16 UTC, aegis1920 commented on src/main/java/repository/FileRepository.java
> +            if (Objects.equals(id, book.getId())){
book에게 tell 해보는 건 어떨까요? book.isSame() 이런 식으로요!

2023-10-03 14:16 UTC, aegis1920 commented on src/main/java/repository/FileRepository.java
> +        if (bookList.isEmpty()) return 1;
1 자체를 의미있게 상수화해줘도 좋을 것 같아요

2023-10-03 14:16 UTC, aegis1920 commented on src/main/java/repository/FileRepository.java
> +    private final List<Book> bookList;
자료구조와 상관없이 유연하게 적용될 수 있도록 변수명을 books로 하는 건 어떠신가요?

2023-10-03 14:16 UTC, aegis1920 commented on src/main/java/repository/FileRepository.java
> +        return bookList.get(bookList.size()-1).getId()+1;
이런 걸 생각하면 bookList를 일급컬렉션으로 만드는 것도 좋아보이네요ㅎㅎ

2023-10-03 14:16 UTC, aegis1920 commented on src/test/java/FileServiceTest.java
> +    BookService service;
접근제한자를 붙여줘도 좋을 것 같습니다!

2023-10-03 14:16 UTC, aegis1920 commented on src/test/java/FileServiceTest.java
> +        service = new BookService(repository);
한 번만 읽어도 되지 않을까요? 위 변수 할당할 때 바로 초기화되어도 될 것 같습니다. BeforeEach면 테스트 실행 시 매번 다시 할당할텐데 그럴 필요 없을 것 같아요

2023-10-03 14:16 UTC, aegis1920 commented on src/test/java/FileServiceTest.java
> +        repository.clear();
clear도 before, after 두 곳에 다 있는데 그럴 필요 없어보여요! 한 곳에 가도록 수정이 필요해보입니다. before와 after 둘 중 어디에 있는 게 좋을까요? 고민해보시죠!

2023-10-03 14:16 UTC, aegis1920 commented on src/test/java/FileServiceTest.java
> +public class FileServiceTest {
FileService가 아니라 일반 서비스? 이런 식으로 되어야할 것 같네요? 애초에 File은 단순히 파일을 읽는 용도이지 일반 모드로 정의한 것과는 달라보여요

2023-10-03 14:16 UTC, aegis1920 commented on src/main/java/service/BookService.java
> +            if (book.getStatus()==CLEANING)
이 부분도 tell 하도록 바꿔보시죠!

2023-10-03 14:16 UTC, aegis1920 commented on src/main/java/domain/Status.java
> +public enum Status {
domain 패키지 바로 아래 status가 있어서 어떤 status인지 모를 것 같습니다. 좀 더 명확하게 enum명을 작성해주시면 좋을 것 같습니다.

2023-10-03 14:16 UTC, aegis1920 commented on src/main/java/domain/Status.java
> +    AVAILABLE("대여 가능"), BORROWED("대여중"), CLEANING("정리중"), LOST("분실");
AVAILABLE에서 대여라는 용어도 들어가야할 것 같습니다.

2023-10-04 01:24 UTC, hyun2371 commented
> > 각 메서드마다 공통적으로 책을 저장하는데 해당 부분을 메서드로 추출하는 것이 좋을까요?
> 
> 이 부분 이해를 잘 못했는데요. 부연설명 가능할까요?

```java
service.saveBook("개인주의자 선언", "문유석", 111);
Book book = repository.getBookList().get(0);
```
각 테스트 함수에서 책을 저장하고 가져오는 코드가 중복되어서요. 
해당 로직을 메서드로 추출 후 beforeEach()에서 호출하는게 더 가독성이 있을지 궁금했습니다!

2023-10-04 02:39 UTC, hyun2371 commented on src/test/java/FileServiceTest.java
> +        repository.clear();
각 테스트를 수행하고 나서 비우는게 자연스러울 것 같습니다. after에만 해당 함수가 있도록 바꾸겠습니다!

2023-10-04 02:54 UTC, hyun2371 commented on src/main/java/controller/BookController.java
> +            mode = getInput();
넵! Controller에서 getInput()을 분리하여 IOManager(전 PrintManager)에 넣겠습니다!

2023-10-04 03:32 UTC, hyun2371 commented on src/main/java/domain/Book.java
> +    @Builder
생성자 파라미터가 많아서 가독성이 좋지 않다고 느꼈습니다.
그래서 @Builder를 사용해서 가독성을 높이고자 하였는데, 빼는게 더 좋은 코드일까요?

```java
Integer id = Integer.valueOf(split[0]);
String title = split[1];
String author = split[2];
Integer page = Integer.parseInt(split[3]);
BookStatus status = BookStatus.valueOf(split[4]);

LocalDateTime returnTime = null;
if (!split[5].equals("null"))
    returnTime = LocalDateTime.parse(split[5]);

Book book = new Book(id,title,author,page, status,returnTime);
```

<br/>

```java
LocalDateTime returnTime = null;
if (!data[5].equals("null"))
 returnTime = LocalDateTime.parse(data[5]);

Book book = Book.builder()
        .id(Integer.valueOf(data[0]))
        .title(data[1])
        .author(data[2])
        .page(Integer.parseInt(data[3]))
        .status(BookStatus.valueOf(data[4]))
        .returnTime(returnTime)
        .build();
```

2023-10-04 04:47 UTC, hyun2371 commented on src/main/java/domain/Status.java
> +public enum Status {
상수, 필드, 함수 간 띄어쓰기 완료했습니다!

2023-10-04 06:39 UTC, hyun2371 commented on src/main/java/domain/Book.java
> +    public boolean isStillCleaning(){
책 반납 후 정리 중일 때만 호출하니까 returnTime이 null인 경우는 없을거라고 생각합니다!

2023-10-04 07:02 UTC, hyun2371 commented on src/main/java/domain/Status.java
> +    AVAILABLE("대여 가능"), BORROWED("대여중"), CLEANING("정리중"), LOST("분실");
AVAILABLE("대여 가능", "대여") 로 작성하라는 말씀이신가요?
하나의 상수에만 두 개의 파라미터가 들어갈 수 있는지 알고싶습니다!

2023-10-04 07:21 UTC, hyun2371 commented on src/main/java/repository/FileRepository.java
> +            if (Objects.equals(id, book.getId())){
멘토님, Book에게 tell하는게 Book 클래스에 관련 메서드를 정의하라는 뜻이 맞을까요?

2023-10-04 08:13 UTC, hyun2371 commented on src/main/java/domain/Book.java
> +    public void printBookInfo() {
넵. 출력은 Book 클래스의 역할과 무관한 것 같아 IOManager로 이동시켰습니다!

2023-10-04 11:33 UTC, hyun2371 commented on src/main/java/repository/FileRepository.java
> +        return bookList.get(bookList.size()-1).getId()+1;
맞게 수정했는지 확인 부탁드립니다! 
[bookList -> 일급 컬렉션](37a2e62)

2023-10-05 09:53 UTC, cloudwi commented on src/main/java/controller/BookController.java
> +                bookService = new BookService(new NormalRepository(PATH, modeType.getBooks()), ioManager);
modeType에서 책들이 get으로 나오는 과정이 어색하다고 느껴지지 않으시나요?

2023-10-05 09:53 UTC, cloudwi commented on src/main/java/controller/BookController.java
> +        runMode(mode);
selectMode 매서드 안에서 runMode 매서드를 실행 시켜주고 있어요.

매서드의 이름으로 의도를 분명하게 나타내는 것이 좋을 것 같아요.

2023-10-05 09:53 UTC, cloudwi commented on src/main/java/controller/BookController.java
> +    public void runMode(String mode) {
runMode 매서드가 public 일 필요가 있을까요?

2023-10-05 09:53 UTC, cloudwi commented on src/main/java/controller/BookController.java
> +        bookService.reportLostBook(Integer.valueOf(ioManager.getInput()));
ioManager.getInput() 에서 예외가 발생하는 것을 reportLostBook()에서 몰라도 처리할 수 있지 않을까요?

2023-10-05 09:53 UTC, cloudwi commented on src/main/java/repository/NormalRepository.java
> +                .filter(book -> book.getTitle().contains(title))
getTitle() 형태로 book에서 title을 받아오는 것 보단. Title을 넘겨서 결과 값을 받는 형태가 좋지 않을까요?

2023-10-05 09:53 UTC, cloudwi commented on src/main/java/service/BookService.java
> +        Book book = new Book(repository.createId(), title, author, page);
도서를 저장할때 유효성 검사와 같은 로직이 추가된다면 createId 시점을 고민해보시면 좋을 것 같아요.

2023-10-05 10:38 UTC, hyun2371 commented on src/main/java/controller/BookController.java
> +                bookService = new BookService(new NormalRepository(PATH, modeType.getBooks()), ioManager);
그럼 책들은 Controller에서 주입해주는게 맞는걸까요?

539b6951d398bbfd3f14b4ce971392f500224237 는 ModeType에 따라 message를 받아오고,
7f600e87223b4a23b6fdc3ca89efade6c27aab3b 는 ModeType에 따라 message와 bookService를 받아오는 버전인데 어떤게 더 자연스러울까요?

저는 모드에 따른 상태와 동작들을 한 곳에 모아두는게 맞다고 생각해 아래 버전으로 바꾸었습니다.
이렇게 하면 ModeType에 너무 많은 책임이 부여된건지 알고 싶습니다!

2023-10-05 11:45 UTC, hyun2371 commented on src/main/java/service/BookService.java
> +        Book book = new Book(repository.createId(), title, author, page);
동일한 책이 존재하는지 확인하는 유효성 검사를 추가하고, 해당 검사가 끝나면 Id를 생성해 할당하도록 바꾸었습니다! [도서 저장 유효성 검사 추가](https://github.com/hyun2371/java-library-management/commit/87fffc6312b3c29696ab4e6e0c92b08f33de9ffe)

2023-10-05 12:19 UTC, hyun2371 commented on src/main/java/repository/NormalRepository.java
> +                .filter(book -> book.getTitle().contains(title))
동일한 title이 있는지 확인하는 함수를 Book에 추가하였습니다!
f500ccdcf573dac0c8ab3f2f5505b8e95bedeab8

2023-10-05 12:32 UTC, hyun2371 commented on src/test/java/FileServiceTest.java
> +        service = new BookService(repository);
할당할 때 바로 초기화되도록 수정하였습니다! bf7cac91164463f30f83cd003e07973da92c85a6

2023-10-06 06:13 UTC, hyun2371 commented on src/main/java/controller/BookController.java
> +            case "1"->{
그러면 selectFunction도 enum으로 생성하는게 더 좋을까요?

2023-10-07 09:42 UTC, aegis1920 commented on src/main/java/controller/BookController.java
> +            case "1"->{
1과 2는 BookExecuteMode로 직관적일 것 같은데요. funtion까지 들어가려면 BookModeExecutor 이런 식으로 되어야할 것 같아요.

2023-10-07 09:44 UTC, aegis1920 commented on src/main/java/domain/Book.java
> +    @Builder
취향에 따라 갈리는 부분이라.. 이렇게 보니 또 괜찮아보이네요ㅎㅎ그대로 쓰시죠!

2023-10-07 09:48 UTC, aegis1920 commented on src/main/java/domain/Book.java
> +    public boolean isStillCleaning(){
returnTime이 null일 때 다른 곳에서 이 메서드가 쓰일 수도 있을 것 같은데요. 이를 방지하기 위해 NPE에 대한 대비책을 해두는 것도 좋아보입니다!

2023-10-07 09:49 UTC, aegis1920 commented on src/main/java/repository/FileRepository.java
> +            if (Objects.equals(id, book.getId())){
네 맞습니다! 저번에 말씀드렸던 https://martinfowler.com/bliki/TellDontAsk.html 요거 읽어봐주세요!

2023-10-07 09:50 UTC, aegis1920 commented on src/main/java/repository/FileRepository.java
> +        return bookList.get(bookList.size()-1).getId()+1;
일급컬렉션이 무엇인지 먼저 확인이 필요해보입니다! 뭐라고 생각하셨을까요..? 저는 요 [링크](https://jojoldu.tistory.com/412)를 생각했습니다!

2023-10-07 09:52 UTC, aegis1920 commented on src/main/java/domain/Status.java
> +    AVAILABLE("대여 가능"), BORROWED("대여중"), CLEANING("정리중"), LOST("분실");
아뇨, `AVAILABLE`은 `가능한` 이라는 뜻이라서 `대여`라는 단어가 들어가야할 것 같다고 생각했었습니다. e.g. BORROW_AVAILABLE

2023-10-07 09:53 UTC, aegis1920 commented
> 각 테스트 함수에서 책을 저장하고 가져오는 코드가 중복되어서요. 해당 로직을 메서드로 추출 후 beforeEach()에서 호출하는게 더 가독성이 있을지 궁금했습니다!

넵 그런 이유라면 beforeEach에서 호출해도 될 것 같습니다!

2023-10-08 03:37 UTC, hyun2371 commented on src/main/java/repository/FileRepository.java
> +            if (Objects.equals(id, book.getId())){
넵 참고하겠습니다. 감사합니다!

2023-10-08 03:45 UTC, hyun2371 commented on src/main/java/domain/Book.java
> +    public boolean isStillCleaning(){
`if (returnTime==null) return false;`
위 조건문 추가했습니다!

2023-10-08 04:35 UTC, hyun2371 commented on src/main/java/domain/Book.java
> +    public boolean isStillCleaning(){
<img width="558" alt="image" src="https://github.com/prgrms-be-devcourse/java-library-management/assets/77109954/df276747-98c9-4fd7-ad58-5b9f6636ceca">
<img width="624" alt="image" src="https://github.com/prgrms-be-devcourse/java-library-management/assets/77109954/7a6d93d5-3640-4933-994a-9e79671a9e92">

위 경우들에서만 isStillCleaning() 메서드를 사용하고 있습니다!
반납 시 반납시간이 저장되지 않을 경우를 생각해 NPE 대비 로직을 작성하라는 말씀이신걸까요?

2023-10-08 09:30 UTC, hyun2371 commented on src/main/java/controller/BookController.java
> +    public void selectMode(){
모드 선택과 메뉴 선택 로직을 각각 BookController로부터 분리했습니다! 함수명도 runMode() -> applyMode()로 변경하였습니다!

2023-10-08 09:35 UTC, hyun2371 commented on src/main/java/domain/Status.java
> +    AVAILABLE("대여 가능"), BORROWED("대여중"), CLEANING("정리중"), LOST("분실");
넵. 대여의 의미가 들어가도록 수정하였습니다!

2023-10-08 11:13 UTC, hyun2371 commented on src/main/java/controller/BookController.java
> +            case "1"->{
ModeType과 MenuType으로 각각 분리했습니다! 제가 이번 프로젝트 때 Enum 클래스를 처음 활용해보는거라 두 클래스 모두 검토해주시면 감사하겠습니다!

2023-10-08 11:50 UTC, hyun2371 commented on src/main/java/controller/BookController.java
> +        bookService.reportLostBook(Integer.valueOf(ioManager.getInput()));
throws가 없으면 UnhandledException이라고 오류가 떠서 throws를 추가하였습니다!

2023-10-08 13:28 UTC, hyun2371 commented on src/main/java/repository/FileRepository.java
> +        return bookList.get(bookList.size()-1).getId()+1;
저는 컬렉션을 외부에서 생성자 주입 받아 초기화하는거라고 생각했습니다! 다시 공부하겠습니다!

2023-10-09 12:31 UTC, aegis1920 commented on src/main/java/controller/BookController.java
> +            case "1"->{
ModeType이나 MenuType 모두 Enum 내에 서비스 로직이 들어가있습니다. 서비스 로직은 분리하는 게 좋지 않을까 싶은데요. 예를 들어 ModeType 이라고 한다면 말 그대로 ModeType을 나타내줘야할 것 같은데 BookService를 로드한다던가 하는 것은 ModeHandler와 같은 다른 클래스로 분리하는 게 좀 더 명확하지 않을까싶어요.

2023-10-09 12:34 UTC, aegis1920 commented on src/main/java/domain/Book.java
> +    public boolean isStillCleaning(){
아뇨, isStillCleaning 함수는 Duration.between 함수의 첫 번째 인자로 returnTime이 들어가게 되는데요. 이때 Duration.between 함수를 보면 첫 번째 인자가 not null이어야 해서요. returnTime이 nullable하기 때문에 null이 들어갈 가능성을 줄여야하지 않을까 싶었습니다. 아니면 Duration.between 을 호출하기 전에 null 체크를 하던가요!

2023-10-09 12:35 UTC, aegis1920 commented
피드백 끝까지 반영하시느라 고생 많으셨습니다! 👍 
과제는 여기서 머지하겠습니다! 이후에 궁금한 점이 있으시면 DM주시거나 코멘트 따로 남겨주세요!

2023-10-09 12:35 UTC, merged