[5기 - 박주한] 1~2주차 과제: 도서 관리 어플리케이션 제출합니다.
prgrms-be-devcourse/java-library-management pull request #34
Opened 2023-10-02 04:52 UTC by ParkJuhan94

## 📌 과제 설명 

## 👩‍💻 요구 사항과 구현 내용 

## ✅ 피드백 반영사항  

## ✅ PR 포인트 & 궁금한 점

2023-10-10 14:46 UTC, SangHyunGil requested changes
리뷰 반영해주시느라 고생많으셨어요~
코멘트 남겼으니 확인 부탁드릴게요!
테스트 코드는 추가적으로 작성이 필요해보여 아직 리뷰는 하지 않았으니 반영하면서 같이 작성해주세요!

---

커밋 단위는 하나의 기능 단위만 담고있으면 좋고 명확하게 표현되면 좋을 것 같아요.
이번 반영에서 한 번 적용해보면 어떨까요~?

2023-10-10 14:46 UTC, SangHyunGil commented on build.gradle
> -
스프링 의존성 제거 👍

2023-10-10 14:46 UTC, SangHyunGil commented on src/main/java/com/libraryManagement/io/BookIO.java
> +//    }
사용하지 않는다면 제거해도 괜찮을 것 같네요.

2023-10-10 14:46 UTC, SangHyunGil commented on src/main/java/com/libraryManagement/service/BookService.java
> +    private Book createBook(BookResponseDTO bookResponseDTO) throws IOException {
현재 public, private 순서가 여기저기 흩어져 있는 것 같아요.
Class Layout 관련해서 고민해보시면 좋을 것 같아요.
style guide를 참고해보시면 좋을 것 같은데 아래 오라클 관련 문서 같이 첨부드려요.
https://www.oracle.com/java/technologies/javase/codeconventions-fileorganization.html

2023-10-10 14:46 UTC, SangHyunGil commented on src/main/java/com/libraryManagement/service/BookService.java
> +                repository.updateBookStatus(id, RENT.getName());
String 값 대신 Enum 자체를 사용해도 좋을 것 같아요.

2023-10-10 14:46 UTC, SangHyunGil commented on src/main/java/com/libraryManagement/util/BookResponseDTO.java
> +public class BookResponseDTO {
Dto가 Util 패키지에 있어야할까요~?

2023-10-10 14:46 UTC, SangHyunGil commented on src/main/java/com/libraryManagement/domain/Book.java
> +    public enum Status {
inner class로 추가하신 이유가 있으신가요?

2023-10-10 14:46 UTC, SangHyunGil commented on src/main/java/com/libraryManagement/service/BookService.java
> +    public void rentBook(long id) throws InterruptedException {
하나의 updateBookStatus에서 각각에 대한 행위를 분리하니 하나의 역할만 수행하게되어 더욱 명확해지고 테스트가 쉬워지겠네요 👍

2023-10-10 14:46 UTC, SangHyunGil commented on src/main/java/com/libraryManagement/repository/MemoryRepository.java
> +        bookMap.put(getNumCreatedBooks(), book);
현재 id 생성 전략을 현재 가지고 있는 book의 사이즈만큼으로  가져가게 되면 아래와 같은 문제가 생길 수 있을 것 같아요.
- 1, 2, 3 이 존재하는데 3을 지운 후 새로 추가하면 2 값으로 새로 추가되어 식별자가 중복된다.

이 부분을 해결할 수 있는 방법을 고민해보시고 수정해주시면 좋을 것 같아요.

2023-10-10 14:46 UTC, SangHyunGil commented on src/main/java/com/libraryManagement/repository/MemoryRepository.java
> +            // throw Exception
별도의 예외를 던지지는 않는건가요?

2023-10-10 14:46 UTC, SangHyunGil commented on src/main/java/com/libraryManagement/io/BookIO.java
> +//    }
사용하지 않는거라면 제거해주셔도 좋습니다.

2023-10-10 14:46 UTC, SangHyunGil commented on src/main/java/com/libraryManagement/exception/BookException.java
> +}
CheckedException에서 Unchecked Exception으로 변경하신 이유는 뭔가요~?

2023-10-10 14:46 UTC, SangHyunGil commented on src/main/java/com/libraryManagement/service/BookService.java
> +        if(repository.findBookById(id).isPossibleRent())
그냥 간단한 생각인데 아래와 같이 북을 찾아오고 별도로 가능한지만 처리해줘도 가독성이 좋아질 것 같네요~

```
if (book.isPossibleRent())
```

2023-10-10 14:46 UTC, SangHyunGil commented on src/main/java/com/libraryManagement/repository/MemoryRepository.java
> +            throw new RuntimeException(BOOK_NOT_FOUND_ID.getMessage());
생성해주신 BookException을 활용해보면 어떨까요~?

2023-10-10 14:46 UTC, SangHyunGil commented on src/main/java/com/libraryManagement/io/BookMenu.java
> +                    System.out.println("[System] 0번을 입력하여 프로그램을 종료합니다.\n");
이전에 리뷰드렸던 것처럼 \n을 제외하고 system.lineseparator()을 적용해보는건 어떨까요~? (아래도요!)

2023-10-10 14:46 UTC, SangHyunGil commented on src/main/java/com/libraryManagement/controller/BookController.java
> +    public void findBooks() throws Exception {
왜 Exception을 명시적으로 던져줘야할까요~?

2023-10-10 14:46 UTC, SangHyunGil commented on src/main/java/com/libraryManagement/repository/FileRepository.java
> +            throw new RuntimeException(FILE_WRITE_FAILED.getMessage());
생성해둔 BookException을 활용해보면 어떨까요~?

2023-10-10 14:46 UTC, SangHyunGil commented on src/main/java/com/libraryManagement/repository/Repository.java
> +    List<Book> findAllBooks() throws Exception;   // 모든 책 반환
명시적으로 Exception을 던져줘야하는 이유는 뭘까요~?

2023-10-14 15:03 UTC, ParkJuhan94 commented on src/main/java/com/libraryManagement/service/BookService.java
> +    private Book createBook(BookResponseDTO bookResponseDTO) throws IOException {
style guide 를 살펴보았는데!

변수, 메서드 정렬 순서를
 1.  public -> protected -> private  순으로 하되
 2.  메서드는 접근제어자 보다는 기능으로 묶어서 정렬해주는게 좋은거죠? 
 
public insertBook() 과 private createBook() 이 기능적으로 묶인다고 생각했습니다! 
전체적으로 class layout 손보고있습니다~!

2023-10-14 16:17 UTC, ParkJuhan94 commented on src/main/java/com/libraryManagement/util/BookResponseDTO.java
> +public class BookResponseDTO {
view, controller, service 에서 공통으로 사용하고 있어서 따로 Dto 패키지로 분리해보았습니당

2023-10-14 19:19 UTC, ParkJuhan94 commented on src/main/java/com/libraryManagement/domain/Book.java
> +    public enum Status {
단순히 Book 과 관련있어서 inner 로 넣었는데, 사용하기에 더 불편해 보이네요. 
Book 밖으로 빼는것도 좋을까요?

2023-10-14 19:26 UTC, ParkJuhan94 commented on src/main/java/com/libraryManagement/domain/Book.java
> +    public enum Status {
enum BookStatus 를 Book.java 로 빼는 것이 
패키지 구조를 볼 때,
호출할 때 편한것 같아서 빼보았습니다!

2023-10-14 19:30 UTC, ParkJuhan94 commented on src/main/java/com/libraryManagement/service/BookService.java
> +    public void rentBook(long id) throws InterruptedException {
넵 제일 쾌감을 느꼈던 리팩토링 이었던것 같아요 ㅎㅎㅎ

2023-10-15 09:49 UTC, ParkJuhan94 commented on src/main/java/com/libraryManagement/repository/MemoryRepository.java
> +        bookMap.put(getNumCreatedBooks(), book);
저는 delete 할 때 book을 실제로 지우지않고 상태만 '지워짐'으로 업데이트 시키도록 해서,
식별자 id 가 중복되지 않도록 해놓았습니다~!

이 경우 다른 문제가 있을 수 있을까요?

2023-10-15 09:50 UTC, ParkJuhan94 commented on src/main/java/com/libraryManagement/repository/MemoryRepository.java
> +            // throw Exception
제가 커밋을 이상하게 한 건지 ㅠㅠ 
뒤에서 날린 커밋에서는 예외를 넣어놓았습니다

2023-10-16 10:55 UTC, merged

2023-10-22 07:14 UTC, ParkJuhan94 commented on src/main/java/com/libraryManagement/io/BookIO.java
> +//    }
넵넵