[5기 - 김주환] 1~2주차 과제: 도서 관리 어플리케이션 제출합니다.  (수정중)
prgrms-be-devcourse/java-library-management pull request #36
Opened 2023-10-04 07:10 UTC by happyjamy

## 📌 과제 설명 

## 👩‍💻 요구 사항과 구현 내용 

## ✅ 피드백 반영사항  

## ✅ PR 포인트 & 궁금한 점

2023-10-09 03:57 UTC, SangHyunGil requested changes
리뷰 반영해주시느라 너무 고생많으셨어요!
몇 가지 코멘트 남겼으니 확인 부탁드려요!
---
1. 종료와 여러 타입을 콘솔에 보여주기 위해 MenuResponseSender 을 각각 만들었습니다! 패턴 괜찮은지 확인 부탁드려용

추상화를 통해 ListResponse인지 SingleResponse인지 Exit인지를 구분 없이 사용할 수 있다는 점에서 실제로 사용할때나 추후에 새로운 타입이 추가되어야 할 때 유연하게 사용할 수 있을 것 같아요.
다만 코멘트에서 적어놓았듯이 불필요한 추상화로 인해 오히려 복잡성을 늘리는게 아닐까를 고민해보면 좋을 것 같아요.
- "정말 새로운 Response 타입이 많이 추가될까?"라고 고민해봤을때는 아닐 수도 있을 것 같아요.
- "Console 말고 다른걸 활용해 사용할 니즈가 생길까?"와 같이 고민해보면 당장의 요구사항에는 맞지 않고 일어나지 않은 미래를 너무 생각한 설계이기도 한 것 같아요.
항상 추상화에 대한 고민은 저도 많이 하는 것 같아요 😄 

2. 테스트 때문에 Book 빌더에 id 값도 같이 받게 해뒀는데 괜찮은지 모르겠습니다ㅠㅠ
- 저는 식별자 자체가 도메인에서 유효한 의미를 가질 수 있는 값이라고 생각해요. 현재는 큰 의미없이 Sequence하게 생성하는 값이지만 추후에는 특정 룰을 기반으로 생성하는 비즈니스적인 부분을 포함하게 되면 외부에서 주입해주는 경우도 생기때문에 어색하지 않은 것 같아요.

3. Book 에서 상태 바꾸는 메서드가 행동 기반이 아닌 상태 기반이라 함수 이름에 구현이 다 들어나 있습니다! 이 부분 괜찮을까요?
- 코멘트에 달아놓은 것처럼 액션이라는 상태 기반으로 체크하는 것이 아닌 행위 자체를 검증하는 메서드를 노출하여 체크하도록 하면 해당 부분을 해소할 수 있을 것 같아요.

4. 혹시 유닛 테스트는 ( 서비스 + 도메인 ) 만 해도 되는 걸까요...ㅎㅎ
- 사실 테스트는 꼼꼼하게 하면 할수록 좋지만 여유가 나지 않을 수 있기에 저희에게 중요한 도메인은 "꼭" 작성하려고 하는 편이에요.
그래서 말씀주신 서비스/도메인 영역은 항상 하는게 좋고 여유가 되면 컨트롤러쪽도 같이 해보면 좋을 것 같아요~

2023-10-09 03:57 UTC, SangHyunGil commented on src/test/java/com/programmers/presentation/BookControllerTest.java
>      void testGetAllBooks() {
컨트롤러에 대한 테스트는 살려둬도 좋을 것 같아요.

2023-10-09 03:57 UTC, SangHyunGil commented on src/test/java/com/programmers/presentation/BookControllerTest.java
>      void testSearchBooksByTitle() {
요기도 마찬가지요.

2023-10-09 03:57 UTC, SangHyunGil commented on src/main/java/com/programmers/infrastructure/IO/ConsoleInteractionAggregator.java
> +    public <T> void displayListInfo(List<T> ListItems) {
변수명은 소문자로 시작하도록 변경해주세요.

2023-10-09 03:57 UTC, SangHyunGil commented on src/main/java/com/programmers/infrastructure/IO/responseCommand/ResponseSender.java
> +public interface ResponseSender {
아래에 대해서는 항상 고민해보면 좋은 것 같아요 👍 
- 추상화를 통해 얻는 유연성 vs 추상화로 인해 생기는 복잡성

2023-10-09 03:57 UTC, SangHyunGil commented on src/main/java/com/programmers/infrastructure/IO/responseCommand/ResponseSender.java
> +    Class<? extends ConsoleResponse> getProcessClass();
위처럼 클래스 자체를 노출시키는 방법도 있겠지만 오픈 소스들 보시면 아래와 같이 클래스 정보를 넘기고 해당 타입을 지원하는지 체크하는 패턴도 많이 사용됩니다.
`boolean supports(consoleResponse ConsoleResponse);`

2023-10-09 03:57 UTC, SangHyunGil commented on src/main/java/com/programmers/config/DependencyInjector.java
> +        SimpleModule module = new SimpleModule();
아래와 같이 체이닝 형태로 사용 가능해요.
```
new SimpleModule()
        .addDeserializer(BookStatus.class, new BookStatusDeserializer())
        .addSerializer(BookStatus.class, new BookStatusSerializer());
```

2023-10-09 03:57 UTC, SangHyunGil commented on src/main/java/com/programmers/config/DependencyInjector.java
>          this.objectMapper = new ObjectMapper();
아래와 같이 체이닝 형태로 사용 가능해요.
```
new ObjectMapper();
           .registerModule(module);
```

2023-10-09 03:57 UTC, SangHyunGil commented on src/main/java/com/programmers/domain/status/BookStatus.java
> +public interface BookStatus {
구두로 얘기 나누었던 것처럼 이렇게 상태를 인터페이스로 둠으로써 발생할 수 있는 문제점에 대해서도 생각해보면 좋을 것 같아요. 👍

2023-10-09 03:57 UTC, SangHyunGil commented on src/main/java/com/programmers/domain/status/BookStatus.java
> +    default void validateAction(Action action) {
상태인터페이스에 허용하는 행위를 선언하고 검증하는 메서드로 구현할 수도 있겠지만 현재와 같이 Action을 별도로 관리하게 되는 경우 Status와 Action을 항상 동기화해야하는 문제가 있을 수 있을 것 같아요.
(Action을 추가했는데 Status를 추가안하는 케이스 등등을 고려해야할 수 있을 것 같아요.)
 
그래서 상태 인터페이스에 각 행위를 위임하는 것 자체를 고민해봐도 좋을 것 같아요. 👍

2023-10-09 03:57 UTC, SangHyunGil commented on src/main/java/com/programmers/config/DependencyInjector.java
> +    private static class SingleInstanceHolder {
Holder를 사용해주셨군요 👍

2023-10-09 04:54 UTC, happyjamy commented on src/main/java/com/programmers/infrastructure/IO/responseCommand/ResponseSender.java
> +    Class<? extends ConsoleResponse> getProcessClass();
혹시 ConsoleResponse 인스턴스를 바로 넘기는 것 vs ConsoleResponse.getClass() 로 class 정보를 넘기는 것 뭐가 더 일반적일까요?

2023-10-09 04:59 UTC, happyjamy commented on src/main/java/com/programmers/infrastructure/IO/responseCommand/ResponseSender.java
> +    Class<? extends ConsoleResponse> getProcessClass();
그리고 boolean 을 return 할때 함수명에 is 를 안붙여도 될까용?

2023-10-09 05:05 UTC, happyjamy commented on src/main/java/com/programmers/infrastructure/IO/responseCommand/ResponseSender.java
> +    Class<? extends ConsoleResponse> getProcessClass();
해결!!!!🔍

2023-10-09 12:29 UTC, happyjamy commented on src/main/java/com/programmers/infrastructure/IO/ConsoleInteractionAggregator.java
> +    public <T> void displayListInfo(List<T> ListItems) {
[450eab1](https://github.com/prgrms-be-devcourse/java-library-management/pull/36/commits/450eab1f21b1b8c222c4c62c87e99c3a9961eb94)

변경하였습니다!

2023-10-09 12:30 UTC, happyjamy commented on src/main/java/com/programmers/infrastructure/IO/responseCommand/ResponseSender.java
> +    Class<? extends ConsoleResponse> getProcessClass();
[47471ff](https://github.com/prgrms-be-devcourse/java-library-management/pull/36/commits/47471ff22da8ece0e321bc232c15042b808b8393)

외부에서 class 를 넘겨 지원하는 타입인지 검사하는 형태로 변경 하였습니다!

2023-10-09 12:30 UTC, happyjamy commented on src/main/java/com/programmers/config/DependencyInjector.java
> +        SimpleModule module = new SimpleModule();
[70edba0](https://github.com/prgrms-be-devcourse/java-library-management/pull/36/commits/70edba0f8ab38fd6af49bcbe503ded756a661370)

변경 하였습니다!

2023-10-09 12:30 UTC, happyjamy commented on src/main/java/com/programmers/config/DependencyInjector.java
>          this.objectMapper = new ObjectMapper();
[70edba0](https://github.com/prgrms-be-devcourse/java-library-management/pull/36/commits/70edba0f8ab38fd6af49bcbe503ded756a661370)

변경 하였습니다!

2023-10-09 12:31 UTC, happyjamy commented on src/main/java/com/programmers/domain/status/BookStatus.java
> +public interface BookStatus {
[c499dae](https://github.com/prgrms-be-devcourse/java-library-management/pull/36/commits/c499dae7d00b7f8c03aa7b188169e71523d36f67)

넵!! 좋은 고민 감사합니다! 해당 고민은 팀원들과도 나누었습니다 🙏

2023-10-09 12:31 UTC, happyjamy commented on src/main/java/com/programmers/domain/status/BookStatus.java
> +    default void validateAction(Action action) {
넵! 오늘 게더에서 하신말 토대로 좀 더 고민해 보겠습니다!

2023-10-10 13:57 UTC, SangHyunGil approved these changes
그동안 과제 진행해주시고 리뷰 반영해주시느라 고생많으셨습니다!

이번 과제를 진행해주시면서 많은 고민들을 해주신 것 같아요. (요구사항 변화/프로토콜 변화 등)
이번에 너무 깊은 고민들을 많이해주신 것 같아서 다음에는 조금 더 과제에서 초점을 맞추는 부분에 대해 더 많이 고민해보면 좋겠다는 생각도 들었어요.

다만 많은 부분들을 고민해주신 덕에 구두로 리뷰하면서 고민해주신 부분들에 대해서도 많이 얘기하고 평소에 느끼셨던 부분들에 대한 것들에 대해서도 많이 얘기했었는데요.
이를 통해 기존에 있으셨던 고민들에 대해서 생각 정리도 하고 많은 것들을 알아가셨으면 해요.

머지해주셔도 좋습니다!

2023-10-10 13:57 UTC, SangHyunGil commented on src/main/java/com/programmers/infrastructure/IO/ConsoleInteractionAggregator.java
> +    public <T> void displayListInfo(List<T> listItems) {
👍

2023-10-10 13:57 UTC, SangHyunGil commented on src/main/java/com/programmers/domain/status/BookStatus.java
> +// 변경 가능성이 높다면 Enum 을 이용하는 방식이 좋다.
많은 고민들을 하시는게 느껴지네요 👍

2023-10-10 14:35 UTC, happyjamy commented on src/main/java/com/programmers/domain/status/BookStatus.java
> +// 변경 가능성이 높다면 Enum 을 이용하는 방식이 좋다.
우하하하 도찌님이 말하신걸 받아적은 것에 불과합니다... 좋은 가르침 주셔서 감사합니다!!

2023-10-10 14:35 UTC, merged