[5기 - 김남규] 1~2주차 과제: 도서 관리 어플리케이션 제출합니다.
prgrms-be-devcourse/java-library-management pull request #6
Opened 2023-09-27 12:32 UTC by GiHoo

## 📌 과제 설명 
도서 관리 애플리케이션입니다.
도서는 id, title, author, page, condition을 필드로 가집니다.
일반 모드와 테스트 모드로 구분되어 있습니다.
&nbsp;&nbsp;&nbsp;&nbsp; 일반 모드는 외부 파일에서 도서 정보를 읽어옵니다.(CSV 파일 사용)
&nbsp;&nbsp;&nbsp;&nbsp; 테스트 모드는 콘솔을 통해서만 도서 정보를 읽어올 수 있습니다.
각 모드에 진입하면 도서 등록, 전체 조회, 검색, 대여, 반납, 분실, 삭제, 종료 메뉴를 선택할 수 있습니다.

## 👩‍💻 요구 사항과 구현 내용 
Book : 도서 도메인입니다. setCondition 메서드로 도서 상태를 변경할 수 있습니다.
Console : 모드를 위한 입력을 받습니다.
Service : 각 모드에서 메뉴를 선택할 수 있고, 선택에 맞는 결과를 출력합니다.
&nbsp;&nbsp;&nbsp;&nbsp; GeneralService
&nbsp;&nbsp;&nbsp;&nbsp; TestService
Repository : Service에서 호출하는 메서드를 수행합니다. 저장 장소에서 불러오기, 저장, 조회등의 기능이 있습니다.
&nbsp;&nbsp;&nbsp;&nbsp; GeneralRepository
&nbsp;&nbsp;&nbsp;&nbsp; TestRepository

id값은 도서 리스트의 마지막 id값을 확인하여 1씩 증가시킵니다. 도서가 없다면 0으로 시작합니다.
일반 모드의 Repository에서는 외부 CSV파일을 불러와 list에 저장합니다.
대여, 분실 상태에서 반납 시 5분 도서 정리중 상태를 가지며, 5분이 지나면 대여 가능 상태로 바뀝니다.
모드 종료 시 도서 정리중인 상태의 도서가 있다면 대여 가능 상태로 변경되어 CSV파일에 저장됩니다.

## ✅ PR 포인트 & 궁금한 점 
1. 도서의 상태를 Enum으로 관리해보려 하는데 상태 변경을 위한 setter메서드가 필요한 것 같은데, 
이를 안쓰고 해결할 방법이 있는지 궁금합니다.
2. Service의 구현 클래스의 경우 많은 부분이 반복되는 것 같지만, 실제 출력되는 메세지는 각 메서드마다 차이가 있습니다. 
이런 경우에는 어떤 방식으로 가독성을 높일 수 있을지 궁금합니다.
3. Service 구현 클래스는 핵심 로직을 수행한다고 설계하였습니다. 
콘솔에 결과 출력과 Repository의 메서드 호출을 핵심 로직으로 생각했습니다.
이때, 콘솔에 결과 출력하는 부분을 가독성을 위해 클래스를 추가하는 것이 맞는 방법인지 궁금합니다. 
4. 테스트 코드 작성 시 테스트를 위해 테스트 클래스에 기존 메서드를 다시 정의해도 괜찮은지 궁금합니다.
ConsoleTest에서 Console클래스의 printMode를 반환 타입을 바꾸어 정의했습니다. 
5. 예외 처리를 생각할 때 어디까지 예외를 적용할 것인지 판단하는 기준이 궁금합니다.
이번 과제에서 콘솔로 모드를 입력 받을 때와 메뉴를 고를 때만 입력에 대한 예외를 처리했습니다.
메뉴를 고른 후부터는 잘못된 입력을 통해 서비스가 종료되면 안될 것 같다는 생각을 했기 때문입니다.
프로젝트 시 어느 깊이(부분)까지 예외를 처리하는 것이 좋은 지에 대한 의견이 궁금합니다.

처음 구현을 할 때 객체지향적인 코드와 MVC패턴을 생각하며 코드를 작성했었는데 
과제를 완성하고 나서는 과연 객체지향적인 코드일까라는 생각을 하게 되었습니다.
작성한 코드를 어떻게 하면 개선할 수 있을지 이 부분을 중심으로 피드백 해주시면 감사하겠습니다!

2023-09-28 09:02 UTC, twotwobread reviewed
전체적으로 repository에서 많은 로직들을 수행한다고 생각되어서 책임을 분리해보면 더 좋을 것 같습니다. 컨벤션과 같은 부분이 아니라면 제 리뷰를 그대로 받아들이기 보다는 생각해보고 이해가 되지 않거나 동의하지 못하는 부분들에 대해서 다양한 분들의 의견을 들으면 좋을 것 같습니다!!

2023-09-28 09:02 UTC, twotwobread commented on app/src/main/java/io/Console.java
> +            throw new RuntimeException("[System] 잘못된 입력입니다.");
좀 더 세부적인 exception을 사용하면 더 좋을 것 같습니다. runtime exception은 너무 범위가 크다고 생각합니다.
https://medium.com/@rafacdelnero/11-mistakes-java-developers-make-when-using-exceptions-af481a153397

2023-09-28 09:02 UTC, twotwobread commented on app/src/main/java/io/Console.java
> +        if (mode == 1) {
enum class로 좀 더 명시적으로 가독성 좋게 구성하면 좋을 것 같습니다.

2023-09-28 09:02 UTC, twotwobread commented on app/src/main/java/service/GeneralService.java
> +        load();
생성자는 객체를 생성하기 위한 메서드인데 로직이 돌아가는 형태가 적합하다고 생각되진 않습니다. Console 측에선 객체를 생성하기만 했는데 로직이 돌아가는게 의아하게 느껴졌습니다.

2023-09-28 09:02 UTC, twotwobread commented on app/src/main/java/service/GeneralService.java
> +    Repository repository = new GeneralRepository();
의존성을 외부에서 주입하는 방식을 이용하는 것이 더 객체지향스럽다 생각합니다. 만약 General Service를 실행했을 때 file repository를 이용하는 것이 아니라 in-memory를 사용하고 싶다면 Service 클래스 내부가 변경되어야 합니다. 주입하는 방식이라면 객체의 내부를 수정하는 것이 아니라 해당 주입하는 객체를 변경하면 되기에 외부에서 주입하는 방식이 좋을 것 같습니다.

2023-09-28 09:02 UTC, twotwobread commented on app/src/main/java/service/GeneralService.java
> +    Scanner scanner = new Scanner(System.in);
접근 지정자가 필요합니다.

2023-09-28 09:02 UTC, twotwobread commented on app/src/main/java/repository/GeneralRepository.java
> +    private final static String csvFileName = "/Users/kimnamgyu/desktop/study/dev-course/csvFile.csv";
환경이 바뀌면 path가 바뀌게 되니까 csv 파일을 못읽어 올 것 같습니다. 상대 path를 이용하거나 resource path를 읽어올 수 있는 방법을 찾아보는 것도 하나의 방법이 될 것 같습니다.

2023-09-28 09:02 UTC, twotwobread commented on app/src/main/java/repository/GeneralRepository.java
> +    private final static String csvFileName = "/Users/kimnamgyu/desktop/study/dev-course/csvFile.csv";
static final으로 쓰는 것이 관례입니다!!

2023-09-28 09:02 UTC, twotwobread commented on app/src/main/java/repository/GeneralRepository.java
> +            e.printStackTrace();
기존 도서를 load하는 중에 exception이 발생하면 stack trace 출력 후 넘어가는 건가요?

2023-09-28 09:02 UTC, twotwobread commented on app/src/main/java/repository/GeneralRepository.java
> +                    book.setCondition("대여 중");
repository는 데이터에 대한 접근하는 책임만을 가지고 상태를 확인하는 것과 같은 로직은 상위 계층에서 수행하는 것이 repository 객체의 책임을 줄이는 방법 같습니다.

2023-09-28 09:02 UTC, twotwobread commented on app/src/test/java/repository/GeneralRepositoryTest.java
> +    private final static String csvFileName = "/Users/kimnamgyu/desktop/study/dev-course/csvFile.csv";
테스트에서 save한 도서 정보가 일반 모드에서도 읽혀지진 않나요?? 테스트 환경은 분리해서 가져가면 더 좋을 것 같아요. (테스트를 위한 csv 파일을 만들어서 이를 이용.)

2023-09-28 13:42 UTC, GiHoo commented
리뷰 감사합니다! 작성하면서 발견하지 못한 부분, 생각하지 못한 부분을

2023-09-28 13:47 UTC, GiHoo commented
> 전체적으로 repository에서 많은 로직들을 수행한다고 생각되어서 책임을 분리해보면 더 좋을 것 같습니다. 컨벤션과 같은 부분이 아니라면 제 리뷰를 그대로 받아들이기 보다는 생각해보고 이해가 되지 않거나 동의하지 못하는 부분들에 대해서 다양한 분들의 의견을 들으면 좋을 것 같습니다!!

리뷰 감사합니다! 
작성하면서 발견하지 못한 부분, 생각하지 못한 부분을 알 수 있게 되었습니다.
enum을통해 가독성을 높여보겠습니다.
예외를 세분화 시켜보겠습니다.
Repository의 책임 분리와 의존성 주입 부분을 생각하여 적용시켜보겠습니다!

2023-09-28 13:53 UTC, twotwobread commented
1. 도서의 상태를 Enum으로 관리해보려 하는데 상태 변경을 위한 setter메서드가 필요한 것 같은데, 이를 안쓰고 해결할 방법이 있는지 궁금합니다.
```
setter와 같이 상태를 바꾸는 메서드가 없는 방식은 떠오르지 않지만 상태를 변경하는 코드가 꼭 필요한 경우엔 사용해도된다고 생각합니다. 
```
2. Service의 구현 클래스의 경우 많은 부분이 반복되는 것 같지만, 실제 출력되는 메세지는 각 메서드마다 차이가 있습니다. 이런 경우에는 어떤 방식으로 가독성을 높일 수 있을지 궁금합니다.
```
일단 출력과 같은 부가적인 로직과 대여, 반납, 분실 등의 애플리케이션 주요 로직을 분리할 것 같습니다. 주요 로직과 부가적 로직이 섞이면 가독성이 나빠지는 것 같습니다.  
```

3. Service 구현 클래스는 핵심 로직을 수행한다고 설계하였습니다. 콘솔에 결과 출력과 Repository의 메서드 호출을 핵심 로직으로 생각했습니다. 이때, 콘솔에 결과 출력하는 부분을 가독성을 위해 클래스를 추가하는 것이 맞는 방법인지 궁금합니다.
```
저는 일단 repository의 메서드 호출은 저장된 데이터에 대한 접근만을 수행한다고 생각하고 콘솔에 결과 출력은 부가적인 로직이라고 생각합니다.
그래서 콘솔에 결과를 출력하는 부분은 핵심 로직들(대여, 반납, 분실 등)과 분리되는 클래스로 추가되는 것이 좋지 않을까 생각합니다.
```
4. 테스트 코드 작성 시 테스트를 위해 테스트 클래스에 기존 메서드를 다시 정의해도 괜찮은지 궁금합니다. ConsoleTest에서 Console클래스의 printMode를 반환 타입을 바꾸어 정의했습니다.
```
저는 좋지 않다고 생각합니다. 테스트 코드의 가장 큰 목적은 운영 코드에서의 버그가 발생했을 때 이를 빠르게 파악하고 해결하기 위함이라고 생각합니다.
근데 테스트 클래스에서 새롭게 만든 메서드를 이용해서 로직을 테스트 한다는 것은 운영 시 돌아가는 코드를 테스트 하는 것과는 다르다고 생각합니다.
그리고 이렇게 되면 특정 로직이 바뀌었을 때 운영 코드 뿐만 아니라 테스트 코드도 같이 바뀌어야 한다는 문제가 있기에 좋지 않다고 생각합니다.
```
6. 예외 처리를 생각할 때 어디까지 예외를 적용할 것인지 판단하는 기준이 궁금합니다. 이번 과제에서 콘솔로 모드를 입력 받을 때와 메뉴를 고를 때만 입력에 대한 예외를 처리했습니다. 메뉴를 고른 후부터는 잘못된 입력을 통해 서비스가 종료되면 안될 것 같다는 생각을 했기 때문입니다. 프로젝트 시 어느 깊이(부분)까지 예외를 처리하는 것이 좋은 지에 대한 의견이 궁금합니다.
```
컨트롤할 수 없는 부분들인 외부로 받은 입력과 같은 요소를 이용하는 로직에서 validation를 수행하고 예외를 던지는 것 같습니다.
```

2023-09-29 06:26 UTC, ksy90101 requested changes
여기도 제대로된 파일이 있어야 할때, 리뷰 하도록 하겠습니다.

1. .idea파일은 무엇일까요? 이게 있어야 할까요?
2. app폴더 내에 애플리케이션이 있어야 하는 이유가 있을까요?

두가지를 고민해보시고, .idea는 필요 없다면 gitignore를 진행해주세요.

모르겠다면 슬랙으로 DM주세요~

2023-09-30 02:29 UTC, GiHoo commented
> 여기도 제대로된 파일이 있어야 할때, 리뷰 하도록 하겠습니다.
> 
> 1. .idea파일은 무엇일까요? 이게 있어야 할까요?
> 2. app폴더 내에 애플리케이션이 있어야 하는 이유가 있을까요?
> 

1. .idea 파일은 intelliJ가 프로젝트 생성 시 자동으로 만들어주는 파일입니다. git에 올릴 필요가 없기에 삭제하였습니다!
2. app폴더는 Gradle빌드를 위해 만들었던 모듈 파일인데 굳이 app폴더로 프로젝트 구조를 덮을 필요가 없는 것 같습니다. 삭제하였습니다!

2023-09-30 06:50 UTC, ksy90101 requested changes
리뷰를 너무 많이 남기면 어려울거 같아서 중간에 끊을게요.
리뷰를 보기 전에 아래를 한번 신경써서 리팩토링을 크게 한 뒤에 하면 어떨까요?

1. 의미잇는 변수명을 사용해보면 어떨까요? list, iterator라는 단어보단 books와 같은 단어르 사용해보세요.
2. inner enum, class를 빼고 패키지로 한번 나타내면 어떨까요?
3. Service는 무엇일까요? MVC에서 View는 왜 잇을까요? View코드를 View로 한곳에 모아보세요.
4.

2023-09-30 06:50 UTC, ksy90101 commented on build.gradle
> +    implementation 'org.apache.commons:commons-csv:1.8' // Apache Commons CSV 라이브러리 의존성 추가
라이브러리를 쓰지 않고 한번 해보시겠어요?
라이브러리를 쓰지 않아도 충분히 현재 미션에선 해볼수 있습니,다.

당연히 저도 라이브러리를 쓰는걸 선호하긴 합니다. 예를들어 라이브러리의 기능을 10%만 사용하는데, 90%의 쓸모없는 코드가 같이 빌드될 이유가 있을까요?

간단하게 구현할수 있는것들은 직접 구현해봄으로써 라이브러리의 소중함과 실력을 올리면 어떨가해요.

2023-09-30 06:50 UTC, ksy90101 commented on build.gradle
> +    testImplementation group: 'org.assertj', name: 'assertj-core', version: '3.24.2'
현재 문법은 옛날 방식이에요 ㅎㅎ
최신 문법으로 변경해보면 어떨까요?

2023-09-30 06:50 UTC, ksy90101 commented on build.gradle
> +targetCompatibility = '17'
👍

2023-09-30 06:50 UTC, ksy90101 commented on build.gradle
> +}
https://blog.coderifleman.com/2015/04/04/text-files-end-with-a-newline/

이글을 한번 참고해보면 어떨까요?

2023-09-30 06:50 UTC, ksy90101 commented on src/main/java/domain/Book.java
> +    public String toString() {
toString은 언제 쓰일까요?
https://github.com/Meet-Coder-Study/book-effective-java/blob/main/3%EC%9E%A5/12_toString%EC%9D%84_%ED%95%AD%EC%83%81_%EC%9E%AC%EC%A0%95%EC%9D%98%ED%95%98%EB%9D%BC_%EC%9D%B4%ED%98%B8%EB%B9%88.md
위 글을 한번 참고해보세요.

2023-09-30 06:50 UTC, ksy90101 commented on src/main/java/domain/Book.java
> +    }
inner enum을 쓴 이유가 있나요?
아울러 enum의 이름 규칙은 무엇일까요?

2023-09-30 06:50 UTC, ksy90101 commented on src/main/java/io/Console.java
> +    Scanner scanner = new Scanner(System.in);
접근제어자, final, static 이 총 3개의 키워드가 있어야 할지 고민해보면 어떨까요?

2023-09-30 06:50 UTC, ksy90101 commented on src/main/java/io/Console.java
> +            service = new TestService();
1과 2가 무엇이 의미하는지 한번 상수로 나타내면 어떨까요?

2023-09-30 06:50 UTC, ksy90101 commented on src/main/java/repository/GeneralRepository.java
> +            csvReader.close();
try-with-resources를 한번 찾아보면 어떨까요?

2023-09-30 06:50 UTC, ksy90101 commented on src/main/java/repository/GeneralRepository.java
> +            list.add(new Book(id, title, author, page, "대여 가능"));
"대여 가능"이라는 키워드를 상수로 나타내면 어떨까요?
상수로 하면 어떤 장점이 있을지 고민해보세요.

2023-09-30 06:50 UTC, ksy90101 commented on src/main/java/repository/GeneralRepository.java
> +            if (title.toLowerCase().contains(searchTitle)) {
book에게 맞는게 있는지 메시지를 던지면 어떨까요?

2023-09-30 06:50 UTC, ksy90101 commented on src/main/java/repository/GeneralRepository.java
> +        }
2depth이상이라면 너무 많은 행동을 하는걸수도 있습니다.
이런경우 메서드로 분리해서 의미를 나타내면 어덜까요?

2023-09-30 06:50 UTC, ksy90101 commented on src/main/java/repository/GeneralRepository.java
> +    public String rentById(int rentId, List<Book> list) {
list라는 단어는 어떤걸 의미하는지 알기가 어렵습니다.의미잇는 단어를 사용하면 어떨까요?

2023-09-30 06:50 UTC, ksy90101 commented on src/main/java/repository/GeneralRepository.java
> +        Iterator<Book> iterator = list.iterator();
여기도 iterator보단 더 의미잇는 단어를 사용해보면 어떨까요?

2023-09-30 06:50 UTC, ksy90101 commented on src/main/java/repository/GeneralRepository.java
> +                if(Objects.equals(book.getCondition(), "대여 가능")){
대여가 가능한지 book에게 메시지를 던져서 자기의 상태를 알아서 처리할수 있게 하면 어떨까요?

2023-09-30 06:50 UTC, ksy90101 commented on src/main/java/repository/TestRepository.java
> +public class TestRepository implements Repository{
```suggestion
public class TestRepository implements Repository {
```

2023-09-30 08:14 UTC, GiHoo commented on build.gradle
> +    implementation 'org.apache.commons:commons-csv:1.8' // Apache Commons CSV 라이브러리 의존성 추가
처음에 csv파일을 ","로 구분하여 읽어오는 방법을 생각했었습니다!
구현해야 할, 리팩토링 할 문제들을 처리하고 직접 구현하도록 하겠습니다!

2023-09-30 08:33 UTC, GiHoo commented on build.gradle
> +}
텍스트 파일의 마지막 행은 개행..!

2023-09-30 08:39 UTC, GiHoo commented on src/main/java/repository/GeneralRepository.java
> +            list.add(new Book(id, title, author, page, "대여 가능"));
메모리를 새로이 할당하지 않으며, IDE의 도움을 받을 수 있을 것입니다!

2023-09-30 08:47 UTC, GiHoo commented on src/main/java/repository/GeneralRepository.java
> +            if (title.toLowerCase().contains(searchTitle)) {
메세지를 Service 측에서 다루고 있습니다. (foundBooks list의 저장 유무에 따른)

2023-10-01 08:55 UTC, GiHoo commented on src/main/java/domain/Book.java
> +    public String toString() {
객체를 표현하는 문자열을 리턴할 때 사용합니다.
  1. 콘솔로 객체를 확인할 때
  2. 디버깅 할 때
  3. 로깅할 때

재정의 의의
재정의할 때 가장 중요한 건 객체 스스로를 완벽히 설명하는 문자열이어야 한다는 것입니다.
-> 객체가 가진 주요 정보를 모두 반환하는 것이 좋다.

2023-10-02 13:05 UTC, ksy90101 commented on src/main/java/domain/Book.java
> +    public String toString() {
콘솔로 객체를 확인할때보단, 로깅할때라고 생각해주시면 좋을거 같아요.

2023-10-02 13:11 UTC, ksy90101 requested changes
라이브러리 제거 이후에 다시 요청주세요 :)

2023-10-02 13:11 UTC, ksy90101 commented on build.gradle
> +    implementation 'org.apache.commons:commons-csv:1.8' // Apache Commons CSV 라이브러리 의존성 추가
@GiHoo 이걸 제거하고 한번 다시 리뷰 요청주시겠어요??

2023-10-05 13:47 UTC, ksy90101 requested changes
간단한 피드백을 더 남겼어요.
중간에 끊긴했는데 궁금한게 있다면 문의주세요~ 
파이팅이에요!

2023-10-05 13:47 UTC, ksy90101 commented on build.gradle
> +    testImplementation 'org.assertj:assertj-core:3.24.2'
별건 아니지만, testImplementation, testRuntimeOnly 끼리 모아두고, 개행은 피하면 어떨까요?
의존성도 지금은 3개라 보는게 편하지만 차후엔 여러개가 될수 있어요. 그럴수록 잘 보이도록 해야 한답니다.

2023-10-05 13:47 UTC, ksy90101 commented on src/main/java/repository/GeneralRepository.java
> +    private static final String csvFileName = "/Users/kimnamgyu/desktop/study/dev-course/csvFile.csv";
이걸 제가 켜서 진행하려고 하니, 지금 csv가 없어서 문제가 됩니다.
이걸 프로젝트 내부에서 관리하게 하고, 아울러 이걸 제가 만들지 않아도 자동으로 만들도록 해보시면 어떨까요?

2023-10-05 13:47 UTC, ksy90101 commented on src/test/java/repository/GeneralRepositoryTest.java
> +    private static final String csvFileName = "/Users/kimnamgyu/desktop/study/dev-course/csvTestFile.csv";
여기도 개인용으로 만들어서 제가 테스트 코드를 실행시키니 에러가 발생합니다.
프로젝트 내부에서 관리하도록 해보시겠어요?

2023-10-05 13:47 UTC, ksy90101 commented on src/main/java/io/Console.java
> +    private Service service;
이게 실제로 쓰이는건지 확인해보시면 어떨까요?

2023-10-05 13:47 UTC, ksy90101 commented on src/main/java/io/Console.java
> +public class Console {
현재 이게 View의 역활을 하는것인가요?
View에서 Service를 아는게 맞는지 고민해보세요.

2023-10-05 13:47 UTC, ksy90101 commented on src/main/java/io/Console.java
> +        int input = scanner.nextInt();
숫자가 아닌 다른 값이 들어오면 어떻게 될까요?
이런 validate 에러는 제어할수 있도록 하시면 어떨까요?

2023-10-05 13:47 UTC, ksy90101 commented on src/main/java/io/Console.java
> +        scanner.close();
close를 하면 상수로 한 의미가 무엇인가요?

2023-10-05 13:47 UTC, ksy90101 commented on src/main/java/view/MessagePrinter.java
> +        System.out.print("\n[System] " + message+"\n");
system.lineseparator()을 한번 알아보시면 어떨까요?

2023-10-05 13:47 UTC, ksy90101 commented on src/test/java/repository/GeneralRepositoryTest.java
> +    private static final String csvFileName = "/Users/kimnamgyu/desktop/study/dev-course/csvTestFile.csv";
상수 네이밍에 대해서 고민해보시겠어요?

2023-10-05 13:47 UTC, ksy90101 commented on src/main/java/repository/GeneralRepository.java
> +    private static final String csvFileName = "/Users/kimnamgyu/desktop/study/dev-course/csvFile.csv";
상수 네이밍에 대해서 한번 찾아보시겠어요?

2023-10-05 13:47 UTC, ksy90101 commented on src/main/java/repository/GeneralRepository.java
> +        if(!isBookExist) message = "존재하지 않는 도서번호 입니다.";
이 메시지가 중복이 되는데요. 이걸 제거해보면 어떨까요?
아울러 존재하지 않은 도서번호인 경우엔 Exception으로 관리해야 하지 않을가요?

2023-10-05 13:47 UTC, ksy90101 commented on src/main/java/repository/GeneralRepository.java
> +                String[] record = readRecord.split(",");
record는 java17의 예약어 입니다.
예약어를 변수로 쓰면 혼동이 올수가 잇습니다.

2023-10-05 13:47 UTC, ksy90101 commented on src/main/java/repository/GeneralRepository.java
> +                .collect(Collectors.toList());
```suggestion
return bookList.stream()
                .filter(book -> book.getTitle().toLowerCase().contains(searchTitle))
                .map(book -> new Book(book.getId(), book.getTitle(), book.getAuthor(), book.getPage(), book.getCondition()))
                .toList();
```

java16에서 toList()가 추가되었는데 한번 알아보시면 어떨까요?

2023-10-05 13:47 UTC, ksy90101 commented on src/main/java/repository/GeneralRepository.java
> +    public List<Book> findByTitle(String searchTitle, List<Book> bookList) {
ByTitle이면 Title을 정확히 입력했을때, 즉 동등할때일거 같은데요.
이름을 다시 지어보면 어떨까요?
현재는 contains아닌가요?

2023-10-05 13:47 UTC, ksy90101 commented on src/main/java/repository/GeneralRepository.java
> +                .filter(book -> book.getTitle().toLowerCase().contains(searchTitle))
1. 대소문자 구분없이 검색이 가능하게 하는걸 정책으로 세우신 이유가 궁금합니다.
2. 기본적으로 객체지향에선 디미터의 법칙이라는 개념이 있는데요. 즉 지금과 같이 메서드가 연속된다면 객체지향을 위반한것이다. 라는 것인데 이걸 쉽게 해결할수 있는 방법은 메시지를 보내는것입니다. book에게 메시지를 보내서 searchTitle이 포함되어 있는지 체크하도록 하면 어떨까요?

2023-10-05 13:47 UTC, ksy90101 commented on src/main/java/repository/GeneralRepository.java
> +        Timer m_timer = new Timer(true);
변수명의 컨벤션은 무엇일지 한번 찾아보시겠어요?

2023-10-05 13:47 UTC, ksy90101 commented on src/main/java/repository/GeneralRepository.java
> +        try (BufferedWriter writer = new BufferedWriter(new FileWriter(csvFileName))) {
try~with~resoruce 아주 굿굿 입니다 👍

2023-10-05 13:47 UTC, ksy90101 commented on src/test/java/repository/GeneralRepositoryTest.java
> +        assertThat(repository.findByTitle("title", list).size()).isEqualTo(2);
```suggestion
        assertThat(repository.findByTitle("title", list)).hasSize(2);
```
이런식으로도 사용가능합니다.

2023-10-05 13:47 UTC, ksy90101 commented on src/test/java/repository/GeneralRepositoryTest.java
> +        list.clear();
clear하는게 계속 중복인데, Junit 생명주기에서 BeforeEach처럼 AfterEach라는 개념도 잇는데요.
한번 찾아보시고 적용해보시면 어떨까요?

2023-10-05 13:47 UTC, ksy90101 commented on src/test/java/repository/GeneralRepositoryTest.java
> +        assertThat(list.size()).isEqualTo(0);
```suggestion
        assertThat(list.size()).isZero();
```
이런것도 있답니다 :)

2023-10-05 13:47 UTC, ksy90101 commented on src/test/java/repository/GeneralRepositoryTest.java
> +}
NLF를 안지키셨어요 ㅠㅠ

2023-10-05 13:47 UTC, ksy90101 commented on src/test/java/repository/GeneralRepositoryTest.java
> +    }
로직이 있는경우엔 try~with~resource를 쓰는게 좋지만, 이렇게 하실바에, 차라리 닫는 메서드를 사용하면 어덜까요?

아울러 이게 필요한 이유가 무엇인가요?

2023-10-05 13:47 UTC, ksy90101 commented on src/test/java/repository/GeneralRepositoryTest.java
> +        List<Book> list = new ArrayList<>();
list라는 예약어와 포괄적인 단어보단 의미잇는 단어를 쓰면 좋습니다.
대표적으로 Collections는 리소스의 복수형을 쓰는데요.

예를들어 이런 경우엔 books가 되겠죠.

2023-10-05 13:47 UTC, ksy90101 commented on src/main/java/service/GeneralService.java
> +    }
이게 있는 이유가 무엇인가요?

2023-10-05 13:47 UTC, ksy90101 commented on src/main/java/service/GeneralService.java
> +    private static final Scanner scanner = new Scanner(System.in);
Service의 개념이 무엇인지 한번 고민해보시면 어떨까요?
서비스에서 scanner가 왜 필요한가요?

2023-10-05 13:47 UTC, ksy90101 commented on src/main/java/service/GeneralService.java
> +public class GeneralService implements Service{
```suggestion
public class GeneralService implements Service {
```

2023-10-05 13:47 UTC, ksy90101 commented on src/main/java/service/GeneralService.java
> +public class GeneralService implements Service{
해당 부분에 대해서 테스트 코드를 작성해보시면 어떨까요?
아울러 궁금한게 General이라는 단어는 어떤 의미로 달아두신걸까요?

2023-10-06 02:11 UTC, GiHoo commented on build.gradle
> +    testImplementation 'org.assertj:assertj-core:3.24.2'
저는 의존성을 추가할 때 사용처가 비슷한 부류끼리 묶어서 개행을 했었는데, 여러 개의 의존성일 때를 생각하여 개행을 피하도록 하겠습니다!

2023-10-06 02:20 UTC, GiHoo commented on src/main/java/service/GeneralService.java
> +public class GeneralService implements Service{
일반적인 사용자가 사용할 때를 생각하여 General이라는 단어를 사용하였습니다. 
이는 TotalService 클래스로 변경되었습니다. 

기존에는 Service가 Repository를 호출하기만 하는 역할이라 생각하여 Repository 테스트만 작성하였습니다.
Service의 역할을 고민하고 이에 대한 테스트는 무엇일지 고민해보겠습니다!

2023-10-06 02:21 UTC, ksy90101 commented on src/main/java/service/GeneralService.java
> +public class GeneralService implements Service{
다른 Service가 생기면 어떤 이름으로 하실예정이에요?
Service가 무조건 하나라고 보장할수 있나요?

2023-10-06 02:39 UTC, GiHoo commented on src/main/java/repository/GeneralRepository.java
> +    private static final String csvFileName = "/Users/kimnamgyu/desktop/study/dev-course/csvFile.csv";
줄임말을 사용하지 않고 가급적이면 풀네임에 가까운 이름을 작성하자
변수명과 메서드명은 카멜케이스를, 상수명은 언더스코어를 사용하여 작성하자
https://velog.io/@smallcherry/Java-NamingRules

확인했습니다 감사합니다!

2023-10-06 02:50 UTC, GiHoo commented on src/main/java/repository/GeneralRepository.java
> +                String[] record = readRecord.split(",");
https://devdocs.io/openjdk~17/java.base/java/lang/record
생각하고 있지 못했던 부분입니다. 감사합니다!

2023-10-06 02:55 UTC, GiHoo commented on src/main/java/repository/GeneralRepository.java
> +    public List<Book> findByTitle(String searchTitle, List<Book> bookList) {
넵 맞습니다 book.contains(searchTitle)를 사용하고 있습니다.
답변해주신 것을 생각해보니 ByTitle은 일치하는 경우에 사용하는 것이 맞는 것 같습니다.(findById를 생각해보았을 때)

역할에 따른 메서드 네이밍에 대한 고민을 해보겠습니다 감사합니다!

2023-10-06 02:59 UTC, GiHoo commented on src/main/java/repository/GeneralRepository.java
> +                .filter(book -> book.getTitle().toLowerCase().contains(searchTitle))
책 제목이 영어로 들어왔을 때의 검색 조건을 생각하여 대소문자 구분 없이 검색 가능하게 설계하였습니다.

2023-10-06 05:16 UTC, GiHoo commented on src/main/java/service/GeneralService.java
> +public class GeneralService implements Service{
현재 주어진 요구사항에서는 서비스를 하나로 통합하는 것이 좋다고 생각했습니다. (여러 기능이 매우 유사하게 진행되기 떄문에)

다만, 추가 요구사항으로 다른 서비스를 필요로 한다면 인터페이스는 남아있기에 다른 서비스 클래스를 만들 것 같습니다.

현재 통합서비스는 GeneralAndTestService라 하고, 이후의 요구사항에 맞는 Service명을 네이밍할 것 같습니다!

2023-10-06 07:37 UTC, GiHoo commented on src/main/java/io/Console.java
> +public class Console {
Console은 Input을 받아 Service단으로 넘어가게 해주는 역할이라 생각합니다.

2023-10-06 07:42 UTC, GiHoo commented on src/main/java/repository/GeneralRepository.java
> +        if(!isBookExist) message = "존재하지 않는 도서번호 입니다.";
존재하지 않는 도서 번호라는 메시지를 콘솔로 출력해주고 다음 서비스로 진행되는 것이 생각했던 흐름이었습니다
그렇기에 메시지를 콘솔로 출력했는데, 예외 사항으로 넘어가는 흐름도 생각해보겠습니다!!

2023-10-06 09:15 UTC, ksy90101 commented on src/main/java/service/GeneralService.java
> +public class GeneralService implements Service{
저라면 도메인별대로 서비스를 둘거 같습니다.

즉 이런 경우에 BookService가 될거 같은데요.

차후 새로운 도메인개념이 추가된다는걸 알기 위해서죠.

즉, 서비스를 어떻게 나눠야 하는가? 이걸 좀 고민해봤으면 좋았겠다. 라는 생각이였습니다.

2023-10-06 14:01 UTC, GiHoo commented on src/main/java/repository/GeneralRepository.java
> +        if(!isBookExist) message = "존재하지 않는 도서번호 입니다.";
서비스를 종료하지 않고 예외 메세지를 사용자에게 전달할 수 있어야 한다.

예외는 제외를 할 수 있도록, 의도하지 않는 상황에서는 예외가 발생하도록!

2023-10-07 07:25 UTC, GiHoo commented on src/main/java/view/MessagePrinter.java
> +        System.out.print("\n[System] " + message+"\n");
개행 문자는 운영체제 별로 다르게 표현하는데,
System.lineSeparator()를 통하여 Java에서는 운영체제 별 서로 다른 개행문자를 대응할 수 있습니다!

2023-10-07 07:45 UTC, GiHoo commented on src/main/java/service/GeneralService.java
> +    private static final Scanner scanner = new Scanner(System.in);
비즈니스 로직을 수행해야 하는 역할입니다.
Service에서 필요로 하는 input을 같은 패키지에 클래스로 구현해보겠습니다!

2023-10-07 07:47 UTC, GiHoo commented on src/main/java/service/GeneralService.java
> +public class GeneralService implements Service{
위에서 답변 드렸던 내용은 도서 관리 프로그램이기 때문에 
도메인이 추가되는 것을 고려하지 않고, 저장 방식의 추가를 고려했었습니다.(데이터베이스 저장소 추가와 같은)

하지만, 다른 프로그램을 만든다고 한다면 도메인 별로 서비스를 나누는 것을 생각하여 코드를 작성해보겠습니다 감사합니다!

2023-10-10 15:37 UTC, merged