[5기 - 박유진] 1~2주차 과제: 도서 관리 어플리케이션 제출합니다.
prgrms-be-devcourse/java-library-management pull request #8
Opened 2023-09-27 16:10 UTC by eugene225

## 📌 과제 설명 
- 도서 등록 : 제목, 저자, 페이지 입력하여 도서 등록
- 전체 도서 조회 : List 로 전체 도서 목록 출력
- 제목으로 도서 조회 : 단어 입력받아서 제목이 포함되는 책 목록 출력
- 도서 대여 : POSSIBLE 상태의 책을 대여(RENTING) 처리 
- 도서 반납 : 대여(RENTING) 상태의 책을 정리(ORGANIZING) 처리 후, 5분 뒤 대여가능(POSSIBLE) 처리 / 분실(LOST) 상태의 책을 정리(ORGANIZING) 처리 후, 5분 뒤 대여가능(POSSIBLE) 처리
- 도서 분실 처리 : 분실(LOST) 처리
- 도서 삭제 : 도서 삭제 후 ID 재정렬

## 👩‍💻 요구 사항과 구현 내용 
- Book : id, title, author, pageNum, BookState 을 가진 도서 도메인
- BookState : POSSIBLE (대여가능) / RENTING (대여중) / ORGANIZING (정리중) / LOST (분실) 상태를 정의한 Enum
- BookService : List<Book> 필드값 도서리스트를 기반으로 작동하는 테스트모드 기본 기능 구현
- FileService : 파일 읽기, 파일 쓰기, 파일 삭제 일반모드를 위해 필요한 파일 관리 기능 구현

- 일반모드 : 프로그램 시작시 file 내용 List<Book>로 불러오기 + 도서 정리중에 프로그램이 종료됐을 경우 파일에 저장된 정리중(ORGANIZING) 상태의 도서를 대여가능(POSSIBLE)으로 초기화 / 프로그램 종료 시 List<Book> 내용 파일에 쓰기

## ✅ 피드백 반영사항  

## ✅ PR 포인트 & 궁금한 점 
- 레포지토리 클래스를 필드값으로 지정해서 따로 생성하지 않아도 괜찮은지 궁금합니다.
- 필드값 초기화와 생성자 초기화 중 어느 것이 더 프로그램 효율에 좋은지 궁금합니다.

2023-09-29 06:31 UTC, ksy90101 requested changes
여기도, 레포지토리에 올려야 하는게 무엇일지를 먼저 생각해보면 좋을거 같습니다.
또한 폴더 처리까지요.

1. .idea폴더가 무엇일까요?
2. .gradle폴더가 무엇일까요?
3. build 폴더는 무엇일까요?
4. out폴더는 무엇일까요?
5. library폴더로 감싸야 하는 이유는 무엇일까요?

이 5개의 답을 적어주세요~ 리뷰는 사용하지 않는 파일이 있는 이후에 하겠습니다.

이해가 안된다면 슬랙으로 DM주세요!!

2023-09-30 05:06 UTC, ksy90101 requested changes
전체적으로 고생하셨어요 :)
전체적으로 구조를 위해 한가지를 먼저 해보신 다음에 리뷰를 적용해보면 좋겠습니다.

1. Service의 역할은 무엇일까? Repository란 무엇일까?
2. Input, Output에 대한것을 한곳에 모아서 처리할수 없을까? MVC에서 View단을 따로 분리하는것 처럼 말이죠.

이 두가지를 먼저 생각해서 리팩토링을 한 뒤에 하시는걸 추천드립니다 :)

어려운게 있다면 슬랙으로 DM주세요!

2023-09-30 05:06 UTC, ksy90101 commented on settings.gradle
> +
라인이 굳이 필요할까요?

2023-09-30 05:06 UTC, ksy90101 commented on build.gradle
> +    id 'java'
java버전을 명시하면 어떨까요?

https://dlee0129.tistory.com/265
https://docs.gradle.org/current/userguide/toolchains.html#sec:consuming
sourceCompatibility & targetCompatibility
toolchain - languageVersion
이거에 대해서도 공부해두면 좋을거 같습니다~

2023-09-30 05:06 UTC, ksy90101 commented on build.gradle
> +}
https://blog.coderifleman.com/2015/04/04/text-files-end-with-a-newline/

이글을 한번 참고해보시겠어요?

2023-09-30 05:06 UTC, ksy90101 commented on src/main/java/org/example/domain/Book.java
> +        + "\n페이지 수 : " + this.getPageNum() +" 페이지" + "\n상태 : " + this.getState() + "\n------------------------------\n";
상태를 보니, 한글로 나와야 할거 같은데 현재 영어로 나옵니다.

2023-09-30 05:06 UTC, ksy90101 commented on src/main/java/org/example/domain/Book.java
> +    }
setter가 필요한 이유가 무엇일까요?

2023-09-30 05:06 UTC, ksy90101 commented on src/main/java/org/example/domain/Book.java
> +    }
단순히 setter가 아니라, 자기 자신의 상태를 변경하기 위해 메시지를 보내면 어떨까요?
`대여됨으로 변경` 이런식으로요.

2023-09-30 05:06 UTC, ksy90101 commented on src/main/java/org/example/domain/Book.java
> +    }
toString을 만든 이유가 무엇인가요?

2023-09-30 05:06 UTC, ksy90101 commented on src/main/java/org/example/domain/Book.java
> +    private Integer id;
Reference type을 쓴 이유가 있나요?

2023-09-30 05:06 UTC, ksy90101 commented on src/main/java/org/example/domain/Book.java
> +    private Integer pageNum;
Num이라는 단축어 보단, Number와 같은 혹은 아니면 그냥 Page로 써도 어색해 보이진 않을거 같은데요 어떻게 생각하시나요?

2023-09-30 05:06 UTC, ksy90101 commented on src/main/java/org/example/domain/Book.java
> +    }
기본 생성자가 있어야 하는 이유가 무엇일까요?

2023-09-30 05:06 UTC, ksy90101 commented on src/main/java/org/example/Console.java
> +public enum Console {
Input, OutPut에 대한 영역에 대해서 차후에 변경될 여지가 많을거 같은데 인터페이스로 추출해서 구현하면 어떨까요?
enum형식이 아니라 class형식으로 해야 겠죠.

2023-09-30 05:06 UTC, ksy90101 commented on src/main/java/org/example/Console.java
> +            BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
BufferdReader를 쓴 이유가 따로 있나요?
Scanner도 있는데 ㅎㅎ

2023-09-30 05:06 UTC, ksy90101 commented on src/main/java/org/example/Console.java
> +            int pageNum = Integer.parseInt(br.readLine());
혹시 여기서 숫자가 들어오지 않으면 어떻게 될까요?

2023-09-30 05:06 UTC, ksy90101 commented on src/main/java/org/example/Console.java
> +        }
이런식으로 아니라 아래와 같은 방식을 사용하면 좀더 깔끔해지지 않을까요?
enum이 추가된다면 여기 코드를 바꿀 필요도 없구요.

```
    public static Operator of(final String symbol) {
        return Arrays.stream(values())
                .filter(operator -> operator.isTextOperator(symbol))
                .findFirst()
                .orElseThrow(() -> new IllegalArgumentException("해당 연산자를 찾을수 없습니다."));
    }
```

2023-09-30 05:06 UTC, ksy90101 commented on src/main/java/org/example/Main.java
> +        while(true) {
while(ture)가 된다면 무한루프가 돌거 같은데 의도한바가 맞나요?

2023-09-30 05:06 UTC, ksy90101 commented on src/main/java/org/example/Mode.java
> +    public void normalMode(int i) throws IOException {
한 메서드에 10개 이상의 라인이 존재한다는것은 한 메서드에서 하는 일이 많다는 의미입니다.
가독성도 떨어지고, 객체지향적으로 잘 나눠졌다고 볼수가 없는데요,.

이런 경우엔 두가지 생각해서 분리해보면 어떨까요?

1. 여기에 System.oput.println과 같은 출력과 관련된 코드가 있는게 맞는가?
2. 다른 메서드로 분리해서 해당 부분을 나타낼수 없을까?

2023-09-30 05:06 UTC, ksy90101 commented on src/main/java/org/example/service/BookService.java
> +    private List<Book> books = new ArrayList<>();
Service의 역할은 무엇일까요?

2023-09-30 05:06 UTC, ksy90101 commented on src/main/java/org/example/service/BookService.java
> +        bookList.stream().filter(book -> book.getState().equals(BookState.ORGANIZING))
`book.getState().equals(BookState.ORGANIZING)`
이런경우 한줄의 점 하나씩 이라는 개념의 디미터의 법칙을 위반한건데요.
쉽게 생각해보면 book에게 너 상태가 ORGANIZING이 맞아? 라고 메시지를 보내서 알아보는것으로 쉽게 해결해볼수 있을거 같은데요. 한번 그런식으로 뺴면 어떨까요?

2023-10-03 15:22 UTC, eugene225 commented on src/main/java/org/example/domain/Book.java
> +    }
csv 파일에 , 를 구분자로 한 도서 정보를 저장하기 위해서 만들었습니다

2023-10-03 16:01 UTC, eugene225 commented on src/main/java/org/example/Console.java
> +public enum Console {
Mode의 switch문에서 어떤 명령을 진행하는지 알아보기 쉽게 하기 위해서 enum을 사용했는데 인터페이스로 구현한다면 어떤 방식으로 해야 할지 감이 오지 않습니다..

2023-10-03 16:02 UTC, eugene225 commented on src/main/java/org/example/Console.java
> +            BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
이유는 따로 없고 알고리즘 문제 풀이할때에 시간 단축을 위해서 사용하던 습관 그대로 사용하게 되었습니다..! Scanner를 사용하는게 더 좋을까요?

2023-10-03 16:09 UTC, eugene225 commented on src/main/java/org/example/service/BookService.java
> +    private List<Book> books = new ArrayList<>();
List 자료구조 한가지만 필요하다고 생각해서 따로 repository를 구현하지 않았었습니다. 직접 분리해서 구현해보니 반복되는 코드를 줄일 수 있었고, repository의 역할분리에 대해서 확실히 이해하게 된 것 같습니다.

2023-10-05 14:10 UTC, ksy90101 commented on src/main/java/org/example/domain/Book.java
> +    }
toString은 어떻게 쓰이는 용도인지
아래글을 한번 읽어보시면 어떨까요?
https://github.com/Meet-Coder-Study/book-effective-java/blob/main/3%EC%9E%A5/12_toString%EC%9D%84_%ED%95%AD%EC%83%81_%EC%9E%AC%EC%A0%95%EC%9D%98%ED%95%98%EB%9D%BC_%EC%9D%B4%ED%98%B8%EB%B9%88.md

2023-10-05 14:10 UTC, ksy90101 commented on src/main/java/org/example/Console.java
> +            BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
그건 @eugene225 님이 두개를 찾아시고, 어떤게 더 좋을지 한번 고민해보세요~

2023-10-05 14:17 UTC, ksy90101 requested changes
안녕하세요. 고생하셨어요.
이번엔 좀 큰 경험을 해봤으면 좋겠다 라고 생각해서 세세한 구조보단 큰 틀을 생각해보면 좋을만한 리뷰를 남겼습니다.
궁금한건 슬랙으로~

2023-10-05 14:17 UTC, ksy90101 commented on src/main/java/org/example/domain/BookRepository.java
> +public class BookRepository {
이번엔 좀 큰 미션을 드릴게요.

제가 추가 피드백을 남기기 전에 해당 부분에 테스트 코드를 작성해보시겠어요?

2023-10-05 14:17 UTC, ksy90101 commented on src/main/java/org/example/domain/Book.java
> +    }
view를 위한 코드가 여기 있어야 할까요?

2023-10-05 14:17 UTC, ksy90101 commented on src/main/java/org/example/domain/Book.java
> +    }
```suggestion
    public boolean isOrganizing() {
         return this.state == BookState.ORGANIZING;
    }
```
이렇게 쓰는게 더 깔끔하지 않을까요?

2023-10-05 14:17 UTC, ksy90101 commented on src/main/java/org/example/domain/Book.java
> +    }
여기 수정이 안되었어요.

2023-10-05 14:17 UTC, ksy90101 commented on src/main/java/org/example/domain/BookState.java
> +    public abstract void showChangeState();
이걸 함수형 인터페이스로 변경해보시겠어요?

2023-10-05 14:17 UTC, ksy90101 commented on src/main/java/org/example/service/BookService.java
> +        }else findBookState.showState();
지금 가독성이 굉장히 좋지 않은데요.
if와 else는 아래와 returnBook과 같이 쓰는게 더 보기 좋을거 같아요.

2023-10-05 14:17 UTC, ksy90101 commented on src/main/java/org/example/service/BookService.java
> +    public List<Book> findByTitle(String word) {
work가 포함되어 있을때라는 스펙일텐데 findByTitle은 Title이 같은걸 찾아라. 라는 의미인거 같아요.
아울러 find라는 단어는 한개만 찾는다는 의미로도 많이 쓰는데요.
이런 경우 이름을 하면 좋을지 고민해보세요.

2023-10-05 14:17 UTC, ksy90101 commented on src/main/java/org/example/service/BookService.java
> +                .findFirst().orElseThrow(() -> new RuntimeException());
```suggestion
        BookState bookState = Arrays.stream(BookState.values()).filter(state -> state.toString().equals(text))
                .findFirst()
                .orElseThrow(() -> new RuntimeException());
```

1. 한줄에 점 하나씩 쓰면 가독성이 높습니다.
2. RunTimeExcpetion은 에러중에도 꽤 상위에 있어서 에러 클래스만 보면 나중에 로그에서 대체 어떤 에러때문이야? 코드를 다 뒤져야 하거든요... 표준에러중에 맞는 에러를 써보시고, 메시지도 넣어보시면 어떨까요?

2023-10-05 14:17 UTC, ksy90101 commented on src/main/java/org/example/service/BookService.java
> +            return deleteBook;
service에서 print를 하는게 맞을까요?

2023-10-05 14:17 UTC, ksy90101 commented on src/main/java/org/example/service/FileService.java
> +public class FileService {
이건 Service가 아니라 Repository 아닌가요?
Service, Repository, Model에 대한 정의를 한번 더 고민해보세요.

아울러 해당 부분도 테스트 코드를 작성해보시겠어요?

2023-10-05 14:17 UTC, ksy90101 commented on src/main/java/org/example/service/FileService.java
> +            br = new BufferedReader(new FileReader(csv));
BR는 사용뒤 close해야하는데요 그 이유를 찾아보시면 어떨까요?
아울러 try~with~resource라는 키워드를 찾아서 적용해보세요.

2023-10-10 15:37 UTC, merged