[5기 김별이] 1~2주차 과제 도서관리 어플리케이션 제출합니다.
prgrms-be-devcourse/java-library-management pull request #9
Opened 2023-09-27 16:47 UTC by byulcode

## 📌 과제 설명 
+ 콘솔로 입출력하는 도서 관리 어플리케이션 입니다.
+ 일반 모드(도서를 파일에 등록)와 테스트 모드(도서를 List에 등록)로 구분되어 있습니다.
+ 도서를 등록, 전체 조회, 제목 별 조회, 대여, 반납, 분실 처리, 삭제를 할 수 있습니다.
+ 도서를 반납하면 '도서 정리' 상태가 되며, 5분 후 '대여 가능' 상태가 됩니다.

## 👩‍💻 요구 사항과 구현 내용 
controller
+ 선택된 모드에 맞는 repository를 서비스에 주입
+ 기능 선택
+ 콘솔 입력 서비스에 전달
+ 예외 핸들링 후 콘솔에 출력

service
+ 데이터 & 예외 처리
+ 상태 변경
+ 도서 반납에 대한 스케줄링

repository
+ 일반모드는 HashMap, 테스트 모드는 List 사용해서 관리
+ 저장, 조회, 삭제 기능 구현

model 
+ Book 클래스 정의
+ 도서 상태 enum으로 관리

io
+ 콘솔 입출력을 위한 인터페이스 및 구현체 정의 

util
+ 파일 입력, 조회 및 HashMap 변환 
## ✅ PR 포인트 & 궁금한 점 
1. 일반모드에서 데이터 변경이 있을 때마다 파일을 썼는데, 더 효율적인 방법은 없는지 궁금합니다.
2. 어느 파일에서 테스트코드를 작성해야 하는지 잘 모르겠습니다. 그래서 일반 모드에서는 service테스트 코드를, 테스트 모드에서는 repository 테스트코드를 작성했습니다.
3. 이 프로젝트이 경우 커스텀 Exception을 만들어서 예외 처리를 하는 것이 좋은지, 아니면 예외 발생 시점에 unchecked 예외를 발생시키며 메시지를 출력하는 것이 좋은지 궁금합니다

2023-09-29 06:32 UTC, ksy90101 requested changes
여기도 현재 리뷰하기엔 파일 정리가 제대로 되어 있지 않습니다.

1. .gradle폴더는 무엇일까요?
2. .idea 폴더는 무엇일까요?

두가지를 찾아보시고 답을 주시고 gitingore라는 기능을 사용해보세요.

(여긴 추가적으로 gitingore파일이 없네요?)

2023-09-29 08:21 UTC, ksy90101 requested changes
빌드가 실패합니다.

2023-09-29 08:21 UTC, ksy90101 commented on build.gradle
> +    id 'java'
https://dlee0129.tistory.com/265

자바 버전을 통일 시키기 위해, 설정하면 어떨까요?

2023-09-29 08:21 UTC, ksy90101 commented on build.gradle
> +    implementation 'org.projectlombok:lombok:1.18.22'
롬복은 개인적으로, 한번 롬복없이 사용해보고 롬복을 사용해보면 어떨까 합니다.
따라서, 롬복을 사용하지 말고 코드를 수정해보시겠어요?

롬복을 단순히 쓰면, 이게 어떤 장단점이 있는지 알수가 없거든요 ㅎㅎ

2023-09-29 08:21 UTC, ksy90101 commented on src/main/java/io/Output.java
> +import constant.Question;
이걸로 인해 빌드가 되지 않습니다. 
빌드 성공한 뒤에 다시 요청주세요.

2023-09-29 11:37 UTC, ksy90101 requested changes
고생하셨습니다 :) 

간단한 피드백을 남겼으니 참고해주세요~

궁금한게 있다면 언제든 슬랙으로 DM주세요!

2023-09-29 11:37 UTC, ksy90101 commented on src/main/java/Application.java
> +        Console console = new Console();
```suggestion
    public static void main(String[] args) {
        Console console = new Console();
```

여기에 라인이 필요할까요?

2023-09-29 11:37 UTC, ksy90101 commented on src/main/java/constant/Guide.java
> +}
https://blog.coderifleman.com/2015/04/04/text-files-end-with-a-newline/

이글을 한번 참고해보시겠어요?

2023-09-29 11:37 UTC, ksy90101 commented on src/main/java/constant/Guide.java
> +    START_TEST_MODE("[System] 테스트 모드로 애플리케이션을 실행합니다.\n"),
\n을 사용하기 보단, `system.lineseparator()`를 쓰는게 좋습니다.
해당 키워드를 통해서 한번 어떤 기능은지 찾아보시고 여기에 작성해주시겠어요?

2023-09-29 11:37 UTC, ksy90101 commented on src/main/java/constant/Guide.java
> +    private final String guide;
개행을 두고, 가독성을 높이면 좋을거 같습니다.

2023-09-29 11:37 UTC, ksy90101 commented on src/main/java/constant/Question.java
> +    REGISTER_TITLE("Q. 등록할 도서 제목을 입력하세요."),
여긴 왜 갑자기 개행이 있는 이유가 있을까요?

2023-09-29 11:37 UTC, ksy90101 commented on src/main/java/constant/Selection.java
> +            if (selection.name().startsWith("FUNCTION_")) {
`MODE_`, FUNCTION_`을 상수화 하면 어떨까요?

어떤 의미인지도 나타낼수 있고, 또한 JVM에서 상수는 어떻게 되는지도 한번 찾아보세요~

2023-09-29 11:37 UTC, ksy90101 commented on src/main/java/controller/BookController.java
> +            } else if (mode == 2) {
mode에 대해서, 상수화를 하면 어떨까요?
1,2가 전 뭔지 알수가 없는게 단점일듯 합니다 :) 

아울러 enum을 통해 전략을 쓰면 어떨까요?
https://rutgo-letsgo.tistory.com/167
해당 글을 한번 참고해보세요 :)

2023-09-29 11:37 UTC, ksy90101 commented on src/main/java/controller/BookController.java
> +                        case 7 -> deleteBook();
여기도 사실 0~7까지 어떤 의미인지 알수가 없습니다.
이런 경우에 가독성이 많이 낮을텐데요.
https://rutgo-letsgo.tistory.com/167
이걸 통해 enum화를 하번 해보면 어떨까요?

2023-09-29 11:37 UTC, ksy90101 commented on src/main/java/exception/BookAlreadyLostException.java
> +public class BookAlreadyLostException extends Exception{
여기만 일반 Excetpion인 이유가 있나요?
아울러 간단한 리뷰인데, 띄어쓰기도 잘 신경써주세요.

```suggestion
public class BookAlreadyLostException extends Exception {
```

2023-09-29 11:37 UTC, ksy90101 commented on src/main/java/exception/BookReturnFailException.java
> +    }
예외인데, 예외 메시지는 긍정이네요?

2023-09-29 11:37 UTC, ksy90101 commented on src/main/java/io/Console.java
> +    static Scanner scanner = new Scanner(System.in);
1. 접근제어자를 통해, 객체지향의 은닉성을 하면 어떨까요?
2. final을 통해 불변을 유지하면 어떨까요?
3. 개행을 두고 분리하면 어떨까요?

2023-09-29 11:37 UTC, ksy90101 commented on src/main/java/io/Console.java
> +public class Console implements Output, Input {
Input과 Output을 한 클래스로 구현하신 이유가 있나요?

2023-09-29 11:37 UTC, ksy90101 commented on src/main/java/io/Console.java
> +            return 0;
상수화를 하면 어떨까요?
그리고 차후에 0L을 쓸일이 있으면 어떻게 할껀지 궁금합니다 :)

2023-09-29 11:37 UTC, ksy90101 commented on src/main/java/io/Console.java
> +            return 0L;
상수화를 하면 어떨까요?
그리고 차후에 0L을 쓸일이 있으면 어떻게 할껀지 궁금합니다 :)

2023-09-29 11:37 UTC, ksy90101 commented on src/main/java/io/Output.java
> +    void printException(String exception);
개행을 통일해보세요.

2023-09-29 11:37 UTC, ksy90101 commented on src/main/java/model/Book.java
> +    public Long getBookNo() {
1. 개행을 두면 어떨까요?
2. 클래스는 일반적으로 아래와 같이 순서를 가지고 선언하곤 합니다.
https://web.archive.org/web/20130516014426/http://www.oracle.com/technetwork/java/codeconventions-141855.html#1852

2023-09-29 11:37 UTC, ksy90101 commented on src/main/java/model/Status.java
> +        }
1. 이걸 스트림으로 한번 바꿔보면 어떨까요?
2. null을 return하면 NPE가 발생할거 같은데요. 이런 경우 예외를 사용하는게 더 좋지 않을까요?

2023-09-29 11:37 UTC, ksy90101 commented on src/main/java/repository/FileRepository.java
> +    Map<Long, Book> bookMap = new HashMap<>();
1. 접근제어자와 final, static이 필요할지 한번 고민해보세요.

2023-09-29 11:37 UTC, ksy90101 commented on src/main/java/repository/FileRepository.java
> +                .filter(book -> book.getTitle().contains(searchTitle))
```suggestion
book.getTitle().contains(searchTitle)
```
이렇게 한줄의 점 여러개 있는 경우를 `디미터의 법칙` 이라고 합니다.
대표적으로 객체지향을 지킬수 있는 아주 좋은 법칙인데요.

이런경우 book에게 메시지를 보내서 알려달라고 하면 어떨까요?

2023-09-29 11:37 UTC, ksy90101 commented on src/main/java/repository/MemoryRepository.java
> +    List<Book> bookList = new ArrayList<>();
여기도 접근제어자, final, static 이런 키워드가 필요할지 고민해보세요.

2023-09-29 11:37 UTC, ksy90101 commented on src/main/java/repository/MemoryRepository.java
> +        this.bookList.removeIf(book -> book.getBookNo().equals(bookNo));
여기도 메시지를 보내서, bookNo와 같은지를 체크해보면 어떨까요?

2023-09-29 11:37 UTC, ksy90101 commented on src/main/java/repository/MemoryRepository.java
> +                .filter(book -> book.getTitle().contains(title))
여기도 위에처럼 메시지를 보내면 어떨까요?

2023-09-29 11:37 UTC, ksy90101 commented on src/main/java/service/BookService.java
> +    // 도서 등록
주석이 필요할까요? 이정도의 주석은 사용하지 않는게 좋을거 같아요.
충분히 메서드명으로 나타내주면 좋습니다 :)

2023-09-29 11:37 UTC, ksy90101 commented on src/main/java/service/BookService.java
> +        }
이걸 book에게 물어보고, 이런 메시지를 보내서 체크하게 하면 어떨까요?

`너 현재 어떤 상태야? 내가 빌릴수 있어?`

2023-09-29 11:37 UTC, ksy90101 commented on src/main/java/service/BookService.java
> +            }
익명함수보단, 람다를 써보면 어떨까요?

2023-09-29 11:37 UTC, ksy90101 commented on src/main/java/service/BookService.java
> +        timer.schedule(timerTask, 10000);   // 테스트코드 실행을 위해 짧게 설정
프로덕션에 테스트를 위한 코드가 잇으면 안됩니다.
이런경우엔 어떻게 할수 잇을까요?
https://tecoble.techcourse.co.kr/post/2020-05-17-appropriate_method_for_test_by_interface/
이글 참고해보세요.

2023-09-29 11:37 UTC, ksy90101 commented on src/main/java/util/CsvFileUtil.java
> +            } catch (IOException ignore) {
현재 2depth이상이 도니다면 코드 읽기가 너무 어려울거에요.
객체지향적이 아닐수 있는데요.
이런 경우 객체지향을 위해 메서드 분리를 해보면 어떨까요?

2023-09-29 11:37 UTC, ksy90101 commented on src/main/java/util/CsvFileUtil.java
> +    public void writeFile(Map<Long, Book> bookMemory ) {
```suggestion
    public void writeFile(Map<Long, Book> bookMemory) {
```

2023-09-29 11:37 UTC, ksy90101 commented on src/test/java/repository/MemoryRepositoryTest.java
> +        List<Book> bookList = memoryRepository.findAllBook();
List라는 단어보단, Collection인 경우엔 복수를 사용하는게 더 좋습니다 :)

2023-09-30 09:38 UTC, byulcode commented on src/main/java/constant/Guide.java
> +    START_TEST_MODE("[System] 테스트 모드로 애플리케이션을 실행합니다.\n"),
프로그램이 실행되는 OS의 개행 문자를 리턴하는 기능을 합니다. 예를 들어, Windows 및 Linux에서 실행 시 동일한 결과를 출력하게 합니다.

2023-09-30 09:41 UTC, byulcode commented on src/main/java/io/Console.java
> +public class Console implements Output, Input {
Input과 Output 모두 콘솔에서의 동작을 관리하기 때문에 한 클래스로 구현했습니다

2023-09-30 11:42 UTC, byulcode commented
아래 글을 읽고 custom exception을 만들지 않아도 될 것 같아서 제거했습니다!
https://tecoble.techcourse.co.kr/post/2020-08-17-custom-exception/

2023-10-02 12:20 UTC, ksy90101 commented
@byulcode 장단점이 명확한데, 혹시 어떤 점때문에 제거하셨을까요? (단순 질문입니다.)

2023-10-02 12:57 UTC, ksy90101 requested changes
별이님 피드백 수정하시느라 고생하셨어요.
이번엔 클린코드와 테스트 코드에 관련해서 리뷰를 남겼어요.
마지막까지 파이팅이에요.
어려운게 있다면 언제든 슬랙으로 질문주세요~

2023-10-02 12:57 UTC, ksy90101 commented on build.gradle
> +}
NLF을 여기도 하면 어떨까요?

2023-10-02 12:57 UTC, ksy90101 commented on src/main/java/service/BookService.java
> +    public List<Book> findBooksByTitle(String title) {
UI/UX적으로 이런 생각을 가져본적이 없나요?
"해당 검색 결과가 없다면 사용자에게 특별하게 안내를 해주자."
이런것도 문제 해결 능력중에 꼼꼼함을 보는거 같아요. 어떻게 생각하시나요?

2023-10-02 12:57 UTC, ksy90101 commented on src/main/java/io/Input.java
> +}
여기도 NLF가 안되어 있네요.

2023-10-02 12:57 UTC, ksy90101 commented on src/main/java/controller/BookController.java
> +            switch (Mode.chosenMode(inputMode)) {
swtich문은 default를 설정하면 어떨까요?
default를 설정함으로써 다른 값이 들어온 경우 에러를 발생시킬수도 있고, 차후 문제가 될 경우 더 빠르게 디버깅이 가능합니다.

2023-10-02 12:57 UTC, ksy90101 commented on src/main/java/controller/BookController.java
> +    private final String FUNCTION = "FUNCTION";
자바에서 상수는 어떻게 쓰는지 한번 찾아보세요.

2023-10-02 12:57 UTC, ksy90101 commented on src/main/java/controller/BookController.java
> +    private final String FUNCTION = "FUNCTION";
enum값과 상수와 같이사 차후 아래에서 코드를 볼때 어떤걸 의미하는지 알아보기가 조금 어려울거 같습니다.
(지금은 IDE를 가지고 쉽게 알수 있지만, 그렇지 않은 경우엔 어렵지 않을까요?
이름을 분리해보면 어떨까요?

2023-10-02 12:57 UTC, ksy90101 commented on src/main/java/controller/BookController.java
> +            {
이 block은 필요 없을거 같아요!

2023-10-02 12:57 UTC, ksy90101 commented on src/main/java/service/BookService.java
> +        switch (book.getStatus()) {
무조건 switch문이 좋은 문법일까요?
이런 경우엔 if문으로 작성하면 어떨까요?
마지막으로 반납가능한 상태인지는 book이 메세지를 던져서 알수 잇도록 하면 어떨까요?

2023-10-02 12:57 UTC, ksy90101 commented on src/main/java/service/BookService.java
> +                .orElseThrow(() -> new IllegalArgumentException(ExceptionMsg.NO_TARGET.getMessage()));
1. 인자를 사용하지 않은것 같네요. 이런 경우에 변수를 지정안하면 어덜까요?
2. 아울러 이 로직은 계속 반복되는 로직인거 같은데 이런 경우에 메서드로 추출해서 중복로직을 제거하면 어떨까요?

2023-10-02 12:57 UTC, ksy90101 commented on src/main/java/util/CsvFileUtil.java
> +    public CsvFileUtil(String FILE_PATH) {
매개변수의 이름 규칙은 어떻게 될까요?

2023-10-02 12:57 UTC, ksy90101 commented on src/main/java/util/CsvFileUtil.java
> +    private final String FILE_PATH;
여기도 컨벤션을 확인해주세요.

2023-10-02 12:57 UTC, ksy90101 commented on src/test/java/service/FIleBookServiceTest.java
> +        assertThat(bookService.findAllBook().size()).isEqualTo(4);
assertJ에는 여러가지 메서드들이 있습니다. 이런 경우엔 

```suggestion
        assertThat(bookService.findAllBook()).hasSize(4);
```
이런식으로도 사용할수 잇는데요. 어떤게 더 좋을지는 한번 생각해보세요!

2023-10-02 12:57 UTC, ksy90101 commented on src/main/java/service/BookService.java
> +    }
이 부분을 인터페이스로 추출한 뒤에, 테스트 코드에 맞는 구현체와 프로덕션에 맞는 구현체를 따로따로 구현하면 어떨까요?
아래 글 처럼 말이죠.
https://tecoble.techcourse.co.kr/post/2020-05-17-appropriate_method_for_test_by_interface/

이런 말을 하는 이유는 `returnBookByBookNo` 해당 메서드에서 time을 받는 이유는 딱 테스트 코드를 위한 이유일거 같아요.
완벽히 테스트 코드와 프로덕션 코드를 분리하기 위해서 한번 시도해보면 좋을거 같아서 이야기 드려요.

2023-10-02 12:57 UTC, ksy90101 commented on src/test/java/service/FIleBookServiceTest.java
> +            Thread.sleep(10000);
이걸로 인해, 테스트 코드가 10초가 걸려요.
테스트 코드는 빠르게 동작하는게 중요합니다.

더 시간을 줄여보면 어떨까요?

2023-10-02 12:57 UTC, ksy90101 commented on src/main/java/constant/Function.java
> +    public static Function getFunctionByIdx(int idx) {
해당 메서드도 테스트 코드를 작성해보면 어떨까요?

테스트 코드는 차후 리팩토링시, 문제가 없을지를 의미하는것이기 때문이에요.

아울러 idx보단 index와 같이 축약어를 안쓰는걸 추천드립니다.

2023-10-02 12:57 UTC, ksy90101 commented on src/main/java/constant/Function.java
> +        if (idx >= 0 && idx < functions.length) {
그리고 index를 쓰지않는게 좋습니다.

이유는 아래와 같아요.

1. 차후 BORROW의 위치를 변경하면 모든 코드를 다 고쳐줘야 하지 않을까요?
2. 단순 위치 변경으로 문제가 생길 확률이 높겟죠?
3. 또한 중간 모드가 없어진다면에 대해서도 문제가 생길수도 있죠? 다른 것들이 다 위로 올라가야 하니깐요.
이런 경우엔 차라리 인자로 mode_number와 같은 nubmer를 가지고 하게 하는게 좋습니다.

이렇게 지정해두면 삭제 할때, 굳이 이 메서드를 수정할 필요는 없을수도 있고 밖에까지도 영향이 안갈수도 있을거 같아요.

2023-10-02 12:57 UTC, ksy90101 commented on src/main/java/constant/Mode.java
> +    WRONG_MODE;
이 값은 안쓰이네요.

2023-10-02 12:57 UTC, ksy90101 commented on src/main/java/constant/Mode.java
> +    public static Mode chosenMode(int mode) {
```
package constant;

import java.util.Arrays;

public enum Mode {
    NORMAL_MODE(1),
    TEST_MODE(2),
    WRONG_MODE;

    private int number;

    Mode(int number) {
        this.number = number;
    }

    public static Mode chosenMode(int modeNumber) {
        return Arrays.stream(Mode.values()).filter(mode ->  mode.number == modeNumber)
                .findFirst()
                .orElseThrow(() -> new IllegalArgumentException(ExceptionMsg.WRONG_MODE.getMessage()));
    }
}
```

이런식으로 변경해보면 어떨까요?
차후 Mode가 추가되어도 choseMode는 변경할 필요 없으니깐요.

아울러 이 메소드도 테스트 코드를 작성해두고 차후 변경에 유연하게 대응해보세요.

2023-10-02 12:57 UTC, ksy90101 commented on src/main/java/model/Book.java
> +public class Book {
모델에 대한 테스트 코드도 한번 작성해보시겟어요?
몇가지 메서드들이 있네요 작성해보면 좋을만한것들이요!

2023-10-02 12:57 UTC, ksy90101 commented on src/main/java/model/Book.java
> +    private final int pageNum;
더 나아가서, 이런 고민을 해보면 좋겠어요.
이 3가지 값에 대해서 validate가 필요 없을까?
별이님만의 애플리케이션을 만들어 나가는것이기니깐요.

2023-10-02 12:57 UTC, ksy90101 commented on src/main/java/model/Status.java
> +    public static Status findStatusByString(String statusString) {
여기도 테스트 코드 작성을 해보시면 좋을거 같습니다.

2023-10-02 12:57 UTC, ksy90101 commented on src/main/java/repository/MemoryRepository.java
> +    public Long createBookNo() {
여긴 테스트 코드가 없네요?

2023-10-02 12:57 UTC, ksy90101 commented on src/main/java/repository/FileRepository.java
> +public class FileRepository implements Repository {
여기도 테스트 코드를 한번 작성해보면 어덜까요?
테스트 코드 영역에 파일을 만들고, 테스트가 다 끝나면 파일을 제거하면 테스트 코드 작성이 어려울거 같지 않아요.

2023-10-02 12:57 UTC, ksy90101 commented on src/main/java/service/BookService.java
> +        }
해당 영역에 대한 테스트 코드는 존재하지 않습니다.
아울러 이것도 book에게 물어보면 어떨까요?

이러면 될거 같지 않은가요?

toLost 분실로 처리해줘. 라고 메시지를 보내지만 book이 메세지에서 이미 이건 읽어버린 책이라서 안돼! 라고.

서비스가 lost의 상태를 알필요가 없으니깐요 ㅎㅎ

2023-10-03 06:17 UTC, byulcode commented on src/main/java/controller/BookController.java
> +    private final String FUNCTION = "FUNCTION";
자바에서 상수는 프로그램이 실행과 동시에 선언하여 실행되는 동안은 변하지 않는 용도로 사용합니다! static 키워드를 쓰지 않으면 클래스의 인스턴스마다 메모리가 할당되어  메모리 낭비가 된다고 하네요😿
자바에서 왜 상수를 static final로 선언하는지 자세히 찾아본 적이 없어서 신경 쓰지 못한 것 같습니다. 앞으로 주의할게요!

2023-10-03 06:28 UTC, byulcode commented
> @byulcode 장단점이 명확한데, 혹시 어떤 점때문에 제거하셨을까요? (단순 질문입니다.)
이 프로그램에서는 예외마다 메시지 재 정의만 했기 때문에 IllegalArgumentException, IllegalStateException만으로도 충분히 구현이 가능하다고 판단했기 때문입니다! 
custom exception을 사용하면 만약 다른 조건이 더 추가될 시 예외 클래스가 무의미하게 많아질 것 같다는 느낌이 들었습니다.

2023-10-06 03:55 UTC, byulcode commented on src/main/java/repository/FileRepository.java
> +public class FileRepository implements Repository {
기존 서비스에 대한 테스트코드를 Mockito 프레임워크를 사용해서 데이터가 실제로 저장되지 않도록 수정했습니다. 
그리고 FileRepository에 대한 테스트코드를 실행하면 test.csv 파일을 생성해서 테스트하고, 끝나면 제거되도록 구현했습니다!

2023-10-06 05:54 UTC, byulcode commented
1. Mockito 프레임워크를 사용해서 service 테스트코드를 작성했는데, 사용에 익숙하지 않아서 제대로 작성한 것인지 확인 부탁드립니다!
2. timer부분 인터페이스로 구분했는데, 반복되는 로직이 있어 default 함수로 처리했습니다.

2023-10-07 02:51 UTC, ksy90101 requested changes
전체적으로 너무 잘 해주셨네요 👍 
고생 많으셨습니다.
거의다 마무리 되었네요! 마지막으로 간단하게 수정하고 끝내시면 어떨까 해서 마지막 리뷰 남겨요~

2023-10-07 02:51 UTC, ksy90101 commented on src/main/java/util/BookTestScheduler.java
> +public class BookTestScheduler implements BookScheduler{
java 패키지에 있는 것들은 프로덕션 배포 시, 빌드가 되는데 테스트 코드를 위한게 빌드될 필요가 있을까요?
테스트를 위한 이런 구현체는 테스트 패키지에 있는게 더 어울립니다~

2023-10-07 02:51 UTC, ksy90101 commented on src/main/java/repository/FileRepository.java
> +    }
해당 부분 테스트 코드는 없네요 😢

2023-10-07 02:51 UTC, ksy90101 commented on src/test/java/model/BookTest.java
> +        assertThrows(IllegalStateException.class, () -> books.get(1).isAvailableToBorrow());
assertThatThrownBy(() -> books.get(1).isAvailableToBorrow())
                .isInstanceOf(IllegalStateException.class)
                .hasMessageContaining("대여중인 도서입니다.");

이런식으로 사용해봐도 좋습니다.

메시지까지 검증하는게 좋은데요. 표준 예외를 사용하면 실제 우리가 사용한 예외인지 알수가 없으니깐요.

2023-10-07 02:51 UTC, ksy90101 commented on src/test/java/model/BookTest.java
> +        assertTrue(books.get(2).isAvailableToChangeLost());
이런 경우 for문을 이용해서 해도 무관했을수도 있어요~

2023-10-07 02:51 UTC, ksy90101 commented on src/main/java/repository/FileRepository.java
> +    public FileRepository(String file_path) {
매개변수의 네이밍 규칙은 무엇인지 고민해보세요.

2023-10-07 02:51 UTC, ksy90101 commented on src/main/java/repository/FileRepository.java
> +    private Map<Long, Book> bookMap = new HashMap<>();
final static으로 불변과 자원공유가 필요하지 않을까요?

지금은 한명만 실행하는데 여려명이 실행할땐 어떻게 될까요?

2023-10-07 02:51 UTC, ksy90101 commented on src/main/java/constant/ExceptionMsg.java
> +    private final String message;
```suggestion
    FOUNT_NOTHING("[System] 도서 목록이 존재하지 않습니다" + System.lineSeparator());
   
    private final String message;
```

개행을 두면 훨씬 더 가독성이 높아진답니다.

2023-10-07 02:51 UTC, ksy90101 commented on src/main/java/io/Console.java
> +    private <T extends Number> T readNumber(Class<T> numType) {
👍

2023-10-07 02:51 UTC, ksy90101 commented on src/main/java/model/Book.java
> +        }
validate 함수를 따로 뺴서 작성하면 좋습니다.

아울러 isEmpty vs isBlank 두개의 차이점을 한번 찾아보시면 좋습니다 :)

2023-10-07 02:51 UTC, ksy90101 commented on src/main/java/service/BookService.java
> +        Book book = new Book(repository.createBookNo(), title, author, pageNum, Status.AVAILABLE);
ID와 status는 도메인에서 디폴트 값이 들어가게 하는것이 더 좋을수 있습니다.
생성자를 무조건적으로 열면 나중에 누군가 실수할수 있거든요.
각자의 상태는 도메인이 맡은다!라고 생각하시면 좀 쉬울라나요 ㅎㅎ

2023-10-07 02:51 UTC, ksy90101 commented on src/test/java/model/BookTest.java
> +        books.add(new Book(1L, "대여가능도서", "작가1", 255, Status.AVAILABLE));
addAll이라는 메서드도 있어요~
참고만 하세요~

2023-10-07 02:51 UTC, ksy90101 commented on src/test/java/model/BookTest.java
> +    void isAvailableToBorrow() {
굳이 4개를 다 검증할 필요가 있나요?

즉, 직접 모델인 경우엔 테스트를 할때마다 만들어서 처리하시는게 더 좋을거 같은데요.

2023-10-07 02:51 UTC, ksy90101 commented on src/test/java/service/BookServiceTest.java
> +        verify(repository, times(1)).findAllBook();
👍

2023-10-07 02:51 UTC, ksy90101 commented on src/test/java/repository/MemoryRepositoryTest.java
> +        assertEquals(book, bookFound);
assertJ를 쓰는것도 있고 아닌곳도 있네요 ㅠㅠ

2023-10-10 15:36 UTC, merged